import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 600;
const SERVICES_Y = HERO_H + 80;
const SERVICES_H = 420;
const BOOKING_Y = SERVICES_Y + SERVICES_H + 80;
const BOOKING_H = 300;
const GALLERY_Y = BOOKING_Y + BOOKING_H + 80;
const GALLERY_H = 340;
const STAGE_H = GALLERY_Y + GALLERY_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero section ────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-beautyhome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-beautyhome-hero-bg',
    parentId: 'tpl-beautyhome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    src: '/images/placeholder-salon-hero.jpg',
    alt: '뷰티살롱 히어로 배경 이미지',
    style: { opacity: 30, borderRadius: 0 },
  }),
  heading(
    'tpl-beautyhome-hero-title',
    { x: 80, y: 160, width: 600, height: 100 },
    '당신의 아름다움을 빛나게',
    1,
    '#ffffff',
    'left',
    'tpl-beautyhome-hero',
  ),
  createTextNode({
    id: 'tpl-beautyhome-hero-tagline',
    parentId: 'tpl-beautyhome-hero',
    rect: { x: 80, y: 280, width: 500, height: 60 },
    text: '전문 스타일리스트가 트렌디한 스타일과 맞춤 케어로 최고의 아름다움을 선사합니다.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: 'regular',
    align: 'left',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-beautyhome-hero-cta',
    parentId: 'tpl-beautyhome-hero',
    rect: { x: 80, y: 370, width: 200, height: 52 },
    label: '지금 예약하기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Services showcase (4 cards) ─────────────────────────── */
  heading(
    'tpl-beautyhome-svc-title',
    { x: 80, y: SERVICES_Y, width: 400, height: 50 },
    '인기 서비스',
    2,
    '#123b63',
    'left',
  ),
  // Card 1
  createContainerNode({
    id: 'tpl-beautyhome-card-1',
    rect: { x: 80, y: SERVICES_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-beautyhome-card-1-img',
    parentId: 'tpl-beautyhome-card-1',
    rect: { x: 0, y: 0, width: 260, height: 160 },
    src: '/images/placeholder-beauty-hair.jpg',
    alt: '헤어 스타일링',
    style: { borderRadius: 0 },
  }),
  heading('tpl-beautyhome-card-1-title', { x: 16, y: 172, width: 228, height: 36 }, '헤어 스타일링', 3, '#123b63', 'left', 'tpl-beautyhome-card-1'),
  createTextNode({
    id: 'tpl-beautyhome-card-1-desc',
    parentId: 'tpl-beautyhome-card-1',
    rect: { x: 16, y: 216, width: 228, height: 60 },
    text: '커트, 염색, 펌 등 트렌디한 헤어 스타일을 완성합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 2
  createContainerNode({
    id: 'tpl-beautyhome-card-2',
    rect: { x: 370, y: SERVICES_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-beautyhome-card-2-img',
    parentId: 'tpl-beautyhome-card-2',
    rect: { x: 0, y: 0, width: 260, height: 160 },
    src: '/images/placeholder-beauty-nails.jpg',
    alt: '네일 아트',
    style: { borderRadius: 0 },
  }),
  heading('tpl-beautyhome-card-2-title', { x: 16, y: 172, width: 228, height: 36 }, '네일 아트', 3, '#123b63', 'left', 'tpl-beautyhome-card-2'),
  createTextNode({
    id: 'tpl-beautyhome-card-2-desc',
    parentId: 'tpl-beautyhome-card-2',
    rect: { x: 16, y: 216, width: 228, height: 60 },
    text: '젤, 아크릴, 아트 네일 등 섬세한 네일 케어를 제공합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 3
  createContainerNode({
    id: 'tpl-beautyhome-card-3',
    rect: { x: 660, y: SERVICES_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-beautyhome-card-3-img',
    parentId: 'tpl-beautyhome-card-3',
    rect: { x: 0, y: 0, width: 260, height: 160 },
    src: '/images/placeholder-beauty-skin.jpg',
    alt: '피부 관리',
    style: { borderRadius: 0 },
  }),
  heading('tpl-beautyhome-card-3-title', { x: 16, y: 172, width: 228, height: 36 }, '피부 관리', 3, '#123b63', 'left', 'tpl-beautyhome-card-3'),
  createTextNode({
    id: 'tpl-beautyhome-card-3-desc',
    parentId: 'tpl-beautyhome-card-3',
    rect: { x: 16, y: 216, width: 228, height: 60 },
    text: '페이셜, 필링, 보습 케어로 건강한 피부를 만듭니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 4
  createContainerNode({
    id: 'tpl-beautyhome-card-4',
    rect: { x: 950, y: SERVICES_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-beautyhome-card-4-img',
    parentId: 'tpl-beautyhome-card-4',
    rect: { x: 0, y: 0, width: 260, height: 160 },
    src: '/images/placeholder-beauty-makeup.jpg',
    alt: '메이크업',
    style: { borderRadius: 0 },
  }),
  heading('tpl-beautyhome-card-4-title', { x: 16, y: 172, width: 228, height: 36 }, '메이크업', 3, '#123b63', 'left', 'tpl-beautyhome-card-4'),
  createTextNode({
    id: 'tpl-beautyhome-card-4-desc',
    parentId: 'tpl-beautyhome-card-4',
    rect: { x: 16, y: 216, width: 228, height: 60 },
    text: '웨딩, 촬영, 데일리 등 맞춤 메이크업 서비스를 제공합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),

  /* ── Booking CTA ─────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-beautyhome-booking',
    rect: { x: 0, y: BOOKING_Y, width: W, height: BOOKING_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-beautyhome-booking-title',
    { x: 80, y: 40, width: 500, height: 50 },
    '온라인 예약',
    2,
    '#123b63',
    'left',
    'tpl-beautyhome-booking',
  ),
  createTextNode({
    id: 'tpl-beautyhome-booking-desc',
    parentId: 'tpl-beautyhome-booking',
    rect: { x: 80, y: 110, width: 600, height: 60 },
    text: '원하는 날짜와 시간에 간편하게 예약하세요. 첫 방문 고객에게는 10% 할인 혜택을 드립니다.',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-beautyhome-booking-btn',
    parentId: 'tpl-beautyhome-booking',
    rect: { x: 80, y: 200, width: 180, height: 48 },
    label: '예약하기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Instagram gallery ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-beautyhome-gallery',
    rect: { x: 0, y: GALLERY_Y, width: W, height: GALLERY_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading(
    'tpl-beautyhome-gallery-title',
    { x: 80, y: 40, width: 500, height: 50 },
    '인스타그램 갤러리',
    2,
    '#ffffff',
    'left',
    'tpl-beautyhome-gallery',
  ),
  createTextNode({
    id: 'tpl-beautyhome-gallery-desc',
    parentId: 'tpl-beautyhome-gallery',
    rect: { x: 80, y: 100, width: 500, height: 32 },
    text: '@our_salon에서 최신 작업물을 확인하세요.',
    fontSize: 16,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 1.4,
  }),
  createImageNode({
    id: 'tpl-beautyhome-gallery-img-1',
    parentId: 'tpl-beautyhome-gallery',
    rect: { x: 80, y: 150, width: 260, height: 160 },
    src: '/images/placeholder-insta-1.jpg',
    alt: '인스타그램 작업물 1',
    style: { borderRadius: 8 },
  }),
  createImageNode({
    id: 'tpl-beautyhome-gallery-img-2',
    parentId: 'tpl-beautyhome-gallery',
    rect: { x: 366, y: 150, width: 260, height: 160 },
    src: '/images/placeholder-insta-2.jpg',
    alt: '인스타그램 작업물 2',
    style: { borderRadius: 8 },
  }),
  createImageNode({
    id: 'tpl-beautyhome-gallery-img-3',
    parentId: 'tpl-beautyhome-gallery',
    rect: { x: 652, y: 150, width: 260, height: 160 },
    src: '/images/placeholder-insta-3.jpg',
    alt: '인스타그램 작업물 3',
    style: { borderRadius: 8 },
  }),
  createImageNode({
    id: 'tpl-beautyhome-gallery-img-4',
    parentId: 'tpl-beautyhome-gallery',
    rect: { x: 938, y: 150, width: 260, height: 160 },
    src: '/images/placeholder-insta-4.jpg',
    alt: '인스타그램 작업물 4',
    style: { borderRadius: 8 },
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-beautyhome-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-beautyhome-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-beautyhome-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-proof-label',
    parentId: 'tpl-beautyhome-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-proof-title',
    parentId: 'tpl-beautyhome-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'beauty home 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-proof-copy',
    parentId: 'tpl-beautyhome-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-beautyhome-wix-metric-1',
    parentId: 'tpl-beautyhome-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-metric-1-value',
    parentId: 'tpl-beautyhome-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-metric-1-label',
    parentId: 'tpl-beautyhome-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautyhome-wix-metric-2',
    parentId: 'tpl-beautyhome-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-metric-2-value',
    parentId: 'tpl-beautyhome-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-metric-2-label',
    parentId: 'tpl-beautyhome-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautyhome-wix-metric-3',
    parentId: 'tpl-beautyhome-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-metric-3-value',
    parentId: 'tpl-beautyhome-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-metric-3-label',
    parentId: 'tpl-beautyhome-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautyhome-wix-metric-4',
    parentId: 'tpl-beautyhome-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-metric-4-value',
    parentId: 'tpl-beautyhome-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-metric-4-label',
    parentId: 'tpl-beautyhome-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-showcase-label',
    parentId: 'tpl-beautyhome-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-showcase-title',
    parentId: 'tpl-beautyhome-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-beautyhome-wix-showcase-copy',
    parentId: 'tpl-beautyhome-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-beautyhome-wix-showcase-visual',
    parentId: 'tpl-beautyhome-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
]);

export const beautyHomeTemplate: PageTemplate = {
  id: 'beauty-home',
  name: '뷰티살롱 홈',
  category: 'beauty',
  subcategory: 'homepage',
  description: '살롱 히어로 + 인기 서비스 카드(4개) + 예약 CTA + 인스타그램 갤러리',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
