import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const MARGIN = 80;
const HEADER_H = 140;
const TIER_W = 350;
const TIER_H = 480;
const GAP = 40;
const TIERS_Y = HEADER_H + 40;
const STAGE_H = TIERS_Y + TIER_H + 80;

interface PriceTier {
  key: string;
  name: string;
  price: string;
  desc: string;
  features: string;
  highlight: boolean;
}

const tiers: PriceTier[] = [
  {
    key: 'basic',
    name: '베이직 패키지',
    price: '₩89,000',
    desc: '기본 뷰티 케어',
    features: '커트 + 기본 스타일링\n기본 네일 케어\n두피 진단\n음료 서비스',
    highlight: false,
  },
  {
    key: 'premium',
    name: '프리미엄 패키지',
    price: '₩159,000',
    desc: '인기 추천 패키지',
    features: '커트 + 염색/펌\n젤 네일 아트\n페이셜 기본 케어\n두피 트리트먼트\n음료 + 간식 서비스',
    highlight: true,
  },
  {
    key: 'vip',
    name: 'VIP 패키지',
    price: '₩259,000',
    desc: '풀 뷰티 케어',
    features: '커트 + 염색 + 펌\n프리미엄 네일 아트\n프리미엄 페이셜\n두피 스파 트리트먼트\n메이크업 포함\nVIP 라운지 이용',
    highlight: false,
  },
];

function buildTierCard(tier: PriceTier, idx: number): BuilderCanvasNode[] {
  const x = MARGIN + idx * (TIER_W + GAP);
  const cid = `tpl-beautyprice-tier-${tier.key}`;
  const bg = tier.highlight ? '#123b63' : '#ffffff';
  const titleColor = tier.highlight ? '#ffffff' : '#123b63';
  const textColor = tier.highlight ? 'rgba(255,255,255,0.85)' : '#374151';
  const priceColor = '#e8a838';

  return [
    createContainerNode({
      id: cid,
      rect: { x, y: TIERS_Y, width: TIER_W, height: TIER_H },
      background: bg,
      borderRadius: 16,
      borderColor: tier.highlight ? '#123b63' : '#e2e8f0',
      borderWidth: tier.highlight ? 0 : 1,
      padding: 32,
    }),
    heading(`${cid}-name`, { x: 32, y: 32, width: 286, height: 36 }, tier.name, 3, titleColor, 'center', cid),
    createTextNode({
      id: `${cid}-price`,
      parentId: cid,
      rect: { x: 32, y: 80, width: 286, height: 48 },
      text: tier.price,
      fontSize: 36,
      color: priceColor,
      fontWeight: 'bold',
      align: 'center',
    }),
    createTextNode({
      id: `${cid}-desc`,
      parentId: cid,
      rect: { x: 32, y: 136, width: 286, height: 28 },
      text: tier.desc,
      fontSize: 14,
      color: textColor,
      align: 'center',
    }),
    createTextNode({
      id: `${cid}-features`,
      parentId: cid,
      rect: { x: 32, y: 180, width: 286, height: 200 },
      text: tier.features,
      fontSize: 14,
      color: textColor,
      lineHeight: 1.8,
      align: 'center',
    }),
    createButtonNode({
      id: `${cid}-btn`,
      parentId: cid,
      rect: { x: 75, y: 410, width: 200, height: 44 },
      label: '예약하기',
      href: '#',
      variant: tier.highlight ? 'primary' : 'outline',
      style: { backgroundColor: tier.highlight ? '#e8a838' : 'transparent', borderRadius: 6 },
    }),
  ];
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  heading(
    'tpl-beautyprice-title',
    { x: MARGIN, y: 50, width: 500, height: 56 },
    '가격표 & 패키지',
    1,
    '#123b63',
  ),
  createTextNode({
    id: 'tpl-beautyprice-subtitle',
    rect: { x: MARGIN, y: 110, width: 700, height: 32 },
    text: '합리적인 가격으로 프리미엄 뷰티 서비스를 경험하세요.',
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 1.4,
  }),
  ...tiers.flatMap((t, i) => buildTierCard(t, i)),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-beautypricing-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-proof-label',
    parentId: 'tpl-beautypricing-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-proof-title',
    parentId: 'tpl-beautypricing-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'beauty pricing 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-proof-copy',
    parentId: 'tpl-beautypricing-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-metric-1',
    parentId: 'tpl-beautypricing-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-metric-1-value',
    parentId: 'tpl-beautypricing-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-metric-1-label',
    parentId: 'tpl-beautypricing-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-metric-2',
    parentId: 'tpl-beautypricing-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-metric-2-value',
    parentId: 'tpl-beautypricing-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-metric-2-label',
    parentId: 'tpl-beautypricing-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-metric-3',
    parentId: 'tpl-beautypricing-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-metric-3-value',
    parentId: 'tpl-beautypricing-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-metric-3-label',
    parentId: 'tpl-beautypricing-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-metric-4',
    parentId: 'tpl-beautypricing-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-metric-4-value',
    parentId: 'tpl-beautypricing-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-metric-4-label',
    parentId: 'tpl-beautypricing-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-label',
    parentId: 'tpl-beautypricing-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-title',
    parentId: 'tpl-beautypricing-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-copy',
    parentId: 'tpl-beautypricing-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-showcase-visual',
    parentId: 'tpl-beautypricing-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-visual-title',
    parentId: 'tpl-beautypricing-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-visual-copy',
    parentId: 'tpl-beautypricing-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-showcase-card-1',
    parentId: 'tpl-beautypricing-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-card-1-title',
    parentId: 'tpl-beautypricing-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-card-1-copy',
    parentId: 'tpl-beautypricing-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-showcase-card-2',
    parentId: 'tpl-beautypricing-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-card-2-title',
    parentId: 'tpl-beautypricing-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-card-2-copy',
    parentId: 'tpl-beautypricing-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-showcase-card-3',
    parentId: 'tpl-beautypricing-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-card-3-title',
    parentId: 'tpl-beautypricing-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-showcase-card-3-copy',
    parentId: 'tpl-beautypricing-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-quote',
    parentId: 'tpl-beautypricing-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-quote-mark',
    parentId: 'tpl-beautypricing-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-quote-body',
    parentId: 'tpl-beautypricing-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-quote-role',
    parentId: 'tpl-beautypricing-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-cta-label',
    parentId: 'tpl-beautypricing-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-cta-title',
    parentId: 'tpl-beautypricing-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-cta-copy',
    parentId: 'tpl-beautypricing-wix-cta',
    rect: { x: 64, y: 214, width: 560, height: 64 },
    text: '짧은 설득 문구, 보조 안내, 두 개의 행동 버튼을 같은 영역에 묶어 전환 흐름을 분명하게 만듭니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-beautypricing-wix-cta-primary',
    parentId: 'tpl-beautypricing-wix-cta',
    rect: { x: 64, y: 318, width: 178, height: 52 },
    label: '문의 시작',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#e8a838', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-beautypricing-wix-cta-secondary',
    parentId: 'tpl-beautypricing-wix-cta',
    rect: { x: 266, y: 318, width: 176, height: 52 },
    label: '자세히 보기',
    href: '#services',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-cta-note',
    parentId: 'tpl-beautypricing-wix-cta',
    rect: { x: 64, y: 402, width: 420, height: 30 },
    text: 'Global header와 footer는 그대로 두고 인페이지 전환만 보강합니다.',
    fontSize: 13,
    color: 'rgba(255,255,255,0.68)',
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-beautypricing-wix-timeline',
    parentId: 'tpl-beautypricing-wix-cta',
    rect: { x: 690, y: 70, width: 360, height: 390 },
    background: 'rgba(255,255,255,0.10)',
    borderColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-timeline-label',
    parentId: 'tpl-beautypricing-wix-timeline',
    rect: { x: 28, y: 28, width: 240, height: 24 },
    text: 'Decision path',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-timeline-1-title',
    parentId: 'tpl-beautypricing-wix-timeline',
    rect: { x: 28, y: 76, width: 260, height: 28 },
    text: '1. 이해',
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-beautypricing-wix-timeline-1-body',
    parentId: 'tpl-beautypricing-wix-timeline',
    rect: { x: 28, y: 110, width: 270, height: 40 },
    text: '문제, 대상, 제공 가치를 먼저 정렬합니다.',
    fontSize: 14,
    color: 'rgba(255,255,255,0.76)',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
]);

export const beautyPricingTemplate: PageTemplate = {
  id: 'beauty-pricing',
  name: '가격표 & 패키지',
  category: 'beauty',
  subcategory: 'pricing',
  description: '가격표 제목 + 3개 패키지 티어(이름/가격/설명/기능 목록/예약 버튼)',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
