import type { Locale } from '@/lib/locales';

export function getPublishReadinessCopy(locale: Locale) {
  switch (locale) {
    case 'ko':
      return {
        publishReadyLabel: '게시 준비 완료',
        publishBlockedLabel: '게시 차단',
        savedDraftRequiredStatusLabel: '초안 저장 필요',
        issuesLabel: (count: number) => `이슈 ${count}건`,
        checkedLabel: (checkedAt: string) => `검사 ${checkedAt}`,
        draftLabel: (revision: number) => `초안 v${revision}`,
        noDraftLabel: '초안 없음',
        publishedLabel: (revision: number) => `게시본 v${revision}`,
        noPublishedBaselineLabel: '게시 기준본 없음',
        pageValidationLabel: '페이지 검증',
        pagePublishableDescription: '현재 페이지 스냅샷은 게시할 수 있습니다.',
        pageNeedsFixesDescription: '현재 페이지 스냅샷은 게시 전에 수정이 필요합니다.',
        pageNeedsSavedDraftDescription: '게시 가능 여부는 저장된 초안이 있어야 확정할 수 있습니다.',
        datasetBindingLabel: '데이터셋 연결',
        datasetBindingDescription: '데이터셋 연결 상태는 아래 샘플 레코드 미리보기와 함께 별도로 검토됩니다.',
        publishPageLabel: '페이지 게시',
        publishingLabel: '게시 중...',
        publishCompletedDescription: '게시가 완료되었습니다. 아래 검사 결과를 새로고침했습니다.',
        validationIssuesLabel: '검증 이슈',
        refreshingLabel: '새로고침 중...',
        runChecksLabel: '게시 검사 실행',
        noValidationIssuesDescription: '현재 스냅샷에서 검증 이슈가 발견되지 않았습니다.',
        draftRequiredLabel: '저장된 초안 필요',
        draftRequiredDescription: '저장된 초안이 있어야 게시 검사를 다시 실행할 수 있습니다.',
        noDraftPublishDescription: '이 로케일에는 게시할 저장 초안이 없습니다.',
        refreshFailedDescription: '게시 검사를 새로고침할 수 없습니다.',
        publishFailedDescription: '게시하지 못했습니다.',
      };
    case 'zh-hant':
      return {
        publishReadyLabel: '可發佈',
        publishBlockedLabel: '發佈受阻',
        savedDraftRequiredStatusLabel: '需要儲存草稿',
        issuesLabel: (count: number) => `問題 ${count} 項`,
        checkedLabel: (checkedAt: string) => `已檢查 ${checkedAt}`,
        draftLabel: (revision: number) => `草稿 v${revision}`,
        noDraftLabel: '沒有草稿',
        publishedLabel: (revision: number) => `已發佈 v${revision}`,
        noPublishedBaselineLabel: '沒有已發佈基準',
        pageValidationLabel: '頁面驗證',
        pagePublishableDescription: '目前頁面快照可發佈。',
        pageNeedsFixesDescription: '目前頁面快照需要修正後才能發佈。',
        pageNeedsSavedDraftDescription: '需要已儲存草稿，才能確認是否可發佈。',
        datasetBindingLabel: '資料集綁定',
        datasetBindingDescription: '資料集接縫會在下方搭配範例記錄預覽另行檢查。',
        publishPageLabel: '發佈頁面',
        publishingLabel: '發佈中...',
        publishCompletedDescription: '發佈完成。下方檢查結果已更新。',
        validationIssuesLabel: '驗證問題',
        refreshingLabel: '更新中...',
        runChecksLabel: '執行發佈檢查',
        noValidationIssuesDescription: '目前快照未發現驗證問題。',
        draftRequiredLabel: '需要已儲存草稿',
        draftRequiredDescription: '需要已儲存草稿，才能重新執行發佈檢查。',
        noDraftPublishDescription: '此語言版本沒有可發佈的已儲存草稿。',
        refreshFailedDescription: '無法更新發佈檢查。',
        publishFailedDescription: '發佈失敗。',
      };
    case 'en':
    default:
      return {
        publishReadyLabel: 'Publish ready',
        publishBlockedLabel: 'Publish blocked',
        savedDraftRequiredStatusLabel: 'Saved draft required',
        issuesLabel: (count: number) => `Issues ${count}`,
        checkedLabel: (checkedAt: string) => `Checked ${checkedAt}`,
        draftLabel: (revision: number) => `Draft v${revision}`,
        noDraftLabel: 'No draft',
        publishedLabel: (revision: number) => `Published v${revision}`,
        noPublishedBaselineLabel: 'No published baseline',
        pageValidationLabel: 'Page validation',
        pagePublishableDescription: 'Current page snapshot is publishable.',
        pageNeedsFixesDescription: 'Current page snapshot needs fixes before publish.',
        pageNeedsSavedDraftDescription: 'A saved draft is required before publish readiness can be confirmed.',
        datasetBindingLabel: 'Dataset binding',
        datasetBindingDescription: 'Dataset seams are reviewed separately below with their sample record preview.',
        publishPageLabel: 'Publish page',
        publishingLabel: 'Publishing...',
        publishCompletedDescription: 'Publish completed. Checks refreshed below.',
        validationIssuesLabel: 'Validation issues',
        refreshingLabel: 'Refreshing...',
        runChecksLabel: 'Run publish checks',
        noValidationIssuesDescription: 'No validation issues were found in the current snapshot.',
        draftRequiredLabel: 'Saved draft required',
        draftRequiredDescription: 'A saved draft is required before publish checks can be refreshed.',
        noDraftPublishDescription: 'No saved draft exists for this locale.',
        refreshFailedDescription: 'Publish checks could not be refreshed.',
        publishFailedDescription: 'Publish failed.',
      };
  }
}
