import { act, isValidElement, type ReactNode, type ReactElement } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { beforeEach, afterEach, it, expect, vi } from 'vitest';
import Client from '../PublicCheckout';
import { commerceCartStorageKey } from '@/lib/builder/commerce/cart-shared';
type Control={children?:ReactNode;onSubmit?:(event:{preventDefault:()=>void})=>Promise<void>;onBlur?:(event:{target:{value:string}})=>void;onClick?:()=>void;onChange?:(event:{target:{value:string}})=>void;[key:string]:unknown};
const roots=new Set<Root>();const post=vi.fn<typeof fetch>();const storage=new Map<string,string>();const writes=vi.fn((k:string,v:string)=>{storage.set(k,v);});
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status});
const confirmation={orderId:'synthetic-order',confirmationNumber:'SYNTHETIC-1',locale:'en',currency:'TWD',totals:{grandTotalCents:100},payment:{status:'requires_manual_payment'}};
function find(tree:ReactNode,p:(e:ReactElement<Control>)=>boolean):ReactElement<Control>|undefined{if(Array.isArray(tree)){for(const c of tree){const x=find(c,p);if(x)return x;}}else if(isValidElement<Control>(tree)){if(p(tree))return tree;return find(tree.props.children,p);}return undefined;}
function textContent(tree: ReactNode): string { if (typeof tree === 'string' || typeof tree === 'number') return String(tree); if (Array.isArray(tree)) return tree.map(textContent).join(' '); return isValidElement<Control>(tree) ? textContent(tree.props.children) : ''; }
async function mount(initialLocale:'en'|'ko'|'zh-hant'='en'){
 const doc={activeElement:null,addEventListener:vi.fn(),removeEventListener:vi.fn(),documentElement:{namespaceURI:'http://www.w3.org/1999/xhtml'},nodeType:9};
 const container={nodeType:1,nodeName:'DIV',tagName:'DIV',namespaceURI:'http://www.w3.org/1999/xhtml',ownerDocument:doc,textContent:'',addEventListener:vi.fn(),removeEventListener:vi.fn(),appendChild:vi.fn(),removeChild:vi.fn()};
 vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('document',doc);vi.stubGlobal('window',{HTMLIFrameElement:function(){},localStorage:{getItem:(k:string)=>storage.get(k)??null,setItem:writes,removeItem:(k:string)=>storage.delete(k)}});
 let tree:ReactNode;let locale:'en'|'ko'|'zh-hant'=initialLocale;function Probe(){tree=Client({locale});return null;}
 const root=createRoot(container as unknown as Element);roots.add(root);await act(async()=>root.render(<Probe/>));
 return {handler:()=>find(tree,e=>e.type==='form')!.props.onSubmit!,control:(predicate:(e:ReactElement<Control>)=>boolean)=>find(tree,predicate)?.props,unknown:()=>find(tree,e=>e.props['data-commerce-checkout-unknown']!==undefined),fresh:()=>find(tree,e=>e.props['data-commerce-checkout-new-order']!==undefined)?.props.onClick,submit:()=>find(tree,e=>e.type==='form')!.props.onSubmit!({preventDefault:vi.fn()}),button:()=>find(tree,e=>e.props['data-commerce-checkout-submit']!==undefined)?.props,confirmed:()=>Boolean(find(tree,e=>e.props['data-commerce-checkout-confirmed']==='true')),locale:async(next:'en'|'ko'|'zh-hant'='ko')=>{locale=next;await act(async()=>root.render(<Probe/>));},unmount:async()=>{await act(async()=>root.unmount());roots.delete(root);}};
}
beforeEach(()=>{storage.clear();writes.mockClear();writes.mockImplementation((k,v)=>{storage.set(k,v);});post.mockReset();vi.stubGlobal('fetch',vi.fn((url:RequestInfo|URL,init?:RequestInit)=>init?.method==='POST'?post(url,init):Promise.resolve(reply({ok:true,rules:[]}))));storage.set(commerceCartStorageKey('en'),JSON.stringify({version:1,locale:'en',currency:'TWD',items:[{itemId:'p::default',productId:'p',productSlug:'p',title:'Synthetic',sku:'S',priceCents:100,currency:'TWD',quantity:1,maxQuantity:5,optionValues:{}}],updatedAt:'2026-01-01'}));});
beforeEach(()=>{for(const locale of ['ko','zh-hant'] as const){const value=JSON.parse(storage.get(commerceCartStorageKey('en'))!);value.locale=locale;storage.set(commerceCartStorageKey(locale),JSON.stringify(value));}});

afterEach(async()=>{for(const r of roots)await act(async()=>r.unmount());roots.clear();vi.unstubAllGlobals();});
it('transport loss after simulated server commit must not enable ordinary replay',async()=>{let committed=0;post.mockImplementation(async()=>{committed++;throw new Error('Synthetic reply loss after commit');});const s=await mount();await act(async()=>{await s.submit();});expect(committed).toBe(1);expect(s.button()?.disabled).toBe(true);});
it('same-turn double events dispatch one POST',async()=>{let resolve!:(r:Response)=>void;const wait=new Promise<Response>(yes=>{resolve=yes;});post.mockReturnValue(wait);const s=await mount();let a!:Promise<void>,b!:Promise<void>;await act(async()=>{a=s.submit();b=s.submit();});const calls=post.mock.calls.length;await act(async()=>{resolve(reply({ok:false,errorCode:'checkout_validation_error'},400));await Promise.all([a,b]);});expect(calls).toBe(1);});
it('acknowledged order remains confirmed when localStorage throws',async()=>{post.mockResolvedValue(reply({ok:true,checkout:confirmation}));const s=await mount();writes.mockImplementation(()=>{throw new Error('Synthetic quota');});let rejected:unknown;await act(async()=>{try{await s.submit();}catch(e){rejected=e;}});expect(s.confirmed()).toBe(true);expect(rejected).toBeUndefined();});
it('known pre-effect validation rejection allows correction without clearing cart',async()=>{post.mockResolvedValue(reply({ok:false,errorCode:'checkout_validation_error'},400));const s=await mount();await act(async()=>{await s.submit();});expect(s.button()?.disabled).toBe(false);expect(storage.has(commerceCartStorageKey('en'))).toBe(true);});
it('HTTP500 has unknown outcome and must not enable ordinary replay',async()=>{post.mockResolvedValue(reply({ok:false,errorCode:'checkout_failed'},500));const s=await mount();await act(async()=>{await s.submit();});expect(s.button()?.disabled).toBe(true);});
it('late success after unmount must not mutate browser storage',async()=>{let resolve!:(r:Response)=>void;const wait=new Promise<Response>(yes=>{resolve=yes;});post.mockReturnValue(wait);const s=await mount();let pending!:Promise<void>;await act(async()=>{pending=s.submit();});await s.unmount();await act(async()=>{resolve(reply({ok:true,checkout:confirmation}));await pending;});expect(writes).not.toHaveBeenCalled();expect(storage.has(commerceCartStorageKey('en'))).toBe(true);});

it('retained instance locale change cannot adopt previous locale success',async()=>{let resolve!:(r:Response)=>void;const wait=new Promise<Response>(yes=>{resolve=yes;});post.mockReturnValue(wait);const s=await mount();let pending!:Promise<void>;await act(async()=>{pending=s.submit();});await s.locale();await act(async()=>{resolve(reply({ok:true,checkout:confirmation}));await pending;});expect(s.confirmed()).toBe(false);expect(writes).not.toHaveBeenCalled();});

it('unknown survives edits and explicit new order starts a different task only',async()=>{
 post.mockRejectedValueOnce(new Error('transport'));const s=await mount();await act(async()=>{await s.submit();});
 expect(s.unknown()).toBeDefined();await act(async()=>{s.control(e=>e.props['data-commerce-checkout-name']!==undefined)?.onChange?.({target:{value:'Changed'}});await s.submit();});expect(post).toHaveBeenCalledTimes(1);expect(s.unknown()).toBeDefined();
 const warning=textContent(s.unknown()?.props.children);expect(warning).toContain('previous order may already exist');expect(warning).toContain('duplicate');
 await act(async()=>{s.fresh()?.();});expect(s.unknown()).toBeUndefined();expect(post).toHaveBeenCalledTimes(1);
 post.mockResolvedValueOnce(reply({ok:true,checkout:confirmation}));await act(async()=>{await s.submit();});expect(post).toHaveBeenCalledTimes(2);expect(s.confirmed()).toBe(true);
});
it('invalidated pending locale retains unknown before deliberate new task',async()=>{
 let resolve!:(r:Response)=>void;post.mockReturnValueOnce(new Promise<Response>(yes=>{resolve=yes;}));const s=await mount();let pending!:Promise<void>;await act(async()=>{pending=s.submit();});await s.locale();expect(s.unknown()).toBeDefined();expect(s.button()?.disabled).toBe(true);
 await act(async()=>{await s.submit();});expect(post).toHaveBeenCalledTimes(1);await act(async()=>{resolve(reply({ok:true,checkout:confirmation}));await pending;});expect(s.unknown()).toBeDefined();expect(writes).not.toHaveBeenCalled();
 await act(async()=>{s.fresh()?.();});expect(s.unknown()).toBeUndefined();post.mockResolvedValueOnce(reply({ok:false,errorCode:'checkout_validation_error'},400));await act(async()=>{await s.submit();});expect(JSON.parse(String(post.mock.calls[1][1]?.body)).locale).toBe('ko');
});
it.each([
 ['ko','이전 주문이 이미 생성'],['zh-hant','先前的訂單可能已建立'],['en','previous order may already exist'],
] as const)('discloses uncertainty in %s',async(locale,message)=>{post.mockRejectedValueOnce(new Error('transport'));const s=await mount(locale);await act(async()=>{await s.submit();});expect(textContent(s.unknown()?.props.children)).toContain(message);});
it.each([
 [400,'unrecognized'],[500,'checkout_failed'],[503,'unrecognized'],[400,'invalid_json'],
] as const)('does not infer no-effects solely from status %s / %s',async(status,errorCode)=>{post.mockResolvedValue(reply({ok:false,errorCode},status));const s=await mount();await act(async()=>{await s.submit();});expect(s.unknown()).toBeDefined();expect(s.button()?.disabled).toBe(true);});
it.each([[400,'checkout_validation_error'],[429,'too_many_requests'],[503,'payment_provider_not_configured']] as const)('recognizes explicit pre-effect %s / %s',async(status,errorCode)=>{post.mockResolvedValue(reply({ok:false,errorCode},status));const s=await mount();await act(async()=>{await s.submit();});expect(s.unknown()).toBeUndefined();expect(s.button()?.disabled).toBe(false);});
it.each([
 {...confirmation,orderId:''}, {...confirmation,locale:'ko'}, {...confirmation,currency:'USD'}, {...confirmation,totals:{grandTotalCents:-1}}, {...confirmation,payment:{status:null}},
])('invalid successful confirmation is outcome unknown',async(checkout)=>{post.mockResolvedValue(reply({ok:true,checkout}));const s=await mount();await act(async()=>{await s.submit();});expect(s.confirmed()).toBe(false);expect(s.unknown()).toBeDefined();expect(writes).not.toHaveBeenCalled();});
it('unreadable successful response remains unknown',async()=>{post.mockResolvedValue(new Response('{',{status:200}));const s=await mount();await act(async()=>{await s.submit();});expect(s.unknown()).toBeDefined();expect(writes).not.toHaveBeenCalled();});
it('pending controls are frozen and synthetic edits cannot change submitted draft',async()=>{let resolve!:(r:Response)=>void;post.mockReturnValueOnce(new Promise<Response>(yes=>{resolve=yes;}));const s=await mount();let pending!:Promise<void>;await act(async()=>{pending=s.submit();});const name=s.control(e=>e.props['data-commerce-checkout-name']!==undefined);expect(name?.disabled).toBe(true);await act(async()=>{name?.onChange?.({target:{value:'Not accepted'}});});expect(s.control(e=>e.props['data-commerce-checkout-name']!==undefined)?.value).not.toBe('Not accepted');await act(async()=>{resolve(reply({ok:false,errorCode:'checkout_validation_error'},400));await pending;});expect(s.control(e=>e.props['data-commerce-checkout-name']!==undefined)?.disabled).toBe(false);});
it('cart removal failure preserves success and discloses browser storage limit',async()=>{post.mockResolvedValue(reply({ok:true,checkout:confirmation}));const s=await mount();vi.spyOn(window.localStorage,'removeItem').mockImplementation(()=>{throw new Error('Synthetic removal failure');});await act(async()=>{await s.submit();});expect(s.confirmed()).toBe(true);expect(s.control(e=>e.props['data-commerce-checkout-storage-warning']==='true')).toBeDefined();expect(storage.has(commerceCartStorageKey('en'))).toBe(true);});

it('retained old submit after committed locale switch cannot POST the old cart',async()=>{const s=await mount();const old=s.handler();await s.locale();post.mockResolvedValue(reply({ok:false,errorCode:'checkout_validation_error'},400));await act(async()=>{await old({preventDefault:vi.fn()});});expect(post).not.toHaveBeenCalled();});
it('retained old submit cannot rejoin after locale roundtrip',async()=>{const s=await mount();const old=s.handler();await s.locale('ko');await s.locale('en');post.mockResolvedValue(reply({ok:false,errorCode:'checkout_validation_error'},400));await act(async()=>{await old({preventDefault:vi.fn()});});expect(post).not.toHaveBeenCalled();await act(async()=>{await s.submit();});expect(post).toHaveBeenCalledTimes(1);});
it('old new-order callback cannot release another locale unknown session',async()=>{post.mockRejectedValue(new Error('lost'));const s=await mount();await act(async()=>{await s.submit();});const old=s.fresh();await s.locale('ko');await act(async()=>{old?.();});expect(s.unknown()).toBeDefined();expect(post).toHaveBeenCalledTimes(1);});
it('old submit cannot rejoin a deliberate new task in the same locale',async()=>{const s=await mount();const old=s.handler();post.mockRejectedValueOnce(new Error('lost'));await act(async()=>{await s.submit();});await act(async()=>{s.fresh()?.();});post.mockResolvedValue(reply({ok:false,errorCode:'checkout_validation_error'},400));await act(async()=>{await old({preventDefault:vi.fn()});});expect(post).toHaveBeenCalledTimes(1);await act(async()=>{await s.submit();});expect(post).toHaveBeenCalledTimes(2);});
it('same-session rerender preserves a legitimate active callback',async()=>{const s=await mount();const current=s.handler();await act(async()=>{s.control(e=>e.props['data-commerce-checkout-name']!==undefined)?.onChange?.({target:{value:'Same session'}});});post.mockResolvedValue(reply({ok:false,errorCode:'checkout_validation_error'},400));await act(async()=>{await current({preventDefault:vi.fn()});});expect(post).toHaveBeenCalledTimes(1);});

it('retained recovery callback cannot dispatch after locale ownership changes',async()=>{const s=await mount();const old=s.control(e=>e.props['data-commerce-checkout-email']!==undefined)?.onBlur;await s.locale('ko');await act(async()=>{old?.({target:{value:'synthetic@example.invalid'}});});expect(post).not.toHaveBeenCalled();});
