import { NextRequest, NextResponse } from 'next/server';
import { encryptToken } from '@/lib/builder/bookings/calendar-sync/encryption';
import { exchangeGoogleCode } from '@/lib/builder/bookings/calendar-sync/google';
import { exchangeOutlookCode } from '@/lib/builder/bookings/calendar-sync/outlook';
import { verifyOauthState } from '@/lib/builder/bookings/calendar-sync/oauth-state';
import {
  makeConnectionId,
  saveConnection,
} from '@/lib/builder/bookings/calendar-sync/storage';
import type { CalendarConnection } from '@/lib/builder/bookings/calendar-sync/types';
import { requireBuilderAdminAuth } from '@/lib/builder/columns/auth';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * OAuth callback for Google + Outlook calendar sync.
 *
 * SECURITY (CSRF + identity binding):
 *   1. Admin auth required — caller must hold the same basic-auth session
 *      that initiated the OAuth flow. Without this, anyone who obtains a
 *      valid OAuth code could attach their refresh token to an arbitrary
 *      staffId by replaying the callback URL.
 *   2. State HMAC verification — see `oauth-state.ts`. Format is
 *        `<provider>:<staffId>:<expiresAtMs>:<hexHmac>`
 *      signed with OAUTH_STATE_SECRET. Constant-time compare. Expired
 *      states (> 10 min) are rejected.
 *
 * The OAuth initiator on the admin UI must use `buildOauthState()` from
 * `@/lib/builder/bookings/calendar-sync/oauth-state` so the callback's
 * verifyOauthState() can validate the signature.
 */

export async function GET(request: NextRequest) {
  // 1. Admin auth — the callback URL must only ever be hit by an
  // authenticated admin operator. Blocks unauthenticated attackers from
  // replaying the callback with their own OAuth code + a forged staffId.
  const auth = requireBuilderAdminAuth(request);
  if (auth instanceof NextResponse) return auth;

  const code = request.nextUrl.searchParams.get('code') ?? '';
  const state = request.nextUrl.searchParams.get('state') ?? '';
  const errorParam = request.nextUrl.searchParams.get('error');
  if (errorParam) {
    return NextResponse.json({ error: `OAuth provider error: ${errorParam}` }, { status: 400 });
  }
  if (!code || !state) {
    return NextResponse.json({ error: 'Missing code or state' }, { status: 400 });
  }

  // 2. HMAC-verified state — proves the state was generated by this server
  // within the last 10 minutes and binds the OAuth code to the named
  // staffId. Without this an attacker with any OAuth code could attach
  // their token to an arbitrary staff record by forging `state`.
  const verified = verifyOauthState(state);
  if (!verified) {
    return NextResponse.json({ error: 'Invalid or expired state' }, { status: 400 });
  }
  const { provider, staffId } = verified;

  const exchange = provider === 'google'
    ? await exchangeGoogleCode(code)
    : await exchangeOutlookCode(code);
  if (!exchange.ok) {
    return NextResponse.json({ error: exchange.error }, { status: 502 });
  }

  let encrypted: string;
  try {
    encrypted = encryptToken(exchange.refreshToken);
  } catch (err) {
    return NextResponse.json({ error: err instanceof Error ? err.message : 'encrypt failed' }, { status: 500 });
  }

  const now = new Date().toISOString();
  const connection: CalendarConnection = {
    connectionId: makeConnectionId(staffId, provider),
    staffId,
    provider,
    refreshTokenEncrypted: encrypted,
    scope: provider === 'google'
      ? 'https://www.googleapis.com/auth/calendar.events'
      : 'offline_access Calendars.ReadWrite',
    status: 'connected',
    createdAt: now,
    updatedAt: now,
  };
  await saveConnection(connection);
  return NextResponse.json({ ok: true, connectionId: connection.connectionId, provider, staffId });
}
