import { NextRequest, NextResponse } from 'next/server';
import { encryptToken } from '@/lib/builder/bookings/calendar-sync/encryption';
import { exchangeGoogleCode } from '@/lib/builder/bookings/calendar-sync/google';
import { exchangeOutlookCode } from '@/lib/builder/bookings/calendar-sync/outlook';
import { verifyOauthState } from '@/lib/builder/bookings/calendar-sync/oauth-state';
import {
  makeConnectionId,
  saveConnection,
} from '@/lib/builder/bookings/calendar-sync/storage';
import type { CalendarConnection } from '@/lib/builder/bookings/calendar-sync/types';
import { guardBuilderReadWithPermission } from '@/lib/builder/security/guard';
import {
  getBookingCalendarSyncConnectApiErrorPayload,
  type BookingCalendarSyncConnectApiErrorCode,
} from '@/lib/builder/bookings/bookings-copy';
import { normalizeLocale, type Locale } from '@/lib/locales';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

function errorResponse(
  locale: Locale,
  errorCode: BookingCalendarSyncConnectApiErrorCode,
  status: number,
) {
  return NextResponse.json(
    getBookingCalendarSyncConnectApiErrorPayload(locale, errorCode),
    { status },
  );
}

/**
 * OAuth callback for Google + Outlook calendar sync.
 *
 * SECURITY (CSRF + identity binding):
 *   1. Booking-management permission required — caller must be an
 *      authenticated operator allowed to mutate booking integrations.
 *      Without this, a read-only operator who obtains a valid OAuth code
 *      could attach a refresh token to a staff record.
 *   2. State HMAC verification — see `oauth-state.ts`. Format is
 *        `<provider>:<staffId>:<expiresAtMs>:<hexHmac>`
 *      signed with OAUTH_STATE_SECRET. Constant-time compare. Expired
 *      states (> 10 min) are rejected.
 *
 * The OAuth initiator on the admin UI must use `buildOauthState()` from
 * `@/lib/builder/bookings/calendar-sync/oauth-state` so the callback's
 * verifyOauthState() can validate the signature.
 */

export async function GET(request: NextRequest) {
  // 1. Booking-management permission — the callback URL mutates the
  // stored calendar connection, so read-only booking access is not enough.
  // This still preserves the provider's conventional GET callback.
  const auth = await guardBuilderReadWithPermission(request, 'manage-bookings');
  if (auth instanceof NextResponse) return auth;

  const code = request.nextUrl.searchParams.get('code') ?? '';
  const state = request.nextUrl.searchParams.get('state') ?? '';
  const locale = normalizeLocale(request.nextUrl.searchParams.get('locale') ?? undefined);
  const errorParam = request.nextUrl.searchParams.get('error');
  if (errorParam) {
    return errorResponse(locale, 'oauth_provider_error', 400);
  }
  if (!code || !state) {
    return errorResponse(locale, 'missing_oauth_params', 400);
  }

  // 2. HMAC-verified state — proves the state was generated by this server
  // within the last 10 minutes and binds the OAuth code to the named
  // staffId. Without this an attacker with any OAuth code could attach
  // their token to an arbitrary staff record by forging `state`.
  const verified = verifyOauthState(state);
  if (!verified) {
    return errorResponse(locale, 'invalid_oauth_state', 400);
  }
  const { provider, staffId } = verified;

  const exchange = provider === 'google'
    ? await exchangeGoogleCode(code)
    : await exchangeOutlookCode(code);
  if (!exchange.ok) {
    return errorResponse(locale, 'token_exchange_failed', 502);
  }

  let encrypted: string;
  try {
    encrypted = encryptToken(exchange.refreshToken);
  } catch {
    return errorResponse(locale, 'token_encrypt_failed', 500);
  }

  const now = new Date().toISOString();
  const connection: CalendarConnection = {
    connectionId: makeConnectionId(staffId, provider),
    staffId,
    provider,
    refreshTokenEncrypted: encrypted,
    scope: provider === 'google'
      ? 'https://www.googleapis.com/auth/calendar.events'
      : 'offline_access Calendars.ReadWrite',
    status: 'connected',
    createdAt: now,
    updatedAt: now,
  };
  await saveConnection(connection);
  return NextResponse.json({ ok: true, connectionId: connection.connectionId, provider, staffId });
}
