import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const MARGIN = 80;
const CONTENT_W = W - MARGIN * 2;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const HEADER_H = 140;
const LIST_Y = HEADER_H + 40;
const LIST_H = 300;
const COVERAGE_Y = LIST_Y + LIST_H + 80;
const COVERAGE_H = 240;
const FAQ_Y = COVERAGE_Y + COVERAGE_H + 80;
const FAQ_ITEM_H = 100;
const FAQ_GAP = 16;
const FAQ_COUNT = 4;
const STAGE_H = FAQ_Y + FAQ_COUNT * (FAQ_ITEM_H + FAQ_GAP) + 80;

interface BillingFaq {
  key: string;
  q: string;
  a: string;
}

const billingFaqs: BillingFaq[] = [
  { key: 'claim', q: '보험 청구는 어떻게 하나요?', a: '원무과에서 보험 청구 서류를 발급해 드립니다. 실손보험의 경우 진단서와 영수증을 보험사에 제출하시면 됩니다.' },
  { key: 'uninsured', q: '비급여 항목은 무엇인가요?', a: '미용 시술, 일부 건강검진 항목, 선택 진료 등이 비급여에 해당합니다. 상세 내역은 원무과에 문의해 주세요.' },
  { key: 'payment', q: '결제 방법은 어떤 것이 있나요?', a: '현금, 카드(신용/체크), 계좌이체, 간편결제(카카오페이, 네이버페이)를 지원합니다.' },
  { key: 'installment', q: '분할 납부가 가능한가요?', a: '고액 진료비의 경우 카드 무이자 할부(2~6개월)를 이용하실 수 있습니다. 상세 내용은 수납 창구에서 안내드립니다.' },
];

function buildBillingFaqItem(faq: BillingFaq, idx: number): BuilderCanvasNode[] {
  const y = FAQ_Y + idx * (FAQ_ITEM_H + FAQ_GAP);
  const cid = `tpl-healthins-faq-${faq.key}`;

  return [
    createContainerNode({
      id: cid,
      rect: { x: MARGIN, y, width: CONTENT_W, height: FAQ_ITEM_H },
      background: idx % 2 === 0 ? '#ffffff' : '#f9fafb',
      borderRadius: 10,
      borderColor: '#e2e8f0',
      borderWidth: 1,
      padding: 20,
    }),
    heading(`${cid}-q`, { x: 20, y: 12, width: CONTENT_W - 60, height: 28 }, faq.q, 3, '#123b63', 'left', cid),
    createTextNode({
      id: `${cid}-a`,
      parentId: cid,
      rect: { x: 20, y: 48, width: CONTENT_W - 60, height: 40 },
      text: faq.a,
      fontSize: 14,
      color: '#374151',
      lineHeight: 1.55,
    }),
  ];
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  heading(
    'tpl-healthins-title',
    { x: MARGIN, y: 50, width: 500, height: 56 },
    '보험 및 수납 안내',
    1,
    '#123b63',
  ),
  createTextNode({
    id: 'tpl-healthins-subtitle',
    rect: { x: MARGIN, y: 110, width: 700, height: 32 },
    text: '보험 적용 및 수납에 관한 안내입니다.',
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 1.4,
  }),

  /* ── Accepted insurance list ─────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthins-list',
    rect: { x: MARGIN, y: LIST_Y, width: CONTENT_W, height: LIST_H },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 32,
  }),
  heading(
    'tpl-healthins-list-title',
    { x: 32, y: 24, width: 400, height: 40 },
    '적용 보험 목록',
    2,
    '#123b63',
    'left',
    'tpl-healthins-list',
  ),
  createTextNode({
    id: 'tpl-healthins-list-items',
    parentId: 'tpl-healthins-list',
    rect: { x: 32, y: 80, width: 900, height: 180 },
    text: '국민건강보험 | 삼성화재 실손보험 | 현대해상 실손보험 | DB손해보험 | KB손해보험 | 메리츠화재 | 한화손해보험 | NH농협손해보험 | 롯데손해보험 | 흥국화재',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.8,
  }),

  /* ── Coverage info ───────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthins-coverage',
    rect: { x: 0, y: COVERAGE_Y, width: W, height: COVERAGE_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading(
    'tpl-healthins-coverage-title',
    { x: MARGIN, y: 40, width: 400, height: 44 },
    '보장 안내',
    2,
    '#ffffff',
    'left',
    'tpl-healthins-coverage',
  ),
  createTextNode({
    id: 'tpl-healthins-coverage-desc',
    parentId: 'tpl-healthins-coverage',
    rect: { x: MARGIN, y: 100, width: 800, height: 100 },
    text: '국민건강보험 적용 시 본인부담금만 납부하시면 됩니다. 실손보험 가입자의 경우 비급여 항목에 대해서도 보험 청구가 가능합니다. 보험 청구에 필요한 서류는 원무과에서 당일 발급해 드립니다.',
    fontSize: 16,
    color: 'rgba(255,255,255,0.9)',
    lineHeight: 1.7,
  }),

  /* ── Billing FAQ ─────────────────────────────────────────── */
  heading(
    'tpl-healthins-faq-title',
    { x: MARGIN, y: FAQ_Y - 50, width: 400, height: 40 },
    '수납 관련 FAQ',
    2,
    '#123b63',
  ),
  ...billingFaqs.flatMap((faq, i) => buildBillingFaqItem(faq, i)),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthinsurance-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-proof-label',
    parentId: 'tpl-healthinsurance-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-proof-title',
    parentId: 'tpl-healthinsurance-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'health insurance 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-proof-copy',
    parentId: 'tpl-healthinsurance-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-metric-1',
    parentId: 'tpl-healthinsurance-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-metric-1-value',
    parentId: 'tpl-healthinsurance-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-metric-1-label',
    parentId: 'tpl-healthinsurance-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-metric-2',
    parentId: 'tpl-healthinsurance-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-metric-2-value',
    parentId: 'tpl-healthinsurance-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-metric-2-label',
    parentId: 'tpl-healthinsurance-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-metric-3',
    parentId: 'tpl-healthinsurance-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-metric-3-value',
    parentId: 'tpl-healthinsurance-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-metric-3-label',
    parentId: 'tpl-healthinsurance-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-metric-4',
    parentId: 'tpl-healthinsurance-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-metric-4-value',
    parentId: 'tpl-healthinsurance-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-metric-4-label',
    parentId: 'tpl-healthinsurance-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-label',
    parentId: 'tpl-healthinsurance-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-title',
    parentId: 'tpl-healthinsurance-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-copy',
    parentId: 'tpl-healthinsurance-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-showcase-visual',
    parentId: 'tpl-healthinsurance-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-visual-title',
    parentId: 'tpl-healthinsurance-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-visual-copy',
    parentId: 'tpl-healthinsurance-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-showcase-card-1',
    parentId: 'tpl-healthinsurance-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-card-1-title',
    parentId: 'tpl-healthinsurance-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-card-1-copy',
    parentId: 'tpl-healthinsurance-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-showcase-card-2',
    parentId: 'tpl-healthinsurance-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-card-2-title',
    parentId: 'tpl-healthinsurance-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-card-2-copy',
    parentId: 'tpl-healthinsurance-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-showcase-card-3',
    parentId: 'tpl-healthinsurance-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-card-3-title',
    parentId: 'tpl-healthinsurance-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-showcase-card-3-copy',
    parentId: 'tpl-healthinsurance-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthinsurance-wix-quote',
    parentId: 'tpl-healthinsurance-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-quote-mark',
    parentId: 'tpl-healthinsurance-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-quote-body',
    parentId: 'tpl-healthinsurance-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-quote-role',
    parentId: 'tpl-healthinsurance-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-cta-label',
    parentId: 'tpl-healthinsurance-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-cta-title',
    parentId: 'tpl-healthinsurance-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-cta-copy',
    parentId: 'tpl-healthinsurance-wix-cta',
    rect: { x: 64, y: 214, width: 560, height: 64 },
    text: '짧은 설득 문구, 보조 안내, 두 개의 행동 버튼을 같은 영역에 묶어 전환 흐름을 분명하게 만듭니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-healthinsurance-wix-cta-primary',
    parentId: 'tpl-healthinsurance-wix-cta',
    rect: { x: 64, y: 318, width: 178, height: 52 },
    label: '문의 시작',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#e8a838', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-healthinsurance-wix-cta-secondary',
    parentId: 'tpl-healthinsurance-wix-cta',
    rect: { x: 266, y: 318, width: 176, height: 52 },
    label: '자세히 보기',
    href: '#services',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
  createTextNode({
    id: 'tpl-healthinsurance-wix-cta-note',
    parentId: 'tpl-healthinsurance-wix-cta',
    rect: { x: 64, y: 402, width: 420, height: 30 },
    text: 'Global header와 footer는 그대로 두고 인페이지 전환만 보강합니다.',
    fontSize: 13,
    color: 'rgba(255,255,255,0.68)',
    className: 'card-copy',
  }),
]);

export const healthInsuranceTemplate: PageTemplate = {
  id: 'health-insurance',
  name: '보험 및 수납',
  category: 'health',
  subcategory: 'insurance',
  description: '적용 보험 목록 + 보장 안내 + 수납 FAQ',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
