import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const MARGIN = 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const HEADER_H = 140;
const STORY_Y = HEADER_H + 40;
const STORY_H = 360;
const MISSION_Y = STORY_Y + STORY_H + 80;
const MISSION_H = 300;
const ACCRED_Y = MISSION_Y + MISSION_H + 80;
const ACCRED_H = 200;
const STAGE_H = ACCRED_Y + ACCRED_H + 80;

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  heading(
    'tpl-healthabout-title',
    { x: MARGIN, y: 50, width: 500, height: 56 },
    '병원 소개',
    1,
    '#123b63',
  ),
  createTextNode({
    id: 'tpl-healthabout-subtitle',
    rect: { x: MARGIN, y: 110, width: 700, height: 32 },
    text: '환자 중심의 의료 서비스를 실현하는 우리 병원을 소개합니다.',
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 1.4,
  }),

  /* ── Facility story ──────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthabout-story',
    rect: { x: 0, y: STORY_Y, width: W, height: STORY_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-healthabout-story-img',
    parentId: 'tpl-healthabout-story',
    rect: { x: MARGIN, y: 40, width: 450, height: 280 },
    src: '/images/placeholder-hospital.jpg',
    alt: '병원 건물 외관',
    style: { borderRadius: 12 },
  }),
  heading(
    'tpl-healthabout-story-title',
    { x: 580, y: 40, width: 400, height: 44 },
    '우리의 이야기',
    2,
    '#123b63',
    'left',
    'tpl-healthabout-story',
  ),
  createTextNode({
    id: 'tpl-healthabout-story-desc',
    parentId: 'tpl-healthabout-story',
    rect: { x: 580, y: 100, width: 500, height: 200 },
    text: '2005년 개원 이래 20년간 지역 사회의 건강을 책임져 왔습니다. 최신 의료 장비와 전문 의료진을 갖추고, 환자 한 분 한 분에게 최선의 진료를 제공하고 있습니다.',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.7,
  }),

  /* ── Mission / Vision ────────────────────────────────────── */
  heading(
    'tpl-healthabout-mission-title',
    { x: MARGIN, y: MISSION_Y, width: 500, height: 50 },
    '미션 & 비전',
    2,
    '#123b63',
  ),
  createContainerNode({
    id: 'tpl-healthabout-mission-box',
    rect: { x: MARGIN, y: MISSION_Y + 70, width: 500, height: 200 },
    background: '#123b63',
    borderRadius: 12,
    padding: 32,
  }),
  heading(
    'tpl-healthabout-mission-label',
    { x: 32, y: 20, width: 200, height: 36 },
    '미션',
    3,
    '#e8a838',
    'left',
    'tpl-healthabout-mission-box',
  ),
  createTextNode({
    id: 'tpl-healthabout-mission-text',
    parentId: 'tpl-healthabout-mission-box',
    rect: { x: 32, y: 64, width: 436, height: 100 },
    text: '모든 환자에게 최고 수준의 의료 서비스를 제공하며, 건강한 사회를 만드는 데 기여합니다.',
    fontSize: 16,
    color: 'rgba(255,255,255,0.9)',
    lineHeight: 1.7,
  }),
  createContainerNode({
    id: 'tpl-healthabout-vision-box',
    rect: { x: 620, y: MISSION_Y + 70, width: 500, height: 200 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 32,
  }),
  heading(
    'tpl-healthabout-vision-label',
    { x: 32, y: 20, width: 200, height: 36 },
    '비전',
    3,
    '#123b63',
    'left',
    'tpl-healthabout-vision-box',
  ),
  createTextNode({
    id: 'tpl-healthabout-vision-text',
    parentId: 'tpl-healthabout-vision-box',
    rect: { x: 32, y: 64, width: 436, height: 100 },
    text: '최첨단 의료 기술과 따뜻한 돌봄으로 지역 사회에서 가장 신뢰받는 병원이 되겠습니다.',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.7,
  }),

  /* ── Accreditations ──────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthabout-accred',
    rect: { x: 0, y: ACCRED_Y, width: W, height: ACCRED_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-healthabout-accred-title',
    { x: MARGIN, y: 40, width: 400, height: 44 },
    '인증 및 수상',
    2,
    '#123b63',
    'left',
    'tpl-healthabout-accred',
  ),
  createTextNode({
    id: 'tpl-healthabout-accred-desc',
    parentId: 'tpl-healthabout-accred',
    rect: { x: MARGIN, y: 100, width: 800, height: 60 },
    text: '보건복지부 의료기관 인증 | JCI 국제 의료기관 인증 | 환자안전 우수기관 선정 | 지역사회 봉사 공헌상',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.6,
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthabout-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-proof-label',
    parentId: 'tpl-healthabout-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-proof-title',
    parentId: 'tpl-healthabout-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'health about 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-proof-copy',
    parentId: 'tpl-healthabout-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-metric-1',
    parentId: 'tpl-healthabout-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-metric-1-value',
    parentId: 'tpl-healthabout-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-metric-1-label',
    parentId: 'tpl-healthabout-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-metric-2',
    parentId: 'tpl-healthabout-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-metric-2-value',
    parentId: 'tpl-healthabout-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-metric-2-label',
    parentId: 'tpl-healthabout-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-metric-3',
    parentId: 'tpl-healthabout-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-metric-3-value',
    parentId: 'tpl-healthabout-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-metric-3-label',
    parentId: 'tpl-healthabout-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-metric-4',
    parentId: 'tpl-healthabout-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-metric-4-value',
    parentId: 'tpl-healthabout-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-metric-4-label',
    parentId: 'tpl-healthabout-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-label',
    parentId: 'tpl-healthabout-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-title',
    parentId: 'tpl-healthabout-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-copy',
    parentId: 'tpl-healthabout-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-showcase-visual',
    parentId: 'tpl-healthabout-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-visual-title',
    parentId: 'tpl-healthabout-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-visual-copy',
    parentId: 'tpl-healthabout-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-showcase-card-1',
    parentId: 'tpl-healthabout-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-card-1-title',
    parentId: 'tpl-healthabout-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-card-1-copy',
    parentId: 'tpl-healthabout-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-showcase-card-2',
    parentId: 'tpl-healthabout-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-card-2-title',
    parentId: 'tpl-healthabout-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-card-2-copy',
    parentId: 'tpl-healthabout-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-showcase-card-3',
    parentId: 'tpl-healthabout-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-card-3-title',
    parentId: 'tpl-healthabout-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-showcase-card-3-copy',
    parentId: 'tpl-healthabout-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthabout-wix-quote',
    parentId: 'tpl-healthabout-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-quote-mark',
    parentId: 'tpl-healthabout-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-quote-body',
    parentId: 'tpl-healthabout-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-quote-role',
    parentId: 'tpl-healthabout-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-cta-label',
    parentId: 'tpl-healthabout-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-healthabout-wix-cta-title',
    parentId: 'tpl-healthabout-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
]);

export const healthAboutTemplate: PageTemplate = {
  id: 'health-about',
  name: '병원 소개',
  category: 'health',
  subcategory: 'about',
  description: '시설 스토리 + 미션/비전 + 인증 및 수상 내역',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
