import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const MARGIN = 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const HERO_H = 600;
const DEPT_Y = HERO_H + 80;
const DEPT_H = 420;
const APPT_Y = DEPT_Y + DEPT_H + 80;
const APPT_H = 240;
const INSURANCE_Y = APPT_Y + APPT_H + 80;
const INSURANCE_H = 200;
const STAGE_H = INSURANCE_Y + INSURANCE_H + 80;

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero ────────────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthhome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-healthhome-hero-bg',
    parentId: 'tpl-healthhome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    src: '/images/placeholder-health-hero.jpg',
    alt: '병원 시설 이미지',
    style: { opacity: 30, borderRadius: 0 },
  }),
  heading(
    'tpl-healthhome-hero-title',
    { x: MARGIN, y: 160, width: 600, height: 100 },
    '건강한 삶을 위한 동반자',
    1,
    '#ffffff',
    'left',
    'tpl-healthhome-hero',
  ),
  createTextNode({
    id: 'tpl-healthhome-hero-tagline',
    parentId: 'tpl-healthhome-hero',
    rect: { x: MARGIN, y: 280, width: 500, height: 60 },
    text: '최신 의료 장비와 전문 의료진이 여러분의 건강을 책임집니다.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-healthhome-hero-cta',
    parentId: 'tpl-healthhome-hero',
    rect: { x: MARGIN, y: 370, width: 200, height: 52 },
    label: '진료 예약',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Departments ─────────────────────────────────────────── */
  heading(
    'tpl-healthhome-dept-title',
    { x: MARGIN, y: DEPT_Y, width: 400, height: 50 },
    '진료 과목',
    2,
    '#123b63',
  ),
  // Card 1
  createContainerNode({
    id: 'tpl-healthhome-dept-1',
    rect: { x: MARGIN, y: DEPT_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-healthhome-dept-1-title', { x: 24, y: 24, width: 212, height: 36 }, '내과', 3, '#123b63', 'left', 'tpl-healthhome-dept-1'),
  createTextNode({
    id: 'tpl-healthhome-dept-1-desc',
    parentId: 'tpl-healthhome-dept-1',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '감기, 고혈압, 당뇨 등 내과 전반의 질환을 진단하고 치료합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 2
  createContainerNode({
    id: 'tpl-healthhome-dept-2',
    rect: { x: 370, y: DEPT_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-healthhome-dept-2-title', { x: 24, y: 24, width: 212, height: 36 }, '정형외과', 3, '#123b63', 'left', 'tpl-healthhome-dept-2'),
  createTextNode({
    id: 'tpl-healthhome-dept-2-desc',
    parentId: 'tpl-healthhome-dept-2',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '관절, 척추, 골절 등 근골격계 질환의 전문적인 진료를 제공합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 3
  createContainerNode({
    id: 'tpl-healthhome-dept-3',
    rect: { x: 660, y: DEPT_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-healthhome-dept-3-title', { x: 24, y: 24, width: 212, height: 36 }, '피부과', 3, '#123b63', 'left', 'tpl-healthhome-dept-3'),
  createTextNode({
    id: 'tpl-healthhome-dept-3-desc',
    parentId: 'tpl-healthhome-dept-3',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '피부 질환 치료와 미용 시술을 전문으로 하는 피부과입니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 4
  createContainerNode({
    id: 'tpl-healthhome-dept-4',
    rect: { x: 950, y: DEPT_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-healthhome-dept-4-title', { x: 24, y: 24, width: 212, height: 36 }, '치과', 3, '#123b63', 'left', 'tpl-healthhome-dept-4'),
  createTextNode({
    id: 'tpl-healthhome-dept-4-desc',
    parentId: 'tpl-healthhome-dept-4',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '충치 치료, 교정, 임플란트 등 치과 진료 전반을 제공합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),

  /* ── Appointment CTA ─────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthhome-appt',
    rect: { x: 0, y: APPT_Y, width: W, height: APPT_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-healthhome-appt-title',
    { x: MARGIN, y: 40, width: 400, height: 44 },
    '진료 예약',
    2,
    '#123b63',
    'left',
    'tpl-healthhome-appt',
  ),
  createTextNode({
    id: 'tpl-healthhome-appt-desc',
    parentId: 'tpl-healthhome-appt',
    rect: { x: MARGIN, y: 100, width: 600, height: 44 },
    text: '온라인으로 간편하게 예약하세요. 대기 시간 없이 편리하게 진료받으실 수 있습니다.',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.5,
  }),
  createButtonNode({
    id: 'tpl-healthhome-appt-btn',
    parentId: 'tpl-healthhome-appt',
    rect: { x: MARGIN, y: 170, width: 180, height: 48 },
    label: '예약하기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Insurance info ──────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthhome-insurance',
    rect: { x: 0, y: INSURANCE_Y, width: W, height: INSURANCE_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createTextNode({
    id: 'tpl-healthhome-insurance-text',
    parentId: 'tpl-healthhome-insurance',
    rect: { x: MARGIN, y: 50, width: 600, height: 44 },
    text: '국민건강보험 및 주요 실손보험을 모두 적용받으실 수 있습니다.',
    fontSize: 18,
    color: '#ffffff',
    fontWeight: 'medium',
    lineHeight: 1.4,
  }),
  createTextNode({
    id: 'tpl-healthhome-insurance-sub',
    parentId: 'tpl-healthhome-insurance',
    rect: { x: MARGIN, y: 110, width: 500, height: 40 },
    text: '보험 관련 문의는 원무과(02-1234-5678)로 연락해 주세요.',
    fontSize: 15,
    color: 'rgba(255,255,255,0.8)',
    lineHeight: 1.4,
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-healthhome-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-healthhome-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-healthhome-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-proof-label',
    parentId: 'tpl-healthhome-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-proof-title',
    parentId: 'tpl-healthhome-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'health home 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-proof-copy',
    parentId: 'tpl-healthhome-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-healthhome-wix-metric-1',
    parentId: 'tpl-healthhome-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-metric-1-value',
    parentId: 'tpl-healthhome-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-metric-1-label',
    parentId: 'tpl-healthhome-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthhome-wix-metric-2',
    parentId: 'tpl-healthhome-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-metric-2-value',
    parentId: 'tpl-healthhome-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-metric-2-label',
    parentId: 'tpl-healthhome-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthhome-wix-metric-3',
    parentId: 'tpl-healthhome-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-metric-3-value',
    parentId: 'tpl-healthhome-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-metric-3-label',
    parentId: 'tpl-healthhome-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthhome-wix-metric-4',
    parentId: 'tpl-healthhome-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-metric-4-value',
    parentId: 'tpl-healthhome-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-metric-4-label',
    parentId: 'tpl-healthhome-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-showcase-label',
    parentId: 'tpl-healthhome-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-showcase-title',
    parentId: 'tpl-healthhome-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-showcase-copy',
    parentId: 'tpl-healthhome-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-healthhome-wix-showcase-visual',
    parentId: 'tpl-healthhome-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-showcase-visual-title',
    parentId: 'tpl-healthhome-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-showcase-visual-copy',
    parentId: 'tpl-healthhome-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthhome-wix-showcase-card-1',
    parentId: 'tpl-healthhome-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-showcase-card-1-title',
    parentId: 'tpl-healthhome-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-showcase-card-1-copy',
    parentId: 'tpl-healthhome-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-healthhome-wix-showcase-card-2',
    parentId: 'tpl-healthhome-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-showcase-card-2-title',
    parentId: 'tpl-healthhome-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-healthhome-wix-showcase-card-2-copy',
    parentId: 'tpl-healthhome-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
]);

export const healthHomeTemplate: PageTemplate = {
  id: 'health-home',
  name: '병원 홈',
  category: 'health',
  subcategory: 'homepage',
  description: '히어로 + 4개 진료과목 카드 + 예약 CTA + 보험 안내',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
