import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const MARGIN = 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const HEADER_H = 140;
const STORY_Y = HEADER_H + 40;
const STORY_H = 360;
const PHILOSOPHY_Y = STORY_Y + STORY_H + 80;
const PHILOSOPHY_H = 240;
const AWARDS_Y = PHILOSOPHY_Y + PHILOSOPHY_H + 80;
const AWARDS_H = 240;
const STAGE_H = AWARDS_Y + AWARDS_H + 80;

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  heading('tpl-creativeabout-title', { x: MARGIN, y: 50, width: 500, height: 56 }, '에이전시 소개', 1, '#123b63'),
  createTextNode({
    id: 'tpl-creativeabout-subtitle',
    rect: { x: MARGIN, y: 110, width: 700, height: 32 },
    text: '크리에이티브로 세상을 바꾸는 우리를 소개합니다.',
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 1.4,
  }),

  /* ── Team story ──────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-creativeabout-story',
    rect: { x: 0, y: STORY_Y, width: W, height: STORY_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-creativeabout-story-img',
    parentId: 'tpl-creativeabout-story',
    rect: { x: MARGIN, y: 40, width: 450, height: 280 },
    src: '/images/placeholder-creative-team.jpg',
    alt: '팀 사진',
    style: { borderRadius: 12 },
  }),
  heading('tpl-creativeabout-story-title', { x: 580, y: 40, width: 400, height: 44 }, '우리의 이야기', 2, '#123b63', 'left', 'tpl-creativeabout-story'),
  createTextNode({
    id: 'tpl-creativeabout-story-desc',
    parentId: 'tpl-creativeabout-story',
    rect: { x: 580, y: 100, width: 500, height: 200 },
    text: '2015년 디자이너 3명이 시작한 작은 스튜디오에서, 현재 30명 이상의 크리에이터가 함께하는 종합 에이전시로 성장했습니다. 200개 이상의 프로젝트를 성공적으로 수행하며 클라이언트와 함께 성장해 왔습니다.',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.7,
  }),

  /* ── Creative philosophy ─────────────────────────────────── */
  createContainerNode({
    id: 'tpl-creativeabout-philosophy',
    rect: { x: 0, y: PHILOSOPHY_Y, width: W, height: PHILOSOPHY_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading('tpl-creativeabout-philosophy-title', { x: MARGIN, y: 40, width: 400, height: 44 }, '크리에이티브 철학', 2, '#ffffff', 'left', 'tpl-creativeabout-philosophy'),
  createTextNode({
    id: 'tpl-creativeabout-philosophy-desc',
    parentId: 'tpl-creativeabout-philosophy',
    rect: { x: MARGIN, y: 100, width: 800, height: 100 },
    text: '우리는 "좋은 디자인은 비즈니스를 변화시킨다"는 믿음으로 일합니다. 단순한 시각적 아름다움을 넘어, 비즈니스 목표를 달성하는 전략적 크리에이티브를 추구합니다.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.9)',
    lineHeight: 1.7,
  }),

  /* ── Awards ──────────────────────────────────────────────── */
  heading('tpl-creativeabout-awards-title', { x: MARGIN, y: AWARDS_Y, width: 400, height: 50 }, '수상 및 인정', 2, '#123b63'),
  createContainerNode({
    id: 'tpl-creativeabout-awards-box',
    rect: { x: MARGIN, y: AWARDS_Y + 70, width: W - MARGIN * 2, height: 140 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 32,
  }),
  createTextNode({
    id: 'tpl-creativeabout-awards-list',
    parentId: 'tpl-creativeabout-awards-box',
    rect: { x: 32, y: 32, width: 900, height: 80 },
    text: '레드닷 디자인 어워드 2024 | IF 디자인 어워드 | 대한민국 디자인 대상 | 웹어워드 코리아 대상 | 아시아 크리에이티브 어워드',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.8,
    align: 'center',
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-creativeabout-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-proof-label',
    parentId: 'tpl-creativeabout-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-proof-title',
    parentId: 'tpl-creativeabout-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'creative about 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-proof-copy',
    parentId: 'tpl-creativeabout-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-metric-1',
    parentId: 'tpl-creativeabout-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-metric-1-value',
    parentId: 'tpl-creativeabout-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-metric-1-label',
    parentId: 'tpl-creativeabout-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-metric-2',
    parentId: 'tpl-creativeabout-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-metric-2-value',
    parentId: 'tpl-creativeabout-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-metric-2-label',
    parentId: 'tpl-creativeabout-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-metric-3',
    parentId: 'tpl-creativeabout-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-metric-3-value',
    parentId: 'tpl-creativeabout-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-metric-3-label',
    parentId: 'tpl-creativeabout-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-metric-4',
    parentId: 'tpl-creativeabout-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-metric-4-value',
    parentId: 'tpl-creativeabout-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-metric-4-label',
    parentId: 'tpl-creativeabout-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-label',
    parentId: 'tpl-creativeabout-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-title',
    parentId: 'tpl-creativeabout-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-copy',
    parentId: 'tpl-creativeabout-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-showcase-visual',
    parentId: 'tpl-creativeabout-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-visual-title',
    parentId: 'tpl-creativeabout-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-visual-copy',
    parentId: 'tpl-creativeabout-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-showcase-card-1',
    parentId: 'tpl-creativeabout-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-card-1-title',
    parentId: 'tpl-creativeabout-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-card-1-copy',
    parentId: 'tpl-creativeabout-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-showcase-card-2',
    parentId: 'tpl-creativeabout-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-card-2-title',
    parentId: 'tpl-creativeabout-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-card-2-copy',
    parentId: 'tpl-creativeabout-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-showcase-card-3',
    parentId: 'tpl-creativeabout-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-card-3-title',
    parentId: 'tpl-creativeabout-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-showcase-card-3-copy',
    parentId: 'tpl-creativeabout-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeabout-wix-quote',
    parentId: 'tpl-creativeabout-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-quote-mark',
    parentId: 'tpl-creativeabout-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-quote-body',
    parentId: 'tpl-creativeabout-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-quote-role',
    parentId: 'tpl-creativeabout-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-cta-label',
    parentId: 'tpl-creativeabout-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-cta-title',
    parentId: 'tpl-creativeabout-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-cta-copy',
    parentId: 'tpl-creativeabout-wix-cta',
    rect: { x: 64, y: 214, width: 560, height: 64 },
    text: '짧은 설득 문구, 보조 안내, 두 개의 행동 버튼을 같은 영역에 묶어 전환 흐름을 분명하게 만듭니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-creativeabout-wix-cta-primary',
    parentId: 'tpl-creativeabout-wix-cta',
    rect: { x: 64, y: 318, width: 178, height: 52 },
    label: '문의 시작',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#e8a838', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-creativeabout-wix-cta-secondary',
    parentId: 'tpl-creativeabout-wix-cta',
    rect: { x: 266, y: 318, width: 176, height: 52 },
    label: '자세히 보기',
    href: '#services',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
  createTextNode({
    id: 'tpl-creativeabout-wix-cta-note',
    parentId: 'tpl-creativeabout-wix-cta',
    rect: { x: 64, y: 402, width: 420, height: 30 },
    text: 'Global header와 footer는 그대로 두고 인페이지 전환만 보강합니다.',
    fontSize: 13,
    color: 'rgba(255,255,255,0.68)',
    className: 'card-copy',
  }),
]);

export const creativeAboutTemplate: PageTemplate = {
  id: 'creative-about',
  name: '에이전시 소개',
  category: 'creative',
  subcategory: 'about',
  description: '팀 스토리 + 크리에이티브 철학 + 수상/인정',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
