import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const MARGIN = 80;
const CONTENT_W = W - MARGIN * 2;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const HEADER_H = 140;
const STEP_H = 180;
const STEP_GAP = 24;

interface ProcessStep {
  key: string;
  num: string;
  title: string;
  desc: string;
}

const steps: ProcessStep[] = [
  { key: 'discover', num: '01', title: 'Discover (발견)', desc: '클라이언트의 비즈니스, 목표, 타겟 고객을 깊이 이해합니다. 시장 조사와 경쟁 분석을 통해 인사이트를 도출합니다.' },
  { key: 'define', num: '02', title: 'Define (정의)', desc: '프로젝트의 범위, 일정, 핵심 메시지를 정의합니다. 명확한 전략과 방향성을 수립합니다.' },
  { key: 'design', num: '03', title: 'Design (디자인)', desc: '컨셉 시안을 제작하고 피드백을 반영합니다. 사용자 중심의 디자인을 완성합니다.' },
  { key: 'develop', num: '04', title: 'Develop (개발)', desc: '디자인을 실제 제품으로 구현합니다. 웹 개발, 영상 편집, 인쇄물 제작 등을 진행합니다.' },
  { key: 'deliver', num: '05', title: 'Deliver (전달)', desc: '최종 결과물을 전달하고, 런칭을 지원합니다. 성과를 측정하고 개선점을 제안합니다.' },
];

function buildStepCard(step: ProcessStep, idx: number): BuilderCanvasNode[] {
  const y = HEADER_H + 40 + idx * (STEP_H + STEP_GAP);
  const cid = `tpl-creativeprocess-step-${step.key}`;
  const isOdd = idx % 2 === 1;

  return [
    createContainerNode({
      id: cid,
      rect: { x: MARGIN, y, width: CONTENT_W, height: STEP_H },
      background: isOdd ? '#123b63' : '#f3f4f6',
      borderRadius: 12,
      padding: 32,
    }),
    createTextNode({
      id: `${cid}-num`,
      parentId: cid,
      rect: { x: 32, y: 24, width: 80, height: 50 },
      text: step.num,
      fontSize: 42,
      color: '#e8a838',
      fontWeight: 'bold',
    }),
    heading(
      `${cid}-title`,
      { x: 140, y: 24, width: 400, height: 40 },
      step.title,
      3,
      isOdd ? '#ffffff' : '#123b63',
      'left',
      cid,
    ),
    createTextNode({
      id: `${cid}-desc`,
      parentId: cid,
      rect: { x: 140, y: 80, width: CONTENT_W - 200, height: 70 },
      text: step.desc,
      fontSize: 15,
      color: isOdd ? 'rgba(255,255,255,0.85)' : '#374151',
      lineHeight: 1.6,
    }),
  ];
}

const STAGE_H = HEADER_H + 40 + steps.length * (STEP_H + STEP_GAP) + 60;

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  heading('tpl-creativeprocess-title', { x: MARGIN, y: 50, width: 500, height: 56 }, '작업 프로세스', 1, '#123b63'),
  createTextNode({
    id: 'tpl-creativeprocess-subtitle',
    rect: { x: MARGIN, y: 110, width: 700, height: 32 },
    text: '체계적인 5단계 프로세스로 최상의 결과물을 만듭니다.',
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 1.4,
  }),
  ...steps.flatMap((s, i) => buildStepCard(s, i)),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-creativeprocess-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-proof-label',
    parentId: 'tpl-creativeprocess-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-proof-title',
    parentId: 'tpl-creativeprocess-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'creative process 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-proof-copy',
    parentId: 'tpl-creativeprocess-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-metric-1',
    parentId: 'tpl-creativeprocess-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-metric-1-value',
    parentId: 'tpl-creativeprocess-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-metric-1-label',
    parentId: 'tpl-creativeprocess-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-metric-2',
    parentId: 'tpl-creativeprocess-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-metric-2-value',
    parentId: 'tpl-creativeprocess-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-metric-2-label',
    parentId: 'tpl-creativeprocess-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-metric-3',
    parentId: 'tpl-creativeprocess-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-metric-3-value',
    parentId: 'tpl-creativeprocess-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-metric-3-label',
    parentId: 'tpl-creativeprocess-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-metric-4',
    parentId: 'tpl-creativeprocess-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-metric-4-value',
    parentId: 'tpl-creativeprocess-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-metric-4-label',
    parentId: 'tpl-creativeprocess-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-label',
    parentId: 'tpl-creativeprocess-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-title',
    parentId: 'tpl-creativeprocess-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-copy',
    parentId: 'tpl-creativeprocess-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-showcase-visual',
    parentId: 'tpl-creativeprocess-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-visual-title',
    parentId: 'tpl-creativeprocess-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-visual-copy',
    parentId: 'tpl-creativeprocess-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-showcase-card-1',
    parentId: 'tpl-creativeprocess-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-card-1-title',
    parentId: 'tpl-creativeprocess-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-card-1-copy',
    parentId: 'tpl-creativeprocess-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-showcase-card-2',
    parentId: 'tpl-creativeprocess-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-card-2-title',
    parentId: 'tpl-creativeprocess-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-card-2-copy',
    parentId: 'tpl-creativeprocess-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-showcase-card-3',
    parentId: 'tpl-creativeprocess-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-card-3-title',
    parentId: 'tpl-creativeprocess-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-showcase-card-3-copy',
    parentId: 'tpl-creativeprocess-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-quote',
    parentId: 'tpl-creativeprocess-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-quote-mark',
    parentId: 'tpl-creativeprocess-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-quote-body',
    parentId: 'tpl-creativeprocess-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-quote-role',
    parentId: 'tpl-creativeprocess-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-cta-label',
    parentId: 'tpl-creativeprocess-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-cta-title',
    parentId: 'tpl-creativeprocess-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-cta-copy',
    parentId: 'tpl-creativeprocess-wix-cta',
    rect: { x: 64, y: 214, width: 560, height: 64 },
    text: '짧은 설득 문구, 보조 안내, 두 개의 행동 버튼을 같은 영역에 묶어 전환 흐름을 분명하게 만듭니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-creativeprocess-wix-cta-primary',
    parentId: 'tpl-creativeprocess-wix-cta',
    rect: { x: 64, y: 318, width: 178, height: 52 },
    label: '문의 시작',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#e8a838', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-creativeprocess-wix-cta-secondary',
    parentId: 'tpl-creativeprocess-wix-cta',
    rect: { x: 266, y: 318, width: 176, height: 52 },
    label: '자세히 보기',
    href: '#services',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-cta-note',
    parentId: 'tpl-creativeprocess-wix-cta',
    rect: { x: 64, y: 402, width: 420, height: 30 },
    text: 'Global header와 footer는 그대로 두고 인페이지 전환만 보강합니다.',
    fontSize: 13,
    color: 'rgba(255,255,255,0.68)',
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-creativeprocess-wix-timeline',
    parentId: 'tpl-creativeprocess-wix-cta',
    rect: { x: 690, y: 70, width: 360, height: 390 },
    background: 'rgba(255,255,255,0.10)',
    borderColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-timeline-label',
    parentId: 'tpl-creativeprocess-wix-timeline',
    rect: { x: 28, y: 28, width: 240, height: 24 },
    text: 'Decision path',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-timeline-1-title',
    parentId: 'tpl-creativeprocess-wix-timeline',
    rect: { x: 28, y: 76, width: 260, height: 28 },
    text: '1. 이해',
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-timeline-1-body',
    parentId: 'tpl-creativeprocess-wix-timeline',
    rect: { x: 28, y: 110, width: 270, height: 40 },
    text: '문제, 대상, 제공 가치를 먼저 정렬합니다.',
    fontSize: 14,
    color: 'rgba(255,255,255,0.76)',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-creativeprocess-wix-timeline-2-title',
    parentId: 'tpl-creativeprocess-wix-timeline',
    rect: { x: 28, y: 174, width: 260, height: 28 },
    text: '2. 비교',
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    className: 'card-title',
  }),
]);

export const creativeProcessTemplate: PageTemplate = {
  id: 'creative-process',
  name: '작업 프로세스',
  category: 'creative',
  subcategory: 'process',
  description: '5단계 프로세스: 발견, 정의, 디자인, 개발, 전달',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
