import type { BuilderEvent } from '@/lib/builder/events/events-shared';
import type { Locale } from '@/lib/locales';

export interface EventWidgetsCopy {
  loadingList: string;
  loadingCalendar: string;
  empty: string;
  free: string;
  rsvp: string;
  seats: (remaining: number, capacity: number) => string;
  calendarTime: (day: string, time: string) => string;
  mockEvents: {
    list: BuilderEvent[];
    calendar: BuilderEvent[];
    rsvp: BuilderEvent;
  };
  rsvpForm: {
    defaultTitle: string;
    defaultSuccessMessage: string;
    freeTicket: string;
    paidTicket: (currency: string, price: number) => string;
    seatsLeft: (remaining: number) => string;
    previewMessage: string;
    saveError: string;
    noEvents: string;
    name: string;
    email: string;
    phone: string;
    quantity: string;
    submitting: string;
    soldOut: string;
    submit: string;
  };
}

export const EVENT_RSVP_LEGACY_DEFAULTS = {
  title: '이벤트 신청',
  successMessage: '신청이 접수되었습니다. 확인 메일을 기다려 주세요.',
} as const;

export function localizedEventWidgetText(value: string | undefined, localized: string, legacyDefault: string): string {
  const current = value ?? '';
  return current === legacyDefault ? localized : current;
}

const eventWidgetsCopy: Record<Locale, EventWidgetsCopy> = {
  ko: {
    loadingList: '이벤트를 불러오는 중...',
    loadingCalendar: '캘린더를 불러오는 중...',
    empty: '표시할 이벤트가 없습니다.',
    free: '무료',
    rsvp: '신청',
    seats: (remaining, capacity) => `${remaining} / ${capacity}석`,
    calendarTime: (day, time) => `${day}일 ${time}`,
    mockEvents: {
      list: [
        {
          eventId: 'evt-mock-seminar',
          slug: 'taiwan-company-seminar',
          title: '대만 회사설립 세미나',
          description: '외국인 투자자가 대만 법인을 설립할 때 확인해야 할 절차와 리스크를 정리합니다.',
          date: '2026-06-18',
          time: '14:00',
          location: '타이베이 오피스',
          capacity: 40,
          registeredCount: 12,
          category: 'seminar',
          locale: 'ko',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'free',
          ticketPriceTwd: 0,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
        {
          eventId: 'evt-mock-webinar',
          slug: 'labor-law-webinar',
          title: '대만 노동법 웨비나',
          description: '채용, 해고, 퇴직금, 시간외 수당 쟁점을 사례 중심으로 봅니다.',
          date: '2026-07-02',
          time: '10:30',
          location: 'Online',
          capacity: 100,
          registeredCount: 28,
          category: 'webinar',
          locale: 'ko',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'paid',
          ticketPriceTwd: 800,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
      ],
      calendar: [
        {
          eventId: 'evt-calendar-1',
          slug: 'visa-workshop',
          title: '비자 실무 워크샵',
          description: '취업허가와 거류증 실무를 다룹니다.',
          date: '2026-06-12',
          time: '15:00',
          location: '타이베이 오피스',
          capacity: 25,
          registeredCount: 9,
          category: 'workshop',
          locale: 'ko',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'free',
          ticketPriceTwd: 0,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
        {
          eventId: 'evt-calendar-2',
          slug: 'contract-webinar',
          title: '계약 리스크 웨비나',
          description: '국제계약 주요 조항을 검토합니다.',
          date: '2026-07-03',
          time: '11:00',
          location: 'Online',
          capacity: 80,
          registeredCount: 20,
          category: 'webinar',
          locale: 'ko',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'paid',
          ticketPriceTwd: 500,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
      ],
      rsvp: {
        eventId: 'evt-rsvp-mock',
        slug: 'mock-rsvp-event',
        title: '대만 법률 세미나',
        description: '이벤트 신청 폼 미리보기입니다.',
        date: '2026-06-18',
        time: '14:00',
        location: '타이베이 오피스',
        capacity: 40,
        registeredCount: 12,
        category: 'seminar',
        locale: 'ko',
        status: 'published',
        rsvpEnabled: true,
        ticketType: 'free',
        ticketPriceTwd: 0,
        ticketCurrency: 'TWD',
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-05-20T00:00:00.000Z',
      },
    },
    rsvpForm: {
      defaultTitle: EVENT_RSVP_LEGACY_DEFAULTS.title,
      defaultSuccessMessage: EVENT_RSVP_LEGACY_DEFAULTS.successMessage,
      freeTicket: '무료 RSVP',
      paidTicket: (currency, price) => `${currency} ${price.toLocaleString()} · 결제 확인 대기`,
      seatsLeft: (remaining) => `${remaining}석 남음`,
      previewMessage: '미리보기에서는 신청이 저장되지 않습니다.',
      saveError: '신청을 저장하지 못했습니다.',
      noEvents: '신청 가능한 이벤트가 없습니다.',
      name: '이름',
      email: '이메일',
      phone: '전화번호',
      quantity: '신청 인원',
      submitting: '신청 중...',
      soldOut: '마감',
      submit: '신청하기',
    },
  },
  'zh-hant': {
    loadingList: '活動載入中...',
    loadingCalendar: '行事曆載入中...',
    empty: '目前沒有可顯示的活動。',
    free: '免費',
    rsvp: '報名',
    seats: (remaining, capacity) => `${remaining} / ${capacity} 個名額`,
    calendarTime: (day, time) => `${day}日 ${time}`,
    mockEvents: {
      list: [
        {
          eventId: 'evt-mock-seminar',
          slug: 'taiwan-company-seminar',
          title: '台灣公司設立說明會',
          description: '整理外國投資人在台灣設立公司時需確認的流程與風險。',
          date: '2026-06-18',
          time: '14:00',
          location: '台北辦公室',
          capacity: 40,
          registeredCount: 12,
          category: 'seminar',
          locale: 'zh-hant',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'free',
          ticketPriceTwd: 0,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
        {
          eventId: 'evt-mock-webinar',
          slug: 'labor-law-webinar',
          title: '台灣勞動法線上講座',
          description: '以案例說明招聘、解僱、資遣費與加班費爭議。',
          date: '2026-07-02',
          time: '10:30',
          location: '線上',
          capacity: 100,
          registeredCount: 28,
          category: 'webinar',
          locale: 'zh-hant',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'paid',
          ticketPriceTwd: 800,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
      ],
      calendar: [
        {
          eventId: 'evt-calendar-1',
          slug: 'visa-workshop',
          title: '簽證實務工作坊',
          description: '說明工作許可與居留證實務。',
          date: '2026-06-12',
          time: '15:00',
          location: '台北辦公室',
          capacity: 25,
          registeredCount: 9,
          category: 'workshop',
          locale: 'zh-hant',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'free',
          ticketPriceTwd: 0,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
        {
          eventId: 'evt-calendar-2',
          slug: 'contract-webinar',
          title: '合約風險線上講座',
          description: '檢視國際合約的主要條款。',
          date: '2026-07-03',
          time: '11:00',
          location: '線上',
          capacity: 80,
          registeredCount: 20,
          category: 'webinar',
          locale: 'zh-hant',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'paid',
          ticketPriceTwd: 500,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
      ],
      rsvp: {
        eventId: 'evt-rsvp-mock',
        slug: 'mock-rsvp-event',
        title: '台灣法律講座',
        description: '活動報名表預覽。',
        date: '2026-06-18',
        time: '14:00',
        location: '台北辦公室',
        capacity: 40,
        registeredCount: 12,
        category: 'seminar',
        locale: 'zh-hant',
        status: 'published',
        rsvpEnabled: true,
        ticketType: 'free',
        ticketPriceTwd: 0,
        ticketCurrency: 'TWD',
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-05-20T00:00:00.000Z',
      },
    },
    rsvpForm: {
      defaultTitle: '活動報名',
      defaultSuccessMessage: '報名已送出。請留意確認郵件。',
      freeTicket: '免費報名',
      paidTicket: (currency, price) => `${currency} ${price.toLocaleString()} · 等待付款確認`,
      seatsLeft: (remaining) => `剩餘 ${remaining} 個名額`,
      previewMessage: '預覽模式不會儲存報名。',
      saveError: '無法儲存報名。',
      noEvents: '目前沒有可報名的活動。',
      name: '姓名',
      email: '電子郵件',
      phone: '電話',
      quantity: '報名人數',
      submitting: '送出中...',
      soldOut: '已額滿',
      submit: '送出報名',
    },
  },
  en: {
    loadingList: 'Loading events...',
    loadingCalendar: 'Loading calendar...',
    empty: 'No events to show.',
    free: 'Free',
    rsvp: 'RSVP',
    seats: (remaining, capacity) => `${remaining} / ${capacity} seats`,
    calendarTime: (day, time) => `${day} ${time}`,
    mockEvents: {
      list: [
        {
          eventId: 'evt-mock-seminar',
          slug: 'taiwan-company-seminar',
          title: 'Taiwan Company Formation Seminar',
          description: 'A practical overview of procedures and risks for foreign investors forming a Taiwan company.',
          date: '2026-06-18',
          time: '14:00',
          location: 'Taipei office',
          capacity: 40,
          registeredCount: 12,
          category: 'seminar',
          locale: 'en',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'free',
          ticketPriceTwd: 0,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
        {
          eventId: 'evt-mock-webinar',
          slug: 'labor-law-webinar',
          title: 'Taiwan Labor Law Webinar',
          description: 'Case-led guidance on hiring, dismissal, severance, and overtime pay issues.',
          date: '2026-07-02',
          time: '10:30',
          location: 'Online',
          capacity: 100,
          registeredCount: 28,
          category: 'webinar',
          locale: 'en',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'paid',
          ticketPriceTwd: 800,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
      ],
      calendar: [
        {
          eventId: 'evt-calendar-1',
          slug: 'visa-workshop',
          title: 'Visa Practice Workshop',
          description: 'Practical guidance on work permits and residence certificates.',
          date: '2026-06-12',
          time: '15:00',
          location: 'Taipei office',
          capacity: 25,
          registeredCount: 9,
          category: 'workshop',
          locale: 'en',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'free',
          ticketPriceTwd: 0,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
        {
          eventId: 'evt-calendar-2',
          slug: 'contract-webinar',
          title: 'Contract Risk Webinar',
          description: 'Reviewing key terms in cross-border contracts.',
          date: '2026-07-03',
          time: '11:00',
          location: 'Online',
          capacity: 80,
          registeredCount: 20,
          category: 'webinar',
          locale: 'en',
          status: 'published',
          rsvpEnabled: true,
          ticketType: 'paid',
          ticketPriceTwd: 500,
          ticketCurrency: 'TWD',
          createdAt: '2026-05-20T00:00:00.000Z',
          updatedAt: '2026-05-20T00:00:00.000Z',
        },
      ],
      rsvp: {
        eventId: 'evt-rsvp-mock',
        slug: 'mock-rsvp-event',
        title: 'Taiwan Legal Seminar',
        description: 'Event RSVP form preview.',
        date: '2026-06-18',
        time: '14:00',
        location: 'Taipei office',
        capacity: 40,
        registeredCount: 12,
        category: 'seminar',
        locale: 'en',
        status: 'published',
        rsvpEnabled: true,
        ticketType: 'free',
        ticketPriceTwd: 0,
        ticketCurrency: 'TWD',
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-05-20T00:00:00.000Z',
      },
    },
    rsvpForm: {
      defaultTitle: 'Event RSVP',
      defaultSuccessMessage: 'Your RSVP has been received. Please watch for a confirmation email.',
      freeTicket: 'Free RSVP',
      paidTicket: (currency, price) => `${currency} ${price.toLocaleString()} · awaiting payment confirmation`,
      seatsLeft: (remaining) => `${remaining} seats left`,
      previewMessage: 'RSVPs are not saved in preview.',
      saveError: 'Unable to save RSVP.',
      noEvents: 'No RSVP-enabled events are available.',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      quantity: 'Guests',
      submitting: 'Submitting...',
      soldOut: 'Sold out',
      submit: 'Submit RSVP',
    },
  },
};

export function getEventWidgetsCopy(locale: Locale): EventWidgetsCopy {
  return eventWidgetsCopy[locale] ?? eventWidgetsCopy.en;
}
