import type { Locale } from '@/lib/locales';
import { getEnComponentLibraryCopy } from './component-library-copy.en';
import { getKoComponentLibraryCopy } from './component-library-copy.ko';
import { getZhHantComponentLibraryCopy } from './component-library-copy.zh-hant';

export interface ComponentLibraryCopy {
  eyebrow: string;
  title: (count: number) => string;
  description: string;
  namePlaceholder: string;
  saveAction: string;
  selectFirstHint: string;
  emptyTitle: string;
  emptyState: string;
  searchLabel: string;
  searchPlaceholder: string;
  sortLabel: string;
  sortRecent: string;
  sortName: string;
  viewLabel: string;
  viewList: string;
  viewGrid: string;
  viewListAriaLabel: string;
  viewGridAriaLabel: string;
  shortcutTitle: string;
  shortcutDescription: (count: number) => string;
  shortcutAction: string;
  shortcutAriaLabel: string;
  shortcutRecentTitle: string;
  shortcutPinnedTitle: string;
  shortcutInvalidNotice: (count: number) => string;
  shortcutQuickInsertAction: string;
  shortcutQuickInsertAriaLabel: (name: string) => string;
  remapNoticeTitle: string;
  remapNoticeSummary: (remappedCount: number, droppedCount: number) => string;
  remapNoticeTargetLabel: (targetId: string) => string;
  remapNoticeChangedLabel: (sourceFieldId: string, targetFieldId: string) => string;
  remapNoticeDroppedLabel: (sourceFieldId: string) => string;
  remapNoticeDismissAction: string;
  remapReviewTitle: string;
  remapReviewDescription: (fieldCount: number, targetId: string) => string;
  remapReviewFieldLabel: (sourceFieldLabel: string, fieldKey: string) => string;
  remapReviewCurrentLabel: (targetFieldId: string | null) => string;
  remapReviewSelectAriaLabel: (sourceFieldLabel: string) => string;
  remapReviewDropOption: string;
  remapReviewNoOptions: string;
  remapReviewConfirmAction: string;
  remapReviewCancelAction: string;
  resultsLabel: (visible: number, total: number) => string;
  searchEmptyState: (query: string) => string;
  insertAction: string;
  insertAriaLabel: (name: string) => string;
  invalidInsertAriaLabel: (name: string) => string;
  invalidInsertTitle: string;
  replaceAction: string;
  replaceAriaLabel: (name: string) => string;
  replaceDisabledTitle: string;
  duplicateAction: string;
  duplicateAriaLabel: (name: string) => string;
  duplicateName: (name: string) => string;
  updateAction: string;
  updateAriaLabel: (name: string) => string;
  updateDisabledTitle: string;
  updateReviewTitle: string;
  updateReviewDescription: (name: string) => string;
  updateReviewSavedLabel: string;
  updateReviewCurrentLabel: string;
  updateReviewSnapshotLabel: string;
  updateReviewSnapshotPlaceholder: string;
  reviewDiffTitle: string;
  reviewDiffEmptyLabel: string;
  reviewDiffRootKindLabel: (previousRootKind: string, nextRootKind: string) => string;
  reviewDiffNodeDeltaLabel: (delta: number) => string;
  reviewDiffTextChangedLabel: string;
  reviewDiffBindingChangedLabel: string;
  reviewDiffDetailsTitle: string;
  reviewDiffTextDetailLabel: (previousText: string, nextText: string) => string;
  reviewDiffBindingDetailLabel: (previousBinding: string, nextBinding: string) => string;
  updateReviewConfirmAction: string;
  updateReviewCancelAction: string;
  updatedBadge: string;
  restoreAction: string;
  restoreAriaLabel: (name: string) => string;
  restoreReviewTitle: string;
  restoreReviewDescription: (name: string) => string;
  restoreReviewCurrentLabel: string;
  restoreReviewPreviousLabel: string;
  restoreReviewVersionGroupLabel: string;
  restoreReviewVersionLabel: (position: number, dateLabel: string, snapshotLabel?: string) => string;
  restoreReviewVersionAriaLabel: (position: number, dateLabel: string, snapshotLabel?: string) => string;
  restoreReviewSnapshotLabel: string;
  restoreReviewSnapshotPlaceholder: string;
  restoreReviewSnapshotSaveAction: string;
  restoreReviewSnapshotDeleteAction: string;
  restoreReviewSnapshotDeleteAriaLabel: (position: number) => string;
  restoreReviewConfirmAction: string;
  restoreReviewCancelAction: string;
  versionBadge: (count: number) => string;
  entryMetaLabel: (rootKind: string, nodeCount: number, isValid: boolean) => string;
  pinAction: string;
  pinAriaLabel: (name: string) => string;
  unpinAction: string;
  unpinAriaLabel: (name: string) => string;
  pinnedBadge: string;
  renameAction: string;
  renameAriaLabel: (name: string) => string;
  renamePlaceholder: string;
  renameSaveAction: string;
  renameCancelAction: string;
  deleteAction: string;
  deleteAriaLabel: (name: string) => string;
  dateLocale: string;
}

export function getComponentLibraryCopy(locale: Locale): ComponentLibraryCopy {
  if (locale === 'zh-hant') return getZhHantComponentLibraryCopy();
  if (locale === 'en') return getEnComponentLibraryCopy();
  return getKoComponentLibraryCopy();
}
