import type { ComponentLibraryCopy } from './component-library-copy';
import { getComponentLibraryKindLabel } from './component-library-kind-labels';

const KO_KIND_LABELS: Readonly<Record<string, string>> = {
  button: '버튼',
  composite: '섹션',
  container: '컨테이너',
  form: '폼',
  heading: '헤딩',
  image: '이미지',
  repeaterTemplateGroup: '템플릿 그룹',
  section: '섹션',
  text: '텍스트',
};

export function getKoComponentLibraryCopy(): ComponentLibraryCopy {
  return {
    eyebrow: '내 디자인',
    title: (count) => `컴포넌트 라이브러리 · ${count}`,
    description: '선택한 요소나 섹션을 저장해 다른 페이지에서 빠르게 재사용하세요.',
    namePlaceholder: '이름',
    saveAction: '저장',
    selectFirstHint: '선택한 노드를 라이브러리에 저장하려면 노드를 먼저 선택하세요.',
    emptyTitle: '아직 저장한 항목 없음',
    emptyState: '저장된 컴포넌트가 없습니다.',
    searchLabel: '검색',
    searchPlaceholder: '저장된 컴포넌트 검색',
    sortLabel: '정렬',
    sortRecent: '최신',
    sortName: '이름',
    viewLabel: '보기 방식',
    viewList: '목록',
    viewGrid: '격자',
    viewListAriaLabel: '목록 보기',
    viewGridAriaLabel: '격자 보기',
    shortcutTitle: '내 디자인 바로가기',
    shortcutDescription: (count) => `저장된 컴포넌트 ${count}개를 바로 열기`,
    shortcutAction: '열기',
    shortcutAriaLabel: '컴포넌트 라이브러리로 이동',
    shortcutRecentTitle: '최근 내 디자인',
    shortcutPinnedTitle: '고정한 디자인',
    shortcutInvalidNotice: (count) => `저장 데이터 확인이 필요한 항목 ${count}개는 전체 라이브러리에서 확인하세요.`,
    shortcutQuickInsertAction: '삽입',
    shortcutQuickInsertAriaLabel: (name) => `"${name}" 바로 삽입`,
    remapNoticeTitle: '데이터 필드 자동 맞춤',
    remapNoticeSummary: (remappedCount, droppedCount) => `변경 ${remappedCount}개 · 제외 ${droppedCount}개`,
    remapNoticeTargetLabel: (targetId) => `대상: ${targetId}`,
    remapNoticeChangedLabel: (sourceFieldId, targetFieldId) => `${sourceFieldId} -> ${targetFieldId}`,
    remapNoticeDroppedLabel: (sourceFieldId) => `${sourceFieldId} 제외`,
    remapNoticeDismissAction: '닫기',
    remapReviewTitle: '필드 연결 확인',
    remapReviewDescription: (fieldCount, targetId) => `${targetId}에 맞출 필드 ${fieldCount}개`,
    remapReviewFieldLabel: (sourceFieldLabel, fieldKey) => `${sourceFieldLabel} · ${fieldKey}`,
    remapReviewCurrentLabel: (targetFieldId) => (targetFieldId ? `현재: ${targetFieldId}` : '현재: 제외'),
    remapReviewSelectAriaLabel: (sourceFieldLabel) => `${sourceFieldLabel} 대상 필드 선택`,
    remapReviewDropOption: '이 필드 제외',
    remapReviewNoOptions: '호환 필드 없음',
    remapReviewConfirmAction: '삽입',
    remapReviewCancelAction: '취소',
    resultsLabel: (visible, total) => `표시 ${visible}/${total}`,
    searchEmptyState: (query) => `"${query}"와 일치하는 저장된 컴포넌트가 없습니다.`,
    insertAction: '삽입',
    insertAriaLabel: (name) => `"${name}" 삽입`,
    invalidInsertAriaLabel: (name) => `"${name}" 저장 데이터를 확인해야 삽입할 수 있음`,
    invalidInsertTitle: '저장 데이터를 확인한 뒤 삽입할 수 있습니다.',
    replaceAction: '교체',
    replaceAriaLabel: (name) => `"${name}"로 선택 요소 교체`,
    replaceDisabledTitle: '교체할 요소 하나를 캔버스에서 선택하세요.',
    duplicateAction: '복제',
    duplicateAriaLabel: (name) => `"${name}" 복제`,
    duplicateName: (name) => `${name} 복사본`,
    updateAction: '현재 선택으로 업데이트',
    updateAriaLabel: (name) => `"${name}" 현재 선택으로 업데이트`,
    updateDisabledTitle: '먼저 캔버스에서 업데이트할 요소를 선택하세요.',
    updateReviewTitle: '업데이트 확인',
    updateReviewDescription: (name) => `"${name}"을 현재 선택으로 덮어쓰기 전에 비교하세요.`,
    updateReviewSavedLabel: '저장됨',
    updateReviewCurrentLabel: '현재 선택',
    updateReviewSnapshotLabel: '스냅샷 이름',
    updateReviewSnapshotPlaceholder: '예: 원본 히어로',
    reviewDiffTitle: '구조 변경',
    reviewDiffEmptyLabel: '변경 없음',
    reviewDiffRootKindLabel: (previousRootKind, nextRootKind) => (
      `${getComponentLibraryKindLabel(KO_KIND_LABELS, '위젯', previousRootKind)} → ${getComponentLibraryKindLabel(KO_KIND_LABELS, '위젯', nextRootKind)}`
    ),
    reviewDiffNodeDeltaLabel: (delta) => `요소 ${delta > 0 ? `+${delta}` : delta}`,
    reviewDiffTextChangedLabel: '텍스트 변경',
    reviewDiffBindingChangedLabel: '연결 변경',
    reviewDiffDetailsTitle: '상세 변경',
    reviewDiffTextDetailLabel: (previousText, nextText) => `텍스트: ${previousText} → ${nextText}`,
    reviewDiffBindingDetailLabel: (previousBinding, nextBinding) => `연결: ${previousBinding} → ${nextBinding}`,
    updateReviewConfirmAction: '업데이트',
    updateReviewCancelAction: '취소',
    updatedBadge: '업데이트됨',
    restoreAction: '이전 버전 복원',
    restoreAriaLabel: (name) => `"${name}" 이전 버전 복원`,
    restoreReviewTitle: '복원 확인',
    restoreReviewDescription: (name) => `"${name}"을 직전 버전으로 되돌리기 전에 비교하세요.`,
    restoreReviewCurrentLabel: '현재 저장됨',
    restoreReviewPreviousLabel: '이전 버전',
    restoreReviewVersionGroupLabel: '복원할 버전',
    restoreReviewVersionLabel: (position, dateLabel, snapshotLabel) => (
      snapshotLabel ? `버전 ${position} · ${snapshotLabel}` : `버전 ${position} · ${dateLabel}`
    ),
    restoreReviewVersionAriaLabel: (position, dateLabel, snapshotLabel) => (
      snapshotLabel
        ? `버전 ${position}, ${snapshotLabel}, ${dateLabel} 선택`
        : `버전 ${position}, ${dateLabel} 선택`
    ),
    restoreReviewSnapshotLabel: '스냅샷 이름',
    restoreReviewSnapshotPlaceholder: '예: 원본 히어로',
    restoreReviewSnapshotSaveAction: '이름 저장',
    restoreReviewSnapshotDeleteAction: '버전 삭제',
    restoreReviewSnapshotDeleteAriaLabel: (position) => `버전 ${position} 삭제`,
    restoreReviewConfirmAction: '복원',
    restoreReviewCancelAction: '취소',
    versionBadge: (count) => `이전 버전 ${count}`,
    entryMetaLabel: (rootKind, nodeCount, isValid) => (
      isValid
        ? `${getComponentLibraryKindLabel(KO_KIND_LABELS, '위젯', rootKind)} · ${nodeCount}개 요소`
        : '저장 데이터 확인 필요'
    ),
    pinAction: '고정',
    pinAriaLabel: (name) => `"${name}" 고정`,
    unpinAction: '고정 해제',
    unpinAriaLabel: (name) => `"${name}" 고정 해제`,
    pinnedBadge: '고정됨',
    renameAction: '이름 변경',
    renameAriaLabel: (name) => `"${name}" 이름 변경`,
    renamePlaceholder: '새 이름',
    renameSaveAction: '저장',
    renameCancelAction: '취소',
    deleteAction: '삭제',
    deleteAriaLabel: (name) => `"${name}" 삭제`,
    dateLocale: 'ko-KR',
  };
}
