import type { ComponentLibraryCopy } from './component-library-copy';
import { getComponentLibraryKindLabel } from './component-library-kind-labels';

const ZH_HANT_KIND_LABELS: Readonly<Record<string, string>> = {
  button: '按鈕',
  composite: '區段',
  container: '容器',
  form: '表單',
  heading: '標題',
  image: '圖片',
  repeaterTemplateGroup: '範本群組',
  section: '區段',
  text: '文字',
};

export function getZhHantComponentLibraryCopy(): ComponentLibraryCopy {
  return {
    eyebrow: '我的設計',
    title: (count) => `元件庫 · ${count}`,
    description: '儲存選取的元素或區段，並在其他頁面快速重複使用。',
    namePlaceholder: '名稱',
    saveAction: '儲存',
    selectFirstHint: '請先選取節點，才能將它儲存到元件庫。',
    emptyTitle: '尚無儲存項目',
    emptyState: '尚未儲存任何元件。',
    searchLabel: '搜尋',
    searchPlaceholder: '搜尋已儲存元件',
    sortLabel: '排序',
    sortRecent: '最近',
    sortName: '名稱',
    viewLabel: '檢視方式',
    viewList: '列表',
    viewGrid: '格狀',
    viewListAriaLabel: '列表檢視',
    viewGridAriaLabel: '格狀檢視',
    shortcutTitle: '我的設計捷徑',
    shortcutDescription: (count) => `開啟 ${count} 個已儲存元件`,
    shortcutAction: '開啟',
    shortcutAriaLabel: '前往元件庫',
    shortcutRecentTitle: '最近的我的設計',
    shortcutPinnedTitle: '已釘選的設計',
    shortcutInvalidNotice: (count) => `${count} 個儲存項目需要在完整元件庫中確認。`,
    shortcutQuickInsertAction: '插入',
    shortcutQuickInsertAriaLabel: (name) => `快速插入「${name}」`,
    remapNoticeTitle: '資料欄位已自動調整',
    remapNoticeSummary: (remappedCount, droppedCount) => `變更 ${remappedCount} 個 · 移除 ${droppedCount} 個`,
    remapNoticeTargetLabel: (targetId) => `目標：${targetId}`,
    remapNoticeChangedLabel: (sourceFieldId, targetFieldId) => `${sourceFieldId} -> ${targetFieldId}`,
    remapNoticeDroppedLabel: (sourceFieldId) => `已移除 ${sourceFieldId}`,
    remapNoticeDismissAction: '關閉',
    remapReviewTitle: '確認欄位連結',
    remapReviewDescription: (fieldCount, targetId) => `${fieldCount} 個欄位將套用到 ${targetId}`,
    remapReviewFieldLabel: (sourceFieldLabel, fieldKey) => `${sourceFieldLabel} · ${fieldKey}`,
    remapReviewCurrentLabel: (targetFieldId) => (targetFieldId ? `目前：${targetFieldId}` : '目前：移除'),
    remapReviewSelectAriaLabel: (sourceFieldLabel) => `選擇 ${sourceFieldLabel} 的目標欄位`,
    remapReviewDropOption: '移除此欄位',
    remapReviewNoOptions: '沒有相容欄位',
    remapReviewConfirmAction: '插入',
    remapReviewCancelAction: '取消',
    resultsLabel: (visible, total) => `顯示 ${visible}/${total}`,
    searchEmptyState: (query) => `找不到符合「${query}」的元件。`,
    insertAction: '插入',
    insertAriaLabel: (name) => `插入「${name}」`,
    invalidInsertAriaLabel: (name) => `「${name}」需要確認後才能插入`,
    invalidInsertTitle: '請先確認儲存資料，才能插入。',
    replaceAction: '取代',
    replaceAriaLabel: (name) => `以「${name}」取代所選元素`,
    replaceDisabledTitle: '請在畫布上選取一個要取代的元素。',
    duplicateAction: '複製',
    duplicateAriaLabel: (name) => `複製「${name}」`,
    duplicateName: (name) => `${name} 副本`,
    updateAction: '以目前選取項目更新',
    updateAriaLabel: (name) => `以目前選取項目更新「${name}」`,
    updateDisabledTitle: '請先在畫布上選取要更新的元素。',
    updateReviewTitle: '確認更新',
    updateReviewDescription: (name) => `請先比較，再以目前選取項目取代「${name}」。`,
    updateReviewSavedLabel: '已儲存',
    updateReviewCurrentLabel: '目前選取項目',
    updateReviewSnapshotLabel: '快照名稱',
    updateReviewSnapshotPlaceholder: '例如：原始首頁',
    reviewDiffTitle: '結構變更',
    reviewDiffEmptyLabel: '沒有變更',
    reviewDiffRootKindLabel: (previousRootKind, nextRootKind) => (
      `${getComponentLibraryKindLabel(ZH_HANT_KIND_LABELS, '小工具', previousRootKind)} → ${getComponentLibraryKindLabel(ZH_HANT_KIND_LABELS, '小工具', nextRootKind)}`
    ),
    reviewDiffNodeDeltaLabel: (delta) => (delta > 0 ? `新增 ${delta} 個元素` : `移除 ${Math.abs(delta)} 個元素`),
    reviewDiffTextChangedLabel: '文字已變更',
    reviewDiffBindingChangedLabel: '連結已變更',
    reviewDiffDetailsTitle: '變更明細',
    reviewDiffTextDetailLabel: (previousText, nextText) => `文字：${previousText} → ${nextText}`,
    reviewDiffBindingDetailLabel: (previousBinding, nextBinding) => `連結：${previousBinding} → ${nextBinding}`,
    updateReviewConfirmAction: '更新',
    updateReviewCancelAction: '取消',
    updatedBadge: '已更新',
    restoreAction: '還原舊版',
    restoreAriaLabel: (name) => `還原「${name}」舊版`,
    restoreReviewTitle: '確認還原',
    restoreReviewDescription: (name) => `請先比較，再將「${name}」還原為上一個版本。`,
    restoreReviewCurrentLabel: '目前儲存',
    restoreReviewPreviousLabel: '上一版本',
    restoreReviewVersionGroupLabel: '要還原的版本',
    restoreReviewVersionLabel: (position, dateLabel, snapshotLabel) => (
      snapshotLabel ? `版本 ${position} · ${snapshotLabel}` : `版本 ${position} · ${dateLabel}`
    ),
    restoreReviewVersionAriaLabel: (position, dateLabel, snapshotLabel) => (
      snapshotLabel
        ? `選擇版本 ${position}，${snapshotLabel}，${dateLabel}`
        : `選擇 ${dateLabel} 的版本 ${position}`
    ),
    restoreReviewSnapshotLabel: '快照名稱',
    restoreReviewSnapshotPlaceholder: '例如：原始首頁',
    restoreReviewSnapshotSaveAction: '儲存名稱',
    restoreReviewSnapshotDeleteAction: '刪除版本',
    restoreReviewSnapshotDeleteAriaLabel: (position) => `刪除版本 ${position}`,
    restoreReviewConfirmAction: '還原',
    restoreReviewCancelAction: '取消',
    versionBadge: (count) => `舊版 ${count}`,
    entryMetaLabel: (rootKind, nodeCount, isValid) => (
      isValid
        ? `${getComponentLibraryKindLabel(ZH_HANT_KIND_LABELS, '小工具', rootKind)} · ${nodeCount} 個元素`
        : '儲存資料需確認'
    ),
    pinAction: '釘選',
    pinAriaLabel: (name) => `釘選「${name}」`,
    unpinAction: '取消釘選',
    unpinAriaLabel: (name) => `取消釘選「${name}」`,
    pinnedBadge: '已釘選',
    renameAction: '重新命名',
    renameAriaLabel: (name) => `重新命名「${name}」`,
    renamePlaceholder: '新名稱',
    renameSaveAction: '儲存',
    renameCancelAction: '取消',
    deleteAction: '刪除',
    deleteAriaLabel: (name) => `刪除「${name}」`,
    dateLocale: 'zh-TW',
  };
}
