import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const STAGE_H = 2480;

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  createContainerNode({
    id: 'tpl-magazineabout-hero',
    rect: { x: 0, y: 0, width: W, height: 560 },
    background: '#1f2937',
    borderColor: '#1f2937',
    borderWidth: 1,
    borderRadius: 0,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-proof',
    rect: { x: 64, y: 640, width: 1152, height: 520 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-showcase',
    rect: { x: 64, y: 1240, width: 1152, height: 560 },
    background: '#fffbeb',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-cta',
    rect: { x: 64, y: 1880, width: 1152, height: 520 },
    background: '#1f2937',
    borderColor: '#1f2937',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-hero-eyebrow',
    parentId: 'tpl-magazineabout-hero',
    rect: { x: 72, y: 74, width: 360, height: 30 },
    text: '매거진 About',
    fontSize: 13,
    color: '#b45309',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-magazineabout-hero-title',
    parentId: 'tpl-magazineabout-hero',
    rect: { x: 72, y: 126, width: 650, height: 112 },
    text: '매거진 About 페이지를 위한 풍부한 랜딩 구조',
    fontSize: 42,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.12,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-hero-copy',
    parentId: 'tpl-magazineabout-hero',
    rect: { x: 72, y: 260, width: 560, height: 70 },
    text: '방문자가 빠르게 이해하고 비교하고 행동할 수 있도록 hero, proof, showcase, CTA를 한 흐름으로 구성했습니다.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-magazineabout-hero-primary',
    parentId: 'tpl-magazineabout-hero',
    rect: { x: 72, y: 372, width: 176, height: 52 },
    label: '시작하기',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#b45309', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-magazineabout-hero-secondary',
    parentId: 'tpl-magazineabout-hero',
    rect: { x: 270, y: 372, width: 176, height: 52 },
    label: '자세히 보기',
    href: '#contact',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
  createContainerNode({
    id: 'tpl-magazineabout-hero-visual',
    parentId: 'tpl-magazineabout-hero',
    rect: { x: 760, y: 82, width: 370, height: 340 },
    background: 'rgba(255,255,255,0.12)',
    borderColor: 'rgba(255,255,255,0.24)',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-magazineabout-hero-visual-title',
    parentId: 'tpl-magazineabout-hero-visual',
    rect: { x: 32, y: 42, width: 260, height: 44 },
    text: 'Visual story',
    fontSize: 26,
    color: '#ffffff',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-hero-visual-copy',
    parentId: 'tpl-magazineabout-hero-visual',
    rect: { x: 32, y: 108, width: 270, height: 80 },
    text: '대표 장면, 제품 화면, 행사 사진, 사례 이미지를 넣기 좋은 비주얼 영역입니다.',
    fontSize: 15,
    color: 'rgba(255,255,255,0.78)',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-magazineabout-proof-label',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 54, y: 46, width: 220, height: 28 },
    text: 'Proof points',
    fontSize: 13,
    color: '#b45309',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-magazineabout-proof-title',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 54, y: 88, width: 520, height: 82 },
    text: '신뢰 지표와 선택 기준을 카드로 정리합니다',
    fontSize: 34,
    color: '#1f2937',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-proof-copy',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 54, y: 184, width: 500, height: 58 },
    text: '수치, 혜택, 진행 단계를 분리해 페이지를 훑는 사용자가 빠르게 의사결정하도록 돕습니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-metric-1',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 54, y: 300, width: 220, height: 78 },
    background: '#fffbeb',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-metric-1-value',
    parentId: 'tpl-magazineabout-metric-1',
    rect: { x: 20, y: 16, width: 80, height: 34 },
    text: '4.9',
    fontSize: 28,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-metric-1-label',
    parentId: 'tpl-magazineabout-metric-1',
    rect: { x: 112, y: 22, width: 82, height: 30 },
    text: '평균 만족도',
    fontSize: 13,
    color: '#64748b',
    lineHeight: 1.25,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-metric-2',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 314, y: 300, width: 220, height: 78 },
    background: '#fffbeb',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-metric-2-value',
    parentId: 'tpl-magazineabout-metric-2',
    rect: { x: 20, y: 16, width: 80, height: 34 },
    text: '12+',
    fontSize: 28,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-metric-2-label',
    parentId: 'tpl-magazineabout-metric-2',
    rect: { x: 112, y: 22, width: 82, height: 30 },
    text: '대표 프로그램',
    fontSize: 13,
    color: '#64748b',
    lineHeight: 1.25,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-metric-3',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 54, y: 400, width: 220, height: 78 },
    background: '#fffbeb',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-metric-3-value',
    parentId: 'tpl-magazineabout-metric-3',
    rect: { x: 20, y: 16, width: 80, height: 34 },
    text: '24h',
    fontSize: 28,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-metric-3-label',
    parentId: 'tpl-magazineabout-metric-3',
    rect: { x: 112, y: 22, width: 82, height: 30 },
    text: '초기 응답',
    fontSize: 13,
    color: '#64748b',
    lineHeight: 1.25,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-metric-4',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 314, y: 400, width: 220, height: 78 },
    background: '#fffbeb',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-metric-4-value',
    parentId: 'tpl-magazineabout-metric-4',
    rect: { x: 20, y: 16, width: 80, height: 34 },
    text: '3x',
    fontSize: 28,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-metric-4-label',
    parentId: 'tpl-magazineabout-metric-4',
    rect: { x: 112, y: 22, width: 82, height: 30 },
    text: '전환 접점',
    fontSize: 13,
    color: '#64748b',
    lineHeight: 1.25,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-proof-card-1',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 640, y: 72, width: 420, height: 104 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-proof-card-1-title',
    parentId: 'tpl-magazineabout-proof-card-1',
    rect: { x: 24, y: 22, width: 240, height: 30 },
    text: '핵심 혜택',
    fontSize: 21,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-proof-card-1-copy',
    parentId: 'tpl-magazineabout-proof-card-1',
    rect: { x: 24, y: 58, width: 330, height: 34 },
    text: '방문자가 선택 전에 확인할 정보를 짧고 분명하게 제공합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-proof-card-2',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 640, y: 200, width: 420, height: 104 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-proof-card-2-title',
    parentId: 'tpl-magazineabout-proof-card-2',
    rect: { x: 24, y: 22, width: 240, height: 30 },
    text: '비교 기준',
    fontSize: 21,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-proof-card-2-copy',
    parentId: 'tpl-magazineabout-proof-card-2',
    rect: { x: 24, y: 58, width: 330, height: 34 },
    text: '방문자가 선택 전에 확인할 정보를 짧고 분명하게 제공합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-proof-card-3',
    parentId: 'tpl-magazineabout-proof',
    rect: { x: 640, y: 328, width: 420, height: 104 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-proof-card-3-title',
    parentId: 'tpl-magazineabout-proof-card-3',
    rect: { x: 24, y: 22, width: 240, height: 30 },
    text: '운영 방식',
    fontSize: 21,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-proof-card-3-copy',
    parentId: 'tpl-magazineabout-proof-card-3',
    rect: { x: 24, y: 58, width: 330, height: 34 },
    text: '방문자가 선택 전에 확인할 정보를 짧고 분명하게 제공합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-magazineabout-showcase-label',
    parentId: 'tpl-magazineabout-showcase',
    rect: { x: 54, y: 48, width: 240, height: 28 },
    text: 'Showcase',
    fontSize: 13,
    color: '#b45309',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-magazineabout-showcase-title',
    parentId: 'tpl-magazineabout-showcase',
    rect: { x: 54, y: 90, width: 520, height: 82 },
    text: '매거진 콘텐츠를 섹션별로 깊게 보여줍니다',
    fontSize: 34,
    color: '#1f2937',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-showcase-copy',
    parentId: 'tpl-magazineabout-showcase',
    rect: { x: 54, y: 188, width: 500, height: 58 },
    text: '서비스, 사례, 가격, 일정, 후기 등 카테고리별 상세 콘텐츠를 담을 수 있는 균형 잡힌 영역입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-showcase-card-1',
    parentId: 'tpl-magazineabout-showcase',
    rect: { x: 54, y: 304, width: 320, height: 168 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-showcase-card-1-title',
    parentId: 'tpl-magazineabout-showcase-card-1',
    rect: { x: 24, y: 26, width: 240, height: 32 },
    text: '대표 사례',
    fontSize: 22,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-showcase-card-1-copy',
    parentId: 'tpl-magazineabout-showcase-card-1',
    rect: { x: 24, y: 76, width: 248, height: 58 },
    text: '이미지, 리스트, 링크를 붙여 더 자세한 탐색으로 이어지는 카드입니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-showcase-card-2',
    parentId: 'tpl-magazineabout-showcase',
    rect: { x: 404, y: 304, width: 320, height: 168 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-showcase-card-2-title',
    parentId: 'tpl-magazineabout-showcase-card-2',
    rect: { x: 24, y: 26, width: 240, height: 32 },
    text: '고객 여정',
    fontSize: 22,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-showcase-card-2-copy',
    parentId: 'tpl-magazineabout-showcase-card-2',
    rect: { x: 24, y: 76, width: 248, height: 58 },
    text: '이미지, 리스트, 링크를 붙여 더 자세한 탐색으로 이어지는 카드입니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-showcase-card-3',
    parentId: 'tpl-magazineabout-showcase',
    rect: { x: 754, y: 304, width: 320, height: 168 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-magazineabout-showcase-card-3-title',
    parentId: 'tpl-magazineabout-showcase-card-3',
    rect: { x: 24, y: 26, width: 240, height: 32 },
    text: '성과 요약',
    fontSize: 22,
    color: '#1f2937',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-showcase-card-3-copy',
    parentId: 'tpl-magazineabout-showcase-card-3',
    rect: { x: 24, y: 76, width: 248, height: 58 },
    text: '이미지, 리스트, 링크를 붙여 더 자세한 탐색으로 이어지는 카드입니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-quote',
    parentId: 'tpl-magazineabout-showcase',
    rect: { x: 640, y: 70, width: 420, height: 170 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 20,
    padding: 0,
    className: 'split-text',
  }),
  createTextNode({
    id: 'tpl-magazineabout-quote-mark',
    parentId: 'tpl-magazineabout-quote',
    rect: { x: 26, y: 20, width: 44, height: 42 },
    text: '“',
    fontSize: 40,
    color: '#b45309',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-quote-body',
    parentId: 'tpl-magazineabout-quote',
    rect: { x: 78, y: 34, width: 292, height: 66 },
    text: '정보 구조가 명확해서 필요한 결정을 빠르게 내릴 수 있었습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-magazineabout-quote-role',
    parentId: 'tpl-magazineabout-quote',
    rect: { x: 78, y: 118, width: 230, height: 24 },
    text: '매거진 visitor',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-magazineabout-cta-label',
    parentId: 'tpl-magazineabout-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Next step',
    fontSize: 13,
    color: '#b45309',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-magazineabout-cta-title',
    parentId: 'tpl-magazineabout-cta',
    rect: { x: 64, y: 104, width: 580, height: 90 },
    text: '마지막 섹션에서 문의와 예약을 선명하게 유도합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-cta-copy',
    parentId: 'tpl-magazineabout-cta',
    rect: { x: 64, y: 214, width: 540, height: 64 },
    text: '짧은 설명과 두 개의 행동 버튼을 배치해 페이지의 다음 단계를 놓치지 않게 합니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-magazineabout-cta-primary',
    parentId: 'tpl-magazineabout-cta',
    rect: { x: 64, y: 322, width: 176, height: 52 },
    label: '문의하기',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#b45309', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-magazineabout-cta-secondary',
    parentId: 'tpl-magazineabout-cta',
    rect: { x: 264, y: 322, width: 176, height: 52 },
    label: '자료 보기',
    href: '#contact',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
  createContainerNode({
    id: 'tpl-magazineabout-cta-panel',
    parentId: 'tpl-magazineabout-cta',
    rect: { x: 700, y: 70, width: 360, height: 330 },
    background: 'rgba(255,255,255,0.10)',
    borderColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-magazineabout-cta-panel-1-title',
    parentId: 'tpl-magazineabout-cta-panel',
    rect: { x: 28, y: 36, width: 240, height: 28 },
    text: '1. 이해',
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-cta-panel-1-copy',
    parentId: 'tpl-magazineabout-cta-panel',
    rect: { x: 28, y: 70, width: 270, height: 36 },
    text: '짧은 설명으로 다음 행동까지 자연스럽게 이어집니다.',
    fontSize: 14,
    color: 'rgba(255,255,255,0.76)',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-magazineabout-cta-panel-2-title',
    parentId: 'tpl-magazineabout-cta-panel',
    rect: { x: 28, y: 128, width: 240, height: 28 },
    text: '2. 비교',
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-cta-panel-2-copy',
    parentId: 'tpl-magazineabout-cta-panel',
    rect: { x: 28, y: 162, width: 270, height: 36 },
    text: '짧은 설명으로 다음 행동까지 자연스럽게 이어집니다.',
    fontSize: 14,
    color: 'rgba(255,255,255,0.76)',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-magazineabout-cta-panel-3-title',
    parentId: 'tpl-magazineabout-cta-panel',
    rect: { x: 28, y: 220, width: 240, height: 28 },
    text: '3. 전환',
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-magazineabout-cta-panel-3-copy',
    parentId: 'tpl-magazineabout-cta-panel',
    rect: { x: 28, y: 254, width: 270, height: 36 },
    text: '짧은 설명으로 다음 행동까지 자연스럽게 이어집니다.',
    fontSize: 14,
    color: 'rgba(255,255,255,0.76)',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-accent-a',
    parentId: 'tpl-magazineabout-cta',
    rect: { x: 1020, y: 50, width: 64, height: 64 },
    background: '#b45309',
    borderColor: '#b45309',
    borderWidth: 1,
    borderRadius: 48,
    padding: 0,
    className: 'stat-card',
  }),
  createContainerNode({
    id: 'tpl-magazineabout-accent-b',
    parentId: 'tpl-magazineabout-hero',
    rect: { x: 1080, y: 390, width: 88, height: 88 },
    background: 'rgba(255,255,255,0.16)',
    borderColor: 'rgba(255,255,255,0.24)',
    borderWidth: 1,
    borderRadius: 48,
    padding: 0,
    className: 'stat-card',
  }),
]);

export const magazineAboutTemplate: PageTemplate = {
  id: 'magazine-about',
  name: '매거진 About',
  category: 'magazine',
  subcategory: 'about',
  description: '매거진 About 페이지용 4섹션 Wix-grade 템플릿',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-05-03T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H,
    nodes,
  },
};
