import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 600;
const SERVICES_Y = HERO_H + 80;
const SERVICES_H = 520;
const LOGOS_Y = SERVICES_Y + SERVICES_H + 80;
const LOGOS_H = 200;
const CTA_Y = LOGOS_Y + LOGOS_H + 80;
const CTA_H = 200;
const STAGE_H = CTA_Y + CTA_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero section ────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-conshome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-conshome-hero-bg',
    parentId: 'tpl-conshome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    src: '/images/placeholder-consulting-hero.jpg',
    alt: '컨설팅 비즈니스 히어로 이미지',
    style: { opacity: 30, borderRadius: 0 },
  }),
  heading(
    'tpl-conshome-hero-title',
    { x: 80, y: 160, width: 600, height: 100 },
    '비즈니스 성장을 이끄는 전략 파트너',
    1,
    '#ffffff',
    'left',
    'tpl-conshome-hero',
  ),
  createTextNode({
    id: 'tpl-conshome-hero-tagline',
    parentId: 'tpl-conshome-hero',
    rect: { x: 80, y: 280, width: 500, height: 60 },
    text: '데이터 기반 전략과 실행력으로 기업의 지속 가능한 성장을 지원합니다.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: 'regular',
    align: 'left',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-conshome-hero-cta',
    parentId: 'tpl-conshome-hero',
    rect: { x: 80, y: 370, width: 200, height: 52 },
    label: '무료 상담 신청',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Service pillars (4 cards) ──────────────────────────── */
  heading(
    'tpl-conshome-svc-title',
    { x: 80, y: SERVICES_Y, width: 400, height: 50 },
    '핵심 서비스',
    2,
    '#123b63',
    'left',
  ),
  createContainerNode({
    id: 'tpl-conshome-card-1',
    rect: { x: 80, y: SERVICES_Y + 70, width: 260, height: 200 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-conshome-card-1-t', { x: 24, y: 24, width: 212, height: 36 }, '경영 전략', 3, '#123b63', 'left', 'tpl-conshome-card-1'),
  createTextNode({
    id: 'tpl-conshome-card-1-d',
    parentId: 'tpl-conshome-card-1',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '시장 분석, 성장 전략, 디지털 전환 등 경영 전반에 걸친 자문을 제공합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-conshome-card-2',
    rect: { x: 370, y: SERVICES_Y + 70, width: 260, height: 200 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-conshome-card-2-t', { x: 24, y: 24, width: 212, height: 36 }, '운영 최적화', 3, '#123b63', 'left', 'tpl-conshome-card-2'),
  createTextNode({
    id: 'tpl-conshome-card-2-d',
    parentId: 'tpl-conshome-card-2',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '프로세스 개선, 비용 절감, 공급망 최적화로 운영 효율을 극대화합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-conshome-card-3',
    rect: { x: 660, y: SERVICES_Y + 70, width: 260, height: 200 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-conshome-card-3-t', { x: 24, y: 24, width: 212, height: 36 }, '재무 컨설팅', 3, '#123b63', 'left', 'tpl-conshome-card-3'),
  createTextNode({
    id: 'tpl-conshome-card-3-d',
    parentId: 'tpl-conshome-card-3',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '재무 구조 분석, 투자 전략, 리스크 관리로 재무 건전성을 강화합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-conshome-card-4',
    rect: { x: 950, y: SERVICES_Y + 70, width: 260, height: 200 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-conshome-card-4-t', { x: 24, y: 24, width: 212, height: 36 }, 'IT 전략', 3, '#123b63', 'left', 'tpl-conshome-card-4'),
  createTextNode({
    id: 'tpl-conshome-card-4-d',
    parentId: 'tpl-conshome-card-4',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '디지털 혁신, 시스템 도입, 데이터 분석 기반 IT 전략을 수립합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),

  /* ── Client logos ───────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-conshome-logos',
    rect: { x: 0, y: LOGOS_Y, width: W, height: LOGOS_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-conshome-logos-title',
    { x: 80, y: 40, width: 400, height: 50 },
    '신뢰하는 파트너사',
    2,
    '#123b63',
    'left',
    'tpl-conshome-logos',
  ),
  createTextNode({
    id: 'tpl-conshome-logos-desc',
    parentId: 'tpl-conshome-logos',
    rect: { x: 80, y: 100, width: 800, height: 40 },
    text: '삼성, LG, 현대, SK 등 국내외 500+ 기업이 저희와 함께합니다.',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.5,
  }),

  /* ── Consultation CTA ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-conshome-cta',
    rect: { x: 0, y: CTA_Y, width: W, height: CTA_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createTextNode({
    id: 'tpl-conshome-cta-text',
    parentId: 'tpl-conshome-cta',
    rect: { x: 80, y: 50, width: 600, height: 44 },
    text: '비즈니스 성장의 첫걸음, 무료 상담으로 시작하세요.',
    fontSize: 18,
    color: '#ffffff',
    fontWeight: 'medium',
    lineHeight: 1.4,
  }),
  createButtonNode({
    id: 'tpl-conshome-cta-btn',
    parentId: 'tpl-conshome-cta',
    rect: { x: 80, y: 110, width: 180, height: 48 },
    label: '상담 신청하기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-consultinghome-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-proof-label',
    parentId: 'tpl-consultinghome-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-proof-title',
    parentId: 'tpl-consultinghome-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'consulting home 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-proof-copy',
    parentId: 'tpl-consultinghome-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-metric-1',
    parentId: 'tpl-consultinghome-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-metric-1-value',
    parentId: 'tpl-consultinghome-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-metric-1-label',
    parentId: 'tpl-consultinghome-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-metric-2',
    parentId: 'tpl-consultinghome-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-metric-2-value',
    parentId: 'tpl-consultinghome-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-metric-2-label',
    parentId: 'tpl-consultinghome-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-metric-3',
    parentId: 'tpl-consultinghome-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-metric-3-value',
    parentId: 'tpl-consultinghome-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-metric-3-label',
    parentId: 'tpl-consultinghome-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-metric-4',
    parentId: 'tpl-consultinghome-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-metric-4-value',
    parentId: 'tpl-consultinghome-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-metric-4-label',
    parentId: 'tpl-consultinghome-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-showcase-label',
    parentId: 'tpl-consultinghome-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-showcase-title',
    parentId: 'tpl-consultinghome-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-showcase-copy',
    parentId: 'tpl-consultinghome-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-showcase-visual',
    parentId: 'tpl-consultinghome-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-showcase-visual-title',
    parentId: 'tpl-consultinghome-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-showcase-visual-copy',
    parentId: 'tpl-consultinghome-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-showcase-card-1',
    parentId: 'tpl-consultinghome-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-showcase-card-1-title',
    parentId: 'tpl-consultinghome-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-showcase-card-1-copy',
    parentId: 'tpl-consultinghome-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-showcase-card-2',
    parentId: 'tpl-consultinghome-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-showcase-card-2-title',
    parentId: 'tpl-consultinghome-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultinghome-wix-showcase-card-2-copy',
    parentId: 'tpl-consultinghome-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultinghome-wix-showcase-card-3',
    parentId: 'tpl-consultinghome-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
]);

export const consultingHomeTemplate: PageTemplate = {
  id: 'consulting-home',
  name: '컨설팅 홈',
  category: 'consulting',
  subcategory: 'homepage',
  description: '전문 히어로 + 서비스 필라(4개 카드) + 고객사 로고 + 상담 CTA',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
