import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 300;
const GRID_Y = HERO_H + 80;
const GRID_H = 700;
const STAGE_H = GRID_Y + GRID_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const testimonials = [
  { quote: '"전략 수립부터 실행까지 체계적으로 지원해 주셔서 매출이 크게 성장했습니다."', name: '— 김OO, 제조업 대표' },
  { quote: '"데이터 기반의 분석으로 정확한 의사결정을 할 수 있었습니다. 강력 추천합니다."', name: '— 이OO, IT기업 CEO' },
  { quote: '"조직 혁신 프로젝트를 통해 직원 만족도와 생산성이 동시에 향상되었습니다."', name: '— 박OO, 유통사 인사팀장' },
  { quote: '"M&A 과정에서 전문적인 자문 덕분에 최적의 조건으로 거래를 성사시켰습니다."', name: '— 최OO, 금융사 CFO' },
  { quote: '"스타트업 특성에 맞는 맞춤 전략으로 투자 유치에 성공할 수 있었습니다."', name: '— 정OO, 스타트업 대표' },
  { quote: '"디지털 전환 프로젝트를 성공적으로 완료할 수 있도록 도와주셨습니다."', name: '— 한OO, 헬스케어 CTO' },
];

const cardW = 360;
const cardH = 220;
const gapX = 30;
const gapY = 30;

const cards: BuilderCanvasNode[] = testimonials.flatMap((t, i) => {
  const col = i % 3;
  const row = Math.floor(i / 3);
  const x = 80 + col * (cardW + gapX);
  const y = GRID_Y + 70 + row * (cardH + gapY);
  const prefix = `tpl-constesti-card-${i + 1}`;
  return [
    createContainerNode({
      id: prefix,
      rect: { x, y, width: cardW, height: cardH },
      background: '#ffffff',
      borderRadius: 12,
      padding: 24,
      borderColor: '#e5e7eb',
      borderWidth: 1,
    }),
    createTextNode({
      id: `${prefix}-q`,
      parentId: prefix,
      rect: { x: 24, y: 24, width: 312, height: 120 },
      text: t.quote,
      fontSize: 15,
      color: '#374151',
      lineHeight: 1.6,
    }),
    createTextNode({
      id: `${prefix}-n`,
      parentId: prefix,
      rect: { x: 24, y: 160, width: 312, height: 32 },
      text: t.name,
      fontSize: 14,
      color: '#6b7280',
      fontWeight: 'medium',
      lineHeight: 1.3,
    }),
  ];
});

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  createContainerNode({
    id: 'tpl-constesti-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading('tpl-constesti-hero-title', { x: 80, y: 80, width: 600, height: 60 }, '고객 후기', 1, '#ffffff', 'left', 'tpl-constesti-hero'),
  createTextNode({
    id: 'tpl-constesti-hero-sub',
    parentId: 'tpl-constesti-hero',
    rect: { x: 80, y: 160, width: 500, height: 50 },
    text: '고객사의 생생한 경험담을 확인하세요.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 1.5,
  }),
  heading('tpl-constesti-grid-title', { x: 80, y: GRID_Y, width: 400, height: 50 }, '고객 리뷰', 2, '#123b63', 'left'),
  ...cards,
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-proof-label',
    parentId: 'tpl-consultingtestimonials-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-proof-title',
    parentId: 'tpl-consultingtestimonials-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'consulting testimonials 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-proof-copy',
    parentId: 'tpl-consultingtestimonials-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-metric-1',
    parentId: 'tpl-consultingtestimonials-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-metric-1-value',
    parentId: 'tpl-consultingtestimonials-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-metric-1-label',
    parentId: 'tpl-consultingtestimonials-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-metric-2',
    parentId: 'tpl-consultingtestimonials-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-metric-2-value',
    parentId: 'tpl-consultingtestimonials-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-metric-2-label',
    parentId: 'tpl-consultingtestimonials-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-metric-3',
    parentId: 'tpl-consultingtestimonials-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-metric-3-value',
    parentId: 'tpl-consultingtestimonials-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-metric-3-label',
    parentId: 'tpl-consultingtestimonials-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-metric-4',
    parentId: 'tpl-consultingtestimonials-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-metric-4-value',
    parentId: 'tpl-consultingtestimonials-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-metric-4-label',
    parentId: 'tpl-consultingtestimonials-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-label',
    parentId: 'tpl-consultingtestimonials-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-title',
    parentId: 'tpl-consultingtestimonials-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-copy',
    parentId: 'tpl-consultingtestimonials-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-showcase-visual',
    parentId: 'tpl-consultingtestimonials-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-visual-title',
    parentId: 'tpl-consultingtestimonials-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-visual-copy',
    parentId: 'tpl-consultingtestimonials-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-showcase-card-1',
    parentId: 'tpl-consultingtestimonials-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-card-1-title',
    parentId: 'tpl-consultingtestimonials-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-card-1-copy',
    parentId: 'tpl-consultingtestimonials-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-showcase-card-2',
    parentId: 'tpl-consultingtestimonials-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-card-2-title',
    parentId: 'tpl-consultingtestimonials-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-card-2-copy',
    parentId: 'tpl-consultingtestimonials-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-showcase-card-3',
    parentId: 'tpl-consultingtestimonials-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-card-3-title',
    parentId: 'tpl-consultingtestimonials-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-showcase-card-3-copy',
    parentId: 'tpl-consultingtestimonials-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-quote',
    parentId: 'tpl-consultingtestimonials-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-quote-mark',
    parentId: 'tpl-consultingtestimonials-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-quote-body',
    parentId: 'tpl-consultingtestimonials-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-quote-role',
    parentId: 'tpl-consultingtestimonials-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-cta-label',
    parentId: 'tpl-consultingtestimonials-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-cta-title',
    parentId: 'tpl-consultingtestimonials-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-cta-copy',
    parentId: 'tpl-consultingtestimonials-wix-cta',
    rect: { x: 64, y: 214, width: 560, height: 64 },
    text: '짧은 설득 문구, 보조 안내, 두 개의 행동 버튼을 같은 영역에 묶어 전환 흐름을 분명하게 만듭니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-consultingtestimonials-wix-cta-primary',
    parentId: 'tpl-consultingtestimonials-wix-cta',
    rect: { x: 64, y: 318, width: 178, height: 52 },
    label: '문의 시작',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#e8a838', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-consultingtestimonials-wix-cta-secondary',
    parentId: 'tpl-consultingtestimonials-wix-cta',
    rect: { x: 266, y: 318, width: 176, height: 52 },
    label: '자세히 보기',
    href: '#services',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-cta-note',
    parentId: 'tpl-consultingtestimonials-wix-cta',
    rect: { x: 64, y: 402, width: 420, height: 30 },
    text: 'Global header와 footer는 그대로 두고 인페이지 전환만 보강합니다.',
    fontSize: 13,
    color: 'rgba(255,255,255,0.68)',
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingtestimonials-wix-timeline',
    parentId: 'tpl-consultingtestimonials-wix-cta',
    rect: { x: 690, y: 70, width: 360, height: 390 },
    background: 'rgba(255,255,255,0.10)',
    borderColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-timeline-label',
    parentId: 'tpl-consultingtestimonials-wix-timeline',
    rect: { x: 28, y: 28, width: 240, height: 24 },
    text: 'Decision path',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-timeline-1-title',
    parentId: 'tpl-consultingtestimonials-wix-timeline',
    rect: { x: 28, y: 76, width: 260, height: 28 },
    text: '1. 이해',
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-timeline-1-body',
    parentId: 'tpl-consultingtestimonials-wix-timeline',
    rect: { x: 28, y: 110, width: 270, height: 40 },
    text: '문제, 대상, 제공 가치를 먼저 정렬합니다.',
    fontSize: 14,
    color: 'rgba(255,255,255,0.76)',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-consultingtestimonials-wix-timeline-2-title',
    parentId: 'tpl-consultingtestimonials-wix-timeline',
    rect: { x: 28, y: 174, width: 260, height: 28 },
    text: '2. 비교',
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    className: 'card-title',
  }),
]);

export const consultingTestimonialsTemplate: PageTemplate = {
  id: 'consulting-testimonials',
  name: '컨설팅 고객후기',
  category: 'consulting',
  subcategory: 'testimonials',
  description: '고객 추천사 + 6개 카드',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
