import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 300;
const HISTORY_Y = HERO_H + 80;
const HISTORY_H = 300;
const LEADERS_Y = HISTORY_Y + HISTORY_H + 80;
const LEADERS_H = 360;
const VALUES_Y = LEADERS_Y + LEADERS_H + 80;
const VALUES_H = 280;
const STAGE_H = VALUES_Y + VALUES_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const leaders = [
  { name: '김대표', role: '대표이사 / 전략 전문가', bio: '20년 경영 컨설팅 경력, 대기업 성장 전략 다수 수행' },
  { name: '이상무', role: '운영 부문 대표', bio: '글로벌 SCM 전문가, 제조업 혁신 프로젝트 리더' },
  { name: '박이사', role: '재무 부문 대표', bio: 'CPA/CFA 보유, 기업 구조조정 및 M&A 전문' },
  { name: '최이사', role: 'IT 부문 대표', bio: '디지털 전환 전문가, AI 기반 비즈니스 솔루션 설계' },
];

const leaderCards: BuilderCanvasNode[] = leaders.flatMap((l, i) => {
  const x = 80 + i * 290;
  const prefix = `tpl-consabt-leader-${i + 1}`;
  return [
    createContainerNode({
      id: prefix,
      rect: { x, y: LEADERS_Y + 70, width: 260, height: 240 },
      background: '#f3f4f6',
      borderRadius: 12,
      padding: 24,
    }),
    heading(`${prefix}-name`, { x: 24, y: 24, width: 212, height: 36 }, l.name, 3, '#123b63', 'left', prefix),
    createTextNode({
      id: `${prefix}-role`,
      parentId: prefix,
      rect: { x: 24, y: 66, width: 212, height: 30 },
      text: l.role,
      fontSize: 14,
      color: '#e8a838',
      fontWeight: 'medium',
      lineHeight: 1.4,
    }),
    createTextNode({
      id: `${prefix}-bio`,
      parentId: prefix,
      rect: { x: 24, y: 106, width: 212, height: 80 },
      text: l.bio,
      fontSize: 14,
      color: '#1f2937',
      lineHeight: 1.5,
    }),
  ];
});

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero ────────────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-consabt-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading('tpl-consabt-hero-title', { x: 80, y: 80, width: 600, height: 60 }, '회사 소개', 1, '#ffffff', 'left', 'tpl-consabt-hero'),
  createTextNode({
    id: 'tpl-consabt-hero-sub',
    parentId: 'tpl-consabt-hero',
    rect: { x: 80, y: 160, width: 500, height: 50 },
    text: '2005년 설립 이래 대한민국 대표 경영 컨설팅 펌으로 성장해왔습니다.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 1.5,
  }),

  /* ── Firm history ───────────────────────────────────────── */
  heading('tpl-consabt-hist-title', { x: 80, y: HISTORY_Y, width: 400, height: 50 }, '회사 연혁', 2, '#123b63', 'left'),
  createTextNode({
    id: 'tpl-consabt-hist-desc',
    rect: { x: 80, y: HISTORY_Y + 60, width: 800, height: 180 },
    text: '2005년 서울에서 출발한 저희 컨설팅은 국내외 500개 이상의 프로젝트를 성공적으로 수행했습니다. Fortune 500대 기업부터 유망 스타트업까지 다양한 산업 분야에서 신뢰받는 파트너로 자리 잡았습니다. 2015년 아시아 지역 확장을 시작으로 현재 5개국에 오피스를 운영하고 있습니다.',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.7,
  }),

  /* ── Leadership team ────────────────────────────────────── */
  heading('tpl-consabt-leader-title', { x: 80, y: LEADERS_Y, width: 400, height: 50 }, '리더십 팀', 2, '#123b63', 'left'),
  ...leaderCards,

  /* ── Values ─────────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-consabt-values',
    rect: { x: 0, y: VALUES_Y, width: W, height: VALUES_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading('tpl-consabt-values-title', { x: 80, y: 40, width: 400, height: 50 }, '핵심 가치', 2, '#123b63', 'left', 'tpl-consabt-values'),
  createTextNode({
    id: 'tpl-consabt-values-1',
    parentId: 'tpl-consabt-values',
    rect: { x: 80, y: 100, width: 300, height: 40 },
    text: '고객 중심 — 고객의 성공이 곧 우리의 성공입니다.',
    fontSize: 15,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createTextNode({
    id: 'tpl-consabt-values-2',
    parentId: 'tpl-consabt-values',
    rect: { x: 80, y: 150, width: 300, height: 40 },
    text: '데이터 기반 — 직관이 아닌 데이터로 의사결정합니다.',
    fontSize: 15,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createTextNode({
    id: 'tpl-consabt-values-3',
    parentId: 'tpl-consabt-values',
    rect: { x: 80, y: 200, width: 300, height: 40 },
    text: '혁신 추구 — 끊임없이 새로운 방법론을 탐구합니다.',
    fontSize: 15,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-consultingabout-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-proof-label',
    parentId: 'tpl-consultingabout-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-proof-title',
    parentId: 'tpl-consultingabout-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'consulting about 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-proof-copy',
    parentId: 'tpl-consultingabout-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-metric-1',
    parentId: 'tpl-consultingabout-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-metric-1-value',
    parentId: 'tpl-consultingabout-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-metric-1-label',
    parentId: 'tpl-consultingabout-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-metric-2',
    parentId: 'tpl-consultingabout-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-metric-2-value',
    parentId: 'tpl-consultingabout-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-metric-2-label',
    parentId: 'tpl-consultingabout-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-metric-3',
    parentId: 'tpl-consultingabout-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-metric-3-value',
    parentId: 'tpl-consultingabout-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-metric-3-label',
    parentId: 'tpl-consultingabout-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-metric-4',
    parentId: 'tpl-consultingabout-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-metric-4-value',
    parentId: 'tpl-consultingabout-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-metric-4-label',
    parentId: 'tpl-consultingabout-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-label',
    parentId: 'tpl-consultingabout-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-title',
    parentId: 'tpl-consultingabout-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-copy',
    parentId: 'tpl-consultingabout-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-showcase-visual',
    parentId: 'tpl-consultingabout-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-visual-title',
    parentId: 'tpl-consultingabout-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-visual-copy',
    parentId: 'tpl-consultingabout-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-showcase-card-1',
    parentId: 'tpl-consultingabout-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-card-1-title',
    parentId: 'tpl-consultingabout-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-card-1-copy',
    parentId: 'tpl-consultingabout-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-showcase-card-2',
    parentId: 'tpl-consultingabout-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-card-2-title',
    parentId: 'tpl-consultingabout-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-card-2-copy',
    parentId: 'tpl-consultingabout-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-showcase-card-3',
    parentId: 'tpl-consultingabout-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-card-3-title',
    parentId: 'tpl-consultingabout-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-showcase-card-3-copy',
    parentId: 'tpl-consultingabout-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-consultingabout-wix-quote',
    parentId: 'tpl-consultingabout-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-quote-mark',
    parentId: 'tpl-consultingabout-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-quote-body',
    parentId: 'tpl-consultingabout-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-quote-role',
    parentId: 'tpl-consultingabout-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-cta-label',
    parentId: 'tpl-consultingabout-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-cta-title',
    parentId: 'tpl-consultingabout-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-consultingabout-wix-cta-copy',
    parentId: 'tpl-consultingabout-wix-cta',
    rect: { x: 64, y: 214, width: 560, height: 64 },
    text: '짧은 설득 문구, 보조 안내, 두 개의 행동 버튼을 같은 영역에 묶어 전환 흐름을 분명하게 만듭니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
]);

export const consultingAboutTemplate: PageTemplate = {
  id: 'consulting-about',
  name: '컨설팅 소개',
  category: 'consulting',
  subcategory: 'about',
  description: '회사 연혁 + 리더십 팀(4명) + 핵심 가치',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
