import type { Locale } from '@/lib/locales';

type AdminNavCopy = {
  ariaLabel: string;
  backLabel: string;
  recentLabel: string;
  openMenuLabel: string;
  closeMenuLabel: string;
  openMenuButton: string;
  closeMenuButton: string;
  betaBadge: string;
  newBadge: string;
};

const COPY: Record<'ko' | 'zh-hant' | 'en', AdminNavCopy> = {
  ko: {
    ariaLabel: '빌더 관리 내비게이션',
    backLabel: '편집기로 돌아가기',
    recentLabel: '최근 이동',
    openMenuLabel: '관리 메뉴 열기',
    closeMenuLabel: '관리 메뉴 닫기',
    openMenuButton: '☰ 관리 메뉴',
    closeMenuButton: '✕ 메뉴 닫기',
    betaBadge: '베타',
    newBadge: '신규',
  },
  'zh-hant': {
    ariaLabel: '建構器管理導覽',
    backLabel: '返回編輯器',
    recentLabel: '最近瀏覽',
    openMenuLabel: '開啟管理選單',
    closeMenuLabel: '關閉管理選單',
    openMenuButton: '☰ 管理選單',
    closeMenuButton: '✕ 關閉選單',
    betaBadge: '測試',
    newBadge: '新',
  },
  en: {
    ariaLabel: 'Builder admin navigation',
    backLabel: 'Back to editor',
    recentLabel: 'Recent',
    openMenuLabel: 'Open admin menu',
    closeMenuLabel: 'Close admin menu',
    openMenuButton: '☰ Admin menu',
    closeMenuButton: '✕ Close menu',
    betaBadge: 'Beta',
    newBadge: 'New',
  },
};

const SECTION_LABELS: Record<'ko' | 'zh-hant' | 'en', Record<string, string>> = {
  ko: {
    편집: '편집',
    비즈니스: '비즈니스',
    워크스페이스: '워크스페이스',
    개발: '개발',
    '운영 / 보안': '운영 / 보안',
  },
  'zh-hant': {
    편집: '編輯',
    비즈니스: '商務',
    워크스페이스: '工作區',
    개발: '開發',
    '운영 / 보안': '營運 / 安全',
  },
  en: {
    편집: 'Editor',
    비즈니스: 'Business',
    워크스페이스: 'Workspace',
    개발: 'Development',
    '운영 / 보안': 'Operations / Security',
  },
};

const ITEM_LABELS: Record<'ko' | 'zh-hant' | 'en', Record<string, string>> = {
  ko: {
    '빌더 홈': '빌더 홈',
    CMS: 'CMS',
    '서비스 소스': '서비스 소스',
    '변호사 소스': '변호사 소스',
    'AI 생성기': 'AI 생성기',
    '커스텀 코드': '커스텀 코드',
    번역: '번역',
    커머스: '커머스',
    예약: '예약',
    CRM: 'CRM',
    마케팅: '마케팅',
    폼: '폼',
    이벤트: '이벤트',
    워크스페이스: '워크스페이스',
    받은편지함: '받은편지함',
    앱: '앱',
    검색: '검색',
    SEO: 'SEO',
    함수: '함수',
    로그: '로그',
    SDK: 'SDK',
    시크릿: '시크릿',
    웹훅: '웹훅',
    Ops: 'Ops',
    백업: '백업',
    마이그레이션: '마이그레이션',
    사용자: '사용자',
    '감사 로그': '감사 로그',
    도메인: '도메인',
  },
  'zh-hant': {
    '빌더 홈': '建構器首頁',
    CMS: 'CMS',
    '서비스 소스': '服務來源',
    '변호사 소스': '律師來源',
    'AI 생성기': 'AI 生成器',
    '커스텀 코드': '自訂程式碼',
    번역: '翻譯',
    커머스: '商務',
    예약: '預約',
    CRM: 'CRM',
    마케팅: '行銷',
    폼: '表單',
    이벤트: '活動',
    워크스페이스: '工作區',
    받은편지함: '收件匣',
    앱: '應用程式',
    검색: '搜尋',
    SEO: 'SEO',
    함수: '函式',
    로그: '日誌',
    SDK: 'SDK',
    시크릿: '密鑰',
    웹훅: 'Webhook',
    Ops: 'Ops',
    백업: '備份',
    마이그레이션: '遷移',
    사용자: '使用者',
    '감사 로그': '稽核記錄',
    도메인: '網域',
  },
  en: {
    '빌더 홈': 'Builder Home',
    CMS: 'CMS',
    '서비스 소스': 'Service Source',
    '변호사 소스': 'Lawyer Source',
    'AI 생성기': 'AI Generator',
    '커스텀 코드': 'Custom Code',
    번역: 'Translations',
    커머스: 'Commerce',
    예약: 'Bookings',
    CRM: 'CRM',
    마케팅: 'Marketing',
    폼: 'Forms',
    이벤트: 'Events',
    워크스페이스: 'Workspace',
    받은편지함: 'Inbox',
    앱: 'Apps',
    검색: 'Search',
    SEO: 'SEO',
    함수: 'Functions',
    로그: 'Logs',
    SDK: 'SDK',
    시크릿: 'Secrets',
    웹훅: 'Webhooks',
    Ops: 'Ops',
    백업: 'Backups',
    마이그레이션: 'Migrations',
    사용자: 'Users',
    '감사 로그': 'Audit log',
    도메인: 'Domains',
  },
};

const BREADCRUMB_LABELS: Record<'ko' | 'zh-hant' | 'en', Record<string, string>> = {
  ko: {
    'admin-builder': '빌더',
    cms: 'CMS',
    collections: '컬렉션',
    records: '레코드',
    apps: '앱',
    commerce: '커머스',
    bookings: '예약',
    crm: 'CRM',
    translations: '번역',
    workspace: '워크스페이스',
    ops: 'Ops',
    _dev: '개발',
    '%5Fdev': '개발',
    functions: '함수',
    logs: '로그',
    sdk: 'SDK',
    secrets: '시크릿',
    webhooks: '웹훅',
    members: '회원',
    domains: '도메인',
    backups: '백업',
    migrations: '마이그레이션',
    marketing: '마케팅',
    forms: '폼',
    'forms-flow': '폼 · 플로우',
    events: '이벤트',
    faq: 'FAQ',
    portfolio: '포트폴리오',
    columns: '칼럼',
    search: '검색',
    seo: 'SEO',
    errors: '오류',
    experiments: '실험',
    inbox: '받은편지함',
    sandbox: '샌드박스',
    lightboxes: '라이트박스',
    footer: '푸터',
    header: '헤더',
    'ai-generator': 'AI 생성기',
    'custom-code': '커스텀 코드',
  },
  'zh-hant': {
    'admin-builder': '建構器',
    cms: 'CMS',
    collections: '集合',
    records: '紀錄',
    apps: '應用程式',
    commerce: '商務',
    bookings: '預約',
    crm: 'CRM',
    translations: '翻譯',
    workspace: '工作區',
    ops: 'Ops',
    _dev: '開發',
    '%5Fdev': '開發',
    functions: '函式',
    logs: '日誌',
    sdk: 'SDK',
    secrets: '密鑰',
    webhooks: 'Webhook',
    members: '會員',
    domains: '網域',
    backups: '備份',
    migrations: '遷移',
    marketing: '行銷',
    forms: '表單',
    'forms-flow': '表單 · 流程',
    events: '活動',
    faq: 'FAQ',
    portfolio: '作品集',
    columns: '專欄',
    search: '搜尋',
    seo: 'SEO',
    errors: '錯誤',
    experiments: '實驗',
    inbox: '收件匣',
    sandbox: '沙箱',
    lightboxes: '彈出視窗',
    footer: '頁尾',
    header: '頁首',
    'ai-generator': 'AI 生成器',
    'custom-code': '自訂程式碼',
  },
  en: {
    'admin-builder': 'Builder',
    cms: 'CMS',
    collections: 'Collections',
    records: 'Records',
    apps: 'Apps',
    commerce: 'Commerce',
    bookings: 'Bookings',
    crm: 'CRM',
    translations: 'Translations',
    workspace: 'Workspace',
    ops: 'Ops',
    _dev: 'Dev',
    '%5Fdev': 'Dev',
    functions: 'Functions',
    logs: 'Logs',
    sdk: 'SDK',
    secrets: 'Secrets',
    webhooks: 'Webhooks',
    members: 'Members',
    domains: 'Domains',
    backups: 'Backups',
    migrations: 'Migrations',
    marketing: 'Marketing',
    forms: 'Forms',
    'forms-flow': 'Forms · Flow',
    events: 'Events',
    faq: 'FAQ',
    portfolio: 'Portfolio',
    columns: 'Columns',
    search: 'Search',
    seo: 'SEO',
    errors: 'Errors',
    experiments: 'Experiments',
    inbox: 'Inbox',
    sandbox: 'Sandbox',
    lightboxes: 'Lightboxes',
    footer: 'Footer',
    header: 'Header',
    'ai-generator': 'AI Generator',
    'custom-code': 'Custom Code',
  },
};

function normalizeLocale(locale: Locale | string): 'ko' | 'zh-hant' | 'en' {
  return locale === 'zh-hant' || locale === 'en' ? locale : 'ko';
}

export function getAdminNavCopy(locale: Locale | string): AdminNavCopy {
  return COPY[normalizeLocale(locale)];
}

export function getAdminNavSectionLabel(locale: Locale | string, heading: string): string {
  const normalized = normalizeLocale(locale);
  return SECTION_LABELS[normalized][heading] ?? heading;
}

export function getAdminNavItemLabel(locale: Locale | string, label: string): string {
  const normalized = normalizeLocale(locale);
  return ITEM_LABELS[normalized][label] ?? label;
}

export function getAdminBreadcrumbLabel(locale: Locale | string, segment: string): string {
  const normalized = normalizeLocale(locale);
  return BREADCRUMB_LABELS[normalized][segment] ?? decodeURIComponent(segment);
}
