import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 400;
const PLANS_Y = HERO_H + 80;
const PLANS_H = 380;
const CTA_Y = PLANS_Y + PLANS_H + 80;
const CTA_H = 200;
const STAGE_H = CTA_Y + CTA_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero ────────────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fitnutri-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-fitnutri-hero-img',
    parentId: 'tpl-fitnutri-hero',
    rect: { x: 640, y: 0, width: 640, height: HERO_H },
    src: '/images/placeholder-nutrition-hero.jpg',
    alt: '건강한 식단 이미지',
    style: { opacity: 50, borderRadius: 0 },
  }),
  heading(
    'tpl-fitnutri-hero-title',
    { x: 80, y: 120, width: 520, height: 70 },
    '영양 가이드',
    1,
    '#ffffff',
    'left',
    'tpl-fitnutri-hero',
  ),
  createTextNode({
    id: 'tpl-fitnutri-hero-sub',
    parentId: 'tpl-fitnutri-hero',
    rect: { x: 80, y: 210, width: 480, height: 60 },
    text: '운동만큼 중요한 영양! 전문 영양사와 함께 나에게 맞는 식단을 설계하세요.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: 'regular',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-fitnutri-hero-cta',
    parentId: 'tpl-fitnutri-hero',
    rect: { x: 80, y: 300, width: 200, height: 48 },
    label: '상담 예약하기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Meal plan overview ──────────────────────────────────── */
  heading(
    'tpl-fitnutri-plans-title',
    { x: 80, y: PLANS_Y, width: 400, height: 50 },
    '식단 프로그램',
    2,
    '#123b63',
  ),
  createContainerNode({
    id: 'tpl-fitnutri-plan-1',
    rect: { x: 80, y: PLANS_Y + 70, width: 350, height: 260 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-fitnutri-plan-1-title', { x: 24, y: 24, width: 302, height: 36 }, '다이어트 식단', 3, '#123b63', 'left', 'tpl-fitnutri-plan-1'),
  createTextNode({
    id: 'tpl-fitnutri-plan-1-desc',
    parentId: 'tpl-fitnutri-plan-1',
    rect: { x: 24, y: 70, width: 302, height: 80 },
    text: '칼로리 컨트롤과 영양 균형을 고려한 체중 감량 맞춤 식단입니다. 주간 단위로 식단표를 제공합니다.',
    fontSize: 14,
    color: '#374151',
    lineHeight: 1.6,
  }),
  createTextNode({
    id: 'tpl-fitnutri-plan-1-price',
    parentId: 'tpl-fitnutri-plan-1',
    rect: { x: 24, y: 170, width: 302, height: 28 },
    text: '월 ₩89,000 (식단표 + 상담 2회)',
    fontSize: 14,
    color: '#e8a838',
    fontWeight: 'bold',
  }),
  createContainerNode({
    id: 'tpl-fitnutri-plan-2',
    rect: { x: 460, y: PLANS_Y + 70, width: 350, height: 260 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-fitnutri-plan-2-title', { x: 24, y: 24, width: 302, height: 36 }, '벌크업 식단', 3, '#123b63', 'left', 'tpl-fitnutri-plan-2'),
  createTextNode({
    id: 'tpl-fitnutri-plan-2-desc',
    parentId: 'tpl-fitnutri-plan-2',
    rect: { x: 24, y: 70, width: 302, height: 80 },
    text: '근육량 증가를 위한 고단백 식단 프로그램입니다. 트레이닝 스케줄에 맞춰 영양소 타이밍을 최적화합니다.',
    fontSize: 14,
    color: '#374151',
    lineHeight: 1.6,
  }),
  createTextNode({
    id: 'tpl-fitnutri-plan-2-price',
    parentId: 'tpl-fitnutri-plan-2',
    rect: { x: 24, y: 170, width: 302, height: 28 },
    text: '월 ₩99,000 (식단표 + 상담 2회)',
    fontSize: 14,
    color: '#e8a838',
    fontWeight: 'bold',
  }),
  createContainerNode({
    id: 'tpl-fitnutri-plan-3',
    rect: { x: 840, y: PLANS_Y + 70, width: 350, height: 260 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-fitnutri-plan-3-title', { x: 24, y: 24, width: 302, height: 36 }, '건강 관리 식단', 3, '#123b63', 'left', 'tpl-fitnutri-plan-3'),
  createTextNode({
    id: 'tpl-fitnutri-plan-3-desc',
    parentId: 'tpl-fitnutri-plan-3',
    rect: { x: 24, y: 70, width: 302, height: 80 },
    text: '만성 질환 예방과 전반적인 건강 증진을 위한 균형 잡힌 식단입니다. 혈당/혈압 관리에 초점을 맞춥니다.',
    fontSize: 14,
    color: '#374151',
    lineHeight: 1.6,
  }),
  createTextNode({
    id: 'tpl-fitnutri-plan-3-price',
    parentId: 'tpl-fitnutri-plan-3',
    rect: { x: 24, y: 170, width: 302, height: 28 },
    text: '월 ₩79,000 (식단표 + 상담 1회)',
    fontSize: 14,
    color: '#e8a838',
    fontWeight: 'bold',
  }),

  /* ── Consultation CTA ────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fitnutri-cta',
    rect: { x: 0, y: CTA_Y, width: W, height: CTA_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createTextNode({
    id: 'tpl-fitnutri-cta-text',
    parentId: 'tpl-fitnutri-cta',
    rect: { x: 80, y: 50, width: 600, height: 44 },
    text: '전문 영양사의 1:1 상담으로 나만의 맞춤 식단을 설계하세요.',
    fontSize: 18,
    color: '#ffffff',
    fontWeight: 'medium',
    lineHeight: 1.4,
  }),
  createButtonNode({
    id: 'tpl-fitnutri-cta-btn',
    parentId: 'tpl-fitnutri-cta',
    rect: { x: 80, y: 120, width: 180, height: 48 },
    label: '상담 신청하기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-proof-label',
    parentId: 'tpl-fitnessnutrition-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-proof-title',
    parentId: 'tpl-fitnessnutrition-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'fitness nutrition 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-proof-copy',
    parentId: 'tpl-fitnessnutrition-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-metric-1',
    parentId: 'tpl-fitnessnutrition-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-metric-1-value',
    parentId: 'tpl-fitnessnutrition-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-metric-1-label',
    parentId: 'tpl-fitnessnutrition-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-metric-2',
    parentId: 'tpl-fitnessnutrition-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-metric-2-value',
    parentId: 'tpl-fitnessnutrition-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-metric-2-label',
    parentId: 'tpl-fitnessnutrition-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-metric-3',
    parentId: 'tpl-fitnessnutrition-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-metric-3-value',
    parentId: 'tpl-fitnessnutrition-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-metric-3-label',
    parentId: 'tpl-fitnessnutrition-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-metric-4',
    parentId: 'tpl-fitnessnutrition-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-metric-4-value',
    parentId: 'tpl-fitnessnutrition-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-metric-4-label',
    parentId: 'tpl-fitnessnutrition-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-label',
    parentId: 'tpl-fitnessnutrition-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-title',
    parentId: 'tpl-fitnessnutrition-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-copy',
    parentId: 'tpl-fitnessnutrition-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-showcase-visual',
    parentId: 'tpl-fitnessnutrition-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-visual-title',
    parentId: 'tpl-fitnessnutrition-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-visual-copy',
    parentId: 'tpl-fitnessnutrition-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-showcase-card-1',
    parentId: 'tpl-fitnessnutrition-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-card-1-title',
    parentId: 'tpl-fitnessnutrition-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-card-1-copy',
    parentId: 'tpl-fitnessnutrition-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-showcase-card-2',
    parentId: 'tpl-fitnessnutrition-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-card-2-title',
    parentId: 'tpl-fitnessnutrition-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-card-2-copy',
    parentId: 'tpl-fitnessnutrition-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-showcase-card-3',
    parentId: 'tpl-fitnessnutrition-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-card-3-title',
    parentId: 'tpl-fitnessnutrition-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessnutrition-wix-showcase-card-3-copy',
    parentId: 'tpl-fitnessnutrition-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessnutrition-wix-quote',
    parentId: 'tpl-fitnessnutrition-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
]);

export const fitnessNutritionTemplate: PageTemplate = {
  id: 'fitness-nutrition',
  name: '영양 가이드',
  category: 'fitness',
  subcategory: 'nutrition',
  description: '영양 히어로 + 식단 프로그램(3 카드) + 상담 CTA',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
