import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 400;
const STORY_Y = HERO_H + 80;
const STORY_H = 300;
const FACILITY_Y = STORY_Y + STORY_H + 80;
const FACILITY_H = 300;
const STAGE_H = FACILITY_Y + FACILITY_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero ────────────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fitabout-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-fitabout-hero-img',
    parentId: 'tpl-fitabout-hero',
    rect: { x: 640, y: 0, width: 640, height: HERO_H },
    src: '/images/placeholder-gym-interior.jpg',
    alt: '피트니스 센터 내부',
    style: { opacity: 60, borderRadius: 0 },
  }),
  heading(
    'tpl-fitabout-hero-title',
    { x: 80, y: 140, width: 520, height: 70 },
    '센터 소개',
    1,
    '#ffffff',
    'left',
    'tpl-fitabout-hero',
  ),
  createTextNode({
    id: 'tpl-fitabout-hero-sub',
    parentId: 'tpl-fitabout-hero',
    rect: { x: 80, y: 230, width: 480, height: 50 },
    text: '최고의 시설과 전문 트레이너가 함께하는 프리미엄 피트니스.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: 'regular',
    lineHeight: 1.5,
  }),

  /* ── Gym story ───────────────────────────────────────────── */
  heading(
    'tpl-fitabout-story-title',
    { x: 80, y: STORY_Y, width: 400, height: 50 },
    '센터 이야기',
    2,
    '#123b63',
  ),
  createTextNode({
    id: 'tpl-fitabout-story-p1',
    rect: { x: 80, y: STORY_Y + 60, width: 1120, height: 80 },
    text: '2018년 오픈 이후, 단순한 운동 공간을 넘어 건강한 라이프스타일을 만들어가는 커뮤니티로 성장해 왔습니다. 과학적인 트레이닝 방법론과 최신 장비를 바탕으로 회원 한 분 한 분의 목표 달성을 지원합니다.',
    fontSize: 16,
    color: '#1f2937',
    lineHeight: 1.7,
  }),
  createTextNode({
    id: 'tpl-fitabout-story-p2',
    rect: { x: 80, y: STORY_Y + 160, width: 1120, height: 80 },
    text: '500평 규모의 넓은 공간에 유산소, 근력, 기능성 트레이닝, 그룹 스튜디오 등 다양한 운동 공간을 갖추고 있으며, 샤워실, 사우나, 라운지 등 편의시설도 완비되어 있습니다.',
    fontSize: 16,
    color: '#1f2937',
    lineHeight: 1.7,
  }),

  /* ── Facilities ──────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fitabout-facility',
    rect: { x: 0, y: FACILITY_Y, width: W, height: FACILITY_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-fitabout-facility-title',
    { x: 80, y: 40, width: 400, height: 50 },
    '시설 안내',
    2,
    '#123b63',
    'left',
    'tpl-fitabout-facility',
  ),
  createContainerNode({
    id: 'tpl-fitabout-fac-1',
    parentId: 'tpl-fitabout-facility',
    rect: { x: 80, y: 110, width: 240, height: 140 },
    background: '#ffffff',
    borderRadius: 10,
    padding: 20,
  }),
  heading('tpl-fitabout-fac-1-title', { x: 20, y: 20, width: 200, height: 32 }, '프리웨이트 존', 3, '#123b63', 'left', 'tpl-fitabout-fac-1'),
  createTextNode({
    id: 'tpl-fitabout-fac-1-desc',
    parentId: 'tpl-fitabout-fac-1',
    rect: { x: 20, y: 60, width: 200, height: 50 },
    text: '바벨, 덤벨, 케틀벨 등 완비된 프리웨이트 구역',
    fontSize: 14,
    color: '#374151',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-fitabout-fac-2',
    parentId: 'tpl-fitabout-facility',
    rect: { x: 350, y: 110, width: 240, height: 140 },
    background: '#ffffff',
    borderRadius: 10,
    padding: 20,
  }),
  heading('tpl-fitabout-fac-2-title', { x: 20, y: 20, width: 200, height: 32 }, '머신 트레이닝', 3, '#123b63', 'left', 'tpl-fitabout-fac-2'),
  createTextNode({
    id: 'tpl-fitabout-fac-2-desc',
    parentId: 'tpl-fitabout-fac-2',
    rect: { x: 20, y: 60, width: 200, height: 50 },
    text: '최신 Technogym 머신 30대 이상 보유',
    fontSize: 14,
    color: '#374151',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-fitabout-fac-3',
    parentId: 'tpl-fitabout-facility',
    rect: { x: 620, y: 110, width: 240, height: 140 },
    background: '#ffffff',
    borderRadius: 10,
    padding: 20,
  }),
  heading('tpl-fitabout-fac-3-title', { x: 20, y: 20, width: 200, height: 32 }, '그룹 스튜디오', 3, '#123b63', 'left', 'tpl-fitabout-fac-3'),
  createTextNode({
    id: 'tpl-fitabout-fac-3-desc',
    parentId: 'tpl-fitabout-fac-3',
    rect: { x: 20, y: 60, width: 200, height: 50 },
    text: '요가, 필라테스, 댄스 등 전용 스튜디오 2실',
    fontSize: 14,
    color: '#374151',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-fitabout-fac-4',
    parentId: 'tpl-fitabout-facility',
    rect: { x: 890, y: 110, width: 240, height: 140 },
    background: '#ffffff',
    borderRadius: 10,
    padding: 20,
  }),
  heading('tpl-fitabout-fac-4-title', { x: 20, y: 20, width: 200, height: 32 }, '편의시설', 3, '#123b63', 'left', 'tpl-fitabout-fac-4'),
  createTextNode({
    id: 'tpl-fitabout-fac-4-desc',
    parentId: 'tpl-fitabout-fac-4',
    rect: { x: 20, y: 60, width: 200, height: 50 },
    text: '샤워실, 사우나, 라운지, 무료 주차장 완비',
    fontSize: 14,
    color: '#374151',
    lineHeight: 1.5,
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fitnessabout-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-proof-label',
    parentId: 'tpl-fitnessabout-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-proof-title',
    parentId: 'tpl-fitnessabout-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'fitness about 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-proof-copy',
    parentId: 'tpl-fitnessabout-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-metric-1',
    parentId: 'tpl-fitnessabout-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-metric-1-value',
    parentId: 'tpl-fitnessabout-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-metric-1-label',
    parentId: 'tpl-fitnessabout-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-metric-2',
    parentId: 'tpl-fitnessabout-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-metric-2-value',
    parentId: 'tpl-fitnessabout-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-metric-2-label',
    parentId: 'tpl-fitnessabout-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-metric-3',
    parentId: 'tpl-fitnessabout-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-metric-3-value',
    parentId: 'tpl-fitnessabout-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-metric-3-label',
    parentId: 'tpl-fitnessabout-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-metric-4',
    parentId: 'tpl-fitnessabout-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-metric-4-value',
    parentId: 'tpl-fitnessabout-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-metric-4-label',
    parentId: 'tpl-fitnessabout-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-label',
    parentId: 'tpl-fitnessabout-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-title',
    parentId: 'tpl-fitnessabout-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-copy',
    parentId: 'tpl-fitnessabout-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-showcase-visual',
    parentId: 'tpl-fitnessabout-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-visual-title',
    parentId: 'tpl-fitnessabout-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-visual-copy',
    parentId: 'tpl-fitnessabout-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-showcase-card-1',
    parentId: 'tpl-fitnessabout-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-card-1-title',
    parentId: 'tpl-fitnessabout-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-card-1-copy',
    parentId: 'tpl-fitnessabout-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-showcase-card-2',
    parentId: 'tpl-fitnessabout-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-card-2-title',
    parentId: 'tpl-fitnessabout-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-card-2-copy',
    parentId: 'tpl-fitnessabout-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-showcase-card-3',
    parentId: 'tpl-fitnessabout-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-card-3-title',
    parentId: 'tpl-fitnessabout-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnessabout-wix-showcase-card-3-copy',
    parentId: 'tpl-fitnessabout-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnessabout-wix-quote',
    parentId: 'tpl-fitnessabout-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
]);

export const fitnessAboutTemplate: PageTemplate = {
  id: 'fitness-about',
  name: '피트니스 센터 소개',
  category: 'fitness',
  subcategory: 'about',
  description: '히어로 이미지 + 센터 이야기 + 시설 안내(4 카드)',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
