import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 600;
const CLASSES_Y = HERO_H + 80;
const CLASSES_H = 420;
const CTA_Y = CLASSES_Y + CLASSES_H + 80;
const CTA_H = 300;
const TRAINER_Y = CTA_Y + CTA_H + 80;
const TRAINER_H = 340;
const STAGE_H = TRAINER_Y + TRAINER_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero section ────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fithome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-fithome-hero-bg',
    parentId: 'tpl-fithome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    src: '/images/placeholder-gym-hero.jpg',
    alt: '피트니스 센터 히어로 배경',
    style: { opacity: 30, borderRadius: 0 },
  }),
  heading(
    'tpl-fithome-hero-title',
    { x: 80, y: 160, width: 600, height: 100 },
    '당신의 한계를 넘어서',
    1,
    '#ffffff',
    'left',
    'tpl-fithome-hero',
  ),
  createTextNode({
    id: 'tpl-fithome-hero-tagline',
    parentId: 'tpl-fithome-hero',
    rect: { x: 80, y: 280, width: 500, height: 60 },
    text: '전문 트레이너와 함께하는 맞춤 운동 프로그램으로 건강한 변화를 시작하세요.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: 'regular',
    align: 'left',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-fithome-hero-cta',
    parentId: 'tpl-fithome-hero',
    rect: { x: 80, y: 370, width: 200, height: 52 },
    label: '무료 체험 신청',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Class highlights (4 cards) ──────────────────────────── */
  heading(
    'tpl-fithome-class-title',
    { x: 80, y: CLASSES_Y, width: 400, height: 50 },
    '인기 클래스',
    2,
    '#123b63',
    'left',
  ),
  // Card 1
  createContainerNode({
    id: 'tpl-fithome-card-1',
    rect: { x: 80, y: CLASSES_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-fithome-card-1-img',
    parentId: 'tpl-fithome-card-1',
    rect: { x: 0, y: 0, width: 260, height: 160 },
    src: '/images/placeholder-fitness-yoga.jpg',
    alt: '요가 클래스',
    style: { borderRadius: 0 },
  }),
  heading('tpl-fithome-card-1-title', { x: 16, y: 172, width: 228, height: 36 }, '요가', 3, '#123b63', 'left', 'tpl-fithome-card-1'),
  createTextNode({
    id: 'tpl-fithome-card-1-desc',
    parentId: 'tpl-fithome-card-1',
    rect: { x: 16, y: 216, width: 228, height: 60 },
    text: '유연성과 마음의 평화를 동시에 얻는 요가 프로그램입니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 2
  createContainerNode({
    id: 'tpl-fithome-card-2',
    rect: { x: 370, y: CLASSES_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-fithome-card-2-img',
    parentId: 'tpl-fithome-card-2',
    rect: { x: 0, y: 0, width: 260, height: 160 },
    src: '/images/placeholder-fitness-hiit.jpg',
    alt: 'HIIT 클래스',
    style: { borderRadius: 0 },
  }),
  heading('tpl-fithome-card-2-title', { x: 16, y: 172, width: 228, height: 36 }, 'HIIT', 3, '#123b63', 'left', 'tpl-fithome-card-2'),
  createTextNode({
    id: 'tpl-fithome-card-2-desc',
    parentId: 'tpl-fithome-card-2',
    rect: { x: 16, y: 216, width: 228, height: 60 },
    text: '고강도 인터벌 트레이닝으로 짧은 시간에 최대 효과를 경험하세요.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 3
  createContainerNode({
    id: 'tpl-fithome-card-3',
    rect: { x: 660, y: CLASSES_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-fithome-card-3-img',
    parentId: 'tpl-fithome-card-3',
    rect: { x: 0, y: 0, width: 260, height: 160 },
    src: '/images/placeholder-fitness-boxing.jpg',
    alt: '복싱 클래스',
    style: { borderRadius: 0 },
  }),
  heading('tpl-fithome-card-3-title', { x: 16, y: 172, width: 228, height: 36 }, '복싱', 3, '#123b63', 'left', 'tpl-fithome-card-3'),
  createTextNode({
    id: 'tpl-fithome-card-3-desc',
    parentId: 'tpl-fithome-card-3',
    rect: { x: 16, y: 216, width: 228, height: 60 },
    text: '스트레스 해소와 체력 증진을 동시에! 복싱 피트니스 프로그램입니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 4
  createContainerNode({
    id: 'tpl-fithome-card-4',
    rect: { x: 950, y: CLASSES_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-fithome-card-4-img',
    parentId: 'tpl-fithome-card-4',
    rect: { x: 0, y: 0, width: 260, height: 160 },
    src: '/images/placeholder-fitness-pilates.jpg',
    alt: '필라테스 클래스',
    style: { borderRadius: 0 },
  }),
  heading('tpl-fithome-card-4-title', { x: 16, y: 172, width: 228, height: 36 }, '필라테스', 3, '#123b63', 'left', 'tpl-fithome-card-4'),
  createTextNode({
    id: 'tpl-fithome-card-4-desc',
    parentId: 'tpl-fithome-card-4',
    rect: { x: 16, y: 216, width: 228, height: 60 },
    text: '코어 강화와 체형 교정을 위한 전문 필라테스 수업입니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),

  /* ── Membership CTA ──────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fithome-cta',
    rect: { x: 0, y: CTA_Y, width: W, height: CTA_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-fithome-cta-title',
    { x: 80, y: 40, width: 500, height: 50 },
    '지금 시작하세요',
    2,
    '#123b63',
    'left',
    'tpl-fithome-cta',
  ),
  createTextNode({
    id: 'tpl-fithome-cta-desc',
    parentId: 'tpl-fithome-cta',
    rect: { x: 80, y: 110, width: 600, height: 60 },
    text: '첫 달 50% 할인! 무료 체험 후 나에게 맞는 멤버십을 선택하세요. 전문 트레이너의 1:1 상담이 포함됩니다.',
    fontSize: 16,
    color: '#374151',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-fithome-cta-btn',
    parentId: 'tpl-fithome-cta',
    rect: { x: 80, y: 200, width: 200, height: 48 },
    label: '멤버십 보기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Trainer spotlight ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fithome-trainer',
    rect: { x: 0, y: TRAINER_Y, width: W, height: TRAINER_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading(
    'tpl-fithome-trainer-title',
    { x: 80, y: 40, width: 500, height: 50 },
    '트레이너 소개',
    2,
    '#ffffff',
    'left',
    'tpl-fithome-trainer',
  ),
  createTextNode({
    id: 'tpl-fithome-trainer-desc',
    parentId: 'tpl-fithome-trainer',
    rect: { x: 80, y: 100, width: 500, height: 48 },
    text: '국제 공인 자격증을 보유한 전문 트레이너팀이 여러분의 목표 달성을 도와드립니다.',
    fontSize: 16,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 1.6,
  }),
  createImageNode({
    id: 'tpl-fithome-trainer-img',
    parentId: 'tpl-fithome-trainer',
    rect: { x: 80, y: 170, width: 400, height: 140 },
    src: '/images/placeholder-trainers-group.jpg',
    alt: '트레이너팀 단체 사진',
    style: { borderRadius: 12 },
  }),
  createButtonNode({
    id: 'tpl-fithome-trainer-btn',
    parentId: 'tpl-fithome-trainer',
    rect: { x: 520, y: 220, width: 180, height: 48 },
    label: '트레이너 보기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-fitnesshome-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-fitnesshome-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-fitnesshome-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-proof-label',
    parentId: 'tpl-fitnesshome-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-proof-title',
    parentId: 'tpl-fitnesshome-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'fitness home 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-proof-copy',
    parentId: 'tpl-fitnesshome-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-fitnesshome-wix-metric-1',
    parentId: 'tpl-fitnesshome-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-metric-1-value',
    parentId: 'tpl-fitnesshome-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-metric-1-label',
    parentId: 'tpl-fitnesshome-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnesshome-wix-metric-2',
    parentId: 'tpl-fitnesshome-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-metric-2-value',
    parentId: 'tpl-fitnesshome-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-metric-2-label',
    parentId: 'tpl-fitnesshome-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnesshome-wix-metric-3',
    parentId: 'tpl-fitnesshome-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-metric-3-value',
    parentId: 'tpl-fitnesshome-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-metric-3-label',
    parentId: 'tpl-fitnesshome-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-fitnesshome-wix-metric-4',
    parentId: 'tpl-fitnesshome-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-metric-4-value',
    parentId: 'tpl-fitnesshome-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-metric-4-label',
    parentId: 'tpl-fitnesshome-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-showcase-label',
    parentId: 'tpl-fitnesshome-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-showcase-title',
    parentId: 'tpl-fitnesshome-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-showcase-copy',
    parentId: 'tpl-fitnesshome-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-fitnesshome-wix-showcase-visual',
    parentId: 'tpl-fitnesshome-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-showcase-visual-title',
    parentId: 'tpl-fitnesshome-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-fitnesshome-wix-showcase-visual-copy',
    parentId: 'tpl-fitnesshome-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
]);

export const fitnessHomeTemplate: PageTemplate = {
  id: 'fitness-home',
  name: '피트니스 홈',
  category: 'fitness',
  subcategory: 'homepage',
  description: '다이나믹 히어로 + 인기 클래스 카드(4개) + 멤버십 CTA + 트레이너 스포트라이트',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
