import type { BookingServicesAdminCopy } from './BookingServicesAdmin.copy';

export const bookingServicesAdminCopyZh = {
  toolbar: (count) => `${count} 個服務（包含停用草稿）`,
  newService: '新增服務',
  serviceNotes: '沒有服務備註。',
  cardLabel: '服務',
  minLabel: '分鐘',
  activeLabel: '啟用',
  inactiveLabel: '停用',
  seatsLabel: '席',
  reminderLabel: '提醒',
  everyLabel: '每',
  staffLabel: '員工',
  resourcesLabel: '資源',
  imageFallback: '服務',
  editServiceTitle: '編輯服務',
  newServiceTitle: '新增服務',
  saveService: '儲存服務',
  saving: '儲存中...',
  cancel: '取消',
  paidBooking: (currency, amount) => `付費 ${currency} ${amount.toLocaleString()}`,
  freeBooking: '免費預約',
  deposit: (currency, amount) => `訂金 ${currency} ${amount.toLocaleString()}`,
  collectPaymentLater: '稍後收款',
  staffPriceOverrideSummary: (staffName, currency, amount) => `員工價 ${staffName}: ${currency} ${amount.toLocaleString()}`,
  staffPriceOverrides: '員工專屬價格',
  staffPriceOverrideHint: '留白則使用預設付款金額。',
  resourcePriceOverrides: '資源專屬價格',
  resourcePriceOverrideHint: '留白則使用員工或預設付款金額。',
  resourcePriceOverrideSummary: (resourceName, currency, amount) => `資源價 ${resourceName}: ${currency} ${amount.toLocaleString()}`,
  discountCodes: '折扣碼',
  discountCodesHint: '僅適用於付費服務。客戶輸入的代碼會在付款前由伺服器重新計算。',
  discountCode: '代碼',
  discountType: '類型',
  discountValue: '數值',
  discountLocale: '語言',
  discountAllLocales: '全部',
  discountActive: '啟用',
  discountPercent: '% 折扣',
  discountFixed: '固定折扣',
  addDiscountCode: '新增折扣碼',
  removeDiscountCode: '移除',
  discountCodeSummary: (code, type, value) => `${code} · ${type === 'percent' ? `${value}%` : value.toLocaleString()}`,
  anyActiveStaff: '任何啟用中的員工',
  noSharedResources: '沒有共享資源',
  active: '啟用',
  inactive: '停用',
  edit: '編輯',
  deactivate: '停用',
  editService: '編輯服務',
  close: '關閉',
  nameKo: '名稱 KO',
  nameEn: '名稱 EN',
  nameZh: '名稱 ZH',
  durationMinutes: '所需時間（分鐘）',
  priceTwd: '價格（TWD）',
  paymentMode: '付款方式',
  paymentAmount: '付款金額',
  depositDueNow: '立即支付訂金',
  paymentCurrency: '付款幣別',
  meetingMode: '諮詢方式',
  cancellationPolicy: '取消政策',
  noPolicy: '沒有政策',
  category: '分類',
  bufferBefore: '前置緩衝',
  bufferAfter: '後置緩衝',
  capacity: '名額',
  bookingInterval: '預約間隔',
  reminderSchedule: '提醒排程',
  reminderHint: '全部取消勾選可關閉此服務的電子郵件與簡訊提醒。',
  hoursBefore24: '24 小時前',
  hoursBefore1: '1 小時前',
  imageUrl: '圖片網址',
  descriptionKo: '說明 KO',
  descriptionEn: '說明 EN',
  descriptionZh: '說明 ZH',
  staff: '員工',
  requiredResources: '必要資源',
  inactiveResources: (names) => `停用資源：${names.join(', ')}`,
  resourceHint: '選取後，若同一房間或設備上有其他預約重疊，時段會關閉。',
  inactiveResourcesList: (names) => `停用資源：${names.join(', ')}`,
  reminderSummary: (hours) => (hours.length > 0 ? `提醒 ${hours.join('小時 + ')}小時前` : '提醒關閉'),
  policySummary: (id, name) => `政策 ${id}${name ? ` · ${name}` : ''}`,
  policyLabel: (policy) => {
    const segments = [policy.name];
    if (policy.cancellationFeePercent > 0) segments.push(`手續費 ${policy.cancellationFeePercent}%`);
    if (!policy.isActive) segments.push('停用');
    return segments.join(' · ');
  },
  inactiveResourceWarning: (names) => `停用資源：${names.join(', ')}`,
  resourceActive: '啟用',
  resourceInactive: '停用',
  freeOption: '免費預約',
  paidOption: '預約前付款',
  inPerson: '現場',
  zoom: 'Zoom 自動連結',
  phone: '電話',
  hybrid: '混合',
  paginationPage: (page, total, items) => `第 ${page}/${total} 頁（共 ${items} 項）`,
  paginationPageSize: '每頁',
  paginationPrev: '上一頁',
  paginationNext: '下一頁',
} satisfies BookingServicesAdminCopy;
