import type { BookingServicesAdminCopy } from './BookingServicesAdmin.copy';

export const bookingServicesAdminCopyEn = {
  toolbar: (count) => `${count} services, including inactive drafts.`,
  newService: 'New service',
  serviceNotes: 'No service notes.',
  cardLabel: 'service',
  minLabel: 'min',
  activeLabel: 'Active',
  inactiveLabel: 'Inactive',
  seatsLabel: 'seats',
  reminderLabel: 'Reminder',
  everyLabel: 'Every',
  staffLabel: 'Staff',
  resourcesLabel: 'Resources',
  imageFallback: 'SERVICE',
  editServiceTitle: 'Edit service',
  newServiceTitle: 'New service',
  saveService: 'Save service',
  saving: 'Saving...',
  cancel: 'Cancel',
  paidBooking: (currency, amount) => `Paid ${currency} ${amount.toLocaleString()}`,
  freeBooking: 'Free booking',
  deposit: (currency, amount) => `Deposit ${currency} ${amount.toLocaleString()}`,
  collectPaymentLater: 'Collect payment later',
  staffPriceOverrideSummary: (staffName, currency, amount) => `Staff price ${staffName}: ${currency} ${amount.toLocaleString()}`,
  staffPriceOverrides: 'Staff-specific price',
  staffPriceOverrideHint: 'Leave blank to use the default payment amount.',
  resourcePriceOverrides: 'Resource-specific price',
  resourcePriceOverrideHint: 'Leave blank to use the staff/default payment amount.',
  resourcePriceOverrideSummary: (resourceName, currency, amount) => `Resource price ${resourceName}: ${currency} ${amount.toLocaleString()}`,
  discountCodes: 'Discount codes',
  discountCodesHint: 'Paid services only. Customer-entered codes are recalculated on the server before payment.',
  discountCode: 'Code',
  discountType: 'Type',
  discountValue: 'Value',
  discountLocale: 'Locale',
  discountAllLocales: 'All',
  discountActive: 'Active',
  discountPercent: '% off',
  discountFixed: 'Fixed off',
  addDiscountCode: 'Add discount code',
  removeDiscountCode: 'Remove',
  discountCodeSummary: (code, type, value) => `${code} · ${type === 'percent' ? `${value}%` : value.toLocaleString()}`,
  anyActiveStaff: 'Any active staff',
  noSharedResources: 'No shared resources',
  active: 'Active',
  inactive: 'Inactive',
  edit: 'Edit',
  deactivate: 'Deactivate',
  editService: 'Edit service',
  close: 'Close',
  nameKo: 'Name KO',
  nameEn: 'Name EN',
  nameZh: 'Name ZH',
  durationMinutes: 'Duration minutes',
  priceTwd: 'Price TWD',
  paymentMode: 'Payment mode',
  paymentAmount: 'Payment amount',
  depositDueNow: 'Deposit due now',
  paymentCurrency: 'Payment currency',
  meetingMode: 'Meeting mode',
  cancellationPolicy: 'Cancellation policy',
  noPolicy: 'No policy',
  category: 'Category',
  bufferBefore: 'Buffer before',
  bufferAfter: 'Buffer after',
  capacity: 'Capacity',
  bookingInterval: 'Booking interval',
  reminderSchedule: 'Reminder schedule',
  reminderHint: 'Uncheck both to turn off email and SMS reminders for this service.',
  hoursBefore24: '24h before',
  hoursBefore1: '1h before',
  imageUrl: 'Image URL',
  descriptionKo: 'Description KO',
  descriptionEn: 'Description EN',
  descriptionZh: 'Description ZH',
  staff: 'Staff',
  requiredResources: 'Required resources',
  inactiveResources: (names) => `Inactive resources: ${names.join(', ')}`,
  resourceHint: 'When selected, slots close if another booking overlaps on the same room or equipment.',
  inactiveResourcesList: (names) => `Inactive resources: ${names.join(', ')}`,
  reminderSummary: (hours) => (hours.length > 0 ? `Reminder ${hours.join('h + ')}h` : 'Reminders off'),
  policySummary: (id, name) => `Policy ${id}${name ? ` · ${name}` : ''}`,
  policyLabel: (policy) => {
    const segments = [policy.name];
    if (policy.cancellationFeePercent > 0) segments.push(`fee ${policy.cancellationFeePercent}%`);
    if (!policy.isActive) segments.push('inactive');
    return segments.join(' · ');
  },
  inactiveResourceWarning: (names) => `Inactive resources: ${names.join(', ')}`,
  resourceActive: 'Active',
  resourceInactive: 'Inactive',
  freeOption: 'Free booking',
  paidOption: 'Paid before booking',
  inPerson: 'In-person',
  zoom: 'Zoom auto link',
  phone: 'Phone',
  hybrid: 'Hybrid',
  paginationPage: (page, total, items) => `Page ${page}/${total} (${items} items)`,
  paginationPageSize: 'Per page',
  paginationPrev: 'Previous',
  paginationNext: 'Next',
} satisfies BookingServicesAdminCopy;
