import type { BookingServicesAdminCopy } from './BookingServicesAdmin.copy';

export const bookingServicesAdminCopyKo = {
  toolbar: (count) => `${count}개의 서비스(비활성 초안 포함)`,
  newService: '새 서비스',
  serviceNotes: '서비스 메모 없음.',
  cardLabel: '서비스',
  minLabel: '분',
  activeLabel: '활성',
  inactiveLabel: '비활성',
  seatsLabel: '석',
  reminderLabel: '리마인더',
  everyLabel: '매',
  staffLabel: '담당자',
  resourcesLabel: '자원',
  imageFallback: '서비스',
  editServiceTitle: '서비스 편집',
  newServiceTitle: '새 서비스',
  saveService: '서비스 저장',
  saving: '저장 중...',
  cancel: '취소',
  paidBooking: (currency, amount) => `유료 ${currency} ${amount.toLocaleString()}`,
  freeBooking: '무료 예약',
  deposit: (currency, amount) => `보증금 ${currency} ${amount.toLocaleString()}`,
  collectPaymentLater: '나중에 결제 받기',
  staffPriceOverrideSummary: (staffName, currency, amount) => `담당자별 ${staffName}: ${currency} ${amount.toLocaleString()}`,
  staffPriceOverrides: '담당자별 가격',
  staffPriceOverrideHint: '비워두면 기본 결제 금액을 사용합니다.',
  resourcePriceOverrides: '자원별 가격',
  resourcePriceOverrideHint: '비워두면 담당자 또는 기본 결제 금액을 사용합니다.',
  resourcePriceOverrideSummary: (resourceName, currency, amount) => `자원별 ${resourceName}: ${currency} ${amount.toLocaleString()}`,
  discountCodes: '할인 코드',
  discountCodesHint: '유료 서비스에만 적용됩니다. 고객이 입력한 코드는 결제 전 서버에서 다시 계산됩니다.',
  discountCode: '코드',
  discountType: '유형',
  discountValue: '값',
  discountLocale: '언어',
  discountAllLocales: '전체',
  discountActive: '활성',
  discountPercent: '% 할인',
  discountFixed: '고정 할인',
  addDiscountCode: '할인 코드 추가',
  removeDiscountCode: '삭제',
  discountCodeSummary: (code, type, value) => `${code} · ${type === 'percent' ? `${value}%` : value.toLocaleString()}`,
  anyActiveStaff: '활성 담당자 누구나',
  noSharedResources: '공유 자원 없음',
  active: '활성',
  inactive: '비활성',
  edit: '편집',
  deactivate: '비활성화',
  editService: '서비스 편집',
  close: '닫기',
  nameKo: '이름 KO',
  nameEn: '이름 EN',
  nameZh: '이름 ZH',
  durationMinutes: '소요 시간(분)',
  priceTwd: '가격(TWD)',
  paymentMode: '결제 방식',
  paymentAmount: '결제 금액',
  depositDueNow: '지금 결제할 보증금',
  paymentCurrency: '결제 통화',
  meetingMode: '상담 방식',
  cancellationPolicy: '취소 정책',
  noPolicy: '정책 없음',
  category: '카테고리',
  bufferBefore: '버퍼 시작 전',
  bufferAfter: '버퍼 종료 후',
  capacity: '정원',
  bookingInterval: '예약 간격',
  reminderSchedule: '리마인더 일정',
  reminderHint: '둘 다 선택 해제하면 이 서비스의 이메일과 SMS 리마인더를 끌 수 있습니다.',
  hoursBefore24: '24시간 전',
  hoursBefore1: '1시간 전',
  imageUrl: '이미지 URL',
  descriptionKo: '설명 KO',
  descriptionEn: '설명 EN',
  descriptionZh: '설명 ZH',
  staff: '담당자',
  requiredResources: '필수 자원',
  inactiveResources: (names) => `비활성 자원: ${names.join(', ')}`,
  resourceHint: '선택하면 같은 회의실 또는 장비에 다른 예약이 겹치면 슬롯이 닫힙니다.',
  inactiveResourcesList: (names) => `비활성 자원: ${names.join(', ')}`,
  reminderSummary: (hours) => (hours.length > 0 ? `리마인더 ${hours.join('시간 + ')}시간 전` : '리마인더 끔'),
  policySummary: (id, name) => `정책 ${id}${name ? ` · ${name}` : ''}`,
  policyLabel: (policy) => {
    const segments = [policy.name];
    if (policy.cancellationFeePercent > 0) segments.push(`수수료 ${policy.cancellationFeePercent}%`);
    if (!policy.isActive) segments.push('비활성');
    return segments.join(' · ');
  },
  inactiveResourceWarning: (names) => `비활성 자원: ${names.join(', ')}`,
  resourceActive: '활성',
  resourceInactive: '비활성',
  freeOption: '무료 예약',
  paidOption: '예약 전 결제',
  inPerson: '대면',
  zoom: 'Zoom 자동 링크',
  phone: '전화',
  hybrid: '하이브리드',
  paginationPage: (page, total, items) => `${page}/${total}페이지 (총 ${items}개)`,
  paginationPageSize: '페이지당',
  paginationPrev: '이전',
  paginationNext: '다음',
} satisfies BookingServicesAdminCopy;
