import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const MARGIN = 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const HERO_H = 600;
const PROGRAMS_Y = HERO_H + 80;
const PROGRAMS_H = 420;
const STATS_Y = PROGRAMS_Y + PROGRAMS_H + 80;
const STATS_H = 200;
const CTA_Y = STATS_Y + STATS_H + 80;
const CTA_H = 200;
const STAGE_H = CTA_Y + CTA_H + 80;

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero ────────────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-eduhome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-eduhome-hero-bg',
    parentId: 'tpl-eduhome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    src: '/images/placeholder-education-hero.jpg',
    alt: '캠퍼스 전경 이미지',
    style: { opacity: 30, borderRadius: 0 },
  }),
  heading(
    'tpl-eduhome-hero-title',
    { x: MARGIN, y: 160, width: 600, height: 100 },
    '미래를 여는 교육',
    1,
    '#ffffff',
    'left',
    'tpl-eduhome-hero',
  ),
  createTextNode({
    id: 'tpl-eduhome-hero-tagline',
    parentId: 'tpl-eduhome-hero',
    rect: { x: MARGIN, y: 280, width: 500, height: 60 },
    text: '최고의 교수진과 실무 중심 커리큘럼으로 여러분의 꿈을 실현하세요.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-eduhome-hero-cta',
    parentId: 'tpl-eduhome-hero',
    rect: { x: MARGIN, y: 370, width: 200, height: 52 },
    label: '입학 지원하기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Program highlights ──────────────────────────────────── */
  heading(
    'tpl-eduhome-programs-title',
    { x: MARGIN, y: PROGRAMS_Y, width: 400, height: 50 },
    '주요 프로그램',
    2,
    '#123b63',
  ),
  createContainerNode({
    id: 'tpl-eduhome-prog-1',
    rect: { x: MARGIN, y: PROGRAMS_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-eduhome-prog-1-title', { x: 24, y: 24, width: 212, height: 36 }, '컴퓨터공학', 3, '#123b63', 'left', 'tpl-eduhome-prog-1'),
  createTextNode({
    id: 'tpl-eduhome-prog-1-desc',
    parentId: 'tpl-eduhome-prog-1',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: 'AI, 빅데이터, 소프트웨어 개발 등 IT 분야의 전문 인재를 양성합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-eduhome-prog-2',
    rect: { x: 370, y: PROGRAMS_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-eduhome-prog-2-title', { x: 24, y: 24, width: 212, height: 36 }, '경영학', 3, '#123b63', 'left', 'tpl-eduhome-prog-2'),
  createTextNode({
    id: 'tpl-eduhome-prog-2-desc',
    parentId: 'tpl-eduhome-prog-2',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '글로벌 비즈니스 리더를 양성하는 실무 중심의 경영 교육과정입니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-eduhome-prog-3',
    rect: { x: 660, y: PROGRAMS_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-eduhome-prog-3-title', { x: 24, y: 24, width: 212, height: 36 }, '디자인', 3, '#123b63', 'left', 'tpl-eduhome-prog-3'),
  createTextNode({
    id: 'tpl-eduhome-prog-3-desc',
    parentId: 'tpl-eduhome-prog-3',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '시각, UX/UI, 산업 디자인 분야의 창의적 인재를 키웁니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-eduhome-prog-4',
    rect: { x: 950, y: PROGRAMS_Y + 70, width: 260, height: 300 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-eduhome-prog-4-title', { x: 24, y: 24, width: 212, height: 36 }, '외국어', 3, '#123b63', 'left', 'tpl-eduhome-prog-4'),
  createTextNode({
    id: 'tpl-eduhome-prog-4-desc',
    parentId: 'tpl-eduhome-prog-4',
    rect: { x: 24, y: 70, width: 212, height: 80 },
    text: '영어, 중국어, 일본어 등 글로벌 커뮤니케이션 역량을 강화합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),

  /* ── Stats ───────────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-eduhome-stats',
    rect: { x: 0, y: STATS_Y, width: W, height: STATS_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  createTextNode({
    id: 'tpl-eduhome-stats-data',
    parentId: 'tpl-eduhome-stats',
    rect: { x: MARGIN, y: 60, width: 800, height: 60 },
    text: '재학생 3,000+ | 취업률 95% | 교수진 200+ | 해외 파트너 50+',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    align: 'center',
    lineHeight: 1.5,
  }),

  /* ── Apply CTA ───────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-eduhome-cta',
    rect: { x: 0, y: CTA_Y, width: W, height: CTA_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createTextNode({
    id: 'tpl-eduhome-cta-text',
    parentId: 'tpl-eduhome-cta',
    rect: { x: MARGIN, y: 50, width: 600, height: 44 },
    text: '새로운 시작을 준비하세요. 지금 입학 상담을 신청하세요.',
    fontSize: 18,
    color: '#ffffff',
    fontWeight: 'medium',
    lineHeight: 1.4,
  }),
  createButtonNode({
    id: 'tpl-eduhome-cta-btn',
    parentId: 'tpl-eduhome-cta',
    rect: { x: MARGIN, y: 120, width: 180, height: 48 },
    label: '입학 상담 신청',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-educationhome-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-proof-label',
    parentId: 'tpl-educationhome-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-proof-title',
    parentId: 'tpl-educationhome-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'education home 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-proof-copy',
    parentId: 'tpl-educationhome-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-metric-1',
    parentId: 'tpl-educationhome-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-metric-1-value',
    parentId: 'tpl-educationhome-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-metric-1-label',
    parentId: 'tpl-educationhome-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-metric-2',
    parentId: 'tpl-educationhome-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-metric-2-value',
    parentId: 'tpl-educationhome-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-metric-2-label',
    parentId: 'tpl-educationhome-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-metric-3',
    parentId: 'tpl-educationhome-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-metric-3-value',
    parentId: 'tpl-educationhome-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-metric-3-label',
    parentId: 'tpl-educationhome-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-metric-4',
    parentId: 'tpl-educationhome-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-metric-4-value',
    parentId: 'tpl-educationhome-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-metric-4-label',
    parentId: 'tpl-educationhome-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-label',
    parentId: 'tpl-educationhome-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-title',
    parentId: 'tpl-educationhome-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-copy',
    parentId: 'tpl-educationhome-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-showcase-visual',
    parentId: 'tpl-educationhome-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-visual-title',
    parentId: 'tpl-educationhome-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-visual-copy',
    parentId: 'tpl-educationhome-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-showcase-card-1',
    parentId: 'tpl-educationhome-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-card-1-title',
    parentId: 'tpl-educationhome-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-card-1-copy',
    parentId: 'tpl-educationhome-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-showcase-card-2',
    parentId: 'tpl-educationhome-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-card-2-title',
    parentId: 'tpl-educationhome-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-card-2-copy',
    parentId: 'tpl-educationhome-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationhome-wix-showcase-card-3',
    parentId: 'tpl-educationhome-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-educationhome-wix-showcase-card-3-title',
    parentId: 'tpl-educationhome-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
]);

export const educationHomeTemplate: PageTemplate = {
  id: 'education-home',
  name: '교육기관 홈',
  category: 'education',
  subcategory: 'homepage',
  description: '히어로 + 주요 프로그램(4개) + 통계 + 입학 CTA',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
