import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const MARGIN = 80;
const CONTENT_W = W - MARGIN * 2;
const HEADER_H = 140;
const QA_H = 120;
const GAP = 16;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

interface Faq {
  key: string;
  q: string;
  a: string;
}

const faqs: Faq[] = [
  { key: 'requirement', q: '입학 자격은 어떻게 되나요?', a: '고등학교 졸업(예정)자 또는 동등 학력 인정자가 지원 가능합니다. 학과별 추가 요건은 입학처에 문의해 주세요.' },
  { key: 'deadline', q: '원서 접수 기간은 언제인가요?', a: '정시는 매년 12월~1월, 수시는 9월~10월에 접수합니다. 정확한 일정은 입학처 공지를 확인해 주세요.' },
  { key: 'scholarship', q: '장학금 제도가 있나요?', a: '성적 우수, 가정형편, 특기자 장학금 등 다양한 장학 프로그램을 운영합니다. 신입생 전원 대상 입학 장학금도 있습니다.' },
  { key: 'dormitory', q: '기숙사를 이용할 수 있나요?', a: '교내 기숙사(2인실/4인실)를 운영하며, 원거리 학생에게 우선권을 부여합니다. 기숙사비는 학기당 150만원입니다.' },
  { key: 'transfer', q: '편입학이 가능한가요?', a: '네, 매년 3월에 편입학 전형을 실시합니다. 전적 대학 이수 학점에 따라 학년이 배정됩니다.' },
  { key: 'internship', q: '인턴십 기회가 있나요?', a: '산학협력 기업과의 연계를 통해 3~4학년 학생에게 인턴십 기회를 제공합니다. 취업 연계율이 높습니다.' },
  { key: 'exchange', q: '해외 교환학생 프로그램이 있나요?', a: '미국, 일본, 유럽 등 50여 개 파트너 대학과 교환학생 프로그램을 운영합니다.' },
  { key: 'credit', q: '학점 인정은 어떻게 되나요?', a: '온라인 강좌, 자격증 등 다양한 경로로 학점 인정이 가능합니다. 학사 규정에 따라 심사를 진행합니다.' },
];

function buildFaqItem(faq: Faq, idx: number): BuilderCanvasNode[] {
  const y = HEADER_H + 40 + idx * (QA_H + GAP);
  const cid = `tpl-edufaq-item-${faq.key}`;

  return [
    createContainerNode({
      id: cid,
      rect: { x: MARGIN, y, width: CONTENT_W, height: QA_H },
      background: idx % 2 === 0 ? '#ffffff' : '#f9fafb',
      borderRadius: 10,
      borderColor: '#e2e8f0',
      borderWidth: 1,
      padding: 20,
    }),
    heading(`${cid}-q`, { x: 20, y: 16, width: CONTENT_W - 60, height: 32 }, faq.q, 3, '#123b63', 'left', cid),
    createTextNode({
      id: `${cid}-a`,
      parentId: cid,
      rect: { x: 20, y: 54, width: CONTENT_W - 60, height: 48 },
      text: faq.a,
      fontSize: 14,
      color: '#374151',
      lineHeight: 1.55,
    }),
  ];
}

const STAGE_H = HEADER_H + 40 + faqs.length * (QA_H + GAP) + 60;

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  heading('tpl-edufaq-title', { x: MARGIN, y: 50, width: 600, height: 56 }, '입학 FAQ', 1, '#123b63'),
  createTextNode({
    id: 'tpl-edufaq-subtitle',
    rect: { x: MARGIN, y: 110, width: 700, height: 32 },
    text: '입학에 관해 자주 묻는 질문과 답변을 모았습니다.',
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 1.4,
  }),
  ...faqs.flatMap((faq, i) => buildFaqItem(faq, i)),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-educationfaq-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-proof-label',
    parentId: 'tpl-educationfaq-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-proof-title',
    parentId: 'tpl-educationfaq-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'education faq 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-proof-copy',
    parentId: 'tpl-educationfaq-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-metric-1',
    parentId: 'tpl-educationfaq-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-metric-1-value',
    parentId: 'tpl-educationfaq-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-metric-1-label',
    parentId: 'tpl-educationfaq-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-metric-2',
    parentId: 'tpl-educationfaq-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-metric-2-value',
    parentId: 'tpl-educationfaq-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-metric-2-label',
    parentId: 'tpl-educationfaq-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-metric-3',
    parentId: 'tpl-educationfaq-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-metric-3-value',
    parentId: 'tpl-educationfaq-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-metric-3-label',
    parentId: 'tpl-educationfaq-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-metric-4',
    parentId: 'tpl-educationfaq-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-metric-4-value',
    parentId: 'tpl-educationfaq-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-metric-4-label',
    parentId: 'tpl-educationfaq-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-label',
    parentId: 'tpl-educationfaq-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-title',
    parentId: 'tpl-educationfaq-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-copy',
    parentId: 'tpl-educationfaq-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-showcase-visual',
    parentId: 'tpl-educationfaq-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-visual-title',
    parentId: 'tpl-educationfaq-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-visual-copy',
    parentId: 'tpl-educationfaq-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-showcase-card-1',
    parentId: 'tpl-educationfaq-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-card-1-title',
    parentId: 'tpl-educationfaq-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-card-1-copy',
    parentId: 'tpl-educationfaq-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-showcase-card-2',
    parentId: 'tpl-educationfaq-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-card-2-title',
    parentId: 'tpl-educationfaq-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-card-2-copy',
    parentId: 'tpl-educationfaq-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-showcase-card-3',
    parentId: 'tpl-educationfaq-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-card-3-title',
    parentId: 'tpl-educationfaq-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-showcase-card-3-copy',
    parentId: 'tpl-educationfaq-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-quote',
    parentId: 'tpl-educationfaq-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-quote-mark',
    parentId: 'tpl-educationfaq-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-quote-body',
    parentId: 'tpl-educationfaq-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-quote-role',
    parentId: 'tpl-educationfaq-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-cta-label',
    parentId: 'tpl-educationfaq-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-cta-title',
    parentId: 'tpl-educationfaq-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-cta-copy',
    parentId: 'tpl-educationfaq-wix-cta',
    rect: { x: 64, y: 214, width: 560, height: 64 },
    text: '짧은 설득 문구, 보조 안내, 두 개의 행동 버튼을 같은 영역에 묶어 전환 흐름을 분명하게 만듭니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-educationfaq-wix-cta-primary',
    parentId: 'tpl-educationfaq-wix-cta',
    rect: { x: 64, y: 318, width: 178, height: 52 },
    label: '문의 시작',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#e8a838', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-educationfaq-wix-cta-secondary',
    parentId: 'tpl-educationfaq-wix-cta',
    rect: { x: 266, y: 318, width: 176, height: 52 },
    label: '자세히 보기',
    href: '#services',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
  createTextNode({
    id: 'tpl-educationfaq-wix-cta-note',
    parentId: 'tpl-educationfaq-wix-cta',
    rect: { x: 64, y: 402, width: 420, height: 30 },
    text: 'Global header와 footer는 그대로 두고 인페이지 전환만 보강합니다.',
    fontSize: 13,
    color: 'rgba(255,255,255,0.68)',
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-educationfaq-wix-timeline',
    parentId: 'tpl-educationfaq-wix-cta',
    rect: { x: 690, y: 70, width: 360, height: 390 },
    background: 'rgba(255,255,255,0.10)',
    borderColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'split-image',
  }),
]);

export const educationFaqTemplate: PageTemplate = {
  id: 'education-faq',
  name: '입학 FAQ',
  category: 'education',
  subcategory: 'faq',
  description: '입학 관련 FAQ + 8개 Q&A 쌍',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
