import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const MARGIN = 80;
const CONTENT_W = W - MARGIN * 2;
const HEADER_H = 140;
const QA_H = 120;
const GAP = 16;

interface Faq {
  key: string;
  q: string;
  a: string;
}

const faqs: Faq[] = [
  { key: 'consult', q: '초기 상담은 무료인가요?', a: '네, 첫 30분 상담은 무료로 진행됩니다. 전화, 이메일 또는 사무소 방문을 통해 예약하실 수 있습니다. 상담 후 진행 여부는 자유롭게 결정하실 수 있습니다.' },
  { key: 'language', q: '한국어로 상담이 가능한가요?', a: '네, 저희 사무소의 모든 변호사는 한국어에 능통합니다. 한국어로 상담, 서류 작성, 법정 통역까지 모든 법률 서비스를 한국어로 제공합니다.' },
  { key: 'fee', q: '변호사 비용은 어떻게 되나요?', a: '사건의 복잡도와 유형에 따라 다릅니다. 시간당 과금, 성공 보수, 정액 수수료 등 다양한 방식을 제공하며, 상담 시 투명하게 안내해 드립니다.' },
  { key: 'duration', q: '사건 처리에 보통 얼마나 걸리나요?', a: '사건 유형에 따라 다르지만, 간단한 계약 검토는 1~2주, 소송 사건은 3~12개월이 소요될 수 있습니다. 구체적인 일정은 상담 시 안내드립니다.' },
  { key: 'online', q: '온라인 상담도 가능한가요?', a: '네, Zoom, Google Meet 등을 통한 화상 상담을 지원합니다. 대만 외 지역에 거주하시는 분들도 편리하게 상담받으실 수 있습니다.' },
  { key: 'document', q: '필요한 서류는 무엇인가요?', a: '사건 유형에 따라 다르지만, 일반적으로 신분증, 관련 계약서, 통신 기록 등이 필요합니다. 상담 예약 시 필요 서류 목록을 미리 안내해 드립니다.' },
  { key: 'area', q: '어떤 법률 분야를 다루나요?', a: '기업법, 부동산법, 이민법, 가족법, 노동법, 지적재산권 등 대만 법률 전반에 걸쳐 폭넓은 서비스를 제공합니다.' },
  { key: 'emergency', q: '긴급 상황에는 어떻게 연락하나요?', a: '긴급 법률 문제의 경우, 사무소 대표번호로 전화해 주시면 담당 변호사가 빠르게 연락드립니다. 영업시간 외에는 긴급 연락 양식을 이용해 주세요.' },
];

function buildFaqItem(faq: Faq, idx: number): BuilderCanvasNode[] {
  const y = HEADER_H + 40 + idx * (QA_H + GAP);
  const cid = `tpl-faq-item-${faq.key}`;

  return [
    createContainerNode({
      id: cid,
      rect: { x: MARGIN, y, width: CONTENT_W, height: QA_H },
      background: idx % 2 === 0 ? '#ffffff' : '#f9fafb',
      borderRadius: 10,
      borderColor: '#e2e8f0',
      borderWidth: 1,
      padding: 20,
    }),
    heading(`${cid}-q`, { x: 20, y: 16, width: CONTENT_W - 60, height: 32 }, faq.q, 3, '#123b63', 'left', cid),
    createTextNode({
      id: `${cid}-a`,
      parentId: cid,
      rect: { x: 20, y: 54, width: CONTENT_W - 60, height: 48 },
      text: faq.a,
      fontSize: 14,
      color: '#374151',
      lineHeight: 1.55,
    }),
  ];
}

const STAGE_H = HEADER_H + 40 + faqs.length * (QA_H + GAP) + 60;

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  heading(
    'tpl-faq-title',
    { x: MARGIN, y: 50, width: 600, height: 56 },
    '자주 묻는 질문',
    1,
    '#123b63',
  ),
  createTextNode({
    id: 'tpl-faq-subtitle',
    rect: { x: MARGIN, y: 110, width: 700, height: 32 },
    text: '고객님들이 가장 궁금해하시는 질문과 답변을 모았습니다.',
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 1.4,
  }),
  ...faqs.flatMap((faq, i) => buildFaqItem(faq, i)),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-lawfaq-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-proof-label',
    parentId: 'tpl-lawfaq-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-proof-title',
    parentId: 'tpl-lawfaq-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'law faq 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-proof-copy',
    parentId: 'tpl-lawfaq-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-metric-1',
    parentId: 'tpl-lawfaq-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-metric-1-value',
    parentId: 'tpl-lawfaq-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-metric-1-label',
    parentId: 'tpl-lawfaq-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-metric-2',
    parentId: 'tpl-lawfaq-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-metric-2-value',
    parentId: 'tpl-lawfaq-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-metric-2-label',
    parentId: 'tpl-lawfaq-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-metric-3',
    parentId: 'tpl-lawfaq-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-metric-3-value',
    parentId: 'tpl-lawfaq-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-metric-3-label',
    parentId: 'tpl-lawfaq-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-metric-4',
    parentId: 'tpl-lawfaq-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-metric-4-value',
    parentId: 'tpl-lawfaq-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-metric-4-label',
    parentId: 'tpl-lawfaq-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-label',
    parentId: 'tpl-lawfaq-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-title',
    parentId: 'tpl-lawfaq-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-copy',
    parentId: 'tpl-lawfaq-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-showcase-visual',
    parentId: 'tpl-lawfaq-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-visual-title',
    parentId: 'tpl-lawfaq-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-visual-copy',
    parentId: 'tpl-lawfaq-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-showcase-card-1',
    parentId: 'tpl-lawfaq-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-card-1-title',
    parentId: 'tpl-lawfaq-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-card-1-copy',
    parentId: 'tpl-lawfaq-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-showcase-card-2',
    parentId: 'tpl-lawfaq-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-card-2-title',
    parentId: 'tpl-lawfaq-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-card-2-copy',
    parentId: 'tpl-lawfaq-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-showcase-card-3',
    parentId: 'tpl-lawfaq-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-card-3-title',
    parentId: 'tpl-lawfaq-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-showcase-card-3-copy',
    parentId: 'tpl-lawfaq-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-quote',
    parentId: 'tpl-lawfaq-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-quote-mark',
    parentId: 'tpl-lawfaq-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-quote-body',
    parentId: 'tpl-lawfaq-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-quote-role',
    parentId: 'tpl-lawfaq-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-cta-label',
    parentId: 'tpl-lawfaq-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-cta-title',
    parentId: 'tpl-lawfaq-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-cta-copy',
    parentId: 'tpl-lawfaq-wix-cta',
    rect: { x: 64, y: 214, width: 560, height: 64 },
    text: '짧은 설득 문구, 보조 안내, 두 개의 행동 버튼을 같은 영역에 묶어 전환 흐름을 분명하게 만듭니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-lawfaq-wix-cta-primary',
    parentId: 'tpl-lawfaq-wix-cta',
    rect: { x: 64, y: 318, width: 178, height: 52 },
    label: '문의 시작',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#e8a838', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-lawfaq-wix-cta-secondary',
    parentId: 'tpl-lawfaq-wix-cta',
    rect: { x: 266, y: 318, width: 176, height: 52 },
    label: '자세히 보기',
    href: '#services',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
  createTextNode({
    id: 'tpl-lawfaq-wix-cta-note',
    parentId: 'tpl-lawfaq-wix-cta',
    rect: { x: 64, y: 402, width: 420, height: 30 },
    text: 'Global header와 footer는 그대로 두고 인페이지 전환만 보강합니다.',
    fontSize: 13,
    color: 'rgba(255,255,255,0.68)',
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-lawfaq-wix-timeline',
    parentId: 'tpl-lawfaq-wix-cta',
    rect: { x: 690, y: 70, width: 360, height: 390 },
    background: 'rgba(255,255,255,0.10)',
    borderColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'split-image',
  }),
]);

export const lawFaqTemplate: PageTemplate = {
  id: 'law-faq',
  name: '자주 묻는 질문',
  category: 'law',
  subcategory: 'faq',
  description: 'FAQ 제목 + 8개 Q&A 쌍(질문 + 답변 텍스트), 컨테이너 그룹',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
