import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { createHeroDecomposedNodes } from '@/lib/builder/canvas/decompose-hero';
import type { Locale } from '@/lib/locales';

const root = process.cwd();

function read(relativePath: string): string {
  return readFileSync(path.join(root, relativePath), 'utf8');
}

function heroQuickMenuLabels(locale: Locale): string[] {
  return createHeroDecomposedNodes(0, locale, 0)
    .filter((node) => /^home-hero-quick-menu-item-\d+$/.test(node.id))
    .map((node) => {
      if (!('label' in node.content) || typeof node.content.label !== 'string') {
        throw new Error(`Missing quick menu label for ${node.id}.`);
      }
      return node.content.label;
    });
}

describe('canvas selection render contract', () => {
  it('keeps node selection subscriptions scoped to primitive per-node selectors', () => {
    const canvasNode = read('src/components/builder/canvas/CanvasNode.tsx');
    const canvasStageNodes = read('src/components/builder/canvas/CanvasStageNodes.tsx');
    const canvasFlow = read('src/lib/builder/canvas/flow.ts');

    expect(canvasNode).toContain('const CanvasNode = memo(function CanvasNode');
    expect(canvasStageNodes).toContain("import { Fragment, memo, useCallback, useMemo } from 'react';");
    expect(canvasStageNodes).toContain('export default memo(CanvasStageNodes);');
    expect(canvasStageNodes).toContain('function getSortedRootNodeBuckets(rootVisibleNodes: BuilderCanvasNode[]): SortedRootNodeBuckets {');
    expect(canvasStageNodes).toContain('const { flowSectionNodes, nonFlowRootNodes } = useMemo(');
    expect(canvasStageNodes).toContain('const { selectedNodeIds, selectedNodeIdSet } = useBuilderCanvasStore.getState();');
    expect(canvasStageNodes).toContain('const keepMultiSelection = selectedNodeIds.length > 1 && selectedNodeIdSet.has(nodeId);');
    expect(canvasStageNodes).not.toContain('sortedRootNodes.filter(isTopLevelFlowSection)');
    expect(canvasStageNodes).not.toContain('sortedRootNodes.filter((node) => !isTopLevelFlowSection(node))');
    expect(canvasStageNodes).not.toContain('selectedIds.includes(nodeId)');
    expect(canvasNode).not.toContain('selected: boolean;');
    expect(canvasNode).not.toContain('const selectedNodeIds = useBuilderCanvasStore');
    expect(canvasNode).not.toContain('const primarySelectedNodeId = useBuilderCanvasStore');
    expect(canvasNode).toContain('const selected = useBuilderCanvasStore((s) => s.selectedNodeIdSet.has(node.id));');
    expect(canvasNode).toContain('for (const selectedId of s.selectedNodeIdSet)');
    expect(canvasNode).not.toContain('s.selectedNodeIds.includes(node.id)');
    expect(canvasNode).not.toContain('Array.from(s.selectedNodeIdSet)');
    expect(canvasNode).toContain('const EMPTY_PREVIEW_INDEX_SET: ReadonlySet<number> = new Set<number>();');
    expect(canvasNode).toContain('function resolvePreviewIndexSet(');
    expect(canvasNode).toContain('if (!needsPreviewState) return EMPTY_PREVIEW_INDEX_SET;');
    expect(canvasNode).toContain('const servicesRevealedIndices = resolvePreviewIndexSet(');
    expect(canvasNode).toContain('const faqRevealedIndices = resolvePreviewIndexSet(');
    expect(canvasNode).not.toContain('const servicesRevealedIndices = new Set(');
    expect(canvasNode).not.toContain('const faqRevealedIndices = new Set(');
    expect(canvasNode).not.toContain('const interactivePreview = useBuilderCanvasStore((s) => s.interactivePreview);');
    expect(canvasNode).toContain('if (!isServicePreviewNode) return -1;');
    expect(canvasNode).toContain('if (!isFaqPreviewNode) return -1;');
    expect(canvasNode).toContain('needsServicesPreviewState ? s.interactivePreview.servicesOpenIndex : -1');
    expect(canvasNode).toContain('needsFaqPreviewState ? s.interactivePreview.faqOpenIndex : -1');
    expect(canvasNode).toContain("node.id === 'home-hero-quick-menu'");
    expect(canvasStageNodes).toContain('nodesById: Map<string, BuilderCanvasNode>;');
    expect(canvasStageNodes).toContain('export function getInnerFlowLayoutState({');
    expect(canvasStageNodes).toContain('export function getVisibleNodeRelationshipState({');
    expect(canvasStageNodes).toContain('const flowLayoutChildNodeIds = new Set<string>();');
    expect(canvasStageNodes).toContain('const flowLayoutParentIds = viewport === \'desktop\'');
    expect(canvasStageNodes).toContain('flowLayoutChildNodeIds.add(node.id);');
    expect(canvasStageNodes).toContain('computeFlowSiblingMetrics(siblings, viewport)');
    expect(canvasStageNodes).toContain('const visibleNodeRelationshipState = useMemo(');
    expect(canvasStageNodes).toContain('() => getVisibleNodeRelationshipState({ nodesById, viewport, visibleNodes })');
    expect(canvasStageNodes).toContain('visibleNodeRelationshipState.visibleChildrenByParentId');
    expect(canvasStageNodes).not.toContain('const innerFlowLayoutState = useMemo(');
    expect(canvasStageNodes).not.toContain('const visibleChildrenByParentId = useMemo(');
    expect(canvasStageNodes).toContain('childrenMap: Record<string, string[]>;');
    expect(canvasStageNodes).toContain('computeTopLevelFlowSectionMetricsFromIndex({');
    expect(canvasStageNodes).toContain('childrenMap,');
    expect(canvasStageNodes).not.toContain('computeTopLevelFlowSectionMetrics(visibleNodes)');
    expect(canvasStageNodes).toContain('export function getVisibleChildrenByParentId(');
    expect(canvasStageNodes).toContain('const visibleChildrenByParentId = new Map<string, BuilderCanvasNode[]>();');
    expect(canvasStageNodes).toContain('flowSectionNodes: readonly BuilderCanvasNode[];');
    expect(canvasStageNodes).toContain('visibleChildrenByParentId: VisibleChildrenByParentId;');
    expect(canvasStageNodes).toContain('visibleChildrenByParentId={visibleNodeRelationshipState.visibleChildrenByParentId}');
    expect(canvasStageNodes).toContain('innerFlowPreviewGapInfo={innerFlowPreviewGapInfo}');
    expect(canvasStageNodes).not.toContain('selectedNodeIds: string[];');
    expect(canvasStageNodes).not.toContain('selected={');
    expect(canvasNode).toContain('flowLayoutChildNodeIds: ReadonlySet<string>;');
    expect(canvasNode).toContain('innerFlowSiblingMetrics: Map<string, { marginTop: number; minHeight: number }>;');
    expect(canvasNode).toContain('visibleChildrenByParentId: ReadonlyMap<string, readonly BuilderCanvasNode[]>;');
    expect(canvasNode).toContain('innerFlowPreviewGapInfo: CanvasNodeInnerFlowPreviewGapInfo | null;');
    expect(canvasNode).toContain('const parentUsesFlowLayout = flowLayoutChildNodeIds.has(node.id);');
    expect(canvasNode).toContain('const innerFlowMarginTop = !isFlowSection && parentUsesFlowLayout && viewport !== \'desktop\' && node.parentId');
    expect(canvasNode).toContain('innerFlowSiblingMetrics.get(node.id)?.marginTop');
    expect(canvasNode).toContain('const nestedChildren = visibleChildrenByParentId.get(node.id) ?? EMPTY_CANVAS_NODE_CHILDREN;');
    expect(canvasNode).toContain('const flowSiblings = visibleChildrenByParentId.get(node.id) ?? EMPTY_CANVAS_NODE_CHILDREN;');
    expect(canvasNode).toContain('const activeInnerFlowPreviewGapInfo = innerFlowPreviewGapInfo?.parentId === node.id');
    expect(canvasNode).not.toContain('parentUsesFlowLayoutFn(node, nodesById)');
    expect(canvasNode).not.toContain('const childrenMap = useBuilderCanvasStore');
    expect(canvasNode).not.toContain('const childIds = childrenMap[node.id] ?? [];');
    expect(canvasNode).not.toContain('const siblings = visibleNodes.filter(');
    expect(canvasNode).not.toContain('getFlowSiblings(visibleNodes, node.id)');
    expect(canvasNode).not.toContain('computeFlowSiblingMetrics(siblings, viewport)');
    expect(canvasNode).not.toContain('visibleNodes: BuilderCanvasNode[];');
    expect(canvasNode).not.toContain('visibleNodes={visibleNodes}');
    expect(canvasNode).not.toContain('getFlowSiblingInsertionIndex(visibleNodes');
    expect(canvasNode).not.toContain('getFlowGroupKey');
    expect(canvasFlow).toContain('nodesById: Map<string, BuilderCanvasNode>,\n  childrenMap: Record<string, string[]>,');
    expect(canvasFlow).toContain('type ResolvedFlowSiblingEntry = {');
    expect(canvasFlow).toContain('if (siblings.length === 1) {');
    expect(canvasFlow).toContain('const resolvedEntries = new Array<ResolvedFlowSiblingEntry>(siblings.length);');
    expect(canvasFlow).toContain('for (let index = 0; index < siblings.length; index += 1) {');
    expect(canvasFlow).not.toContain('const resolvedEntries = siblings.map((node) => {');
    expect(canvasFlow).toContain('export function computeTopLevelFlowSectionMetricsFromIndex({');
    expect(canvasFlow).toContain('const nodesById = new Map<string, BuilderCanvasNode>();');
    expect(canvasFlow).toContain('childrenMap: buildChildrenMap(nodes),');
    expect(canvasFlow).toContain('resolveSectionContentHeight(node, nodesById, childrenMap, viewport)');
    expect(canvasFlow).not.toContain('getCanvasNodeDescendantIds');
    expect(canvasFlow).not.toContain('const nodesById = new Map(nodes.map((node) => [node.id, node]));');
    expect(canvasFlow).not.toContain('const topLevelNodes = nodes.filter((node) => !node.parentId);');
  });

  it('keeps shell-level selected and modal node lookups on the indexed node map', () => {
    const sandboxPage = read('src/components/builder/canvas/SandboxPage.tsx');
    const sandboxPageCss = read('src/components/builder/canvas/SandboxPage.module.css');
    const sandboxTopBar = read('src/components/builder/canvas/SandboxTopBar.tsx');
    const sandboxCatalogPanel = read('src/components/builder/canvas/SandboxCatalogPanel.tsx');
    const componentLibraryPanel = read('src/components/builder/canvas/ComponentLibraryPanel.tsx');
    const componentLibraryPanelContent = read('src/components/builder/canvas/ComponentLibraryPanelContent.tsx');
    const componentLibraryPanelHeader = read('src/components/builder/canvas/ComponentLibraryPanelHeader.tsx');
    const componentLibraryPanelList = [read('src/components/builder/canvas/ComponentLibraryPanelList.tsx'), read('src/components/builder/canvas/ComponentLibraryPanelItem.tsx')].join('\n');
    const sandboxEditorRail = read('src/components/builder/canvas/SandboxEditorRail.tsx');
    const sandboxEditorWorkspace = read('src/components/builder/canvas/SandboxEditorWorkspace.tsx');
    const sandboxEditorWorkspaceTypes = read('src/components/builder/canvas/SandboxEditorWorkspace.types.ts');
    const sandboxPublishedSiteChrome = read('src/components/builder/canvas/SandboxPublishedSiteChrome.tsx');
    const sandboxPublicChromePreview = read('src/components/builder/canvas/SandboxPublicChromePreview.tsx');
    const quickContactWidget = read('src/components/QuickContactWidget.tsx');
    const sandboxInspectorPanel = read('src/components/builder/canvas/SandboxInspectorPanel.tsx');
    const sandboxInspectorLayoutTab = read('src/components/builder/canvas/SandboxInspectorLayoutTab.tsx');
    const sandboxInspectorPanelWidgets = read('src/components/builder/canvas/SandboxInspectorPanel.widgets.tsx');
    const sandboxLayersPanel = read('src/components/builder/canvas/SandboxLayersPanel.tsx');
    const layersTreeRow = read('src/components/builder/canvas/LayersTreeRow.tsx');
    const navigationEditor = read('src/components/builder/canvas/NavigationEditor.tsx');
    const siteSettingsPresetsTab = read('src/components/builder/canvas/SiteSettingsPresetsTab.tsx');
    const pageSwitcher = read('src/components/builder/canvas/PageSwitcher.tsx');
    const pageSwitcherStyles = read('src/components/builder/canvas/PageSwitcher.styles.ts');
    const templateGalleryModal = read('src/components/builder/canvas/TemplateGalleryModal.tsx');
    const templateGalleryModalStyles = read('src/components/builder/canvas/TemplateGalleryModal.styles.ts');
    const canvasContainer = read('src/components/builder/canvas/CanvasContainer.tsx');
    const canvasNode = read('src/components/builder/canvas/CanvasNode.tsx');
    const canvasInteraction = read('src/components/builder/canvas/canvasInteraction.ts');
    const canvasFeedbackGeometry = read('src/components/builder/canvas/useCanvasFeedbackGeometry.ts');
    const canvasStageGeometry = read('src/components/builder/canvas/useCanvasStageGeometry.ts');
    const canvasStore = read('src/lib/builder/canvas/store.ts');
    const useCanvasInteractions = read('src/components/builder/canvas/hooks/useCanvasInteractions.ts');
    const canvasContextMenuLayer = read('src/components/builder/canvas/CanvasContextMenuLayer.tsx');
    const contextMenu = read('src/components/builder/canvas/ContextMenu.tsx');
    const canvasDropHighlight = read('src/components/builder/canvas/CanvasDropHighlight.tsx');
    const canvasFeedbackOverlay = read('src/components/builder/canvas/CanvasFeedbackOverlay.tsx');
    const alignmentGuides = read('src/components/builder/canvas/AlignmentGuides.tsx');
    const dragGhost = read('src/components/builder/canvas/DragGhost.tsx');
    const multiSelectionBoundingBox = read('src/components/builder/canvas/MultiSelectionBoundingBox.tsx');
    const resizeReadout = read('src/components/builder/canvas/ResizeReadout.tsx');
    const snapDistanceLabel = read('src/components/builder/canvas/SnapDistanceLabel.tsx');
    const canvasOverlapPickerLayer = read('src/components/builder/canvas/CanvasOverlapPickerLayer.tsx');
    const canvasSelectionToolbarLayer = read('src/components/builder/canvas/CanvasSelectionToolbarLayer.tsx');
    const selectionToolbar = read('src/components/builder/canvas/SelectionToolbar.tsx');
    const selectionToolbarActionButton = read('src/components/builder/canvas/SelectionToolbarActionButton.tsx');
    const selectionToolbarActions = read('src/components/builder/canvas/useSelectionToolbarActions.ts');
    const editorChromeIcon = read('src/components/builder/canvas/EditorChromeIcon.tsx');
    const undoStackTimeline = read('src/components/builder/canvas/UndoStackTimeline.tsx');
    const versionHistoryPanel = read('src/components/builder/canvas/VersionHistoryPanel.tsx');
    const versionHistoryPanelCss = read('src/components/builder/canvas/VersionHistoryPanel.module.css');
    const saveSectionModal = read('src/components/builder/sections/SaveSectionModal.tsx');
    const saveSectionModalCss = read('src/components/builder/sections/SaveSectionModal.module.css');
    const builtInSectionsPanel = read('src/components/builder/sections/BuiltInSectionsPanel.tsx');
    const sectionTemplateCard = read('src/components/builder/sections/SectionTemplateCard.tsx');
    const sectionLibraryPanelCss = read('src/components/builder/sections/SectionLibraryPanel.module.css');
    const canvasNodeBadge = read('src/components/builder/canvas/CanvasNodeBadge.tsx');
    const canvasNodeBadgeCss = read('src/components/builder/canvas/CanvasNodeBadge.module.css');
    const canvasNodeSelectionOverlayCss = read('src/components/builder/canvas/CanvasNodeSelectionOverlay.module.css');
    const canvasStageToolbar = read('src/components/builder/canvas/CanvasStageToolbar.tsx');
    const canvasStageToolbarCss = read('src/components/builder/canvas/CanvasStageToolbar.module.css');
    const canvasZoomDock = read('src/components/builder/canvas/CanvasZoomDock.tsx');
    const singleRectFastPath = canvasStore.slice(
      canvasStore.indexOf('function applyTransientSingleNodeRectDocument'),
      canvasStore.indexOf('function alignNodeRects'),
    );

    expect(sandboxPage).toContain('nodesById,');
    expect(sandboxPage).toContain('const canvasDocument = useBuilderCanvasStore((state) => state.document);');
    expect(sandboxPage).toContain('const nodesById = useBuilderCanvasStore((state) => state.nodesById);');
    expect(sandboxPage).toContain('const selectedNodeId = useBuilderCanvasStore((state) => state.selectedNodeId);');
    expect(sandboxPage).toContain('const selectedNodeIds = useBuilderCanvasStore((state) => state.selectedNodeIds);');
    expect(sandboxPage).toContain('const draftSaveState = useBuilderCanvasStore((state) => state.draftSaveState);');
    expect(sandboxPage).toContain('const clipboardCount = useBuilderCanvasStore((state) => state.clipboardCount);');
    expect(sandboxPage).toContain('const setStoreViewport = useBuilderCanvasStore((state) => state.setViewport);');
    expect(sandboxPage).toContain('nodesById.get(selectedNodeId)');
    expect(sandboxPage).toContain('nodesById.get(assetLibraryNodeId)');
    expect(sandboxPage).toContain('nodesById.get(imageEditorRequest.nodeId)');
    expect(sandboxPage).toContain('const openPublishPanel = useCallback(() => setPublishOpen(true), []);');
    expect(sandboxPage).toContain('const openSeoPanel = useCallback(() => setSeoOpen(true), []);');
    expect(sandboxPage).toContain('const openSettingsPanel = useCallback(() => setSettingsOpen(true), []);');
    expect(sandboxPage).toContain('const openHistoryPanel = useCallback(() => setHistoryOpen(true), []);');
    expect(sandboxPage).toContain('const openPreviewPanel = useCallback(() => setPreviewOpen(true), []);');
    expect(sandboxPage).toContain('const openPagesDrawer = useCallback(() => setActiveDrawer(\'pages\'), []);');
    expect(sandboxPage).toContain('onPublish={openPublishPanel}');
    expect(sandboxPage).toContain('onOpenSeo={openSeoPanel}');
    expect(sandboxPage).toContain('onOpenSettings={openSettingsPanel}');
    expect(sandboxPage).toContain('onOpenHistory={openHistoryPanel}');
    expect(sandboxPage).toContain('onOpenPreview={openPreviewPanel}');
    expect(sandboxPage).toContain('onOpenPages={openPagesDrawer}');
    expect(sandboxPage).not.toContain('canvasDocument?.nodes.find((node) => node.id === selectedNodeId)');
    expect(sandboxPage).not.toContain('canvasDocument?.nodes.find((node) => node.id === assetLibraryNodeId)');
    expect(sandboxPage).not.toContain("canvasDocument?.nodes.find((node) => node.id === imageEditorRequest?.nodeId)");
    expect(sandboxPage).not.toContain('useBuilderCanvasStore();');
    expect(sandboxPage).not.toContain('onPublish={() => setPublishOpen(true)}');
    expect(sandboxPage).not.toContain('onOpenSeo={() => setSeoOpen(true)}');
    expect(sandboxPage).not.toContain('onOpenSettings={() => setSettingsOpen(true)}');
    expect(sandboxPage).not.toContain('onOpenHistory={() => setHistoryOpen(true)}');
    expect(sandboxPage).not.toContain('onOpenPreview={() => setPreviewOpen(true)}');
    expect(sandboxPage).not.toContain('onOpenPages={() => setActiveDrawer(\'pages\')}');
    expect(sandboxTopBar).toContain('const selectedNodeId = useBuilderCanvasStore((state) => state.selectedNodeId);');
    expect(sandboxTopBar).toContain('const hasSelectedOverride = useBuilderCanvasStore((state) => {');
    expect(sandboxTopBar).toContain('state.nodesById.get(state.selectedNodeId)');
    expect(sandboxTopBar).toContain('const resetResponsiveOverride = useBuilderCanvasStore((state) => state.resetResponsiveOverride);');
    expect(sandboxTopBar).toContain('className={styles.pageDropdownCurrent}');
    expect(sandboxTopBar).toContain('const pageSelectorLabel = `${copy.pageControlLabel} ${pageLabel}`;');
    expect(sandboxTopBar).toContain('aria-label={pageSelectorAriaLabel}');
    expect(sandboxTopBar).toContain('data-builder-topbar-page-selector="true"');
    expect(sandboxTopBar).toContain('export default memo(SandboxTopBar);');
    expect(sandboxTopBar).not.toContain('document?.nodes.find((node) => node.id === selectedNodeId)');
    expect(sandboxTopBar).not.toContain('const { nodesById, selectedNodeId, resetResponsiveOverride } = useBuilderCanvasStore();');
    expect(sandboxTopBar).not.toContain('const selectedNode = selectedNodeId ? nodesById.get(selectedNodeId) ?? null : null;');
    expect(sandboxCatalogPanel).toContain('const nodes = useBuilderCanvasStore((state) => state.document?.nodes ?? EMPTY_CATALOG_NODES);');
    expect(sandboxCatalogPanel).toContain('const hasDocument = useBuilderCanvasStore((state) => state.document != null);');
    expect(sandboxCatalogPanel).toContain('const documentLocale = useBuilderCanvasStore((state) => state.document?.locale);');
    expect(sandboxCatalogPanel).toContain('const addNode = useBuilderCanvasStore((state) => state.addNode);');
    expect(sandboxCatalogPanel).toContain('const addNodes = useBuilderCanvasStore((state) => state.addNodes);');
    expect(sandboxCatalogPanel).toContain('const setSelectedNodeId = useBuilderCanvasStore((state) => state.setSelectedNodeId);');
    expect(sandboxCatalogPanel).toContain('const setDraftSaveState = useBuilderCanvasStore((state) => state.setDraftSaveState);');
    expect(sandboxCatalogPanel).not.toContain('const { document, addNode, addNodes, setSelectedNodeId, setDraftSaveState } = useBuilderCanvasStore();');
    expect(componentLibraryPanel).toContain('<ComponentLibraryPanelContent');
    expect(componentLibraryPanelContent).toContain('className={styles.componentLibraryPanel}');
    expect(componentLibraryPanelHeader).toContain('className={styles.componentLibraryHeader}');
    expect(read('src/components/builder/canvas/ComponentLibraryPanelControls.tsx')).toContain('className={styles.componentLibrarySaveRow}');
    expect(componentLibraryPanelContent).toContain('<ComponentLibraryPanelList');
    expect(componentLibraryPanelList).toContain('className={styles.componentLibraryEmptyState}');
    expect(componentLibraryPanelList).toContain('className={styles.componentLibraryItem}');
    expect(componentLibraryPanelList).toContain('data-builder-component-library-rename-input');
    expect(componentLibraryPanelContent).not.toContain('data-builder-component-library="true" style=');
    expect(sandboxEditorWorkspaceTypes).toContain('nodesById: Map<string, BuilderCanvasNode>;');
    expect(sandboxEditorWorkspace).toContain('nodesById={nodesById}');
    expect(sandboxEditorWorkspace).toContain("import SandboxPublishedSiteChrome from '@/components/builder/canvas/SandboxPublishedSiteChrome';");
    expect(sandboxEditorWorkspace).toContain('<SandboxPublishedSiteChrome');
    expect(sandboxPublishedSiteChrome).toContain("import SandboxPublicChromePreview, {");
    expect(sandboxPublishedSiteChrome).toContain('<SandboxPublicChromePreview');
    expect(sandboxPublicChromePreview).toContain("import QuickContactWidget from '@/components/QuickContactWidget';");
    expect(sandboxPublicChromePreview).not.toContain("import SectionDotNav from '@/components/SectionDotNav';");
    expect(sandboxPublicChromePreview).toContain("import ScrollTopButton from '@/components/ScrollTopButton';");
    expect(sandboxPublicChromePreview).toContain("import YearEndEventPopup from '@/components/YearEndEventPopup';");
    expect(sandboxPublicChromePreview).not.toContain('currentSlug={currentSlug}');
    expect(sandboxPublicChromePreview).not.toContain('scrollRootSelector={\'[data-builder-canvas-scroll-root="true"]\'}');
    expect(sandboxPublicChromePreview).not.toContain('updateHash={false}');
    expect(sandboxPublicChromePreview).toContain('<QuickContactWidget locale={locale} previewCollapsed />');
    expect(sandboxPublicChromePreview).toContain('<ScrollTopButton locale={locale} />');
    expect(sandboxPublicChromePreview).toContain('className={styles.publicChromeEventButton}');
    expect(sandboxPublicChromePreview).toContain('previewOpen');
    expect(sandboxPublicChromePreview).toContain('onPreviewClose={() => setEventPreviewOpen(false)}');
    expect(sandboxEditorWorkspace).not.toContain('2026 EVENT');
    expect(sandboxPublicChromePreview).not.toContain('2026 EVENT');
    expect(sandboxEditorWorkspace).not.toContain('publicChromePanels');
    expect(sandboxEditorWorkspace).not.toContain('onSetPublicChromePanels');
    expect(sandboxEditorWorkspace).not.toContain('aria-pressed={publicChromePanels.chat}');
    expect(sandboxEditorWorkspace).not.toContain('className={styles.publicChromeAction}');
    expect(quickContactWidget).not.toContain("import YearEndEventPopup from '@/components/YearEndEventPopup';");
    expect(quickContactWidget).not.toContain('2026 EVENT');
    expect(quickContactWidget).not.toContain('quick-contact-event-button');
    expect(sandboxPage).not.toContain('publicChromePanels');
    expect(sandboxPage).not.toContain('setPublicChromePanels({ chat: true, event: true });');
    expect(sandboxPage).not.toContain('setPublicChromePanels({ chat: false, event: true });');
    expect(sandboxPublishedSiteChrome).toContain('currentSlug={currentSlug}');
    expect(sandboxEditorRail).toContain('nodesById: Map<string, BuilderCanvasNode>;');
    expect(sandboxEditorRail).toContain('return HOME_SECTION_TEMPLATE_TARGETS.filter((target) => nodesById.has(target.nodeId));');
    expect(sandboxEditorRail).toContain('current = nodesById.get(current.parentId);');
    expect(sandboxEditorRail).toContain('return nodesById.get(target.nodeId) ?? null;');
    expect(sandboxEditorRail).toContain('data-builder-rail-item="layers"');
    expect(sandboxEditorRail).toContain('data-builder-rail-item="history"');
    expect(sandboxEditorRail).toContain('const recommendedDesignerPresetCopy = copy.design.presets[recommendedDesignerPreset.key];');
    expect(sandboxEditorRail).toContain('const currentFitLeaderPresetCopy = copy.design.presets[currentFitLeaderPreset.key];');
    expect(sandboxEditorRail).toContain('{recommendedDesignerPresetCopy.recommendation}');
    expect(sandboxEditorRail).toContain('{copy.design.qualitySignal(signal)}');
    expect(sandboxEditorRail).toContain('const presetCopy = copy.design.presets[preset.key];');
    expect(sandboxEditorRail).toContain('copy.design.priorityReason(item.category)');
    expect(sandboxEditorRail).not.toContain('<strong>{preset.label}</strong>');
    expect(sandboxEditorRail).not.toContain('{designerTargetSummary.recommendation}');
    expect(sandboxEditorRail).not.toContain("'적용 전 미리보기: 변경 대상 없음'");
    expect(sandboxEditorRail).not.toContain("import { getCanvasNodesById } from '@/lib/builder/canvas/indexes';");
    expect(sandboxEditorRail).not.toContain('getCanvasNodesById(document.nodes)');
    expect(sandboxEditorRail).not.toContain('document.nodes.find((node) => node.id === target.nodeId)');
    expect(navigationEditor).toContain("import styles from './SandboxPage.module.css';");
    expect(navigationEditor).toContain('data-builder-navigation-editor="true"');
    expect(navigationEditor).toContain('className={styles.navigationItemRow}');
    expect(navigationEditor).toContain('className={styles.navigationIconButton}');
    expect(navigationEditor).toContain('<NavigationIcon name="up" />');
    expect(navigationEditor).toContain('<NavigationIcon name="down" />');
    expect(navigationEditor).toContain('<NavigationIcon name="edit" />');
    expect(navigationEditor).toContain('<NavigationIcon name="trash" />');
    expect(navigationEditor).toContain('const navigationItemCount = countNavigationItems(items);');
    expect(navigationEditor).toContain('const navigationStatusLabel = loading ? copy.loading : copy.itemCountLabel(navigationItemCount);');
    expect(navigationEditor).toContain('data-builder-navigation-loading={loading ? \'true\' : \'false\'}');
    expect(navigationEditor).toContain('data-builder-navigation-count={navigationItemCount}');
    expect(navigationEditor).not.toContain('style={itemStyle}');
    expect(navigationEditor).not.toContain('style={smallBtnStyle}');
    expect(navigationEditor).not.toContain('style={dangerBtnStyle}');
    expect(navigationEditor).not.toContain('>↑<');
    expect(navigationEditor).not.toContain('>↓<');
    expect(navigationEditor).not.toContain('>✎<');
    expect(navigationEditor).not.toContain('>✕<');
    expect(sandboxPageCss).toContain('.navigationEditor {');
    expect(sandboxPageCss).toContain('.navigationItemRow {');
    expect(sandboxPageCss).toContain('.navigationIconButton {');
    expect(sandboxPageCss).toContain('width: 26px;');
    expect(sandboxPageCss).toContain('font-size: 0;');
    expect(undoStackTimeline).toContain("import EditorChromeIcon from './EditorChromeIcon';");
    expect(undoStackTimeline).toContain("getUndoStackTimelineCopy(documentLocale ?? currentBuilderLocale())");
    expect(undoStackTimeline).toContain('className={`${styles.panelSection} ${styles.undoTimeline}`}');
    expect(undoStackTimeline).toContain('className={styles.undoTimelineActionButton}');
    expect(undoStackTimeline).toContain('<EditorChromeIcon name="undo" />');
    expect(undoStackTimeline).toContain('<EditorChromeIcon name="redo" />');
    expect(undoStackTimeline).not.toContain('Undo stack');
    expect(undoStackTimeline).not.toContain('Initial canvas snapshot');
    expect(undoStackTimeline).not.toContain('style={{');
    expect(editorChromeIcon).toContain("| 'undo'");
    expect(editorChromeIcon).toContain("| 'redo'");
    expect(editorChromeIcon).toContain("| 'close'");
    expect(sandboxPageCss).toContain('.undoTimeline {');
    expect(sandboxPageCss).toContain('.undoTimelineActionButton {');
    expect(sandboxPageCss).toContain('.undoTimelineSnapshot {');
    expect(versionHistoryPanel).toContain("import styles from './VersionHistoryPanel.module.css';");
    expect(versionHistoryPanel).toContain('data-builder-version-history-dialog="true"');
    expect(versionHistoryPanel).toContain('data-builder-version-revision-source={sourceKey}');
    expect(versionHistoryPanel).toContain('className={styles.panel}');
    expect(versionHistoryPanel).toContain('className={styles.timelineItem}');
    expect(versionHistoryPanel).toContain('className={styles.diffStats}');
    expect(versionHistoryPanel).toContain('<EditorChromeIcon name="close" />');
    expect(versionHistoryPanel).not.toContain('VersionHistoryPanel.styles');
    expect(versionHistoryPanel).not.toContain('style={');
    expect(versionHistoryPanelCss).toContain('.backdrop {');
    expect(versionHistoryPanelCss).toContain('.panel {');
    expect(versionHistoryPanelCss).toContain('.timelineItem {');
    expect(versionHistoryPanelCss).toContain('.diffItem[data-kind=');
    expect(saveSectionModal).toContain("import EditorChromeIcon from '@/components/builder/canvas/EditorChromeIcon';");
    expect(saveSectionModal).toContain("import styles from './SaveSectionModal.module.css';");
    expect(saveSectionModal).toContain('data-builder-save-section-dialog="true"');
    expect(saveSectionModal).toContain('className={styles.panel}');
    expect(saveSectionModal).toContain('className={styles.previewFrame}');
    expect(saveSectionModal).toContain('<EditorChromeIcon name="close" />');
    expect(saveSectionModal).not.toContain('style={{');
    expect(saveSectionModal).not.toContain('React.CSSProperties');
    expect(saveSectionModalCss).toContain('.backdrop {');
    expect(saveSectionModalCss).toContain('.panel {');
    expect(saveSectionModalCss).toContain('.previewFrame {');
    expect(saveSectionModalCss).toContain('.primaryButton:disabled');
    expect(builtInSectionsPanel).toContain("import styles from './SectionLibraryPanel.module.css';");
    expect(builtInSectionsPanel).toContain('data-builder-built-in-section-library="true"');
    expect(builtInSectionsPanel).toContain('className={styles.marketHeader}');
    expect(builtInSectionsPanel).toContain('className={styles.filterButton}');
    expect(builtInSectionsPanel).toContain('className={styles.templateGrid}');
    expect(builtInSectionsPanel).not.toContain('style={');
    expect(builtInSectionsPanel).not.toContain('CSSProperties');
    expect(sectionTemplateCard).toContain("import styles from './SectionLibraryPanel.module.css';");
    expect(sectionTemplateCard).toContain('className={styles.templateCard}');
    expect(sectionTemplateCard).toContain('className={styles.templateThumbnail}');
    expect(sectionTemplateCard).not.toContain('style={');
    expect(sectionTemplateCard).not.toContain('CSSProperties');
    expect(sectionLibraryPanelCss).toContain('.marketHeader,');
    expect(sectionLibraryPanelCss).toContain('.templateCard,');
    expect(sectionLibraryPanelCss).toContain('.savedCard {');
    expect(sectionLibraryPanelCss).toContain('.iconButton[data-tone=');
    expect(sandboxInspectorPanel).toContain('nodesById.get(selectedNodeId)');
    expect(sandboxInspectorPanel).toContain('resolveOfficeQuickEdit(nodesById');
    expect(sandboxInspectorPanel).toContain('resolveBuilderCanvasRepeaterQuickEdit(');
    expect(sandboxInspectorPanel).toContain('const documentNodes = useBuilderCanvasStore((state) => state.document?.nodes ?? EMPTY_INSPECTOR_NODES);');
    expect(sandboxInspectorPanel).toContain('const builderLocale = useBuilderCanvasStore((state) => state.document?.locale ?? \'ko\');');
    expect(sandboxInspectorPanel).toContain('const selectedNodeId = useBuilderCanvasStore((state) => state.selectedNodeId);');
    expect(sandboxInspectorPanel).toContain('const selectedNodeIds = useBuilderCanvasStore((state) => state.selectedNodeIds);');
    expect(sandboxInspectorPanel).toContain('const selectedSurfaceKey = useBuilderCanvasStore((state) => state.selectedSurfaceKey);');
    expect(sandboxInspectorPanel).toContain('const nodesById = useBuilderCanvasStore((state) => state.nodesById);');
    expect(sandboxInspectorPanel).toContain('const childrenMap = useBuilderCanvasStore((state) => state.childrenMap);');
    expect(sandboxInspectorPanel).not.toContain('document?.nodes.find((node) => node.id === selectedNodeId)');
    expect(sandboxInspectorPanel).not.toContain('new Map(nodes.map((node) => [node.id, node]))');
    expect(sandboxInspectorPanel).not.toContain('} = useBuilderCanvasStore();');
    expect(sandboxInspectorPanel).toContain('className={`${styles.panelSection} ${styles.panelSectionActivePane}`}');
    expect(sandboxInspectorPanel).not.toContain("style={{ animation: 'fadeIn 150ms ease' }}");
    expect(sandboxInspectorLayoutTab).toContain('className={styles.inspectorViewportPanel}');
    expect(sandboxInspectorLayoutTab).toContain('className={styles.inspectorViewportSelector}');
    expect(sandboxInspectorLayoutTab).toContain('className={styles.inspectorViewportButton}');
    expect(sandboxInspectorLayoutTab).toContain('className={styles.inspectorViewportOverrideBanner}');
    expect(sandboxInspectorLayoutTab).toContain('className={styles.inspectorFlowNotice}');
    expect(sandboxInspectorLayoutTab).not.toContain("gridTemplateColumns: 'repeat(3, minmax(0, 1fr))'");
    expect(sandboxInspectorLayoutTab).not.toContain("padding: '7px 6px'");
    expect(sandboxInspectorLayoutTab).not.toContain("background: active ? '#eaf3ff' : '#fff'");
    expect(sandboxInspectorLayoutTab).toContain('className={styles.inspectorAnchorHint}');
    expect(sandboxInspectorLayoutTab).toContain('className={styles.inspectorAnchorCode}');
    expect(sandboxInspectorLayoutTab).not.toContain("fontSize: '0.7rem', color: '#94a3b8'");
    expect(sandboxInspectorLayoutTab).not.toContain("code style={{ color: '#0f172a' }}");
    expect(sandboxInspectorPanelWidgets).toContain('className={styles.inspectorDeviceVisibility}');
    expect(sandboxInspectorPanelWidgets).toContain('className={styles.inspectorDeviceToggle}');
    expect(sandboxInspectorPanelWidgets).toContain("data-visible={visible ? 'true' : 'false'}");
    expect(sandboxInspectorPanelWidgets).toContain('className={styles.compositeSurfaceEditor}');
    expect(sandboxInspectorPanelWidgets).toContain('data-builder-composite-surface-editor="true"');
    expect(sandboxInspectorPanelWidgets).toContain('className={styles.compositeSurfaceEditorHeader}');
    expect(sandboxInspectorPanelWidgets).toContain('className={styles.compositeSurfaceEditorTitle}');
    expect(sandboxInspectorPanelWidgets).toContain('className={styles.compositeSurfaceEditorClose}');
    expect(sandboxInspectorPanelWidgets).toContain('className={styles.compositeSurfaceEditorTextarea}');
    expect(sandboxInspectorPanelWidgets).not.toContain("background: 'linear-gradient(180deg, #f8fafc, #f1f5f9)'");
    expect(sandboxInspectorPanelWidgets).not.toContain('style={{\n        padding: 12,');
    expect(sandboxInspectorPanelWidgets).not.toContain("style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}");
    expect(sandboxInspectorPanelWidgets).not.toContain("padding: '6px 10px'");
    expect(sandboxPageCss).toContain('.inspectorViewportPanel {');
    expect(sandboxPageCss).toContain('.panelSectionActivePane {');
    expect(sandboxPageCss).toContain('.inspectorViewportSelector {');
    expect(sandboxPageCss).toContain('grid-template-columns: 1fr;');
    expect(sandboxPageCss).toContain('.inspectorViewportButton {');
    expect(sandboxPageCss).toContain('white-space: nowrap;');
    expect(sandboxPageCss).toContain('.inspectorDeviceVisibility {');
    expect(sandboxPageCss).toContain(".inspectorDeviceToggle[data-visible='false']::after {");
    expect(sandboxPageCss).toContain('.inspectorAnchorHint {');
    expect(sandboxPageCss).toContain('.inspectorAnchorCode {');
    expect(sandboxPageCss).toContain('.compositeSurfaceEditor {');
    expect(sandboxPageCss).toContain('.compositeSurfaceEditorTextarea:focus {');
    expect(sandboxPageCss).toContain('.pageDropdownCurrent {');
    expect(sandboxPageCss).toContain('text-overflow: ellipsis;');
    expect(sandboxPageCss).toContain('.catalogQuickButton {');
    expect(sandboxPageCss).toContain('.catalogCategoryButton {');
    expect(sandboxPageCss).toContain('.textWidgetPresetButton {');
    expect(sandboxPageCss).toContain('.mediaWidgetPresetButton {');
    expect(sandboxPageCss).toContain('height: 112px;');
    expect(sandboxPageCss).toContain('-webkit-line-clamp: 2;');
    expect(sandboxPageCss).toContain('.componentLibraryPanel {');
    expect(sandboxPageCss).toContain('.componentLibraryHeader {');
    expect(sandboxPageCss).toContain('.componentLibrarySaveButton:disabled {');
    expect(sandboxPageCss).toContain('.componentLibraryEmptyState {');
    expect(sandboxPageCss).toContain('.componentLibraryItem {');
    expect(sandboxPageCss).toContain('.designerAudit {');
    expect(sandboxPageCss).toContain('max-height: 560px;');
    expect(sandboxPageCss).toContain('overscroll-behavior: contain;');
    expect(sandboxPageCss).toContain('.designerAuditSystemFit {');
    expect(sandboxPageCss).toContain('max-height: 82px;');
    expect(sandboxPageCss).toContain('.designerAuditPriority {');
    expect(sandboxPageCss).toContain('max-height: 116px;');
    expect(sandboxPageCss).toContain('.designerPresetCard {');
    expect(sandboxPageCss).toContain('grid-template-columns: 50px minmax(0, 1fr);');
    expect(sandboxPageCss).toContain('border-radius: 8px;');
    expect(sandboxPageCss).toContain('.designerPresetDescription {');
    expect(sandboxPageCss).toContain('-webkit-line-clamp: 2;');
    expect(siteSettingsPresetsTab).toContain("import { getSandboxEditorRailCopy } from './sandbox-editor-rail-copy';");
    expect(siteSettingsPresetsTab).toContain('const designerPresetCopy = getSandboxEditorRailCopy(locale).design.presets;');
    expect(siteSettingsPresetsTab).toContain('const localizedPreset = designerPresetCopy[preset.key];');
    expect(siteSettingsPresetsTab).toContain('onApplyComponentDesignPreset(preset.key, localizedPreset.label)');
    expect(siteSettingsPresetsTab).not.toContain('onApplyComponentDesignPreset(preset.key, preset.label)');
    expect(pageSwitcher).toContain('style={treeContainerStyle}');
    expect(pageSwitcher).toContain('style={treeLoadingStyle}');
    expect(pageSwitcher).toContain("import EditorChromeIcon from './EditorChromeIcon';");
    expect(pageSwitcher).toContain('style={pageDragHandleStyle(draggingPageId === page.pageId)}');
    expect(pageSwitcher).toContain('<EditorChromeIcon name="dragHandle" style={pageRowControlIconStyle} />');
    expect(pageSwitcher).toContain('style={pageMoreButtonStyle(showMoreButton, menuOpen)}');
    expect(pageSwitcher).toContain('<EditorChromeIcon name="moreHorizontal" style={pageRowControlIconStyle} />');
    expect(pageSwitcher).toContain('style={memberAccessDialogOverlayStyle}');
    expect(pageSwitcher).toContain('style={memberAccessDialogPanelStyle}');
    expect(pageSwitcher).toContain('style={memberAccessControlStyle(memberAccessModeDraft === \'public\')}');
    expect(pageSwitcher).toContain('style={memberAccessPageChoiceStyle(isSelected, memberAccessModeDraft === \'public\')}');
    expect(pageSwitcher).toContain('style={slugPromptOverlayStyle}');
    expect(pageSwitcher).toContain('style={slugPromptDialogStyle}');
    expect(pageSwitcher).toContain('style={slugPromptInputStyle}');
    expect(pageSwitcher).toContain('style={slugPromptNavigationLabelStyle}');
    expect(pageSwitcher).toContain('style={slugPromptCreateButtonStyle(creating)}');
    expect(pageSwitcher).not.toContain('↕');
    expect(pageSwitcher).not.toContain('⋯');
    expect(pageSwitcherStyles).toContain('export function pageDragHandleStyle(dragging: boolean): CSSProperties');
    expect(pageSwitcherStyles).toContain('export function pageMoreButtonStyle(visible: boolean, active: boolean): CSSProperties');
    expect(pageSwitcherStyles).toContain('export const pageRowControlIconStyle: CSSProperties = {');
    expect(pageSwitcherStyles).toContain('export const memberAccessDialogOverlayStyle: CSSProperties = {');
    expect(pageSwitcherStyles).toContain('export function memberAccessControlStyle(disabled: boolean): CSSProperties');
    expect(pageSwitcherStyles).toContain('export function memberAccessPageChoiceStyle(selected: boolean, disabled: boolean): CSSProperties');
    expect(pageSwitcherStyles).toContain('export const slugPromptOverlayStyle: CSSProperties = {');
    expect(pageSwitcherStyles).toContain('export const slugPromptDialogStyle: CSSProperties = {');
    expect(pageSwitcherStyles).toContain('export function slugPromptCreateButtonStyle(disabled: boolean): CSSProperties');
    expect(pageSwitcherStyles).not.toContain('export const actionDotsStyle');
    expect(templateGalleryModal).toContain('style={getTemplateCardFrameStyle(template, hovered)}');
    expect(templateGalleryModal).toContain('style={getTemplatePreviewButtonStyle(template)}');
    expect(templateGalleryModal).toContain("style={getTemplateActionButtonStyle(template, 'preview')}");
    expect(templateGalleryModal).toContain("style={getTemplateActionButtonStyle(template, 'use')}");
    expect(templateGalleryModal).toContain('style={getCategoryButtonStyle(active)}');
    expect(templateGalleryModal).toContain("style={getBlankCardStyle(hoveredId === 'blank')}");
    expect(templateGalleryModal).toContain('style={blankCardIconStyle}');
    expect(templateGalleryModal).toContain('style={blankCardDescriptionStyle}');
    expect(templateGalleryModal).toContain('style={getTemplateCategoryChipStyle(template)}');
    expect(templateGalleryModal).toContain('style={featuredTemplateChipStyle}');
    expect(templateGalleryModal).toContain('style={templateMetaChipStyle}');
    expect(templateGalleryModal).toContain('const templateMetaLabel = formatTemplateMeta(template, locale);');
    expect(templateGalleryModal).toContain('className="template-gallery-search-input"');
    expect(templateGalleryModal).toContain('className="template-gallery-filter-select"');
    expect(templateGalleryModal).toContain('className="template-gallery-reset-button"');
    expect(templateGalleryModal).toContain('className="template-gallery-content"');
    expect(templateGalleryModal).toContain('className="template-gallery-preview-toolbar"');
    expect(templateGalleryModal).toContain('className="template-gallery-preview-body"');
    expect(templateGalleryModal).toContain('className="template-gallery-preview-canvas"');
    expect(templateGalleryModal).toContain('className="template-gallery-preview-frame"');
    expect(templateGalleryModal).toContain('className="template-gallery-preview-detail"');
    expect(templateGalleryModal).toContain('.template-gallery-search-input:focus');
    expect(templateGalleryModal).toContain('.template-gallery-filter-select:focus');
    expect(templateGalleryModal).toContain('.template-gallery-reset-button:focus-visible');
    expect(templateGalleryModal).toContain('@media (max-width: 900px)');
    expect(templateGalleryModal).toContain('.template-gallery-preview-body');
    expect(templateGalleryModal).toContain('grid-template-columns: minmax(0, 1fr) !important;');
    expect(templateGalleryModal).toContain('border-left: 0 !important;');
    expect(templateGalleryModal).toContain('border-top: 1px solid #e2e8f0 !important;');
    expect(templateGalleryModal).toContain('justify-content: flex-start !important;');
    expect(templateGalleryModal).toContain('overflow-x: auto;');
    expect(templateGalleryModal).toContain('.template-gallery-content');
    expect(templateGalleryModal).toContain('width: 100% !important;');
    expect(templateGalleryModal).toContain('style={previewToolbarStyle}');
    expect(templateGalleryModal).toContain('style={getPreviewViewportButtonStyle(template, viewport === item)}');
    expect(templateGalleryModal).toContain('style={previewPanelBodyStyle}');
    expect(templateGalleryModal).toContain('style={getPreviewViewportFrameStyle(previewSize)}');
    expect(templateGalleryModal).toContain('style={previewDetailAsideStyle}');
    expect(templateGalleryModal).toContain('style={getPreviewQualityChipStyle(template)}');
    expect(templateGalleryModal).toContain('style={previewDefinitionListStyle}');
    expect(templateGalleryModal).toContain('style={previewTagChipStyle}');
    expect(templateGalleryModal).not.toContain("hoveredId === 'blank' ? '#123b63'");
    expect(templateGalleryModal).not.toContain("fontSize: '2rem'");
    expect(templateGalleryModal).not.toContain('style={{ ...chipStyle');
    expect(templateGalleryModal).not.toContain('palette.accentSoft');
    expect(templateGalleryModal).not.toContain("background: '#ecfeff'");
    expect(templateGalleryModal).not.toContain("gridTemplateColumns: 'minmax(0, 1fr) 300px'");
    expect(templateGalleryModal).not.toContain("minHeight: 34,\n                border: `1px solid ${viewport === item");
    expect(templateGalleryModalStyles).toContain('export function getTemplateCardFrameStyle(template: PageTemplate, hovered: boolean): CSSProperties');
    expect(templateGalleryModalStyles).toContain('export function getTemplatePreviewButtonStyle(template: PageTemplate): CSSProperties');
    expect(templateGalleryModalStyles).toContain("export function getTemplateActionButtonStyle(template: PageTemplate, variant: 'preview' | 'use'): CSSProperties");
    expect(templateGalleryModalStyles).toContain('export function getBlankCardStyle(hovered: boolean): CSSProperties');
    expect(templateGalleryModalStyles).toContain('export const blankCardIconStyle: CSSProperties = {');
    expect(templateGalleryModalStyles).toContain('export function getTemplateCategoryChipStyle(template: PageTemplate): CSSProperties');
    expect(templateGalleryModalStyles).toContain('export const featuredTemplateChipStyle: CSSProperties = {');
    expect(templateGalleryModalStyles).toContain('export const templateMetaChipStyle: CSSProperties = {');
    expect(templateGalleryModalStyles).toContain('export const toolbarStyle: CSSProperties = {');
    expect(templateGalleryModalStyles).toContain("background: 'linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)'");
    expect(templateGalleryModalStyles).toContain('boxShadow: \'0 10px 28px rgba(15, 23, 42, 0.06)\'');
    expect(templateGalleryModalStyles).toContain('height: 42,');
    expect(templateGalleryModalStyles).toContain('borderRadius: 999,');
    expect(templateGalleryModalStyles).toContain('minWidth: 142,');
    expect(templateGalleryModalStyles).toContain("flexWrap: 'wrap',");
    expect(templateGalleryModalStyles).toContain('export const previewToolbarStyle: CSSProperties = {');
    expect(templateGalleryModalStyles).toContain('export function getPreviewViewportButtonStyle(template: PageTemplate, active: boolean): CSSProperties');
    expect(templateGalleryModalStyles).toContain('export function getPreviewViewportFrameStyle(size: TemplatePreviewViewportSize): CSSProperties');
    expect(templateGalleryModalStyles).toContain('export const previewDetailAsideStyle: CSSProperties = {');
    expect(templateGalleryModalStyles).toContain('export const previewTagChipStyle: CSSProperties = {');
    expect(pageSwitcherStyles).toContain('background: active\n      ? \'linear-gradient(180deg, #f7fbff 0%, #eef6ff 100%)\'');
    expect(pageSwitcherStyles).toContain('export const treeContainerStyle: CSSProperties = {');
    expect(pageSwitcherStyles).toContain('export const treeLoadingStyle: CSSProperties = {');
    expect(pageSwitcherStyles).toContain('borderRadius: 9,');
    expect(sandboxLayersPanel).toContain('nodesById,');
    expect(sandboxLayersPanel).toContain('const nodes = useBuilderCanvasStore((state) => state.document?.nodes ?? EMPTY_LAYER_NODES);');
    expect(sandboxLayersPanel).toContain('const nodesById = useBuilderCanvasStore((state) => state.nodesById);');
    expect(sandboxLayersPanel).toContain('const selectedNodeId = useBuilderCanvasStore((state) => state.selectedNodeId);');
    expect(sandboxLayersPanel).toContain('const selectedNodeIdSet = useBuilderCanvasStore((state) => state.selectedNodeIdSet);');
    expect(sandboxLayersPanel).toContain('const activeGroupId = useBuilderCanvasStore((state) => state.activeGroupId);');
    expect(sandboxLayersPanel).toContain('isSelected={selectedNodeIdSet.has(node.id)}');
    expect(sandboxLayersPanel).not.toContain("import { getCanvasNodesById } from '@/lib/builder/canvas/indexes';");
    expect(sandboxLayersPanel).not.toContain('const nodesById = useMemo(() => getCanvasNodesById(nodes), [nodes]);');
    expect(sandboxLayersPanel).not.toContain('new Set(selectedNodeIds)');
    expect(sandboxLayersPanel).not.toContain('isSelected={selectedNodeIds.includes(node.id)}');
    expect(sandboxLayersPanel).not.toContain('} = useBuilderCanvasStore();');
    expect(sandboxLayersPanel).toContain('copy={copy}');
    expect(sandboxLayersPanel).toContain('export function resolveLayerTechnicalLabel(value: unknown, copy: SandboxLayersPanelCopy): string | null {');
    expect(sandboxLayersPanel).toContain("const semanticLabel = resolveLayerTechnicalLabel(content.label, copy)");
    expect(sandboxLayersPanel).toContain('?? resolveLayerTechnicalLabel(node.id, copy);');
    expect(sandboxLayersPanel).toContain("if (tokens[0] === 'home') tokens.shift();");
    expect(sandboxLayersPanel).toContain('copy.row.semanticLabels.sections[compositeKey]');
    expect(sandboxLayersPanel).toContain('copy.row.semanticLabels.roles[token]');
    expect(layersTreeRow).toContain("import type { SandboxLayersPanelCopy } from './sandbox-layers-panel-copy';");
    expect(layersTreeRow).toContain('copy: SandboxLayersPanelCopy;');
    expect(layersTreeRow).toContain('const kindLabel = copy.kindLabels[node.kind] ?? node.kind;');
    expect(layersTreeRow).toContain('const visibilityLabel = node.visible ? copy.row.hideNodeLabel : copy.row.showNodeLabel;');
    expect(layersTreeRow).toContain('const lockLabel = node.locked ? copy.row.unlockNodeLabel : copy.row.lockNodeLabel;');
    expect(layersTreeRow).toContain('<LayerKindMark kind={node.kind} />');
    expect(layersTreeRow).toContain('<VisibilityIcon visible={node.visible} />');
    expect(layersTreeRow).toContain('<LockIcon locked={Boolean(node.locked)} />');
    expect(layersTreeRow).toContain('<MoreIcon />');
    expect(layersTreeRow).toContain('{copy.row.zIndexLabel(node.zIndex)}');
    expect(layersTreeRow).toContain('${copy.row.primaryLabel}');
    expect(layersTreeRow).toContain('${copy.row.childCountLabel(childCount)}');
    expect(layersTreeRow).not.toContain("{node.visible ? 'eye' : 'off'}");
    expect(layersTreeRow).not.toContain("{node.locked ? 'lock' : 'open'}");
    expect(layersTreeRow).not.toContain("isExpanded ? 'v' : '>'");
    expect(layersTreeRow).not.toContain('More layer actions pending');
    expect(layersTreeRow).not.toContain('getLayerNodeKindGlyph');
    expect(sandboxPageCss).toContain('.layerKindIcon svg,');
    expect(sandboxPageCss).toContain('.layerQuickAction svg,');
    expect(sandboxPageCss).toContain('.layerQuickAction {');
    expect(sandboxPageCss).toContain('width: 26px;');
    expect(sandboxPageCss).toContain('font-size: 0;');
    expect(canvasContainer).toContain('state.nodesById.get(state.selectedNodeId)');
    expect(canvasContainer).toContain('state.nodesById.get(nodeId)');
    expect(canvasContainer).toContain('const selectedNodeId = useBuilderCanvasStore((state) => state.selectedNodeId);');
    expect(canvasContainer).toContain('const selectedNodeIds = useBuilderCanvasStore((state) => state.selectedNodeIds);');
    expect(canvasContainer).toContain('const selectedNodeIdSet = useBuilderCanvasStore((state) => state.selectedNodeIdSet);');
    expect(canvasContainer).toContain('const activeGroupId = useBuilderCanvasStore((state) => state.activeGroupId);');
    expect(canvasContainer).toContain('const canUndo = useBuilderCanvasStore((state) => state.canUndo);');
    expect(canvasContainer).toContain('const canRedo = useBuilderCanvasStore((state) => state.canRedo);');
    expect(canvasContainer).toContain('const childrenMap = storeDocument ? storeChildrenMap : fallbackChildrenMap;');
    expect(canvasContainer).toContain('childrenMap={childrenMap}');
    expect(canvasContainer).toContain('const currentViewport = useBuilderCanvasStore((state) => state.viewport);');
    expect(canvasContainer).toContain('function getVisibleCanvasNodeBuckets(nodes: BuilderCanvasNode[]): VisibleCanvasNodeBuckets {');
    expect(canvasContainer).toContain('const { rootVisibleNodes, visibleContainerNodes, visibleNodes } = useMemo(');
    expect(canvasContainer).toContain("nodesById.get('home-services-root')");
    expect(canvasContainer).toContain("nodesById.get('home-faq-root')");
    expect(canvasContainer).not.toContain('state.document?.nodes.find((node) => node.id === state.selectedNodeId)');
    expect(canvasContainer).not.toContain('state.document?.nodes.find((candidate) => candidate.id === nodeId)');
    expect(canvasContainer).not.toContain("nodes.find((node) => node.id === 'home-services-root')");
    expect(canvasContainer).not.toContain("nodes.find((node) => node.id === 'home-faq-root')");
    expect(canvasContainer).not.toContain('() => nodes.filter((node) => node.visible)');
    expect(canvasContainer).not.toContain('() => visibleNodes.filter((node) => isContainerLikeKind(node.kind))');
    expect(canvasContainer).not.toContain('() => visibleNodes.filter((node) => !node.parentId)');
    expect(canvasContainer).not.toContain('} = useBuilderCanvasStore();');
    expect(canvasContainer).toContain('nodesById={nodesById}');
    expect(canvasContainer).toContain('<CanvasStageNodes');
    expect(canvasContainer).toContain("import { getCanvasFeedbackSnapActiveRect, useCanvasFeedbackGeometry } from './useCanvasFeedbackGeometry';");
    expect(canvasContainer).toContain('const snapActiveRect = getCanvasFeedbackSnapActiveRect(');
    expect(canvasContainer).toContain('snapActiveRect={snapActiveRect}');
    expect(canvasContainer).toContain('const captureInteractionGeometry = useCallback((): InteractionGeometrySnapshot => ({');
    expect(canvasContainer).not.toContain('nodes: visibleNodes,');
    const interactionGeometrySnapshotType = /export type InteractionGeometrySnapshot = \{[\s\S]*?\n\};/.exec(canvasInteraction)?.[0] ?? '';
    expect(interactionGeometrySnapshotType).not.toContain('nodes: BuilderCanvasNode[];');
    const canvasInteractionHookCall = /useCanvasInteractions\(\{[\s\S]*?\n\s+\}\);/.exec(canvasContainer)?.[0] ?? '';
    expect(canvasInteractionHookCall).not.toContain('\n    nodes,');
    expect(canvasInteractionHookCall).not.toContain('\n    visibleNodes,');
    expect(canvasInteraction).toContain('nodeIdSet: ReadonlySet<string>;');
    expect(canvasInteraction).toContain('movingNodeIds: ReadonlySet<string>;');
    expect(canvasInteraction).toContain('viewportOriginX: number;');
    expect(canvasInteraction).toContain('viewportOriginY: number;');
    expect(canvasInteraction).toContain('export type ContainerHitRect = { id: string; rect: Rect };');
    expect(canvasInteraction).toContain('export function findContainerHitCandidateForPoint(');
    expect(useCanvasInteractions).toContain('findContainerHitCandidateForPoint,');
    expect(useCanvasInteractions).toContain('const hoveredContainerHitRef = useRef<ContainerHitRect | null>(null);');
    expect(useCanvasInteractions).toContain('hoveredContainerHitRef.current,');
    expect(useCanvasInteractions).toContain('if (hoveredContainerHitRef.current === nextHit) return;');
    expect(useCanvasInteractions).toContain('export function resolvePendingMoveAbsoluteRect(');
    expect(useCanvasInteractions).toContain('export function resolvePendingMoveHoverContainerId({');
    expect(canvasInteraction).toContain('export function writeResizeDraftRect(');
    expect(canvasInteraction).toContain('export function writeClampedRect(');
    expect(canvasInteraction).toContain('export function writeClampedAspectRect(');
    expect(useCanvasInteractions).toContain('selectedNodeIdSet: ReadonlySet<string>;');
    expect(useCanvasInteractions).toContain('!selectedNodeIdSet.has(targetNodeId)');
    expect(useCanvasInteractions).toContain('selectedNodeIdSet,');
    expect(useCanvasInteractions).toContain('let unlockedNodeIds: string[] | null = null;');
    expect(useCanvasInteractions).toContain('unlockedNodeIds ??= selectedNodeIds.slice(0, index);');
    expect(useCanvasInteractions).toContain('return unlockedNodeIds ?? selectedNodeIds;');
    expect(useCanvasInteractions).not.toContain('const unlockedNodeIds: string[] = [];');
    expect(useCanvasInteractions).toContain('const nodeIdSet = nodeIds === selectedNodeIds ? selectedNodeIdSet : new Set(nodeIds);');
    expect(useCanvasInteractions).not.toContain('const nodeIdSet = new Set(nodeIds);');
    expect(useCanvasInteractions).toContain('movingNodeIds: moveInteraction.nodeIdSet,');
    expect(useCanvasInteractions).toContain('nodeIdSet,');
    expect(useCanvasInteractions).toContain('for (const nodeId of nodeIds) {');
    expect(useCanvasInteractions).toContain('if (!currentNodesById.has(nodeId)) return false;');
    expect(useCanvasInteractions).not.toContain('return nodeIds.every((nodeId) => currentNodesById.has(nodeId));');
    expect(useCanvasInteractions).not.toContain('width: stageWidth,\n              height: stageHeight,');
    expect(useCanvasInteractions).toContain('const EMPTY_ALIGNMENT_GUIDES: AlignmentGuide[] = [];');
    expect(useCanvasInteractions).toContain('const [guides, setGuides] = useState<AlignmentGuide[]>(EMPTY_ALIGNMENT_GUIDES);');
    expect(useCanvasInteractions).toContain('const guidesRef = useRef<AlignmentGuide[]>(EMPTY_ALIGNMENT_GUIDES);');
    expect(useCanvasInteractions).toContain('guidesRef: { current: AlignmentGuide[] },');
    expect(useCanvasInteractions).toContain('for (let index = 0; index < left.length; index += 1) {');
    expect(useCanvasInteractions).toContain('const guide = left[index];');
    expect(useCanvasInteractions).not.toContain('return left.every((guide, index) => {');
    expect(useCanvasInteractions).toContain('if (areAlignmentGuidesEqual(guidesRef.current, nextGuides)) return;');
    expect(useCanvasInteractions).toContain('guidesRef.current = nextGuides;');
    expect(useCanvasInteractions).toContain('setGuidesIfChanged(guidesRef, setGuides, nextGuides);');
    expect(useCanvasInteractions).toContain('setGuidesIfChanged(guidesRef, setGuides, EMPTY_ALIGNMENT_GUIDES);');
    expect(useCanvasInteractions).not.toContain('setGuides((currentGuides) => (');
    expect(useCanvasInteractions).not.toContain('setGuidesIfChanged(setGuides,');
    expect(useCanvasInteractions).not.toContain('setGuidesIfChanged(guidesRef, setGuides, []);');
    expect(useCanvasInteractions).toContain('const interactionPointerRef = useRef<InteractionPointerPosition | null>(null);');
    expect(useCanvasInteractions).toContain('const pendingPointerMoveRef = useRef<PointerMoveSnapshot>({');
    expect(useCanvasInteractions).toContain('const hasPendingPointerMoveRef = useRef(false);');
    expect(useCanvasInteractions).toContain('const pendingPointerMove = pendingPointerMoveRef.current;');
    expect(useCanvasInteractions).toContain('pendingPointerMove.pointerId = event.pointerId;');
    expect(useCanvasInteractions).toContain('hasPendingPointerMoveRef.current = true;');
    expect(useCanvasInteractions).toContain('hasPendingPointerMoveRef.current = false;');
    expect(useCanvasInteractions).not.toContain('useRef<PointerMoveSnapshot | null>(null)');
    expect(useCanvasInteractions).not.toContain('pendingPointerMoveRef.current = {');
    expect(useCanvasInteractions).not.toContain('pendingPointerMoveRef.current = null;');
    expect(useCanvasInteractions).toContain('const MOVE_ACTIVATION_THRESHOLD_SQUARED = MOVE_ACTIVATION_THRESHOLD_PX * MOVE_ACTIVATION_THRESHOLD_PX;');
    expect(useCanvasInteractions).toContain('export function isMoveActivationDistanceMet(deltaX: number, deltaY: number): boolean {');
    expect(useCanvasInteractions).toContain('&& !isMoveActivationDistanceMet(rawDeltaX, rawDeltaY)');
    expect(useCanvasInteractions).not.toContain('Math.hypot(rawDeltaX, rawDeltaY)');
    expect(useCanvasInteractions).toContain('if (areInteractionPointersEqual(interactionPointerRef.current, nextPointer)) return;');
    expect(useCanvasInteractions).toContain('interactionPointerRef.current = nextPointer;');
    expect(useCanvasInteractions).toContain('setInteractionPointer(nextPointer);');
    expect(useCanvasInteractions).toContain('export function createResizePreviewStateSnapshot(');
    expect(useCanvasInteractions).toContain('for (let index = 0; index < currentNodeIds.length; index += 1) {');
    expect(useCanvasInteractions).toContain('if (currentNodeIds[index] !== nextNodeIds[index]) return false;');
    expect(useCanvasInteractions).not.toContain('currentNodeIds.every((nodeId, index) => nodeId === nextNodeIds[index])');
    expect(useCanvasInteractions).not.toContain('setInteractionPointer((currentPointer) => (');
    expect(useCanvasInteractions).not.toContain('setResizePreviewRect((currentRect) => (');
    expect(useCanvasInteractions).toContain('const viewportOriginX = viewportRect?.left ?? 0;');
    expect(useCanvasInteractions).toContain('const viewportOriginY = viewportRect?.top ?? 0;');
    expect(useCanvasInteractions).toContain('x: pointer.clientX - activeInteraction.viewportOriginX,');
    expect(useCanvasInteractions).toContain('y: pointer.clientY - activeInteraction.viewportOriginY,');
    expect(useCanvasInteractions).toContain('viewportOriginX,');
    expect(useCanvasInteractions).toContain('viewportOriginY,');
    expect(useCanvasInteractions).not.toContain('x: viewportRect ? pointer.clientX - viewportRect.left : pointer.clientX,');
    expect(useCanvasInteractions).not.toContain('event.clientX - (viewportRef.current?.getBoundingClientRect().left ?? 0)');
    const resizePointerFrameBlock = /setInteractionPointerIfChanged\(\{\n\s+x: pointer\.clientX - activeInteraction\.viewportOriginX,[\s\S]*?setGuidesIfChanged/.exec(useCanvasInteractions)?.[0] ?? '';
    expect(resizePointerFrameBlock).not.toContain('getBoundingClientRect');
    expect(useCanvasInteractions).toContain('return rootVisibleNodes;');
    const startMoveBlock = /const startMove = useCallback\([\s\S]*?\n  const startResize = useCallback/.exec(useCanvasInteractions)?.[0] ?? '';
    expect(startMoveBlock).toContain('setInteractionPointerIfChanged(null);');
    expect(startMoveBlock).not.toContain('setInteractionPointerIfChanged({');
    expect(useCanvasInteractions).not.toContain('return rootVisibleNodes.filter((node) => node.visible);');
    expect(canvasInteraction).toContain('export function writeClampedMoveRect(');
    expect(useCanvasInteractions).toContain('const pendingMoveHoverContainer = (() => {');
    expect(useCanvasInteractions).toContain('resolvePendingMoveHoverContainerId({');
    expect(useCanvasInteractions).toContain('updateSingleNodeRectForViewport(');
    expect(useCanvasInteractions).not.toContain('new Map([[nodeId, nextRect]])');
    expect(useCanvasInteractions).toContain('const latestNodesById = storeState.nodesById;');
    expect(useCanvasInteractions).not.toContain('nodes: BuilderCanvasNode[];');
    expect(useCanvasInteractions).not.toContain('visibleNodes: BuilderCanvasNode[];');
    expect(useCanvasInteractions).not.toContain('selectedNodeIds.includes(targetNodeId)');
    expect(canvasNode).toContain('interaction.nodeIdSet.has(node.id)');
    expect(canvasNode).not.toContain('interaction.nodeIds.includes(node.id)');
    expect(useCanvasInteractions).not.toContain("import { getCanvasNodesById } from '@/lib/builder/canvas/indexes';");
    expect(useCanvasInteractions).not.toContain('getCanvasNodesById(freshNodes)');
    expect(useCanvasInteractions).not.toContain('freshNodes.find((n) => n.id === movedId)');
    expect(useCanvasInteractions).not.toContain('freshNodes.find((n) => n.id === resizedId)');
    expect(canvasStore).toContain('const exists = state.selectedNodeIdSet.has(nodeId);');
    expect(canvasStore).not.toContain('const exists = state.selectedNodeIds.includes(nodeId);');
    expect(canvasStore).toContain('updateSingleNodeRectForViewport: (nodeId, rect, viewport, mode = \'commit\') =>');
    expect(canvasStore).toContain('applyTransientSingleNodeRectDocument(state, document, nodeId, nextNode)');
    expect(singleRectFastPath).toContain('return {\n    document,\n    nodesById,\n  };');
    expect(singleRectFastPath).not.toContain('resolveSelectedNodeIdFromMap');
    expect(singleRectFastPath).not.toContain('resolveSelectedNodeIdsFromMap');
    expect(singleRectFastPath).not.toContain('resolveSelectedNodeIdSetForState');
    expect(canvasStageGeometry).toContain('export function getCanvasOverlapCandidatesAtPoint({');
    expect(canvasStageGeometry).toContain('const rankedCandidates: RankedOverlapCandidate[] = [];');
    expect(canvasStageGeometry).toContain('rankedCandidates.splice(insertIndex, 0, candidate);');
    expect(canvasStageGeometry).not.toContain('return selectableNodes\n        .filter(');
    expect(canvasStageGeometry).not.toContain('.sort((left, right) => {');
    expect(canvasStageGeometry).not.toContain('.slice(0, 8)');
    expect(canvasFeedbackGeometry).toContain('const snapOtherRects = useMemo(() => getCanvasFeedbackSnapOtherRects(interaction), [interaction]);');
    expect(canvasFeedbackGeometry).toContain('export function getCanvasFeedbackSnapOtherRects(interaction: InteractionState | null)');
    expect(canvasFeedbackGeometry).toContain('export function getCanvasFeedbackInteractionActiveRect({');
    expect(canvasFeedbackGeometry).toContain("if (interactionMode === 'resize') return resizeCurrentRect;");
    expect(canvasFeedbackGeometry).toContain('if (moveCurrentRects.length === 0) return null;');
    expect(canvasFeedbackGeometry).toContain('if (moveCurrentRects.length === 1) return moveCurrentRects[0];');
    expect(canvasFeedbackGeometry).toContain('return unionRects(moveCurrentRects);');
    expect(canvasFeedbackGeometry).not.toContain("if (interactionMode === 'move') return unionRects(moveCurrentRects);");
    expect(canvasFeedbackGeometry).toContain("if (interaction?.type !== 'move') return EMPTY_CANVAS_FEEDBACK_RECTS;");
    expect(canvasFeedbackGeometry).toContain('interactionMode: \'move\',');
    expect(canvasFeedbackGeometry).toContain('interactionNodeIds: interaction.nodeIds,');
    expect(canvasFeedbackGeometry).toContain('let currentRects: BuilderCanvasNode[\'rect\'][] | null = null;');
    expect(canvasFeedbackGeometry).toContain('currentRects ??= [];');
    expect(canvasFeedbackGeometry).toContain('return currentRects ?? EMPTY_CANVAS_FEEDBACK_RECTS;');
    expect(canvasFeedbackGeometry).not.toContain('.map((nodeId) => absoluteRectById.get(nodeId))');
    expect(canvasFeedbackGeometry).not.toContain(".filter((rect): rect is BuilderCanvasNode['rect'] => Boolean(rect))");
    expect(canvasFeedbackGeometry).toContain('export function getCanvasFeedbackSelectionBboxStage({');
    expect(canvasFeedbackGeometry).toContain('if (selectedNodes.length === 0 || interaction) return null;');
    expect(canvasFeedbackGeometry).toContain('if (selectedNodes.length === 1) {');
    expect(canvasFeedbackGeometry).toContain('return absoluteRectById.get(node.id) ?? resolveViewportRect(node, geometryViewport);');
    expect(canvasFeedbackGeometry).toContain('const multiSelectionBboxScreen = selectedNodes.length >= 2 ? selectionBboxScreen : null;');
    expect(canvasFeedbackGeometry).not.toContain('if (selectedNodes.length < 2 || interaction) return null;');
    expect(canvasFeedbackGeometry).toContain('const interactionActiveRect = useMemo(() => getCanvasFeedbackInteractionActiveRect({');
    expect(canvasFeedbackGeometry).not.toContain('selectedNodeIds: string[];');
    expect(canvasFeedbackGeometry).not.toContain('const activeIds = new Set(interactionNodeIds);');
    const canvasFeedbackHookCall = /useCanvasFeedbackGeometry\(\{[\s\S]*?\n\s+\}\);/.exec(canvasContainer)?.[0] ?? '';
    expect(canvasFeedbackHookCall).not.toContain('\n    visibleNodes,');
    expect(canvasFeedbackHookCall).not.toContain('\n    selectedNodeIds,');
    expect(canvasContextMenuLayer).toContain('export default memo(CanvasContextMenuLayer);');
    expect(canvasContextMenuLayer).toContain("import { memo, useCallback, useMemo } from 'react';");
    expect(canvasContextMenuLayer).toContain('const copy = useMemo(() => getCanvasContextMenuCopy(locale), [locale]);');
    expect(canvasContextMenuLayer).toContain('const actions = useMemo<ContextMenuAction[]>(() => {');
    expect(canvasContextMenuLayer).toContain('if (!hasContextMenu) return EMPTY_CONTEXT_MENU_ACTIONS;');
    expect(canvasContextMenuLayer).toContain('actions={actions}');
    expect(canvasContextMenuLayer).not.toContain('actions={[');
    expect(canvasContextMenuLayer).toContain('nodesById: Map<string, BuilderCanvasNode>;');
    expect(canvasContextMenuLayer).toContain('nodesById.get(contextMenu.nodeId)');
    expect(canvasContextMenuLayer).toContain('selectedNodeIdSet: ReadonlySet<string>;');
    expect(canvasContextMenuLayer).toContain('selectedNodeIdSet.has(contextMenuNode.id)');
    expect(canvasContextMenuLayer).not.toContain('nodes.find((node) => node.id === contextMenu.nodeId)');
    expect(canvasContextMenuLayer).not.toContain('selectedNodeIds.includes(contextMenuNode.id)');
    expect(contextMenu).toContain('export default memo(ContextMenu);');
    expect(canvasDropHighlight).toContain('export default memo(CanvasDropHighlight);');
    expect(canvasDropHighlight).toContain('nodesById: Map<string, BuilderCanvasNode>;');
    expect(canvasDropHighlight).toContain('nodesById.get(hoveredContainerId)');
    expect(canvasDropHighlight).not.toContain('visibleNodes.find((node) => node.id === hoveredContainerId)');
    expect(alignmentGuides).toContain('export default memo(AlignmentGuides);');
    expect(canvasFeedbackOverlay).toContain('export default memo(CanvasFeedbackOverlay);');
    expect(canvasFeedbackOverlay).toContain('locale?: Locale;');
    expect(canvasFeedbackOverlay).toContain('zoom: number;');
    expect(canvasFeedbackOverlay).toContain('panX: number;');
    expect(canvasFeedbackOverlay).toContain('panY: number;');
    expect(canvasFeedbackOverlay).toContain('const dragGhostMode = interactionMode && startRects.length > 0 ? interactionMode : null;');
    expect(canvasFeedbackOverlay).toContain("const shouldRenderResizeReadout = Boolean(interactionMode === 'resize' && resizeRect);");
    expect(canvasFeedbackOverlay).toContain('const shouldRenderMultiSelectionBbox = Boolean(!interactionMode && multiSelectionBbox && selectedCount >= 2);');
    expect(canvasFeedbackOverlay).toContain('const shouldRenderSnapDistanceLabel = Boolean(');
    expect(canvasFeedbackOverlay).toContain('interactionMode && snapActiveRect && snapOtherRects.length > 0,');
    expect(canvasFeedbackOverlay).toContain('{dragGhostMode ? (');
    expect(canvasFeedbackOverlay).toContain('mode={dragGhostMode}');
    expect(canvasFeedbackOverlay).toContain('{shouldRenderResizeReadout ? (');
    expect(canvasFeedbackOverlay).toContain('{shouldRenderMultiSelectionBbox ? (');
    expect(canvasFeedbackOverlay).toContain('locale={locale}');
    expect(canvasFeedbackOverlay).toContain('{shouldRenderSnapDistanceLabel ? (');
    expect(canvasFeedbackOverlay).not.toContain('{interactionMode ? (\n        <DragGhost');
    expect(canvasFeedbackOverlay).not.toContain("{interactionMode === 'resize' ? (\n        <ResizeReadout");
    expect(canvasFeedbackOverlay).not.toContain('{!interactionMode ? (\n        <MultiSelectionBoundingBox');
    expect(canvasFeedbackOverlay).not.toContain('{interactionMode ? (\n        <SnapDistanceLabel');
    expect(canvasFeedbackOverlay).not.toContain("import type { ZoomState } from '@/lib/builder/canvas/zoom';");
    expect(canvasFeedbackOverlay).not.toContain("zoomState: Pick<ZoomState, 'zoom' | 'panX' | 'panY'>;");
    expect(canvasFeedbackOverlay).not.toContain('const { zoom, panX, panY } = zoomState;');
    expect(canvasContainer).toContain('zoom={zoomState.zoom}');
    expect(canvasContainer).toContain('panX={zoomState.panX}');
    expect(canvasContainer).toContain('panY={zoomState.panY}');
    expect(canvasContainer).toContain('locale={locale}');
    expect(canvasContainer).toContain('multiSelectionBboxScreen,');
    expect(canvasContainer).toContain('multiSelectionBbox={multiSelectionBboxScreen}');
    expect(canvasContainer).toContain("resizePointer={interactionMode === 'resize' ? interactionPointer : null}");
    expect(canvasContainer).not.toContain('resizePointer={interactionPointer}');
    expect(dragGhost).toContain('export default memo(DragGhost);');
    expect(dragGhost).toContain('const DragOriginRects = memo(function DragOriginRects');
    expect(dragGhost).toContain('const DragCurrentRects = memo(function DragCurrentRects');
    expect(dragGhost).toContain('left: `${rect.x * zoom + panX}px`,');
    expect(dragGhost).toContain('width: `${rect.width * zoom}px`,');
    expect(dragGhost).not.toContain('function useScreenRects(');
    expect(dragGhost).not.toContain('function toScreen(');
    expect(dragGhost).not.toContain('const screenRects =');
    expect(dragGhost).not.toContain('rects.map((rect) => toScreen(rect, zoom, panX, panY))');
    expect(multiSelectionBoundingBox).toContain('export default memo(MultiSelectionBoundingBox);');
    expect(multiSelectionBoundingBox).toContain("import { formatMultiSelectionBboxLabel } from './selection-overlay-copy';");
    expect(multiSelectionBoundingBox).toContain('locale?: Locale;');
    expect(multiSelectionBoundingBox).toContain('data-builder-multi-selection-bbox="true"');
    expect(multiSelectionBoundingBox).toContain('data-builder-multi-selection-badge="true"');
    expect(resizeReadout).toContain('export default memo(ResizeReadout);');
    expect(resizeReadout).toContain('const readoutLeft = pointer');
    expect(resizeReadout).toContain('style={{ left: `${readoutLeft}px`, top: `${readoutTop}px` }}');
    expect(resizeReadout).not.toContain('useMemo');
    expect(resizeReadout).not.toContain('const position =');
    expect(resizeReadout).not.toContain('position?.left');
    expect(snapDistanceLabel).toContain('export function getSnapDistanceMeasurements(');
    expect(snapDistanceLabel).toContain('const activeCenterX = active.x + active.width / 2;');
    expect(snapDistanceLabel).toContain('const activeCenterY = active.y + active.height / 2;');
    expect(snapDistanceLabel).toContain('let result: DistanceMeasurement[] | null = null;');
    expect(snapDistanceLabel).toContain('return result ?? EMPTY_DISTANCE_MEASUREMENTS;');
    expect(snapDistanceLabel).not.toContain('const result: DistanceMeasurement[] = [];');
    expect(snapDistanceLabel).not.toContain('function centerX(');
    expect(snapDistanceLabel).not.toContain('function centerY(');
    expect(snapDistanceLabel).not.toContain('centerX(active)');
    expect(snapDistanceLabel).not.toContain('centerY(active)');
    expect(snapDistanceLabel).not.toContain('const screenMeasurements = useMemo(');
    expect(snapDistanceLabel).not.toContain('...measurement,');
    expect(snapDistanceLabel).toContain('left: `${measurement.x * zoom + panX}px`,');
    expect(snapDistanceLabel).toContain('export default memo(SnapDistanceLabel);');
    expect(snapDistanceLabel).not.toContain('const measurements = computeDistances');
    expect(canvasOverlapPickerLayer).toContain('export default memo(CanvasOverlapPickerLayer);');
    expect(canvasOverlapPickerLayer).toContain('selectedNodeIdSet: ReadonlySet<string>;');
    expect(canvasOverlapPickerLayer).toContain('selectedNodeIdSet.has(node.id)');
    expect(canvasOverlapPickerLayer).not.toContain('new Set(selectedNodeIds)');
    expect(canvasOverlapPickerLayer).not.toContain('selectedNodeIds.includes(node.id)');
    expect(canvasSelectionToolbarLayer).toContain('export default memo(CanvasSelectionToolbarLayer);');
    expect(canvasSelectionToolbarLayer).toContain("import { memo, useCallback, type MouseEvent } from 'react';");
    expect(canvasSelectionToolbarLayer).toContain('const handleEditText = useCallback(() => {');
    expect(canvasSelectionToolbarLayer).toContain('const handleReplaceImage = useCallback(() => {');
    expect(canvasSelectionToolbarLayer).toContain('const handleOpenMoreMenu = useCallback((event: MouseEvent<HTMLButtonElement>) => {');
    expect(canvasSelectionToolbarLayer).toContain('onEditText={handleEditText}');
    expect(canvasSelectionToolbarLayer).toContain('onOpenMoreMenu={handleOpenMoreMenu}');
    expect(canvasSelectionToolbarLayer).not.toContain('onEditText={() => {');
    expect(canvasSelectionToolbarLayer).not.toContain('onOpenMoreMenu={(event) => {');
    expect(selectionToolbar).toContain('export default memo(SelectionToolbar);');
    expect(selectionToolbar).toContain("import SelectionToolbarActionButton from './SelectionToolbarActionButton';");
    expect(selectionToolbar).toContain("} from './selection-overlay-copy';");
    expect(selectionToolbar).toContain("import { useSelectionToolbarActions } from './useSelectionToolbarActions';");
    expect(selectionToolbar).toContain('aria-label={getSelectionToolbarAriaLabel(locale)}');
    expect(selectionToolbar).toContain('data-builder-selection-toolbar-summary="true"');
    expect(selectionToolbar).toContain('const actions = useSelectionToolbarActions({');
    expect(selectionToolbar).toContain('<SelectionToolbarActionButton');
    expect(selectionToolbar).not.toContain('const MemoSelectionToolbarActionButton');
    expect(selectionToolbarActionButton).toContain("import EditorChromeIcon, { type EditorChromeIconName } from './EditorChromeIcon';");
    expect(selectionToolbarActionButton).toContain('readonly icon: EditorChromeIconName;');
    expect(selectionToolbarActionButton).toContain('aria-label={action.label}');
    expect(selectionToolbarActionButton).toContain('<EditorChromeIcon name={action.icon} className={styles.selectionToolbarIcon} />');
    expect(selectionToolbarActionButton).toContain('export default memo(SelectionToolbarActionButton);');
    expect(selectionToolbarActions).toContain('export function useSelectionToolbarActions');
    expect(selectionToolbarActions).toContain('useMemo<SelectionToolbarAction[]>(() => {');
    expect(selectionToolbarActions).toContain('const nextActions: SelectionToolbarAction[] = [];');
    expect(selectionToolbarActions).toContain("icon: 'link'");
    expect(selectionToolbarActions).toContain("icon: 'text'");
    expect(selectionToolbarActions).toContain("icon: 'image'");
    expect(selectionToolbarActions).toContain("icon: 'duplicate'");
    expect(selectionToolbarActions).toContain("icon: 'bringForward'");
    expect(selectionToolbarActions).toContain("icon: 'sendBackward'");
    expect(selectionToolbarActions).toContain("icon: 'trash'");
    expect(selectionToolbarActions).toContain("icon: 'moreHorizontal'");
    expect(selectionToolbarActions).not.toContain("icon: '⎘'");
    expect(selectionToolbarActions).not.toContain("icon: '✕'");
    expect(selectionToolbarActions).not.toContain("icon: '⋯'");
    expect(editorChromeIcon).toContain("| 'link'");
    expect(editorChromeIcon).toContain("| 'text'");
    expect(editorChromeIcon).toContain("| 'image'");
    expect(editorChromeIcon).toContain("| 'duplicate'");
    expect(editorChromeIcon).toContain("| 'bringForward'");
    expect(editorChromeIcon).toContain("| 'sendBackward'");
    expect(editorChromeIcon).toContain("| 'trash'");
    expect(editorChromeIcon).toContain("| 'moreHorizontal'");
    expect(editorChromeIcon).toContain("| 'dragHandle'");
    expect(selectionToolbar).toContain('const copy = useMemo(() => getLinkPickerCopy(locale), [locale]);');
    expect(selectionToolbar).not.toContain('const actions: SelectionToolbarAction[] = [];');
    expect(canvasNodeBadge).toContain("import { getCanvasNodeBadgeCopy } from './canvas-shortcuts-copy';");
    expect(canvasNodeBadge).not.toContain('style=');
    expect(canvasNodeBadge).toContain('className={styles.badgeItem}');
    expect(canvasNodeBadge).toContain('data-tone="locked"');
    expect(canvasNodeBadge).toContain('data-tone="sticky"');
    expect(canvasNodeBadge).toContain('data-tone="anchor"');
    expect(canvasNodeBadge).toContain('data-tone="animation"');
    expect(canvasNodeBadge).toContain('data-tone="link"');
    expect(canvasNodeBadge).toContain('className={`${styles.badgeItem} ${styles.linkBadgeButton}`}');
    expect(canvasNodeBadge).toContain('type="button"');
    expect(canvasNodeBadgeCss).toContain(":global([data-node-id]):hover > .nodeBadge {\n  opacity: 1;\n}");
    expect(canvasNodeBadgeCss).toContain(":global([data-selected='true']) > .nodeBadge {\n  opacity: 0;\n}");
    expect(canvasNodeBadgeCss).toContain(":global([data-selected='true']):hover > .nodeBadge,");
    expect(canvasNodeBadgeCss).toContain(":global([data-selected='true']):focus-within > .nodeBadge {\n  opacity: 0;\n}");
    expect(canvasNodeBadgeCss).toContain(".badgeItem[data-tone='sticky']");
    expect(canvasNodeBadgeCss).toContain(".badgeItem[data-tone='anchor']");
    expect(canvasNodeBadgeCss).toContain(".badgeItem[data-tone='animation']");
    expect(canvasNodeBadgeCss).toContain('.linkBadgeButton {');
    expect(canvasNodeBadgeCss).toContain('.linkBadgeButton:focus-visible');
    expect(canvasNodeSelectionOverlayCss).toContain('.nodeSizeLabel {');
    expect(canvasNodeSelectionOverlayCss).toContain('display: none;');
    expect(canvasStageToolbar).toContain('export default memo(CanvasStageToolbar);');
    expect(canvasStageToolbar).toContain("import { memo, useCallback, useMemo, type ChangeEvent } from 'react';");
    expect(canvasStageToolbar).toContain("import stageToolbarStyles from './CanvasStageToolbar.module.css';");
    expect(canvasStageToolbar).not.toContain('CSSProperties');
    expect(canvasStageToolbar).not.toContain('GRID_ENABLED_BUTTON_STYLE');
    expect(canvasStageToolbar).not.toContain('style=');
    expect(canvasStageToolbar).toContain('const copy = useMemo(() => getCanvasStageToolbarCopy(locale), [locale]);');
    expect(canvasStageToolbar).toContain('const handleToggleGridClick = useCallback(() => {');
    expect(canvasStageToolbar).toContain('data-builder-stage-toolbar="true"');
    expect(canvasStageToolbar).toContain('className={`${shellStyles.canvasToolbar} ${stageToolbarStyles.root}`}');
    expect(canvasStageToolbar).toContain('className={stageToolbarStyles.button}');
    expect(canvasStageToolbar).toContain('className={stageToolbarStyles.gridSizeControl}');
    expect(canvasStageToolbar).toContain('className={stageToolbarStyles.gridSizePrefix}');
    expect(canvasStageToolbar).toContain('className={stageToolbarStyles.gridSizeInput}');
    expect(canvasStageToolbar).toContain("data-active={gridEnabled ? 'true' : undefined}");
    expect(canvasStageToolbar).toContain('onClick={handleToggleGridClick}');
    expect(canvasStageToolbar).toContain('onChange={handleGridSizeInputChange}');
    expect(canvasStageToolbar).not.toContain('onClick={() => {');
    expect(canvasStageToolbarCss).toContain('.root {');
    expect(canvasStageToolbarCss).toContain('.button[data-active=\'true\']');
    expect(canvasStageToolbarCss).toContain('.gridSizeControl {');
    expect(canvasStageToolbarCss).toContain('.gridSizeInput:disabled');
    expect(canvasStageToolbarCss).toContain('@media (max-width: 760px)');
    expect(canvasZoomDock).toContain('export default memo(CanvasZoomDock);');
    expect(canvasZoomDock).toContain('const copy = useMemo(() => getCanvasZoomDockCopy(locale), [locale]);');
    expect(canvasZoomDock).toContain('const currentZoomLabel = useMemo(() => zoomLabel(zoomState), [zoomState]);');
    expect(canvasZoomDock).toContain('const handleZoomOut = useCallback(() => {');
    expect(canvasZoomDock).toContain('onClick={handleZoomOut}');
    expect(canvasZoomDock).toContain('onChange={handleZoomSliderChange}');
    expect(canvasZoomDock).not.toContain('onClick={() => setZoomState');
    expect(sandboxPageCss).toContain('.canvasToolbar {');
    expect(sandboxPageCss).toContain('pointer-events: auto;');
    expect(sandboxPageCss).toContain('z-index: 50010;');
    expect(sandboxPublicChromePreview).toContain("data-builder-mobile-drawer-open={activeDrawer ? 'true' : undefined}");
    expect(sandboxPageCss).toContain(".publicChromePreview[data-builder-mobile-drawer-open='true']");
  });

  it('repairs legacy home hero search node hierarchy before editor render', () => {
    const adminBuilderPage = read('src/app/(builder)/[locale]/admin-builder/page.tsx');

    expect(adminBuilderPage).toContain('function upgradeHeroSearchForm(document: BuilderCanvasDocument, locale: Locale): BuilderCanvasDocument {');
    expect(adminBuilderPage).toContain("HERO_SEARCH_WRAPPER_Y,\n  HERO_SECTION_ROOT_HEIGHT,");
    expect(adminBuilderPage).toContain("parentId: 'home-hero-root',\n        rect: { x: 0, y: HERO_SEARCH_WRAPPER_Y, width: 1280, height: 62 },");
    expect(adminBuilderPage).toContain("parentId: 'home-hero-search-wrapper',\n        rect: { x: 0, y: 0, width: 1151, height: 62 },");
    expect(adminBuilderPage).toContain("parentId: 'home-hero-search-container',\n        rect: { x: 0, y: 0, width: 760, height: 62 },");
    expect(adminBuilderPage).toContain("parentId: 'home-hero-search-wrap',\n        rect: { x: 0, y: 0, width: 760, height: 62 },");
    expect(adminBuilderPage).toContain("parentId: 'home-hero-search-bar',\n        rect: { x: 0, y: 0, width: 700, height: 62 },");
    expect(adminBuilderPage).toContain("parentId: 'home-hero-search-bar',\n        rect: { x: 700, y: 0, width: 60, height: 62 },");
    expect(adminBuilderPage).toContain("parentId: 'home-hero-search-wrap',\n        rect: { ...node.rect, x: 0, y: 70, width: 760 },");
    expect(adminBuilderPage).toContain("parentId: 'home-hero-quick-menu',");
  });

  it('keeps decomposed hero quick menu FAQ labels aligned with the public home', () => {
    const heroSearch = read('src/components/HeroSearch.tsx');
    const adminBuilderPage = read('src/app/(builder)/[locale]/admin-builder/page.tsx');

    expect(heroQuickMenuLabels('ko')).toContain('자주 묻는 질문');
    expect(heroQuickMenuLabels('zh-hant')).toContain('常見問題');
    expect(heroQuickMenuLabels('en')).toContain('FAQ');
    expect(heroSearch).toContain("{ label: '자주 묻는 질문', href: '/ko/faq' },");
    expect(heroSearch).toContain("{ label: '常見問題', href: '/zh-hant/faq' },");
    expect(adminBuilderPage).toContain('const quickMenuNodeById = new Map(quickMenuNodes.map((node) => [node.id, node]));');
    expect(adminBuilderPage).toContain("updatedBy: `${document.updatedBy || 'builder'}+hero-quick-menu-labels`,");
  });

  it('keeps the home hero and closed header overlays visually clean in the editor', () => {
    const adminBuilderPage = read('src/app/(builder)/[locale]/admin-builder/page.tsx');
    const canvasNode = read('src/components/builder/canvas/CanvasNode.tsx');
    const sandboxPageCss = read('src/components/builder/canvas/SandboxPage.module.css');
    const globalCss = read('src/app/globals.css');

    expect(adminBuilderPage).toContain('function upgradeHomeHeroEditorialPolish(document: BuilderCanvasDocument): BuilderCanvasDocument {');
    expect(adminBuilderPage).toContain("rect: { x: 51, y: 184, width: 1178, height: 483 },");
    expect(adminBuilderPage).toContain("rect: { x: 0, y: 0, width: 780, height: 363 },");
    expect(adminBuilderPage).toContain("rect: { x: 0, y: 1, width: 240, height: 32 },");
    expect(adminBuilderPage).toContain("rect: { x: 0, y: 56, width: 780, height: 167 },");
    expect(adminBuilderPage).toContain("rect: { x: 0, y: 247, width: 580, height: 116 },");
    expect(adminBuilderPage).toContain("rect: { x: 0, y: 338, width: 260, height: 32 },");
    expect(adminBuilderPage).toContain("rect: { x: 1216, y: 746, width: 48, height: 48 },");
    expect(sandboxPageCss).toContain(".stage :global([data-node-id='home-hero-root'] > [data-builder-node-body='true']),");
    expect(sandboxPageCss).toContain(".stage :global([data-node-id='home-hero-root'] > [data-builder-node-body='true'] > .hero)");
    expect(sandboxPageCss).toContain('height: auto !important;');
    expect(sandboxPageCss).toContain('min-height: inherit !important;');
    expect(sandboxPageCss).toContain('font-family: var(--font-body) !important;');
    expect(sandboxPageCss).toContain(".stage :global([data-node-id='home-hero-links'] .hero-links-minimal) {");
    expect(sandboxPageCss).toContain('margin-top: 0 !important;');
    expect(sandboxPageCss).toContain(".stage :global([data-node-id='home-hero-media']),");
    expect(sandboxPageCss).toContain(".stage :global([data-node-id^='home-hero-media-image'])");
    expect(sandboxPageCss).toContain('z-index: 0 !important;');
    expect(sandboxPageCss).toContain(".stage :global([data-node-id='home-hero-media-image-2']),");
    expect(sandboxPageCss).toContain('pointer-events: none;');
    expect(sandboxPageCss).toContain(".stage :global([data-node-id='home-hero-search-wrapper'] > [data-builder-node-body='true'] > .hero-search-wrapper)");
    const heroSearchWrapperEditorRule = sandboxPageCss.match(/\.stage :global\(\[data-node-id='home-hero-search-wrapper'\] > \[data-builder-node-body='true'\] > \.hero-search-wrapper\) \{\n(?:  .+\n)+\}/)?.[0] ?? '';
    expect(heroSearchWrapperEditorRule).toContain('position: relative !important;');
    expect(heroSearchWrapperEditorRule).toContain('left: auto !important;');
    expect(heroSearchWrapperEditorRule).toContain('right: auto !important;');
    expect(heroSearchWrapperEditorRule).toContain('bottom: auto !important;');
    expect(heroSearchWrapperEditorRule).toContain('width: 100% !important;');
    expect(heroSearchWrapperEditorRule).toContain('transform: none !important;');
    expect(canvasNode).toContain('function resolveHomeHeroSearchEditorRect(');
    expect(canvasNode).toContain('const HOME_HERO_SEARCH_BASELINE_Y = 618;');
    expect(canvasNode).toContain('const renderRect = resolveHomeHeroSearchEditorRect(node, effectiveRect, nodesById, viewport);');
    expect(canvasNode).toContain('effectiveRect: renderRect,');
    expect(sandboxPageCss).toContain(".stage :global([data-node-id='home-hero-scroll-arrow'] > [data-builder-node-body='true'] > .hero-scroll-arrow)");
    expect(globalCss).toContain("[data-node-id^='home-hero-media-image'] img");
    expect(globalCss).toContain('filter: brightness(78%) saturate(104%) contrast(102%);');
    expect(globalCss).toContain('padding-bottom: calc(clamp(5rem, 10vw, 8rem) - var(--space-4));');
    // The home upgrade pipeline is now gated on a decomposed home
    // (isHomeCanvasDocument) so it never runs on a composite live-mirror home.
    expect(adminBuilderPage).toContain('const upgradedInitialDocument =');
    expect(adminBuilderPage).toContain('isHomeCanvasDocument(standardServicesUpgradedInitialDocument)');
    expect(adminBuilderPage).toContain('upgradeHomeHeroEditorialPolish(');
    expect(sandboxPageCss).toContain('.globalHeaderRegion :global(.builder-site-header .site-mobile-nav-drawer:not(.open)),');
    expect(sandboxPageCss).toContain('.globalHeaderRegion :global(.builder-site-header .mega-menu:not(.open)) {');
    expect(sandboxPageCss).toContain('display: none !important;');
    expect(globalCss).toContain('width: min(760px, 100%);');
    expect(globalCss).toContain('right: calc(var(--edge-safe-right) + 16px);');
    expect(globalCss).toContain('border-radius: 999px;');
    expect(globalCss).toContain('letter-spacing: 0;');
  });
});
