import { promises as fs } from 'node:fs';import os from 'node:os';import path from 'node:path';
import { NextRequest } from 'next/server';import { beforeEach,afterEach,it,expect,vi } from 'vitest';
import type { Booking,BookingService,Staff } from '@/lib/builder/bookings/types';
const gate=vi.hoisted(()=>({beforeAcquire:undefined as undefined|(()=>Promise<void>)}));
vi.mock('@/lib/builder/security/rate-limit',()=>({checkRateLimit:vi.fn(async()=>({allowed:true,retryAfterMs:0}))}));
vi.mock('@/lib/builder/bookings/availability',async(importOriginal)=>{const a=await importOriginal<typeof import('@/lib/builder/bookings/availability')>();return {...a,isSlotAvailable:vi.fn(async()=>true)};});
vi.mock('@/lib/builder/bookings/slot-lock',async(importOriginal)=>{const a=await importOriginal<typeof import('@/lib/builder/bookings/slot-lock')>();return {...a,acquireSlotLock:vi.fn(async(args)=>{await gate.beforeAcquire?.();return a.acquireSlotLock(args);})};});
vi.mock('@/lib/builder/bookings/notifications',()=>({sendBookingCancellation:vi.fn(async()=>{throw new Error('Synthetic notification failure');})}));
vi.mock('@/lib/builder/bookings/packages',()=>({restorePackageCreditForBooking:vi.fn(async(b)=>b)}));
vi.mock('@/lib/builder/bookings/zoom-handoff',()=>({maybeCreateBookingZoomLink:vi.fn(async()=>null)}));
vi.mock('@/lib/builder/webhooks/dispatcher',()=>({emitEvent:vi.fn()}));
vi.mock('@/lib/builder/apps/hook-runtime',()=>({dispatchAppHookEvent:vi.fn(async()=>undefined)}));
let root:string;let storage:typeof import('@/lib/builder/bookings/storage');let route:typeof import('../route');let tokens:typeof import('@/lib/builder/bookings/manage-token');let notifications:typeof import('@/lib/builder/bookings/notifications');let booking:Booking;
function request(action:unknown){return new NextRequest('http://localhost/api/booking/manage/synthetic',{method:'PATCH',headers:{origin:'http://localhost','content-type':'application/json'},body:JSON.stringify(action)});}
function ctx(token=tokens.createBookingManageToken(booking)){return {params:Promise.resolve({token})};}
async function bytes(){return fs.readFile(path.join(root,'bookings',booking.bookingId+'.json'),'utf8');}
beforeEach(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'booking-lifecycle-audit-'));vi.stubEnv('BUILDER_BOOKINGS_ROOT',root);vi.stubEnv('BUILDER_BOOKINGS_BACKEND','local');vi.stubEnv('BOOKING_MANAGE_TOKEN_SECRET','Synthetic-test-signing-key-only-0123456789');vi.stubGlobal('fetch',vi.fn(async()=>{throw new Error('Unexpected network');}));vi.resetModules();gate.beforeAcquire=undefined;storage=await import('@/lib/builder/bookings/storage');route=await import('../route');tokens=await import('@/lib/builder/bookings/manage-token');notifications=await import('@/lib/builder/bookings/notifications');vi.mocked(notifications.sendBookingCancellation).mockClear();
 const now=new Date().toISOString();const startAt=new Date(Date.now()+86400000*7).toISOString();booking={bookingId:'synthetic-booking',serviceId:'synthetic-service',staffId:'synthetic-staff',customer:{name:'Synthetic',email:'synthetic@example.invalid',locale:'en'},startAt,endAt:new Date(Date.parse(startAt)+3600000).toISOString(),status:'confirmed',source:'web',createdAt:now,updatedAt:now,reminders:[]};
 const service:BookingService={serviceId:booking.serviceId,slug:'synthetic',name:{ko:'합성',en:'Synthetic','zh-hant':'合成'},description:{ko:'합성',en:'Synthetic','zh-hant':'合成'},durationMinutes:60,staffIds:[booking.staffId],bufferBeforeMinutes:0,bufferAfterMinutes:0,isActive:true,paymentMode:'free',createdAt:now,updatedAt:now};const staff:Staff={staffId:booking.staffId,name:{ko:'합성',en:'Synthetic','zh-hant':'合成'},title:{ko:'합성',en:'Synthetic','zh-hant':'合成'},isActive:true,createdAt:now,updatedAt:now};await storage.saveService(service);await storage.saveStaff(staff);await storage.saveBooking(booking);vi.clearAllMocks();
});
afterEach(async()=>{gate.beforeAcquire=undefined;vi.unstubAllGlobals();vi.unstubAllEnvs();await fs.rm(root,{recursive:true,force:true});});
it('invalid and mismatched-owner bearer tokens cannot mutate booking',async()=>{const original=await bytes();expect((await route.PATCH(request({action:'cancel'}),ctx('invalid'))).status).toBe(401);const other=tokens.createBookingManageToken({...booking,customer:{...booking.customer,email:'other@example.invalid'}});expect((await route.PATCH(request({action:'cancel'}),ctx(other))).status).toBe(404);expect(await bytes()).toBe(original);expect(notifications.sendBookingCancellation).not.toHaveBeenCalled();});
it('expired bearer token cannot mutate booking',async()=>{const original=await bytes();expect((await route.PATCH(request({action:'cancel'}),ctx(tokens.createBookingManageToken(booking,-1000)))).status).toBe(401);expect(await bytes()).toBe(original);});
it('completed cancellation remains successful when notification throws; repeated cancel rejects without rewriting',async()=>{const first=await route.PATCH(request({action:'cancel'}),ctx());expect(first.status).toBe(200);expect(await first.json()).toMatchObject({ok:true,emailDelivery:{ok:false,reason:'internal_error'}});expect((await storage.getBooking(booking.bookingId))?.status).toBe('cancelled');const persisted=await bytes();expect((await route.PATCH(request({action:'cancel'}),ctx())).status).toBe(409);expect(await bytes()).toBe(persisted);expect(notifications.sendBookingCancellation).toHaveBeenCalledTimes(1);});
it('past booking is not eligible for reschedule and stays unchanged',async()=>{await storage.saveBooking({...booking,startAt:'2000-01-01T00:00:00Z',endAt:'2000-01-01T01:00:00Z'});const original=await bytes();expect((await route.PATCH(request({action:'reschedule',startAt:new Date(Date.now()+86400000).toISOString()}),ctx())).status).toBe(409);expect(await bytes()).toBe(original);});
it('cancel finishing between reschedule read and lease must not be overwritten by stale reschedule',async()=>{let afterCancel='';gate.beforeAcquire=async()=>{gate.beforeAcquire=undefined;const cancelled=await route.PATCH(request({action:'cancel'}),ctx());expect(cancelled.status).toBe(200);afterCancel=await bytes();};const response=await route.PATCH(request({action:'reschedule',startAt:new Date(Date.now()+86400000*8).toISOString()}),ctx());const saved=await storage.getBooking(booking.bookingId);console.info('STALE_OBSERVATION',JSON.stringify({status:response.status,savedStatus:saved?.status,cancellationRetained:Boolean(saved?.cancelledAt)}));expect(response.status).toBe(409);expect(await bytes()).toBe(afterCancel);await noRescheduleEffects();});

async function noRescheduleEffects(){const a=await import('@/lib/builder/bookings/availability');const z=await import('@/lib/builder/bookings/zoom-handoff');expect(a.isSlotAvailable).not.toHaveBeenCalled();expect(z.maybeCreateBookingZoomLink).not.toHaveBeenCalled();}
const target=()=>new Date(Date.now()+86400000*8).toISOString();
it('owner change before lease is reauthorized and not overwritten',async()=>{let changed='';gate.beforeAcquire=async()=>{gate.beforeAcquire=undefined;await storage.saveBooking({...booking,customer:{...booking.customer,email:'new-owner@example.invalid'}});changed=await bytes();};const response=await route.PATCH(request({action:'reschedule',startAt:target()}),ctx());expect(response.status).toBe(404);expect(await bytes()).toBe(changed);await noRescheduleEffects();});
it.each(['completed','past'] as const)('current %s eligibility after lease blocks stale reschedule',async(kind)=>{let changed='';gate.beforeAcquire=async()=>{gate.beforeAcquire=undefined;await storage.saveBooking(kind==='completed'?{...booking,status:'completed'}:{...booking,startAt:'2000-01-01T00:00:00Z',endAt:'2000-01-01T01:00:00Z'});changed=await bytes();};const response=await route.PATCH(request({action:'reschedule',startAt:target()}),ctx());expect(response.status).toBe(409);expect(await bytes()).toBe(changed);await noRescheduleEffects();});
it.each(['service','staff','resources'] as const)('changed %s lease scope fails closed',async(kind)=>{let changed='';gate.beforeAcquire=async()=>{gate.beforeAcquire=undefined;const service=(await storage.getService(booking.serviceId))!;if(kind==='service'){await storage.saveService({...service,serviceId:'new-service'});await storage.saveBooking({...booking,serviceId:'new-service'});}else if(kind==='staff'){await storage.saveBooking({...booking,staffId:'new-staff'});}else{await storage.saveService({...service,requiredResourceIds:['new-resource']});}changed=await bytes();};const response=await route.PATCH(request({action:'reschedule',startAt:target()}),ctx());expect(response.status).toBe(409);expect((await response.json()).errorCode).toBe('slot_lock_conflict');expect(await bytes()).toBe(changed);await noRescheduleEffects();});
it('allowed reschedule uses current duration and preserves current customer/payment metadata',async()=>{gate.beforeAcquire=async()=>{gate.beforeAcquire=undefined;const service=(await storage.getService(booking.serviceId))!;await storage.saveService({...service,durationMinutes:90});await storage.saveBooking({...booking,customer:{...booking.customer,name:'Current name',notes:'Current note'},paymentStatus:'paid',paymentAmount:500,meetingLink:'https://example.invalid/current'});};const startAt=target();const response=await route.PATCH(request({action:'reschedule',startAt}),ctx());expect(response.status).toBe(200);const saved=(await storage.getBooking(booking.bookingId))!;expect(saved.customer.name).toBe('Current name');expect(saved.customer.notes).toBe('Current note');expect(saved.paymentStatus).toBe('paid');expect(saved.paymentAmount).toBe(500);expect(saved.meetingLink).toBe('https://example.invalid/current');expect(Date.parse(saved.endAt)-Date.parse(startAt)).toBe(90*60000);const z=await import('@/lib/builder/bookings/zoom-handoff');expect(z.maybeCreateBookingZoomLink).toHaveBeenCalledWith(expect.objectContaining({service:expect.objectContaining({durationMinutes:90}),customerName:'Current name'}));});
it('normal reschedule succeeds and keeps existing fields',async()=>{const startAt=target();const response=await route.PATCH(request({action:'reschedule',startAt}),ctx());expect(response.status).toBe(200);const saved=(await storage.getBooking(booking.bookingId))!;expect(saved.startAt).toBe(startAt);expect(saved.customer).toEqual(booking.customer);expect(saved.status).toBe('confirmed');});

it('current service cancellation policy is rechecked after acquiring the lease',async()=>{let changed='';gate.beforeAcquire=async()=>{gate.beforeAcquire=undefined;const now=new Date().toISOString();await storage.saveCancellationPolicy({policyId:'strict',name:'Synthetic strict',cancelHoursBefore:0,rescheduleHoursBefore:1000,fullRefundHoursBefore:0,partialRefundHoursBefore:0,partialRefundPercent:0,cancellationFeePercent:0,isActive:true,createdAt:now,updatedAt:now});await storage.saveService({...((await storage.getService(booking.serviceId))!),cancellationPolicyId:'strict'});changed=await bytes();};const response=await route.PATCH(request({action:'reschedule',startAt:target()}),ctx());expect(response.status).toBe(409);expect((await response.json()).errorCode).toBe('reschedule_unavailable');expect(await bytes()).toBe(changed);await noRescheduleEffects();});
it('explicit requested staff preserves its locked scope when previous assigned staff changes',async()=>{gate.beforeAcquire=async()=>{gate.beforeAcquire=undefined;await storage.saveBooking({...booking,staffId:'previous-assignment-changed',customer:{...booking.customer,notes:'Keep current note'}});};const response=await route.PATCH(request({action:'reschedule',startAt:target(),staffId:booking.staffId}),ctx());expect(response.status).toBe(200);const saved=(await storage.getBooking(booking.bookingId))!;expect(saved.staffId).toBe(booking.staffId);expect(saved.customer.notes).toBe('Keep current note');});
