import type { PortfolioProject } from '@/lib/builder/portfolio/portfolio-shared';
import type { Locale } from '@/lib/locales';

export interface PortfolioListCopy {
  loading: string;
  loadError: string;
  categoryFilterLabel: string;
  allCategories: string;
  empty: string;
  mockProjects: PortfolioProject[];
}

const portfolioListCopy: Record<Locale, PortfolioListCopy> = {
  ko: {
    loading: '포트폴리오를 불러오는 중...',
    loadError: '포트폴리오를 불러오지 못했습니다.',
    categoryFilterLabel: '포트폴리오 분류 필터',
    allCategories: '전체',
    empty: '표시할 포트폴리오가 없습니다.',
    mockProjects: [
      {
        projectId: 'portfolio-widget-mock-1',
        slug: 'taiwan-company-setup-case',
        title: '한국 기업 대만 법인 설립 지원',
        summary: '투자 구조, 법인 등기, 세무 등록까지 한 번에 정리한 회사 설립 사례입니다.',
        description: '대만 회사 설립 자문 사례',
        body: '대만 회사 설립 자문 사례',
        category: 'company-setup',
        client: '익명 기업',
        completedAt: '2026-03-20',
        tags: ['회사설립'],
        locale: 'ko',
        status: 'published',
        featured: true,
        order: 1,
        coverImageUrl: '/images/001-taiwan-company-establishment-basics/featured-01.jpg',
        gallery: [],
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-05-20T00:00:00.000Z',
      },
      {
        projectId: 'portfolio-widget-mock-2',
        slug: 'taiwan-labor-dispute-case',
        title: '대만 노동 분쟁 자문',
        summary: '해고 통지, 퇴직금, 시간외 수당 쟁점을 정리한 노동법 대응 사례입니다.',
        description: '대만 노동법 자문 사례',
        body: '대만 노동법 자문 사례',
        category: 'labor',
        completedAt: '2026-02-12',
        tags: ['노동법'],
        locale: 'ko',
        status: 'published',
        featured: false,
        order: 2,
        coverImageUrl: '/images/blog/008-taiwan-labor-severance-law/featured-01.jpg',
        gallery: [],
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-05-20T00:00:00.000Z',
      },
    ],
  },
  'zh-hant': {
    loading: '作品集載入中...',
    loadError: '無法載入作品集。',
    categoryFilterLabel: '作品集分類篩選',
    allCategories: '全部',
    empty: '目前沒有可顯示的作品集。',
    mockProjects: [
      {
        projectId: 'portfolio-widget-mock-1',
        slug: 'taiwan-company-setup-case',
        title: '韓國企業台灣公司設立支援',
        summary: '投資架構、公司登記與稅務登錄一次整理的公司設立案例。',
        description: '台灣公司設立顧問案例',
        body: '台灣公司設立顧問案例',
        category: 'company-setup',
        client: '匿名企業',
        completedAt: '2026-03-20',
        tags: ['公司設立'],
        locale: 'zh-hant',
        status: 'published',
        featured: true,
        order: 1,
        coverImageUrl: '/images/001-taiwan-company-establishment-basics/featured-01.jpg',
        gallery: [],
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-05-20T00:00:00.000Z',
      },
      {
        projectId: 'portfolio-widget-mock-2',
        slug: 'taiwan-labor-dispute-case',
        title: '台灣勞資爭議顧問',
        summary: '整理資遣通知、退休金與加班費爭點的勞動法應對案例。',
        description: '台灣勞動法顧問案例',
        body: '台灣勞動法顧問案例',
        category: 'labor',
        completedAt: '2026-02-12',
        tags: ['勞動法'],
        locale: 'zh-hant',
        status: 'published',
        featured: false,
        order: 2,
        coverImageUrl: '/images/blog/008-taiwan-labor-severance-law/featured-01.jpg',
        gallery: [],
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-05-20T00:00:00.000Z',
      },
    ],
  },
  en: {
    loading: 'Loading portfolio...',
    loadError: 'Unable to load portfolio.',
    categoryFilterLabel: 'Portfolio category filter',
    allCategories: 'All',
    empty: 'No portfolio projects to show.',
    mockProjects: [
      {
        projectId: 'portfolio-widget-mock-1',
        slug: 'taiwan-company-setup-case',
        title: 'Taiwan company setup for a Korean business',
        summary: 'A company formation case covering investment structure, registration, and tax setup.',
        description: 'Taiwan company setup advisory case',
        body: 'Taiwan company setup advisory case',
        category: 'company-setup',
        client: 'Anonymous company',
        completedAt: '2026-03-20',
        tags: ['Company setup'],
        locale: 'en',
        status: 'published',
        featured: true,
        order: 1,
        coverImageUrl: '/images/001-taiwan-company-establishment-basics/featured-01.jpg',
        gallery: [],
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-05-20T00:00:00.000Z',
      },
      {
        projectId: 'portfolio-widget-mock-2',
        slug: 'taiwan-labor-dispute-case',
        title: 'Taiwan labor dispute advisory',
        summary: 'A labor-law response case covering dismissal notice, severance, and overtime pay issues.',
        description: 'Taiwan labor law advisory case',
        body: 'Taiwan labor law advisory case',
        category: 'labor',
        completedAt: '2026-02-12',
        tags: ['Labor law'],
        locale: 'en',
        status: 'published',
        featured: false,
        order: 2,
        coverImageUrl: '/images/blog/008-taiwan-labor-severance-law/featured-01.jpg',
        gallery: [],
        createdAt: '2026-05-20T00:00:00.000Z',
        updatedAt: '2026-05-20T00:00:00.000Z',
      },
    ],
  },
};

export function getPortfolioListCopy(locale: Locale): PortfolioListCopy {
  return portfolioListCopy[locale] ?? portfolioListCopy.en;
}
