import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 600;
const SPECIALS_Y = HERO_H + 80;
const SPECIALS_H = 380;
const GALLERY_Y = SPECIALS_Y + SPECIALS_H + 80;
const GALLERY_H = 300;
const CTA_Y = GALLERY_Y + GALLERY_H + 80;
const CTA_H = 200;
const STAGE_H = CTA_Y + CTA_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero section ────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-cafehome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-cafehome-hero-bg',
    parentId: 'tpl-cafehome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    src: '/images/placeholder-cafe-hero.jpg',
    alt: '카페 인테리어 히어로 이미지',
    style: { opacity: 40, borderRadius: 0 },
  }),
  heading(
    'tpl-cafehome-hero-title',
    { x: 80, y: 160, width: 600, height: 100 },
    '한 잔의 여유, 매일의 행복',
    1,
    '#ffffff',
    'left',
    'tpl-cafehome-hero',
  ),
  createTextNode({
    id: 'tpl-cafehome-hero-tagline',
    parentId: 'tpl-cafehome-hero',
    rect: { x: 80, y: 280, width: 500, height: 60 },
    text: '직접 로스팅한 스페셜티 커피와 수제 베이커리를 만나보세요.',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: 'regular',
    align: 'left',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-cafehome-hero-cta',
    parentId: 'tpl-cafehome-hero',
    rect: { x: 80, y: 370, width: 200, height: 52 },
    label: '메뉴 보기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Today's specials (3 cards) ─────────────────────────── */
  heading(
    'tpl-cafehome-special-title',
    { x: 80, y: SPECIALS_Y, width: 400, height: 50 },
    '오늘의 추천',
    2,
    '#123b63',
    'left',
  ),
  createContainerNode({
    id: 'tpl-cafehome-spec-1',
    rect: { x: 80, y: SPECIALS_Y + 70, width: 360, height: 260 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-cafehome-spec-1-img',
    parentId: 'tpl-cafehome-spec-1',
    rect: { x: 0, y: 0, width: 360, height: 140 },
    src: '/images/placeholder-coffee-1.jpg',
    alt: '시그니처 라떼',
    style: { borderRadius: 0 },
  }),
  heading('tpl-cafehome-spec-1-t', { x: 16, y: 152, width: 328, height: 36 }, '시그니처 라떼', 3, '#123b63', 'left', 'tpl-cafehome-spec-1'),
  createTextNode({
    id: 'tpl-cafehome-spec-1-d',
    parentId: 'tpl-cafehome-spec-1',
    rect: { x: 16, y: 196, width: 328, height: 50 },
    text: '에티오피아 예가체프 원두로 만든 부드러운 라떼',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-cafehome-spec-2',
    rect: { x: 470, y: SPECIALS_Y + 70, width: 360, height: 260 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-cafehome-spec-2-img',
    parentId: 'tpl-cafehome-spec-2',
    rect: { x: 0, y: 0, width: 360, height: 140 },
    src: '/images/placeholder-pastry-1.jpg',
    alt: '크루아상',
    style: { borderRadius: 0 },
  }),
  heading('tpl-cafehome-spec-2-t', { x: 16, y: 152, width: 328, height: 36 }, '버터 크루아상', 3, '#123b63', 'left', 'tpl-cafehome-spec-2'),
  createTextNode({
    id: 'tpl-cafehome-spec-2-d',
    parentId: 'tpl-cafehome-spec-2',
    rect: { x: 16, y: 196, width: 328, height: 50 },
    text: '프랑스산 버터로 만든 바삭한 수제 크루아상',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-cafehome-spec-3',
    rect: { x: 860, y: SPECIALS_Y + 70, width: 360, height: 260 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-cafehome-spec-3-img',
    parentId: 'tpl-cafehome-spec-3',
    rect: { x: 0, y: 0, width: 360, height: 140 },
    src: '/images/placeholder-smoothie-1.jpg',
    alt: '베리 스무디',
    style: { borderRadius: 0 },
  }),
  heading('tpl-cafehome-spec-3-t', { x: 16, y: 152, width: 328, height: 36 }, '베리 스무디', 3, '#123b63', 'left', 'tpl-cafehome-spec-3'),
  createTextNode({
    id: 'tpl-cafehome-spec-3-d',
    parentId: 'tpl-cafehome-spec-3',
    rect: { x: 16, y: 196, width: 328, height: 50 },
    text: '신선한 블루베리와 딸기로 만든 건강한 스무디',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),

  /* ── Atmosphere gallery ─────────────────────────────────── */
  createContainerNode({
    id: 'tpl-cafehome-gallery',
    rect: { x: 0, y: GALLERY_Y, width: W, height: GALLERY_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading('tpl-cafehome-gallery-title', { x: 80, y: 40, width: 400, height: 50 }, '카페 분위기', 2, '#123b63', 'left', 'tpl-cafehome-gallery'),
  createImageNode({
    id: 'tpl-cafehome-gallery-img-1',
    parentId: 'tpl-cafehome-gallery',
    rect: { x: 80, y: 110, width: 350, height: 160 },
    src: '/images/placeholder-cafe-interior-1.jpg',
    alt: '카페 내부 전경',
    style: { borderRadius: 8 },
  }),
  createImageNode({
    id: 'tpl-cafehome-gallery-img-2',
    parentId: 'tpl-cafehome-gallery',
    rect: { x: 460, y: 110, width: 350, height: 160 },
    src: '/images/placeholder-cafe-interior-2.jpg',
    alt: '카페 좌석',
    style: { borderRadius: 8 },
  }),
  createImageNode({
    id: 'tpl-cafehome-gallery-img-3',
    parentId: 'tpl-cafehome-gallery',
    rect: { x: 840, y: 110, width: 350, height: 160 },
    src: '/images/placeholder-cafe-interior-3.jpg',
    alt: '카페 테라스',
    style: { borderRadius: 8 },
  }),

  /* ── Visit CTA ──────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-cafehome-cta',
    rect: { x: 0, y: CTA_Y, width: W, height: CTA_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createTextNode({
    id: 'tpl-cafehome-cta-text',
    parentId: 'tpl-cafehome-cta',
    rect: { x: 80, y: 50, width: 600, height: 44 },
    text: '오늘 한 잔의 여유를 즐기러 오세요. 매일 아침 7시부터 영업합니다.',
    fontSize: 18,
    color: '#ffffff',
    fontWeight: 'medium',
    lineHeight: 1.4,
  }),
  createButtonNode({
    id: 'tpl-cafehome-cta-btn',
    parentId: 'tpl-cafehome-cta',
    rect: { x: 80, y: 110, width: 180, height: 48 },
    label: '위치 보기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-cafehome-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-cafehome-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-cafehome-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-proof-label',
    parentId: 'tpl-cafehome-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-proof-title',
    parentId: 'tpl-cafehome-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'cafe home 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-proof-copy',
    parentId: 'tpl-cafehome-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-cafehome-wix-metric-1',
    parentId: 'tpl-cafehome-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-metric-1-value',
    parentId: 'tpl-cafehome-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-metric-1-label',
    parentId: 'tpl-cafehome-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-cafehome-wix-metric-2',
    parentId: 'tpl-cafehome-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-metric-2-value',
    parentId: 'tpl-cafehome-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-metric-2-label',
    parentId: 'tpl-cafehome-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-cafehome-wix-metric-3',
    parentId: 'tpl-cafehome-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-metric-3-value',
    parentId: 'tpl-cafehome-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-metric-3-label',
    parentId: 'tpl-cafehome-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-cafehome-wix-metric-4',
    parentId: 'tpl-cafehome-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-metric-4-value',
    parentId: 'tpl-cafehome-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-metric-4-label',
    parentId: 'tpl-cafehome-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-showcase-label',
    parentId: 'tpl-cafehome-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-showcase-title',
    parentId: 'tpl-cafehome-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-showcase-copy',
    parentId: 'tpl-cafehome-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-cafehome-wix-showcase-visual',
    parentId: 'tpl-cafehome-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-showcase-visual-title',
    parentId: 'tpl-cafehome-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-showcase-visual-copy',
    parentId: 'tpl-cafehome-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-cafehome-wix-showcase-card-1',
    parentId: 'tpl-cafehome-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-showcase-card-1-title',
    parentId: 'tpl-cafehome-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-showcase-card-1-copy',
    parentId: 'tpl-cafehome-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-cafehome-wix-showcase-card-2',
    parentId: 'tpl-cafehome-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-cafehome-wix-showcase-card-2-title',
    parentId: 'tpl-cafehome-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
]);

export const cafeHomeTemplate: PageTemplate = {
  id: 'cafe-home',
  name: '카페 홈',
  category: 'cafe',
  subcategory: 'homepage',
  description: '따뜻한 히어로 + 오늘의 추천(3개 카드) + 분위기 갤러리 + 방문 CTA',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
