import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 500;
const PRODUCTS_Y = HERO_H + 80;
const PRODUCTS_H = 520;
const CATEGORIES_Y = PRODUCTS_Y + PRODUCTS_H + 80;
const CATEGORIES_H = 300;
const PROMO_Y = CATEGORIES_Y + CATEGORIES_H + 80;
const PROMO_H = 160;
const STAGE_H = PROMO_Y + PROMO_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Hero banner ────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-echome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-echome-hero-bg',
    parentId: 'tpl-echome-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    src: '/images/placeholder-shop-hero.jpg',
    alt: '온라인 쇼핑몰 히어로 배너',
    style: { opacity: 30, borderRadius: 0 },
  }),
  heading(
    'tpl-echome-hero-title',
    { x: 80, y: 120, width: 600, height: 100 },
    '새로운 시즌, 새로운 스타일',
    1,
    '#ffffff',
    'left',
    'tpl-echome-hero',
  ),
  createTextNode({
    id: 'tpl-echome-hero-sub',
    parentId: 'tpl-echome-hero',
    rect: { x: 80, y: 240, width: 500, height: 60 },
    text: '트렌디한 신상품을 만나보세요. 지금 주문하면 무료 배송!',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: 'regular',
    align: 'left',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-echome-hero-cta',
    parentId: 'tpl-echome-hero',
    rect: { x: 80, y: 330, width: 200, height: 52 },
    label: '쇼핑하기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Featured products (4 cards) ────────────────────────── */
  heading(
    'tpl-echome-prod-title',
    { x: 80, y: PRODUCTS_Y, width: 400, height: 50 },
    '인기 상품',
    2,
    '#123b63',
    'left',
  ),
  // Card 1
  createContainerNode({
    id: 'tpl-echome-prod-1',
    rect: { x: 80, y: PRODUCTS_Y + 70, width: 260, height: 400 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-echome-prod-1-img',
    parentId: 'tpl-echome-prod-1',
    rect: { x: 0, y: 0, width: 260, height: 220 },
    src: '/images/placeholder-product-1.jpg',
    alt: '상품 이미지 1',
    style: { borderRadius: 0 },
  }),
  heading('tpl-echome-prod-1-name', { x: 16, y: 232, width: 228, height: 36 }, '프리미엄 가방', 3, '#123b63', 'left', 'tpl-echome-prod-1'),
  createTextNode({
    id: 'tpl-echome-prod-1-price',
    parentId: 'tpl-echome-prod-1',
    rect: { x: 16, y: 276, width: 228, height: 30 },
    text: '₩89,000',
    fontSize: 18,
    color: '#e8a838',
    fontWeight: 'bold',
  }),
  createTextNode({
    id: 'tpl-echome-prod-1-desc',
    parentId: 'tpl-echome-prod-1',
    rect: { x: 16, y: 314, width: 228, height: 60 },
    text: '고급 소재로 제작된 데일리 가방. 다양한 컬러 옵션.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 2
  createContainerNode({
    id: 'tpl-echome-prod-2',
    rect: { x: 370, y: PRODUCTS_Y + 70, width: 260, height: 400 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-echome-prod-2-img',
    parentId: 'tpl-echome-prod-2',
    rect: { x: 0, y: 0, width: 260, height: 220 },
    src: '/images/placeholder-product-2.jpg',
    alt: '상품 이미지 2',
    style: { borderRadius: 0 },
  }),
  heading('tpl-echome-prod-2-name', { x: 16, y: 232, width: 228, height: 36 }, '캐주얼 스니커즈', 3, '#123b63', 'left', 'tpl-echome-prod-2'),
  createTextNode({
    id: 'tpl-echome-prod-2-price',
    parentId: 'tpl-echome-prod-2',
    rect: { x: 16, y: 276, width: 228, height: 30 },
    text: '₩129,000',
    fontSize: 18,
    color: '#e8a838',
    fontWeight: 'bold',
  }),
  createTextNode({
    id: 'tpl-echome-prod-2-desc',
    parentId: 'tpl-echome-prod-2',
    rect: { x: 16, y: 314, width: 228, height: 60 },
    text: '편안하고 세련된 디자인의 캐주얼 스니커즈.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 3
  createContainerNode({
    id: 'tpl-echome-prod-3',
    rect: { x: 660, y: PRODUCTS_Y + 70, width: 260, height: 400 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-echome-prod-3-img',
    parentId: 'tpl-echome-prod-3',
    rect: { x: 0, y: 0, width: 260, height: 220 },
    src: '/images/placeholder-product-3.jpg',
    alt: '상품 이미지 3',
    style: { borderRadius: 0 },
  }),
  heading('tpl-echome-prod-3-name', { x: 16, y: 232, width: 228, height: 36 }, '미니멀 시계', 3, '#123b63', 'left', 'tpl-echome-prod-3'),
  createTextNode({
    id: 'tpl-echome-prod-3-price',
    parentId: 'tpl-echome-prod-3',
    rect: { x: 16, y: 276, width: 228, height: 30 },
    text: '₩199,000',
    fontSize: 18,
    color: '#e8a838',
    fontWeight: 'bold',
  }),
  createTextNode({
    id: 'tpl-echome-prod-3-desc',
    parentId: 'tpl-echome-prod-3',
    rect: { x: 16, y: 314, width: 228, height: 60 },
    text: '심플한 디자인의 클래식 손목시계.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  // Card 4
  createContainerNode({
    id: 'tpl-echome-prod-4',
    rect: { x: 950, y: PRODUCTS_Y + 70, width: 260, height: 400 },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 0,
  }),
  createImageNode({
    id: 'tpl-echome-prod-4-img',
    parentId: 'tpl-echome-prod-4',
    rect: { x: 0, y: 0, width: 260, height: 220 },
    src: '/images/placeholder-product-4.jpg',
    alt: '상품 이미지 4',
    style: { borderRadius: 0 },
  }),
  heading('tpl-echome-prod-4-name', { x: 16, y: 232, width: 228, height: 36 }, '실크 스카프', 3, '#123b63', 'left', 'tpl-echome-prod-4'),
  createTextNode({
    id: 'tpl-echome-prod-4-price',
    parentId: 'tpl-echome-prod-4',
    rect: { x: 16, y: 276, width: 228, height: 30 },
    text: '₩59,000',
    fontSize: 18,
    color: '#e8a838',
    fontWeight: 'bold',
  }),
  createTextNode({
    id: 'tpl-echome-prod-4-desc',
    parentId: 'tpl-echome-prod-4',
    rect: { x: 16, y: 314, width: 228, height: 60 },
    text: '부드러운 실크 소재의 멀티 스카프.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),

  /* ── Categories ─────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-echome-cat',
    rect: { x: 0, y: CATEGORIES_Y, width: W, height: CATEGORIES_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-echome-cat-title',
    { x: 80, y: 40, width: 400, height: 50 },
    '카테고리',
    2,
    '#123b63',
    'left',
    'tpl-echome-cat',
  ),
  createTextNode({
    id: 'tpl-echome-cat-list',
    parentId: 'tpl-echome-cat',
    rect: { x: 80, y: 110, width: 800, height: 120 },
    text: '의류 · 가방 · 신발 · 액세서리 · 뷰티 · 홈리빙 · 디지털 · 식품',
    fontSize: 18,
    color: '#1f2937',
    fontWeight: 'medium',
    lineHeight: 1.8,
  }),

  /* ── Promo strip ────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-echome-promo',
    rect: { x: 0, y: PROMO_Y, width: W, height: PROMO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createTextNode({
    id: 'tpl-echome-promo-text',
    parentId: 'tpl-echome-promo',
    rect: { x: 80, y: 30, width: 700, height: 44 },
    text: '지금 가입하면 첫 구매 15% 할인! 무료 배송 혜택까지.',
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.4,
  }),
  createButtonNode({
    id: 'tpl-echome-promo-btn',
    parentId: 'tpl-echome-promo',
    rect: { x: 80, y: 90, width: 180, height: 48 },
    label: '회원가입',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-ecommercehome-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-ecommercehome-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-ecommercehome-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-proof-label',
    parentId: 'tpl-ecommercehome-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-proof-title',
    parentId: 'tpl-ecommercehome-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'ecommerce home 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-proof-copy',
    parentId: 'tpl-ecommercehome-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-ecommercehome-wix-metric-1',
    parentId: 'tpl-ecommercehome-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-metric-1-value',
    parentId: 'tpl-ecommercehome-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-metric-1-label',
    parentId: 'tpl-ecommercehome-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercehome-wix-metric-2',
    parentId: 'tpl-ecommercehome-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-metric-2-value',
    parentId: 'tpl-ecommercehome-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-metric-2-label',
    parentId: 'tpl-ecommercehome-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercehome-wix-metric-3',
    parentId: 'tpl-ecommercehome-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-metric-3-value',
    parentId: 'tpl-ecommercehome-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-metric-3-label',
    parentId: 'tpl-ecommercehome-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercehome-wix-metric-4',
    parentId: 'tpl-ecommercehome-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-metric-4-value',
    parentId: 'tpl-ecommercehome-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-metric-4-label',
    parentId: 'tpl-ecommercehome-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-showcase-label',
    parentId: 'tpl-ecommercehome-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-showcase-title',
    parentId: 'tpl-ecommercehome-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-showcase-copy',
    parentId: 'tpl-ecommercehome-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-ecommercehome-wix-showcase-visual',
    parentId: 'tpl-ecommercehome-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-ecommercehome-wix-showcase-visual-title',
    parentId: 'tpl-ecommercehome-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
]);

export const ecommerceHomeTemplate: PageTemplate = {
  id: 'ecommerce-home',
  name: '온라인 쇼핑몰 홈',
  category: 'ecommerce',
  subcategory: 'homepage',
  description: '히어로 배너 + 인기 상품(4개) + 카테고리 + 프로모션 스트립',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
