import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 400;
const FOUNDER_Y = HERO_H + 80;
const FOUNDER_H = 360;
const VALUES_Y = FOUNDER_Y + FOUNDER_H + 80;
const VALUES_H = 300;
const STAGE_H = VALUES_Y + VALUES_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Brand story hero ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-ecabout-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading(
    'tpl-ecabout-hero-title',
    { x: 80, y: 100, width: 600, height: 60 },
    '우리의 이야기',
    1,
    '#ffffff',
    'left',
    'tpl-ecabout-hero',
  ),
  createTextNode({
    id: 'tpl-ecabout-hero-desc',
    parentId: 'tpl-ecabout-hero',
    rect: { x: 80, y: 180, width: 600, height: 120 },
    text: '2015년 작은 공방에서 시작된 우리 브랜드는 "좋은 품질, 합리적 가격"이라는 신념으로 성장해 왔습니다. 고객 한 분 한 분의 만족이 우리의 원동력입니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 1.7,
  }),

  /* ── Founder section ────────────────────────────────────── */
  heading(
    'tpl-ecabout-founder-title',
    { x: 80, y: FOUNDER_Y, width: 400, height: 50 },
    '창업자 소개',
    2,
    '#123b63',
    'left',
  ),
  createImageNode({
    id: 'tpl-ecabout-founder-img',
    rect: { x: 80, y: FOUNDER_Y + 70, width: 300, height: 260 },
    src: '/images/placeholder-founder.jpg',
    alt: '창업자 프로필 사진',
    style: { borderRadius: 12 },
  }),
  createTextNode({
    id: 'tpl-ecabout-founder-bio',
    rect: { x: 420, y: FOUNDER_Y + 70, width: 700, height: 260 },
    text: '김민수 대표는 패션 디자인을 전공하고, 글로벌 브랜드에서 10년간 경력을 쌓은 후 자신만의 브랜드를 시작했습니다. "모든 사람이 좋은 디자인을 누릴 수 있어야 합니다"라는 철학으로, 합리적인 가격에 고품질 제품을 만들어가고 있습니다.',
    fontSize: 16,
    color: '#1f2937',
    lineHeight: 1.7,
  }),

  /* ── Values ─────────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-ecabout-values',
    rect: { x: 0, y: VALUES_Y, width: W, height: VALUES_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-ecabout-values-title',
    { x: 80, y: 40, width: 400, height: 50 },
    '브랜드 가치',
    2,
    '#123b63',
    'left',
    'tpl-ecabout-values',
  ),
  createContainerNode({
    id: 'tpl-ecabout-val-1',
    parentId: 'tpl-ecabout-values',
    rect: { x: 80, y: 110, width: 340, height: 140 },
    background: '#ffffff',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-ecabout-val-1-title', { x: 24, y: 16, width: 292, height: 32 }, '품질 우선', 3, '#123b63', 'left', 'tpl-ecabout-val-1'),
  createTextNode({
    id: 'tpl-ecabout-val-1-desc',
    parentId: 'tpl-ecabout-val-1',
    rect: { x: 24, y: 56, width: 292, height: 60 },
    text: '엄선된 소재와 꼼꼼한 품질 관리로 오래 사용할 수 있는 제품을 만듭니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-ecabout-val-2',
    parentId: 'tpl-ecabout-values',
    rect: { x: 460, y: 110, width: 340, height: 140 },
    background: '#ffffff',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-ecabout-val-2-title', { x: 24, y: 16, width: 292, height: 32 }, '지속 가능성', 3, '#123b63', 'left', 'tpl-ecabout-val-2'),
  createTextNode({
    id: 'tpl-ecabout-val-2-desc',
    parentId: 'tpl-ecabout-val-2',
    rect: { x: 24, y: 56, width: 292, height: 60 },
    text: '친환경 포장재와 지속 가능한 생산 공정을 통해 환경을 생각합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  createContainerNode({
    id: 'tpl-ecabout-val-3',
    parentId: 'tpl-ecabout-values',
    rect: { x: 840, y: 110, width: 340, height: 140 },
    background: '#ffffff',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-ecabout-val-3-title', { x: 24, y: 16, width: 292, height: 32 }, '고객 중심', 3, '#123b63', 'left', 'tpl-ecabout-val-3'),
  createTextNode({
    id: 'tpl-ecabout-val-3-desc',
    parentId: 'tpl-ecabout-val-3',
    rect: { x: 24, y: 56, width: 292, height: 60 },
    text: '고객의 피드백을 반영하여 끊임없이 발전하는 브랜드를 지향합니다.',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 1.5,
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-proof-label',
    parentId: 'tpl-ecommerceabout-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-proof-title',
    parentId: 'tpl-ecommerceabout-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'ecommerce about 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-proof-copy',
    parentId: 'tpl-ecommerceabout-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-metric-1',
    parentId: 'tpl-ecommerceabout-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-metric-1-value',
    parentId: 'tpl-ecommerceabout-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-metric-1-label',
    parentId: 'tpl-ecommerceabout-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-metric-2',
    parentId: 'tpl-ecommerceabout-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-metric-2-value',
    parentId: 'tpl-ecommerceabout-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-metric-2-label',
    parentId: 'tpl-ecommerceabout-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-metric-3',
    parentId: 'tpl-ecommerceabout-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-metric-3-value',
    parentId: 'tpl-ecommerceabout-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-metric-3-label',
    parentId: 'tpl-ecommerceabout-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-metric-4',
    parentId: 'tpl-ecommerceabout-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-metric-4-value',
    parentId: 'tpl-ecommerceabout-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-metric-4-label',
    parentId: 'tpl-ecommerceabout-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-label',
    parentId: 'tpl-ecommerceabout-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-title',
    parentId: 'tpl-ecommerceabout-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-copy',
    parentId: 'tpl-ecommerceabout-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-showcase-visual',
    parentId: 'tpl-ecommerceabout-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-visual-title',
    parentId: 'tpl-ecommerceabout-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-visual-copy',
    parentId: 'tpl-ecommerceabout-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-showcase-card-1',
    parentId: 'tpl-ecommerceabout-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-card-1-title',
    parentId: 'tpl-ecommerceabout-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-card-1-copy',
    parentId: 'tpl-ecommerceabout-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-showcase-card-2',
    parentId: 'tpl-ecommerceabout-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-card-2-title',
    parentId: 'tpl-ecommerceabout-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-card-2-copy',
    parentId: 'tpl-ecommerceabout-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-showcase-card-3',
    parentId: 'tpl-ecommerceabout-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-card-3-title',
    parentId: 'tpl-ecommerceabout-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-showcase-card-3-copy',
    parentId: 'tpl-ecommerceabout-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommerceabout-wix-quote',
    parentId: 'tpl-ecommerceabout-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-quote-mark',
    parentId: 'tpl-ecommerceabout-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-quote-body',
    parentId: 'tpl-ecommerceabout-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-quote-role',
    parentId: 'tpl-ecommerceabout-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommerceabout-wix-cta-label',
    parentId: 'tpl-ecommerceabout-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
]);

export const ecommerceAboutTemplate: PageTemplate = {
  id: 'ecommerce-about',
  name: '온라인 쇼핑몰 소개',
  category: 'ecommerce',
  subcategory: 'about',
  description: '브랜드 스토리 + 창업자 소개 + 브랜드 가치',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
