import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HEADER_H = 120;
const GRID_Y = HEADER_H + 60;
const CARD_H = 200;
const CARD_GAP = 30;
const STAGE_H = GRID_Y + (CARD_H + CARD_GAP) * 3 + 60;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const reviewData = [
  { product: '프리미엄 가방', text: '정말 예쁘고 실용적이에요. 출근용으로 매일 사용하고 있어요.', author: '이OO', rating: '★★★★★' },
  { product: '캐주얼 스니커즈', text: '발이 편하고 쿠션이 좋아요. 오래 걸어도 피로하지 않습니다.', author: '박OO', rating: '★★★★★' },
  { product: '미니멀 시계', text: '디자인이 깔끔하고 고급스러워요. 선물용으로도 좋을 것 같아요.', author: '최OO', rating: '★★★★☆' },
  { product: '실크 스카프', text: '촉감이 정말 좋고 색상이 화면과 동일해요. 만족합니다.', author: '김OO', rating: '★★★★★' },
  { product: '리넨 셔츠', text: '여름에 시원하게 입기 좋아요. 세탁 후에도 형태가 잘 유지돼요.', author: '정OO', rating: '★★★★☆' },
  { product: '데님 팬츠', text: '핏이 너무 좋아서 다른 색상도 추가 구매했어요!', author: '한OO', rating: '★★★★★' },
];

function reviewCard(n: number, col: number, row: number): BuilderCanvasNode[] {
  const x = 80 + col * 570;
  const y = GRID_Y + row * (CARD_H + CARD_GAP);
  const cId = `tpl-ecrevs-card-${n}`;
  const d = reviewData[n - 1];
  return [
    createContainerNode({
      id: cId,
      rect: { x, y, width: 540, height: CARD_H },
      background: '#f3f4f6',
      borderRadius: 12,
      padding: 24,
    }),
    heading(`${cId}-product`, { x: 24, y: 16, width: 300, height: 30 }, d.product, 3, '#123b63', 'left', cId),
    createTextNode({
      id: `${cId}-rating`,
      parentId: cId,
      rect: { x: 340, y: 20, width: 160, height: 24 },
      text: d.rating,
      fontSize: 16,
      color: '#e8a838',
      fontWeight: 'bold',
      align: 'right',
    }),
    createTextNode({
      id: `${cId}-text`,
      parentId: cId,
      rect: { x: 24, y: 60, width: 492, height: 80 },
      text: `"${d.text}"`,
      fontSize: 15,
      color: '#374151',
      lineHeight: 1.6,
    }),
    createTextNode({
      id: `${cId}-author`,
      parentId: cId,
      rect: { x: 24, y: 150, width: 200, height: 24 },
      text: `— ${d.author}`,
      fontSize: 14,
      color: '#6b7280',
      fontWeight: 'medium',
    }),
  ];
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  createContainerNode({
    id: 'tpl-ecrevs-header',
    rect: { x: 0, y: 0, width: W, height: HEADER_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading(
    'tpl-ecrevs-title',
    { x: 80, y: 35, width: 400, height: 50 },
    '고객 리뷰',
    1,
    '#ffffff',
    'left',
    'tpl-ecrevs-header',
  ),

  ...reviewCard(1, 0, 0),
  ...reviewCard(2, 1, 0),
  ...reviewCard(3, 0, 1),
  ...reviewCard(4, 1, 1),
  ...reviewCard(5, 0, 2),
  ...reviewCard(6, 1, 2),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-proof-label',
    parentId: 'tpl-ecommercereviews-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-proof-title',
    parentId: 'tpl-ecommercereviews-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'ecommerce reviews 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-proof-copy',
    parentId: 'tpl-ecommercereviews-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-metric-1',
    parentId: 'tpl-ecommercereviews-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-metric-1-value',
    parentId: 'tpl-ecommercereviews-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-metric-1-label',
    parentId: 'tpl-ecommercereviews-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-metric-2',
    parentId: 'tpl-ecommercereviews-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-metric-2-value',
    parentId: 'tpl-ecommercereviews-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-metric-2-label',
    parentId: 'tpl-ecommercereviews-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-metric-3',
    parentId: 'tpl-ecommercereviews-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-metric-3-value',
    parentId: 'tpl-ecommercereviews-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-metric-3-label',
    parentId: 'tpl-ecommercereviews-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-metric-4',
    parentId: 'tpl-ecommercereviews-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-metric-4-value',
    parentId: 'tpl-ecommercereviews-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-metric-4-label',
    parentId: 'tpl-ecommercereviews-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-label',
    parentId: 'tpl-ecommercereviews-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-title',
    parentId: 'tpl-ecommercereviews-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-copy',
    parentId: 'tpl-ecommercereviews-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-showcase-visual',
    parentId: 'tpl-ecommercereviews-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-visual-title',
    parentId: 'tpl-ecommercereviews-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-visual-copy',
    parentId: 'tpl-ecommercereviews-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-showcase-card-1',
    parentId: 'tpl-ecommercereviews-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-card-1-title',
    parentId: 'tpl-ecommercereviews-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-card-1-copy',
    parentId: 'tpl-ecommercereviews-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-showcase-card-2',
    parentId: 'tpl-ecommercereviews-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-card-2-title',
    parentId: 'tpl-ecommercereviews-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-card-2-copy',
    parentId: 'tpl-ecommercereviews-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-showcase-card-3',
    parentId: 'tpl-ecommercereviews-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-card-3-title',
    parentId: 'tpl-ecommercereviews-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-showcase-card-3-copy',
    parentId: 'tpl-ecommercereviews-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercereviews-wix-quote',
    parentId: 'tpl-ecommercereviews-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-quote-mark',
    parentId: 'tpl-ecommercereviews-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-quote-body',
    parentId: 'tpl-ecommercereviews-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-quote-role',
    parentId: 'tpl-ecommercereviews-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommercereviews-wix-cta-label',
    parentId: 'tpl-ecommercereviews-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
]);

export const ecommerceReviewsTemplate: PageTemplate = {
  id: 'ecommerce-reviews',
  name: '온라인 쇼핑몰 리뷰',
  category: 'ecommerce',
  subcategory: 'reviews',
  description: '고객 리뷰 페이지, 상품명 포함 6개 리뷰 카드',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
