import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 400;
const COUNTDOWN_Y = HERO_H + 60;
const COUNTDOWN_H = 120;
const DEALS_Y = COUNTDOWN_Y + COUNTDOWN_H + 60;
const DEALS_H = 900;
const STAGE_H = DEALS_Y + DEALS_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

function dealCard(n: number, col: number, row: number): BuilderCanvasNode[] {
  const x = 80 + col * 390;
  const y = DEALS_Y + row * 440;
  const cId = `tpl-ecsale-deal-${n}`;
  const names = ['여름 원피스', '리넨 셔츠', '데님 팬츠', '캔버스 백', '선글라스', '스트랩 샌들'];
  const prices = ['₩39,000', '₩29,000', '₩49,000', '₩19,000', '₩25,000', '₩35,000'];
  const originals = ['₩79,000', '₩59,000', '₩89,000', '₩39,000', '₩55,000', '₩69,000'];
  return [
    createContainerNode({
      id: cId,
      rect: { x, y, width: 360, height: 420 },
      background: '#f3f4f6',
      borderRadius: 12,
      padding: 0,
    }),
    createImageNode({
      id: `${cId}-img`,
      parentId: cId,
      rect: { x: 0, y: 0, width: 360, height: 220 },
      src: `/images/placeholder-sale-${n}.jpg`,
      alt: `${names[n - 1]} 세일 이미지`,
      style: { borderRadius: 0 },
    }),
    heading(`${cId}-name`, { x: 16, y: 232, width: 328, height: 36 }, names[n - 1], 3, '#123b63', 'left', cId),
    createTextNode({
      id: `${cId}-orig`,
      parentId: cId,
      rect: { x: 16, y: 276, width: 100, height: 24 },
      text: originals[n - 1],
      fontSize: 14,
      color: '#9ca3af',
    }),
    createTextNode({
      id: `${cId}-price`,
      parentId: cId,
      rect: { x: 130, y: 274, width: 120, height: 28 },
      text: prices[n - 1],
      fontSize: 20,
      color: '#e8a838',
      fontWeight: 'bold',
    }),
    createButtonNode({
      id: `${cId}-btn`,
      parentId: cId,
      rect: { x: 16, y: 320, width: 140, height: 44 },
      label: '구매하기',
      href: '#',
      variant: 'primary',
      style: { backgroundColor: '#e8a838', borderRadius: 6 },
    }),
  ];
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Sale hero ──────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-ecsale-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading(
    'tpl-ecsale-hero-title',
    { x: 80, y: 100, width: 700, height: 80 },
    '시즌 오프 세일 최대 50% 할인',
    1,
    '#e8a838',
    'left',
    'tpl-ecsale-hero',
  ),
  createTextNode({
    id: 'tpl-ecsale-hero-sub',
    parentId: 'tpl-ecsale-hero',
    rect: { x: 80, y: 200, width: 500, height: 60 },
    text: '놓치면 후회할 특가 상품을 지금 만나보세요!',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 1.6,
  }),
  createButtonNode({
    id: 'tpl-ecsale-hero-cta',
    parentId: 'tpl-ecsale-hero',
    rect: { x: 80, y: 290, width: 200, height: 52 },
    label: '세일 상품 보기',
    href: '#',
    variant: 'primary',
    style: { backgroundColor: '#e8a838', borderRadius: 6 },
  }),

  /* ── Countdown area ─────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-ecsale-countdown',
    rect: { x: 0, y: COUNTDOWN_Y, width: W, height: COUNTDOWN_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-ecsale-countdown-title',
    { x: 80, y: 20, width: 600, height: 40 },
    '세일 종료까지',
    2,
    '#123b63',
    'left',
    'tpl-ecsale-countdown',
  ),
  createTextNode({
    id: 'tpl-ecsale-countdown-timer',
    parentId: 'tpl-ecsale-countdown',
    rect: { x: 80, y: 66, width: 400, height: 36 },
    text: '3일 12시간 45분 30초',
    fontSize: 28,
    color: '#e8a838',
    fontWeight: 'bold',
  }),

  /* ── Featured deals (6 cards) ───────────────────────────── */
  ...dealCard(1, 0, 0),
  ...dealCard(2, 1, 0),
  ...dealCard(3, 2, 0),
  ...dealCard(4, 0, 1),
  ...dealCard(5, 1, 1),
  ...dealCard(6, 2, 1),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-ecommercesale-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-ecommercesale-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-ecommercesale-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-proof-label',
    parentId: 'tpl-ecommercesale-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-proof-title',
    parentId: 'tpl-ecommercesale-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'ecommerce sale 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-proof-copy',
    parentId: 'tpl-ecommercesale-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-ecommercesale-wix-metric-1',
    parentId: 'tpl-ecommercesale-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-metric-1-value',
    parentId: 'tpl-ecommercesale-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-metric-1-label',
    parentId: 'tpl-ecommercesale-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercesale-wix-metric-2',
    parentId: 'tpl-ecommercesale-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-metric-2-value',
    parentId: 'tpl-ecommercesale-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-metric-2-label',
    parentId: 'tpl-ecommercesale-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercesale-wix-metric-3',
    parentId: 'tpl-ecommercesale-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-metric-3-value',
    parentId: 'tpl-ecommercesale-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-metric-3-label',
    parentId: 'tpl-ecommercesale-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercesale-wix-metric-4',
    parentId: 'tpl-ecommercesale-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-metric-4-value',
    parentId: 'tpl-ecommercesale-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-metric-4-label',
    parentId: 'tpl-ecommercesale-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-showcase-label',
    parentId: 'tpl-ecommercesale-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-showcase-title',
    parentId: 'tpl-ecommercesale-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-showcase-copy',
    parentId: 'tpl-ecommercesale-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-ecommercesale-wix-showcase-visual',
    parentId: 'tpl-ecommercesale-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-showcase-visual-title',
    parentId: 'tpl-ecommercesale-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-showcase-visual-copy',
    parentId: 'tpl-ecommercesale-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-ecommercesale-wix-showcase-card-1',
    parentId: 'tpl-ecommercesale-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-showcase-card-1-title',
    parentId: 'tpl-ecommercesale-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-ecommercesale-wix-showcase-card-1-copy',
    parentId: 'tpl-ecommercesale-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
]);

export const ecommerceSaleTemplate: PageTemplate = {
  id: 'ecommerce-sale',
  name: '온라인 쇼핑몰 세일',
  category: 'ecommerce',
  subcategory: 'sale',
  description: '세일 랜딩 페이지 + 카운트다운 영역 + 특가 상품(6개)',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
