import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const BIO_H = 400;
const STORY_Y = BIO_H + 80;
const STORY_H = 260;
const TEAM_Y = STORY_Y + STORY_H + 80;
const TEAM_H = 300;
const STAGE_H = TEAM_Y + TEAM_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Author bio ─────────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-blogabout-bio',
    rect: { x: 0, y: 0, width: W, height: BIO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-blogabout-photo',
    parentId: 'tpl-blogabout-bio',
    rect: { x: 80, y: 60, width: 280, height: 280 },
    src: '/images/placeholder-author.jpg',
    alt: '에디터 프로필 사진',
    style: { borderRadius: 140 },
  }),
  heading(
    'tpl-blogabout-name',
    { x: 420, y: 80, width: 700, height: 50 },
    '김민지',
    1,
    '#ffffff',
    'left',
    'tpl-blogabout-bio',
  ),
  createTextNode({
    id: 'tpl-blogabout-role',
    parentId: 'tpl-blogabout-bio',
    rect: { x: 420, y: 140, width: 300, height: 28 },
    text: '편집장 · 라이프스타일 칼럼니스트',
    fontSize: 16,
    color: '#e8a838',
    fontWeight: 'medium',
  }),
  createTextNode({
    id: 'tpl-blogabout-intro',
    parentId: 'tpl-blogabout-bio',
    rect: { x: 420, y: 190, width: 700, height: 120 },
    text: '10년간 라이프스타일 매거진에서 활동하며, 일상 속 영감과 트렌드를 글로 전하고 있습니다. "작은 변화가 큰 행복을 만든다"는 신념으로 독자들과 소통합니다.',
    fontSize: 16,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 1.7,
  }),

  /* ── Publication story ──────────────────────────────────── */
  heading(
    'tpl-blogabout-story-title',
    { x: 80, y: STORY_Y, width: 400, height: 50 },
    '매거진 이야기',
    2,
    '#123b63',
    'left',
  ),
  createTextNode({
    id: 'tpl-blogabout-story-text',
    rect: { x: 80, y: STORY_Y + 60, width: W - 160, height: 160 },
    text: '2020년에 시작된 우리 매거진은 "더 나은 일상을 위한 영감"을 모토로 라이프스타일, 문화, 테크, 여행 등 다양한 분야의 콘텐츠를 제공하고 있습니다.\n\n매주 5개 이상의 오리지널 콘텐츠를 발행하며, 10만 명 이상의 독자가 뉴스레터를 구독하고 있습니다.',
    fontSize: 16,
    color: '#1f2937',
    lineHeight: 1.7,
  }),

  /* ── Editorial team ─────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-blogabout-team',
    rect: { x: 0, y: TEAM_Y, width: W, height: TEAM_H },
    background: '#f3f4f6',
    borderRadius: 0,
  }),
  heading(
    'tpl-blogabout-team-title',
    { x: 80, y: 40, width: 400, height: 50 },
    '편집팀',
    2,
    '#123b63',
    'left',
    'tpl-blogabout-team',
  ),
  createContainerNode({
    id: 'tpl-blogabout-team-1',
    parentId: 'tpl-blogabout-team',
    rect: { x: 80, y: 110, width: 340, height: 140 },
    background: '#ffffff',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-blogabout-team-1-name', { x: 24, y: 12, width: 200, height: 28 }, '이수진', 3, '#123b63', 'left', 'tpl-blogabout-team-1'),
  createTextNode({
    id: 'tpl-blogabout-team-1-role',
    parentId: 'tpl-blogabout-team-1',
    rect: { x: 24, y: 46, width: 292, height: 24 },
    text: '테크·디지털 에디터',
    fontSize: 14,
    color: '#6b7280',
  }),
  createTextNode({
    id: 'tpl-blogabout-team-1-bio',
    parentId: 'tpl-blogabout-team-1',
    rect: { x: 24, y: 78, width: 292, height: 40 },
    text: 'IT 전문 기자 출신, 기술이 바꾸는 일상을 글로 전합니다.',
    fontSize: 13,
    color: '#1f2937',
    lineHeight: 1.4,
  }),
  createContainerNode({
    id: 'tpl-blogabout-team-2',
    parentId: 'tpl-blogabout-team',
    rect: { x: 460, y: 110, width: 340, height: 140 },
    background: '#ffffff',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-blogabout-team-2-name', { x: 24, y: 12, width: 200, height: 28 }, '박준영', 3, '#123b63', 'left', 'tpl-blogabout-team-2'),
  createTextNode({
    id: 'tpl-blogabout-team-2-role',
    parentId: 'tpl-blogabout-team-2',
    rect: { x: 24, y: 46, width: 292, height: 24 },
    text: '문화·여행 에디터',
    fontSize: 14,
    color: '#6b7280',
  }),
  createTextNode({
    id: 'tpl-blogabout-team-2-bio',
    parentId: 'tpl-blogabout-team-2',
    rect: { x: 24, y: 78, width: 292, height: 40 },
    text: '30개국 이상을 여행하며 문화와 여행의 매력을 전합니다.',
    fontSize: 13,
    color: '#1f2937',
    lineHeight: 1.4,
  }),
  createContainerNode({
    id: 'tpl-blogabout-team-3',
    parentId: 'tpl-blogabout-team',
    rect: { x: 840, y: 110, width: 340, height: 140 },
    background: '#ffffff',
    borderRadius: 12,
    padding: 24,
  }),
  heading('tpl-blogabout-team-3-name', { x: 24, y: 12, width: 200, height: 28 }, '최하나', 3, '#123b63', 'left', 'tpl-blogabout-team-3'),
  createTextNode({
    id: 'tpl-blogabout-team-3-role',
    parentId: 'tpl-blogabout-team-3',
    rect: { x: 24, y: 46, width: 292, height: 24 },
    text: '건강·웰니스 에디터',
    fontSize: 14,
    color: '#6b7280',
  }),
  createTextNode({
    id: 'tpl-blogabout-team-3-bio',
    parentId: 'tpl-blogabout-team-3',
    rect: { x: 24, y: 78, width: 292, height: 40 },
    text: '건강 전문가로서 웰니스 라이프를 위한 정보를 나눕니다.',
    fontSize: 13,
    color: '#1f2937',
    lineHeight: 1.4,
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-blogabout-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-proof-label',
    parentId: 'tpl-blogabout-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-proof-title',
    parentId: 'tpl-blogabout-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'blog about 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-proof-copy',
    parentId: 'tpl-blogabout-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-metric-1',
    parentId: 'tpl-blogabout-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-metric-1-value',
    parentId: 'tpl-blogabout-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-metric-1-label',
    parentId: 'tpl-blogabout-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-metric-2',
    parentId: 'tpl-blogabout-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-metric-2-value',
    parentId: 'tpl-blogabout-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-metric-2-label',
    parentId: 'tpl-blogabout-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-metric-3',
    parentId: 'tpl-blogabout-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-metric-3-value',
    parentId: 'tpl-blogabout-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-metric-3-label',
    parentId: 'tpl-blogabout-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-metric-4',
    parentId: 'tpl-blogabout-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-metric-4-value',
    parentId: 'tpl-blogabout-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-metric-4-label',
    parentId: 'tpl-blogabout-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-label',
    parentId: 'tpl-blogabout-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-title',
    parentId: 'tpl-blogabout-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-copy',
    parentId: 'tpl-blogabout-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-showcase-visual',
    parentId: 'tpl-blogabout-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-visual-title',
    parentId: 'tpl-blogabout-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-visual-copy',
    parentId: 'tpl-blogabout-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-showcase-card-1',
    parentId: 'tpl-blogabout-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-card-1-title',
    parentId: 'tpl-blogabout-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-card-1-copy',
    parentId: 'tpl-blogabout-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-showcase-card-2',
    parentId: 'tpl-blogabout-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-card-2-title',
    parentId: 'tpl-blogabout-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-card-2-copy',
    parentId: 'tpl-blogabout-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-showcase-card-3',
    parentId: 'tpl-blogabout-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-card-3-title',
    parentId: 'tpl-blogabout-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogabout-wix-showcase-card-3-copy',
    parentId: 'tpl-blogabout-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogabout-wix-quote',
    parentId: 'tpl-blogabout-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
]);

export const blogAboutTemplate: PageTemplate = {
  id: 'blog-about',
  name: '블로그 소개',
  category: 'blog',
  subcategory: 'about',
  description: '저자 바이오 + 매거진 이야기 + 편집팀 소개',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
