import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createButtonNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HERO_H = 400;
const META_Y = HERO_H + 40;
const META_H = 60;
const BODY_Y = META_Y + META_H + 40;
const BODY_H = 600;
const SHARE_Y = BODY_Y + BODY_H + 60;
const SHARE_H = 100;
const STAGE_H = SHARE_Y + SHARE_H + 80;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  /* ── Article hero ───────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-blogart-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  createImageNode({
    id: 'tpl-blogart-hero-img',
    parentId: 'tpl-blogart-hero',
    rect: { x: 0, y: 0, width: W, height: HERO_H },
    src: '/images/placeholder-article-hero.jpg',
    alt: '기사 히어로 이미지',
    style: { opacity: 40, borderRadius: 0 },
  }),
  heading(
    'tpl-blogart-title',
    { x: 160, y: 140, width: 960, height: 100 },
    '2026년을 이끌어갈 10가지 라이프스타일 트렌드',
    1,
    '#ffffff',
    'center',
    'tpl-blogart-hero',
  ),

  /* ── Author & date ──────────────────────────────────────── */
  createTextNode({
    id: 'tpl-blogart-author',
    rect: { x: 160, y: META_Y, width: 400, height: 28 },
    text: '김민지 · 편집장',
    fontSize: 16,
    color: '#123b63',
    fontWeight: 'medium',
  }),
  createTextNode({
    id: 'tpl-blogart-date',
    rect: { x: 160, y: META_Y + 30, width: 200, height: 24 },
    text: '2026년 4월 10일 · 8분 읽기',
    fontSize: 14,
    color: '#6b7280',
  }),

  /* ── Article body ───────────────────────────────────────── */
  createTextNode({
    id: 'tpl-blogart-body-1',
    rect: { x: 160, y: BODY_Y, width: 760, height: 180 },
    text: '2026년은 기존의 생활 방식에 큰 변화를 가져올 한 해입니다. 디지털 기술의 발전과 함께 우리의 일상도 빠르게 변화하고 있으며, 새로운 트렌드들이 등장하고 있습니다.\n\n이번 기사에서는 올해 가장 주목해야 할 10가지 라이프스타일 트렌드를 소개합니다. 각 트렌드가 우리의 삶에 어떤 영향을 미칠지 함께 살펴보겠습니다.',
    fontSize: 17,
    color: '#1f2937',
    lineHeight: 1.8,
  }),
  heading(
    'tpl-blogart-h2-1',
    { x: 160, y: BODY_Y + 200, width: 760, height: 40 },
    '1. 지속 가능한 소비',
    2,
    '#123b63',
    'left',
  ),
  createTextNode({
    id: 'tpl-blogart-body-2',
    rect: { x: 160, y: BODY_Y + 260, width: 760, height: 140 },
    text: '환경에 대한 인식이 높아지면서 소비자들은 지속 가능한 제품과 서비스를 선택하는 경향이 강해지고 있습니다. 재활용 소재, 로컬 생산, 최소 포장 등이 주요 키워드로 떠오르고 있습니다.',
    fontSize: 17,
    color: '#1f2937',
    lineHeight: 1.8,
  }),
  heading(
    'tpl-blogart-h2-2',
    { x: 160, y: BODY_Y + 420, width: 760, height: 40 },
    '2. 디지털 디톡스',
    2,
    '#123b63',
    'left',
  ),
  createTextNode({
    id: 'tpl-blogart-body-3',
    rect: { x: 160, y: BODY_Y + 480, width: 760, height: 100 },
    text: '항상 연결되어 있는 현대 사회에서 의도적으로 디지털 기기와 거리를 두는 시간을 갖는 것이 새로운 트렌드로 자리 잡고 있습니다.',
    fontSize: 17,
    color: '#1f2937',
    lineHeight: 1.8,
  }),

  /* ── Share buttons ──────────────────────────────────────── */
  createContainerNode({
    id: 'tpl-blogart-share',
    rect: { x: 160, y: SHARE_Y, width: 760, height: SHARE_H },
    background: '#f3f4f6',
    borderRadius: 12,
    padding: 24,
  }),
  createTextNode({
    id: 'tpl-blogart-share-label',
    parentId: 'tpl-blogart-share',
    rect: { x: 24, y: 24, width: 100, height: 24 },
    text: '공유하기',
    fontSize: 14,
    color: '#123b63',
    fontWeight: 'bold',
  }),
  createTextNode({
    id: 'tpl-blogart-share-links',
    parentId: 'tpl-blogart-share',
    rect: { x: 24, y: 56, width: 400, height: 24 },
    text: 'Facebook · Twitter · LinkedIn · 링크 복사',
    fontSize: 14,
    color: '#e8a838',
    fontWeight: 'medium',
  }),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-blogarticle-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-proof-label',
    parentId: 'tpl-blogarticle-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-proof-title',
    parentId: 'tpl-blogarticle-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'blog article 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-proof-copy',
    parentId: 'tpl-blogarticle-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-metric-1',
    parentId: 'tpl-blogarticle-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-metric-1-value',
    parentId: 'tpl-blogarticle-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-metric-1-label',
    parentId: 'tpl-blogarticle-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-metric-2',
    parentId: 'tpl-blogarticle-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-metric-2-value',
    parentId: 'tpl-blogarticle-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-metric-2-label',
    parentId: 'tpl-blogarticle-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-metric-3',
    parentId: 'tpl-blogarticle-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-metric-3-value',
    parentId: 'tpl-blogarticle-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-metric-3-label',
    parentId: 'tpl-blogarticle-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-metric-4',
    parentId: 'tpl-blogarticle-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-metric-4-value',
    parentId: 'tpl-blogarticle-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-metric-4-label',
    parentId: 'tpl-blogarticle-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-label',
    parentId: 'tpl-blogarticle-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-title',
    parentId: 'tpl-blogarticle-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-copy',
    parentId: 'tpl-blogarticle-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-showcase-visual',
    parentId: 'tpl-blogarticle-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-visual-title',
    parentId: 'tpl-blogarticle-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-visual-copy',
    parentId: 'tpl-blogarticle-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-showcase-card-1',
    parentId: 'tpl-blogarticle-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-card-1-title',
    parentId: 'tpl-blogarticle-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-card-1-copy',
    parentId: 'tpl-blogarticle-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-showcase-card-2',
    parentId: 'tpl-blogarticle-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-card-2-title',
    parentId: 'tpl-blogarticle-wix-showcase-card-2',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '선택 기준',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-card-2-copy',
    parentId: 'tpl-blogarticle-wix-showcase-card-2',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '가격, 일정, 품질처럼 비교해야 하는 항목을 짧은 문장으로 설명합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-showcase-card-3',
    parentId: 'tpl-blogarticle-wix-showcase',
    rect: { x: 776, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-card-3-title',
    parentId: 'tpl-blogarticle-wix-showcase-card-3',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '다음 행동',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-showcase-card-3-copy',
    parentId: 'tpl-blogarticle-wix-showcase-card-3',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '문의, 예약, 구독, 구매 같은 다음 행동을 명확히 연결합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarticle-wix-quote',
    parentId: 'tpl-blogarticle-wix-proof',
    rect: { x: 650, y: 260, width: 444, height: 180 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'office-card',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-quote-mark',
    parentId: 'tpl-blogarticle-wix-quote',
    rect: { x: 28, y: 22, width: 44, height: 44 },
    text: '“',
    fontSize: 40,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-quote-body',
    parentId: 'tpl-blogarticle-wix-quote',
    rect: { x: 78, y: 34, width: 300, height: 72 },
    text: '정보가 충분히 분리되어 있어 페이지를 훑는 속도가 빨라졌습니다.',
    fontSize: 16,
    color: '#334155',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-quote-role',
    parentId: 'tpl-blogarticle-wix-quote',
    rect: { x: 78, y: 124, width: 240, height: 24 },
    text: 'Template quality reviewer',
    fontSize: 13,
    color: '#64748b',
    fontWeight: 'medium',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-cta-label',
    parentId: 'tpl-blogarticle-wix-cta',
    rect: { x: 64, y: 58, width: 260, height: 28 },
    text: 'Conversion-ready section',
    fontSize: 13,
    color: '#e8a838',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'hero-eyebrow',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-cta-title',
    parentId: 'tpl-blogarticle-wix-cta',
    rect: { x: 64, y: 102, width: 560, height: 92 },
    text: '방문자가 다음 단계로 이동할 수 있게 마지막 전환을 강화합니다',
    fontSize: 38,
    color: '#ffffff',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-blogarticle-wix-cta-copy',
    parentId: 'tpl-blogarticle-wix-cta',
    rect: { x: 64, y: 214, width: 560, height: 64 },
    text: '짧은 설득 문구, 보조 안내, 두 개의 행동 버튼을 같은 영역에 묶어 전환 흐름을 분명하게 만듭니다.',
    fontSize: 17,
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createButtonNode({
    id: 'tpl-blogarticle-wix-cta-primary',
    parentId: 'tpl-blogarticle-wix-cta',
    rect: { x: 64, y: 318, width: 178, height: 52 },
    label: '문의 시작',
    href: '#contact',
    variant: 'primary',
    className: 'hero-cta',
    style: { backgroundColor: '#e8a838', borderRadius: 8 },
  }),
  createButtonNode({
    id: 'tpl-blogarticle-wix-cta-secondary',
    parentId: 'tpl-blogarticle-wix-cta',
    rect: { x: 266, y: 318, width: 176, height: 52 },
    label: '자세히 보기',
    href: '#services',
    variant: 'outline',
    className: 'hero-cta',
    style: { backgroundColor: 'transparent', borderColor: '#ffffff', borderWidth: 1, borderRadius: 8 },
  }),
]);

export const blogArticleTemplate: PageTemplate = {
  id: 'blog-article',
  name: '블로그 기사',
  category: 'blog',
  subcategory: 'article',
  description: '기사 레이아웃: 제목, 저자, 날짜, 히어로 이미지, 본문, 공유 버튼',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
