import type { BuilderCanvasNode } from '@/lib/builder/canvas/types';
import { createDefaultCanvasNodeStyle } from '@/lib/builder/canvas/types';
import {
  createContainerNode,
  createTextNode,
  createImageNode,
  assignCanvasNodeZIndices,
} from '@/lib/builder/decompose/shared';
import type { PageTemplate } from '../types';

const W = 1280;
const HEADER_H = 120;
const LIST_Y = HEADER_H + 60;
const ENTRY_H = 120;
const ENTRY_GAP = 20;
const STAGE_H = LIST_Y + (ENTRY_H + ENTRY_GAP) * 8 + 60;

function heading(
  id: string,
  rect: BuilderCanvasNode['rect'],
  text: string,
  level: number,
  color: string,
  align: 'left' | 'center' | 'right' = 'left',
  parentId?: string,
): BuilderCanvasNode {
  return {
    id,
    kind: 'heading',
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(),
    zIndex: 0,
    rotation: 0,
    locked: false,
    visible: true,
    content: { text, level, color, align },
  };
}

const articles = [
  { title: '2026년 라이프스타일 트렌드', date: '2026.04.10', cat: '라이프스타일' },
  { title: '디지털 노마드의 삶', date: '2026.04.03', cat: '테크' },
  { title: '봄맞이 인테리어 가이드', date: '2026.03.27', cat: '라이프스타일' },
  { title: '유럽 소도시 여행기', date: '2026.03.20', cat: '여행' },
  { title: '건강한 아침 루틴 5가지', date: '2026.03.13', cat: '건강' },
  { title: '미니멀 워드로브 만들기', date: '2026.03.06', cat: '패션' },
  { title: '독서 습관 기르는 법', date: '2026.02.27', cat: '문화' },
  { title: '홈 카페 레시피 모음', date: '2026.02.20', cat: '푸드' },
];

function archiveEntry(n: number): BuilderCanvasNode[] {
  const y = LIST_Y + (ENTRY_H + ENTRY_GAP) * (n - 1);
  const cId = `tpl-blogarc-entry-${n}`;
  const a = articles[n - 1];
  return [
    createContainerNode({
      id: cId,
      rect: { x: 80, y, width: W - 160, height: ENTRY_H },
      background: n % 2 === 1 ? '#f3f4f6' : '#ffffff',
      borderRadius: 8,
      padding: 0,
    }),
    createImageNode({
      id: `${cId}-thumb`,
      parentId: cId,
      rect: { x: 0, y: 0, width: 160, height: ENTRY_H },
      src: `/images/placeholder-archive-${n}.jpg`,
      alt: `${a.title} 썸네일`,
      style: { borderRadius: 0 },
    }),
    heading(`${cId}-title`, { x: 180, y: 16, width: 500, height: 30 }, a.title, 3, '#123b63', 'left', cId),
    createTextNode({
      id: `${cId}-meta`,
      parentId: cId,
      rect: { x: 180, y: 52, width: 300, height: 20 },
      text: `${a.date} · ${a.cat}`,
      fontSize: 13,
      color: '#6b7280',
    }),
    createTextNode({
      id: `${cId}-excerpt`,
      parentId: cId,
      rect: { x: 180, y: 80, width: 700, height: 28 },
      text: '흥미로운 이야기와 실용적인 정보를 제공하는 기사입니다. 더 알아보세요.',
      fontSize: 14,
      color: '#1f2937',
    }),
  ];
}

const nodes: BuilderCanvasNode[] = assignCanvasNodeZIndices([
  createContainerNode({
    id: 'tpl-blogarc-header',
    rect: { x: 0, y: 0, width: W, height: HEADER_H },
    background: '#123b63',
    borderRadius: 0,
  }),
  heading(
    'tpl-blogarc-title',
    { x: 80, y: 35, width: 400, height: 50 },
    '전체 아카이브',
    1,
    '#ffffff',
    'left',
    'tpl-blogarc-header',
  ),

  ...archiveEntry(1),
  ...archiveEntry(2),
  ...archiveEntry(3),
  ...archiveEntry(4),
  ...archiveEntry(5),
  ...archiveEntry(6),
  ...archiveEntry(7),
  ...archiveEntry(8),
  /* ── Wix-grade expansion scaffold ───────────────────────────────────── */
  createContainerNode({
    id: 'tpl-blogarchive-wix-proof',
    rect: { x: 64, y: STAGE_H + 40, width: 1152, height: 520 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-text',
  }),
  createContainerNode({
    id: 'tpl-blogarchive-wix-showcase',
    rect: { x: 64, y: STAGE_H + 620, width: 1152, height: 560 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'office-card',
  }),
  createContainerNode({
    id: 'tpl-blogarchive-wix-cta',
    rect: { x: 64, y: STAGE_H + 1240, width: 1152, height: 600 },
    background: '#123b63',
    borderColor: '#123b63',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-proof-label',
    parentId: 'tpl-blogarchive-wix-proof',
    rect: { x: 56, y: 48, width: 260, height: 28 },
    text: 'Wix-grade proof system',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-proof-title',
    parentId: 'tpl-blogarchive-wix-proof',
    rect: { x: 56, y: 92, width: 560, height: 82 },
    text: 'blog archive 페이지의 핵심 신뢰 요소를 한눈에 보여줍니다',
    fontSize: 36,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.16,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-proof-copy',
    parentId: 'tpl-blogarchive-wix-proof',
    rect: { x: 56, y: 190, width: 540, height: 64 },
    text: '서비스 가치, 성과 지표, 다음 행동을 분리해 방문자가 빠르게 판단할 수 있는 풍부한 페이지 흐름을 만듭니다.',
    fontSize: 17,
    color: '#475569',
    lineHeight: 1.55,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-blogarchive-wix-metric-1',
    parentId: 'tpl-blogarchive-wix-proof',
    rect: { x: 56, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-metric-1-value',
    parentId: 'tpl-blogarchive-wix-metric-1',
    rect: { x: 22, y: 22, width: 120, height: 42 },
    text: '4.9',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-metric-1-label',
    parentId: 'tpl-blogarchive-wix-metric-1',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '고객 평가와 재방문 신뢰 지표',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarchive-wix-metric-2',
    parentId: 'tpl-blogarchive-wix-proof',
    rect: { x: 310, y: 310, width: 230, height: 130 },
    background: '#ffffff',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-metric-2-value',
    parentId: 'tpl-blogarchive-wix-metric-2',
    rect: { x: 22, y: 22, width: 140, height: 42 },
    text: '24h',
    fontSize: 34,
    color: '#1e5a96',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-metric-2-label',
    parentId: 'tpl-blogarchive-wix-metric-2',
    rect: { x: 22, y: 76, width: 168, height: 38 },
    text: '초기 문의와 예약 흐름을 빠르게 연결',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarchive-wix-metric-3',
    parentId: 'tpl-blogarchive-wix-proof',
    rect: { x: 650, y: 70, width: 210, height: 150 },
    background: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-metric-3-value',
    parentId: 'tpl-blogarchive-wix-metric-3',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '6+',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-metric-3-label',
    parentId: 'tpl-blogarchive-wix-metric-3',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: '섹션 단위 정보 구조로 풍부도 강화',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarchive-wix-metric-4',
    parentId: 'tpl-blogarchive-wix-proof',
    rect: { x: 884, y: 70, width: 210, height: 150 },
    background: '#fff7ed',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderRadius: 22,
    padding: 0,
    className: 'stat-card',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-metric-4-value',
    parentId: 'tpl-blogarchive-wix-metric-4',
    rect: { x: 24, y: 28, width: 140, height: 42 },
    text: '3x',
    fontSize: 34,
    color: '#e8a838',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-metric-4-label',
    parentId: 'tpl-blogarchive-wix-metric-4',
    rect: { x: 24, y: 82, width: 150, height: 42 },
    text: 'CTA, proof, showcase 접점을 반복 배치',
    fontSize: 14,
    color: '#475569',
    lineHeight: 1.35,
    className: 'card-copy',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-showcase-label',
    parentId: 'tpl-blogarchive-wix-showcase',
    rect: { x: 56, y: 48, width: 240, height: 28 },
    text: 'Showcase module',
    fontSize: 13,
    color: '#1e5a96',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    className: 'section-label',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-showcase-title',
    parentId: 'tpl-blogarchive-wix-showcase',
    rect: { x: 56, y: 88, width: 540, height: 78 },
    text: '카드, 사례, 단계 설명을 한 섹션 안에서 비교합니다',
    fontSize: 34,
    color: '#123b63',
    fontWeight: 'bold',
    lineHeight: 1.18,
    className: 'hero-title',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-showcase-copy',
    parentId: 'tpl-blogarchive-wix-showcase',
    rect: { x: 56, y: 178, width: 520, height: 58 },
    text: '기존 짧은 페이지에 비교 가능한 카드와 설명을 더해 방문자의 탐색 깊이를 높입니다.',
    fontSize: 16,
    color: '#475569',
    lineHeight: 1.5,
    className: 'hero-subtitle',
  }),
  createContainerNode({
    id: 'tpl-blogarchive-wix-showcase-visual',
    parentId: 'tpl-blogarchive-wix-showcase',
    rect: { x: 640, y: 54, width: 430, height: 208 },
    background: '#e0f2fe',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderRadius: 24,
    padding: 0,
    className: 'split-image',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-showcase-visual-title',
    parentId: 'tpl-blogarchive-wix-showcase-visual',
    rect: { x: 32, y: 36, width: 300, height: 40 },
    text: 'Visual proof area',
    fontSize: 24,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-showcase-visual-copy',
    parentId: 'tpl-blogarchive-wix-showcase-visual',
    rect: { x: 32, y: 94, width: 330, height: 54 },
    text: '이미지나 사례 카드가 들어갈 수 있는 큰 시각 영역을 확보합니다.',
    fontSize: 15,
    color: '#475569',
    lineHeight: 1.42,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarchive-wix-showcase-card-1',
    parentId: 'tpl-blogarchive-wix-showcase',
    rect: { x: 56, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-showcase-card-1-title',
    parentId: 'tpl-blogarchive-wix-showcase-card-1',
    rect: { x: 24, y: 26, width: 250, height: 34 },
    text: '핵심 가치',
    fontSize: 22,
    color: '#123b63',
    fontWeight: 'bold',
    className: 'card-title',
  }),
  createTextNode({
    id: 'tpl-blogarchive-wix-showcase-card-1-copy',
    parentId: 'tpl-blogarchive-wix-showcase-card-1',
    rect: { x: 24, y: 78, width: 250, height: 60 },
    text: '첫 방문자가 바로 이해할 수 있는 대표 메시지를 카드로 고정합니다.',
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.45,
    className: 'card-copy',
  }),
  createContainerNode({
    id: 'tpl-blogarchive-wix-showcase-card-2',
    parentId: 'tpl-blogarchive-wix-showcase',
    rect: { x: 416, y: 310, width: 320, height: 170 },
    background: '#f8fafc',
    borderColor: '#dbe4ee',
    borderWidth: 1,
    borderRadius: 18,
    padding: 0,
    className: 'services-detail-card',
  }),
]);

export const blogArchiveTemplate: PageTemplate = {
  id: 'blog-archive',
  name: '블로그 아카이브',
  category: 'blog',
  subcategory: 'archive',
  description: '전체 아카이브, 8개 기사 카드 시간순 배열',
  document: {
    version: 1,
    locale: 'ko',
    updatedAt: '2026-04-15T00:00:00+09:00',
    updatedBy: 'template-system',
    stageWidth: W,
    stageHeight: STAGE_H + 1960,
    nodes,
  },
};
