import type { RepeaterLoadingDocument } from './repeater-canvas-loading-document';

const baseStyle = {
  backgroundColor: 'transparent',
  borderColor: '#cbd5e1',
  borderStyle: 'solid',
  borderWidth: 0,
  borderRadius: 0,
  shadowX: 0,
  shadowY: 0,
  shadowBlur: 0,
  shadowSpread: 0,
  shadowColor: 'rgba(15, 23, 42, 0.16)',
  opacity: 100,
} as const;

export function makeRepeaterFieldChipDocument(token: string): RepeaterLoadingDocument {
  const rootId = `repeater-chip-root-${token}`;
  const repeaterId = `repeater-chip-${token}`;
  const targetId = 'home.insights.feed';
  return {
    version: 1,
    locale: 'ko',
    updatedAt: new Date().toISOString(),
    updatedBy: `repeater-chip-${token}`,
    stageWidth: 1280,
    stageHeight: 720,
    nodes: [
      {
        id: rootId,
        kind: 'container',
        rect: { x: 0, y: 0, width: 1280, height: 720 },
        style: baseStyle,
        zIndex: 1,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          label: 'Root',
          background: '#f8fafc',
          borderColor: '#e5e7eb',
          borderStyle: 'solid',
          borderWidth: 0,
          borderRadius: 0,
          padding: 56,
          layoutMode: 'absolute',
        },
      },
      {
        id: repeaterId,
        kind: 'container',
        parentId: rootId,
        rect: { x: 72, y: 84, width: 760, height: 360 },
        style: baseStyle,
        zIndex: 2,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          label: 'Field chip repeater',
          background: '#ffffff',
          borderColor: '#e2e8f0',
          borderStyle: 'solid',
          borderWidth: 1,
          borderRadius: 18,
          padding: 20,
          layoutMode: 'repeater',
        },
        dataBinding: {
          targetId,
          recordIndex: 0,
          fields: { title: 'title' },
        },
      },
      {
        id: `repeater-chip-image-${token}`,
        kind: 'image',
        parentId: repeaterId,
        rect: { x: 0, y: 0, width: 220, height: 124 },
        style: { ...baseStyle, borderRadius: 12 },
        zIndex: 3,
        rotation: 0,
        locked: true,
        visible: true,
        content: {
          src: '/images/placeholder-image.svg',
          alt: 'Template image',
          fit: 'cover',
          link: null,
        },
        dataBinding: {
          targetId,
          recordIndex: 0,
          fields: { src: 'featuredImage', alt: 'title' },
        },
      },
      {
        id: `repeater-chip-title-${token}`,
        kind: 'text',
        parentId: repeaterId,
        rect: { x: 0, y: 142, width: 220, height: 70 },
        style: baseStyle,
        zIndex: 4,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          text: 'Template title',
          fontSize: 18,
          color: '#0f172a',
          fontWeight: 'bold',
          align: 'left',
          lineHeight: 1.25,
          letterSpacing: 0,
        },
        dataBinding: {
          targetId,
          recordIndex: 0,
          fields: { text: 'title' },
        },
      },
      {
        id: `repeater-chip-button-${token}`,
        kind: 'button',
        parentId: repeaterId,
        rect: { x: 0, y: 230, width: 148, height: 44 },
        style: { ...baseStyle, borderRadius: 999 },
        zIndex: 5,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          label: 'Template link',
          href: '',
          style: 'primary-solid',
          link: null,
        },
        dataBinding: {
          targetId,
          recordIndex: 0,
          fields: { label: 'readTime', href: 'href' },
        },
      },
    ],
  };
}
