import type { RepeaterLoadingDocument } from './repeater-canvas-loading-document';

const baseStyle = {
  backgroundColor: 'transparent',
  borderColor: '#cbd5e1',
  borderStyle: 'solid',
  borderWidth: 0,
  borderRadius: 0,
  shadowX: 0,
  shadowY: 0,
  shadowBlur: 0,
  shadowSpread: 0,
  shadowColor: 'rgba(15, 23, 42, 0.16)',
  opacity: 100,
} as const;

export function makeRepeaterFieldChipRebindDocument(token: string): RepeaterLoadingDocument {
  const rootId = `repeater-rebind-root-${token}`;
  const sourceRepeaterId = `repeater-rebind-source-${token}`;
  const targetRepeaterId = `repeater-rebind-target-${token}`;
  const sourceTargetId = 'home.insights.feed';
  const targetTargetId = 'home.services.list';
  return {
    version: 1,
    locale: 'ko',
    updatedAt: new Date().toISOString(),
    updatedBy: `repeater-rebind-${token}`,
    stageWidth: 1280,
    stageHeight: 720,
    nodes: [
      {
        id: rootId,
        kind: 'container',
        rect: { x: 0, y: 0, width: 1280, height: 720 },
        style: baseStyle,
        zIndex: 1,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          label: 'Root',
          background: '#f8fafc',
          borderColor: '#e5e7eb',
          borderStyle: 'solid',
          borderWidth: 0,
          borderRadius: 0,
          padding: 56,
          layoutMode: 'absolute',
        },
      },
      {
        id: sourceRepeaterId,
        kind: 'container',
        parentId: rootId,
        rect: { x: 72, y: 84, width: 500, height: 360 },
        style: baseStyle,
        zIndex: 2,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          label: 'Source insights repeater',
          background: '#ffffff',
          borderColor: '#e2e8f0',
          borderStyle: 'solid',
          borderWidth: 1,
          borderRadius: 18,
          padding: 20,
          layoutMode: 'repeater',
        },
        dataBinding: {
          targetId: sourceTargetId,
          recordIndex: 0,
          fields: { title: 'title' },
        },
      },
      {
        id: `repeater-rebind-source-title-${token}`,
        kind: 'text',
        parentId: sourceRepeaterId,
        rect: { x: 0, y: 142, width: 220, height: 70 },
        style: baseStyle,
        zIndex: 3,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          text: 'Source template title',
          fontSize: 18,
          color: '#0f172a',
          fontWeight: 'bold',
          align: 'left',
          lineHeight: 1.25,
          letterSpacing: 0,
        },
        dataBinding: {
          targetId: sourceTargetId,
          recordIndex: 0,
          fields: { text: 'title' },
        },
      },
      {
        id: `repeater-rebind-source-button-${token}`,
        kind: 'button',
        parentId: sourceRepeaterId,
        rect: { x: 0, y: 230, width: 148, height: 44 },
        style: { ...baseStyle, borderRadius: 999 },
        zIndex: 4,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          label: 'Source template link',
          href: '',
          style: 'primary-solid',
          link: null,
        },
        dataBinding: {
          targetId: sourceTargetId,
          recordIndex: 0,
          fields: { label: 'readTime', href: 'href' },
        },
      },
      {
        id: targetRepeaterId,
        kind: 'container',
        parentId: rootId,
        rect: { x: 656, y: 84, width: 500, height: 360 },
        style: baseStyle,
        zIndex: 5,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          label: 'Target services repeater',
          background: '#ffffff',
          borderColor: '#bfdbfe',
          borderStyle: 'solid',
          borderWidth: 1,
          borderRadius: 18,
          padding: 20,
          layoutMode: 'repeater',
        },
        dataBinding: {
          targetId: targetTargetId,
          recordIndex: 0,
          fields: { title: 'title' },
        },
      },
      {
        id: `repeater-rebind-target-title-${token}`,
        kind: 'text',
        parentId: targetRepeaterId,
        rect: { x: 0, y: 0, width: 220, height: 64 },
        style: baseStyle,
        zIndex: 6,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          text: 'Target service title',
          fontSize: 18,
          color: '#0f172a',
          fontWeight: 'bold',
          align: 'left',
          lineHeight: 1.25,
          letterSpacing: 0,
        },
        dataBinding: {
          targetId: targetTargetId,
          recordIndex: 0,
          fields: { text: 'title' },
        },
      },
    ],
  };
}
