import {
  createDefaultCanvasNodeStyle,
  type BuilderCanvasNode,
  type BuilderCanvasNodeStyle,
} from '@/lib/builder/canvas/types';
import { richTextFromPlainText } from '@/lib/builder/rich-text/sanitize';
import { normalizeSavedSectionSnapshot } from '@/lib/builder/sections/normalize';

export const BUILT_IN_SECTION_CATEGORIES = [
  'hero',
  'features',
  'testimonials',
  'cta',
  'footer',
  'legal',
  'stats',
  'pricing',
  'team',
  'gallery',
  'faq',
  'services',
  'contact',
] as const;

export type BuiltInSectionCategory = (typeof BUILT_IN_SECTION_CATEGORIES)[number];

export interface BuiltInSectionTemplate {
  id: string;
  name: string;
  category: BuiltInSectionCategory;
  description?: string;
  thumbnailHint?: string;
  nodes: BuilderCanvasNode[];
  rootNodeId: string;
}

type CanvasRect = BuilderCanvasNode['rect'];
type ContainerContent = Extract<BuilderCanvasNode, { kind: 'container' }>['content'];

interface TemplateDraft {
  id: string;
  name: string;
  category: BuiltInSectionCategory;
  description: string;
  thumbnailHint?: string;
  width: number;
  height: number;
  rootStyle?: Partial<BuilderCanvasNodeStyle>;
  rootContent?: Partial<ContainerContent>;
  children: (rootNodeId: string) => BuilderCanvasNode[];
}

function createBaseNode(
  id: string,
  parentId: string | undefined,
  rect: CanvasRect,
  zIndex: number,
  style: Partial<BuilderCanvasNodeStyle> = {},
) {
  return {
    id,
    parentId,
    rect,
    style: createDefaultCanvasNodeStyle(style),
    zIndex,
    rotation: 0,
    locked: false,
    visible: true,
  };
}

function containerNode({
  id,
  parentId,
  rect,
  zIndex,
  label,
  style,
  content,
}: {
  id: string;
  parentId?: string;
  rect: CanvasRect;
  zIndex: number;
  label: string;
  style?: Partial<BuilderCanvasNodeStyle>;
  content?: Partial<ContainerContent>;
}): BuilderCanvasNode {
  const background = typeof style?.backgroundColor === 'string'
    ? style.backgroundColor
    : '#ffffff';
  const borderColor = typeof style?.borderColor === 'string'
    ? style.borderColor
    : '#e2e8f0';

  return {
    ...createBaseNode(id, parentId, rect, zIndex, style),
    kind: 'container',
    content: {
      label,
      background,
      borderColor,
      borderStyle: style?.borderStyle ?? 'solid',
      borderWidth: style?.borderWidth ?? 0,
      borderRadius: Math.min(style?.borderRadius ?? 10, 48),
      padding: 0,
      layoutMode: 'absolute',
      variant: 'flat',
      ...content,
    },
  } as BuilderCanvasNode;
}

function headingNode({
  id,
  parentId,
  rect,
  zIndex,
  text,
  level = 2,
  color = '#0f172a',
  align = 'left',
  fontSize = 42,
  fontWeight = 'bold',
  lineHeight = 1.1,
  className,
}: {
  id: string;
  parentId: string;
  rect: CanvasRect;
  zIndex: number;
  text: string;
  level?: 1 | 2 | 3 | 4 | 5 | 6;
  color?: string;
  align?: 'left' | 'center' | 'right';
  fontSize?: number;
  fontWeight?: 'regular' | 'medium' | 'bold';
  lineHeight?: number;
  className?: string;
}): BuilderCanvasNode {
  return {
    ...createBaseNode(id, parentId, rect, zIndex),
    kind: 'heading',
    content: {
      text,
      richText: richTextFromPlainText(text),
      level,
      color,
      align,
      fontFamily: 'system-ui',
      fontSize,
      fontWeight,
      lineHeight,
      letterSpacing: 0,
      className,
    },
  } as BuilderCanvasNode;
}

function textNode({
  id,
  parentId,
  rect,
  zIndex,
  text,
  fontSize = 16,
  color = '#475569',
  fontWeight = 'regular',
  align = 'left',
  lineHeight = 1.45,
  as = 'p',
  style,
  className,
  textTransform = 'none',
}: {
  id: string;
  parentId: string;
  rect: CanvasRect;
  zIndex: number;
  text: string;
  fontSize?: number;
  color?: string;
  fontWeight?: 'regular' | 'medium' | 'bold';
  align?: 'left' | 'center' | 'right';
  lineHeight?: number;
  as?: 'div' | 'span' | 'p' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'time';
  style?: Partial<BuilderCanvasNodeStyle>;
  className?: string;
  textTransform?: 'none' | 'uppercase' | 'lowercase' | 'capitalize';
}): BuilderCanvasNode {
  return {
    ...createBaseNode(id, parentId, rect, zIndex, style),
    kind: 'text',
    content: {
      text,
      richText: richTextFromPlainText(text),
      fontSize,
      color,
      fontWeight,
      align,
      lineHeight,
      letterSpacing: 0,
      fontFamily: 'system-ui',
      verticalAlign: 'top',
      textTransform,
      as,
      className,
    },
  } as BuilderCanvasNode;
}

function buttonNode({
  id,
  parentId,
  rect,
  zIndex,
  label,
  href = '#contact',
  buttonStyle = 'primary-solid',
  style,
  className,
}: {
  id: string;
  parentId: string;
  rect: CanvasRect;
  zIndex: number;
  label: string;
  href?: string;
  buttonStyle?: Extract<BuilderCanvasNode, { kind: 'button' }>['content']['style'];
  style?: Partial<BuilderCanvasNodeStyle>;
  className?: string;
}): BuilderCanvasNode {
  return {
    ...createBaseNode(id, parentId, rect, zIndex, {
      borderRadius: 999,
      shadowY: 10,
      shadowBlur: 22,
      shadowColor: 'rgba(15, 23, 42, 0.14)',
      ...style,
    }),
    kind: 'button',
    content: {
      label,
      href,
      style: buttonStyle,
      className,
    },
  } as BuilderCanvasNode;
}

function imageNode({
  id,
  parentId,
  rect,
  zIndex,
  src,
  alt,
  style,
}: {
  id: string;
  parentId: string;
  rect: CanvasRect;
  zIndex: number;
  src: string;
  alt: string;
  style?: Partial<BuilderCanvasNodeStyle>;
}): BuilderCanvasNode {
  return {
    ...createBaseNode(id, parentId, rect, zIndex, {
      borderRadius: 18,
      ...style,
    }),
    kind: 'image',
    content: {
      src,
      alt,
      fit: 'cover',
    },
  } as BuilderCanvasNode;
}

function defineTemplate(draft: TemplateDraft): BuiltInSectionTemplate {
  const rootNodeId = `${draft.id}-root`;
  const root = containerNode({
    id: rootNodeId,
    rect: { x: 0, y: 0, width: draft.width, height: draft.height },
    zIndex: 0,
    label: draft.name,
    style: {
      backgroundColor: '#ffffff',
      borderColor: '#e2e8f0',
      borderWidth: 1,
      borderRadius: 24,
      shadowY: 16,
      shadowBlur: 36,
      shadowColor: 'rgba(15, 23, 42, 0.08)',
      ...draft.rootStyle,
    },
    content: {
      as: draft.category === 'footer' ? 'footer' : 'section',
      ...draft.rootContent,
    },
  });
  const nodes = normalizeSavedSectionSnapshot([root, ...draft.children(rootNodeId)], rootNodeId);

  return {
    id: draft.id,
    name: draft.name,
    category: draft.category,
    description: draft.description,
    thumbnailHint: draft.thumbnailHint,
    nodes,
    rootNodeId,
  };
}

function featureCard(
  id: string,
  parentId: string,
  x: number,
  y: number,
  title: string,
  body: string,
  zIndex: number,
): BuilderCanvasNode[] {
  const cardId = `${id}-card`;
  return [
    containerNode({
      id: cardId,
      parentId,
      rect: { x, y, width: 315, height: 150 },
      zIndex,
      label: title,
      style: {
        backgroundColor: '#ffffff',
        borderColor: '#dbe4ee',
        borderWidth: 1,
        borderRadius: 18,
        shadowY: 10,
        shadowBlur: 24,
        shadowColor: 'rgba(15, 23, 42, 0.07)',
      },
    }),
    textNode({
      id: `${id}-index`,
      parentId: cardId,
      rect: { x: 22, y: 18, width: 48, height: 28 },
      zIndex: zIndex + 1,
      text: id.slice(-2).toUpperCase(),
      fontSize: 13,
      color: '#0f766e',
      fontWeight: 'bold',
    }),
    headingNode({
      id: `${id}-title`,
      parentId: cardId,
      rect: { x: 22, y: 48, width: 255, height: 38 },
      zIndex: zIndex + 2,
      text: title,
      level: 3,
      fontSize: 22,
      lineHeight: 1.15,
    }),
    textNode({
      id: `${id}-body`,
      parentId: cardId,
      rect: { x: 22, y: 90, width: 260, height: 44 },
      zIndex: zIndex + 3,
      text: body,
      fontSize: 14,
      color: '#64748b',
    }),
  ];
}

function quoteCard(
  id: string,
  parentId: string,
  x: number,
  y: number,
  quote: string,
  name: string,
  zIndex: number,
): BuilderCanvasNode[] {
  const cardId = `${id}-card`;
  return [
    containerNode({
      id: cardId,
      parentId,
      rect: { x, y, width: 315, height: 170 },
      zIndex,
      label: name,
      style: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
        borderWidth: 1,
        borderRadius: 18,
        shadowY: 10,
        shadowBlur: 24,
        shadowColor: 'rgba(15, 23, 42, 0.08)',
      },
    }),
    textNode({
      id: `${id}-quote`,
      parentId: cardId,
      rect: { x: 24, y: 24, width: 260, height: 82 },
      zIndex: zIndex + 1,
      text: quote,
      fontSize: 16,
      color: '#334155',
      fontWeight: 'medium',
      lineHeight: 1.42,
    }),
    textNode({
      id: `${id}-name`,
      parentId: cardId,
      rect: { x: 24, y: 122, width: 250, height: 28 },
      zIndex: zIndex + 2,
      text: name,
      fontSize: 14,
      color: '#0f172a',
      fontWeight: 'bold',
    }),
  ];
}

interface ExpandedSectionSpec {
  id: string;
  name: string;
  category: BuiltInSectionCategory;
  description: string;
  thumbnailHint: string;
  eyebrow: string;
  title: string;
  copy: string;
  ctaLabel: string;
  accent: string;
  background: string;
  cardTint: string;
  dark?: boolean;
  cards: [string, string, string][];
}

function expandedCard(
  id: string,
  parentId: string,
  x: number,
  title: string,
  body: string,
  label: string,
  accent: string,
  tint: string,
  zIndex: number,
): BuilderCanvasNode[] {
  const cardId = `${id}-card`;
  return [
    containerNode({
      id: cardId,
      parentId,
      rect: { x, y: 250, width: 300, height: 170 },
      zIndex,
      label: title,
      style: {
        backgroundColor: tint,
        borderColor: '#dbe4ee',
        borderWidth: 1,
        borderRadius: 20,
        shadowY: 12,
        shadowBlur: 28,
        shadowColor: 'rgba(15, 23, 42, 0.08)',
      },
      content: { className: 'services-detail-card' },
    }),
    textNode({
      id: `${id}-label`,
      parentId: cardId,
      rect: { x: 24, y: 20, width: 84, height: 26 },
      zIndex: zIndex + 1,
      text: label,
      fontSize: 12,
      color: accent,
      fontWeight: 'bold',
      className: 'section-label',
    }),
    headingNode({
      id: `${id}-title`,
      parentId: cardId,
      rect: { x: 24, y: 54, width: 240, height: 42 },
      zIndex: zIndex + 2,
      text: title,
      level: 3,
      fontSize: 22,
      lineHeight: 1.12,
      className: 'card-title',
    }),
    textNode({
      id: `${id}-body`,
      parentId: cardId,
      rect: { x: 24, y: 106, width: 245, height: 48 },
      zIndex: zIndex + 3,
      text: body,
      fontSize: 14,
      color: '#64748b',
      className: 'card-copy',
    }),
  ];
}

function defineExpandedTemplate(spec: ExpandedSectionSpec): BuiltInSectionTemplate {
  return defineTemplate({
    id: spec.id,
    name: spec.name,
    category: spec.category,
    description: spec.description,
    thumbnailHint: spec.thumbnailHint,
    width: 1120,
    height: 500,
    rootStyle: {
      backgroundColor: spec.background,
      borderColor: spec.dark ? '#1e293b' : '#dbe4ee',
      borderRadius: 24,
      shadowY: 18,
      shadowBlur: 42,
      shadowColor: spec.dark ? 'rgba(0, 0, 0, 0.28)' : 'rgba(15, 23, 42, 0.10)',
    },
    children: (rootId) => [
      containerNode({
        id: `${spec.id}-accent-block`,
        parentId: rootId,
        rect: { x: 782, y: 52, width: 250, height: 150 },
        zIndex: 1,
        label: 'Visual accent',
        style: {
          backgroundColor: spec.cardTint,
          borderColor: spec.dark ? '#334155' : '#cbd5e1',
          borderWidth: 1,
          borderRadius: 28,
          shadowY: 18,
          shadowBlur: 40,
          shadowColor: 'rgba(15, 23, 42, 0.12)',
        },
        content: { className: 'split-image' },
      }),
      containerNode({
        id: `${spec.id}-accent-dot-a`,
        parentId: rootId,
        rect: { x: 968, y: 36, width: 70, height: 70 },
        zIndex: 2,
        label: 'Accent dot',
        style: {
          backgroundColor: spec.accent,
          borderColor: spec.accent,
          borderRadius: 9999,
          opacity: 86,
        },
      }),
      containerNode({
        id: `${spec.id}-accent-dot-b`,
        parentId: rootId,
        rect: { x: 740, y: 160, width: 92, height: 92 },
        zIndex: 3,
        label: 'Accent ring',
        style: {
          backgroundColor: '#ffffff',
          borderColor: spec.accent,
          borderWidth: 2,
          borderRadius: 9999,
          opacity: spec.dark ? 34 : 74,
        },
      }),
      textNode({
        id: `${spec.id}-eyebrow`,
        parentId: rootId,
        rect: { x: 70, y: 58, width: 430, height: 28 },
        zIndex: 4,
        text: spec.eyebrow,
        fontSize: 13,
        color: spec.accent,
        fontWeight: 'bold',
        textTransform: 'uppercase',
        className: 'hero-eyebrow',
      }),
      headingNode({
        id: `${spec.id}-title`,
        parentId: rootId,
        rect: { x: 70, y: 98, width: 620, height: 96 },
        zIndex: 5,
        text: spec.title,
        level: 2,
        color: spec.dark ? '#ffffff' : '#0f172a',
        fontSize: 38,
        lineHeight: 1.12,
        className: 'hero-title',
      }),
      textNode({
        id: `${spec.id}-copy`,
        parentId: rootId,
        rect: { x: 70, y: 206, width: 590, height: 58 },
        zIndex: 6,
        text: spec.copy,
        fontSize: 16,
        color: spec.dark ? '#cbd5e1' : '#475569',
        lineHeight: 1.45,
        className: 'hero-subtitle',
      }),
      buttonNode({
        id: `${spec.id}-primary`,
        parentId: rootId,
        rect: { x: 70, y: 404, width: 176, height: 52 },
        zIndex: 19,
        label: spec.ctaLabel,
        className: 'hero-cta',
      }),
      textNode({
        id: `${spec.id}-note`,
        parentId: rootId,
        rect: { x: 270, y: 416, width: 340, height: 28 },
        zIndex: 20,
        text: 'Built for fast composition and reusable page sections',
        fontSize: 13,
        color: spec.dark ? '#94a3b8' : '#64748b',
      }),
      ...spec.cards.flatMap(([title, body, label], index) => (
        expandedCard(
          `${spec.id}-${index + 1}`,
          rootId,
          70 + index * 330,
          title,
          body,
          label,
          spec.accent,
          spec.dark ? '#111827' : spec.cardTint,
          7 + index * 4,
        )
      )),
    ],
  });
}

const EXPANDED_SECTION_SPECS: ExpandedSectionSpec[] = [
  {
    id: 'hero-video-background',
    name: 'Video Background Hero',
    category: 'hero',
    description: '미디어 배경을 암시하는 대형 비주얼 히어로',
    thumbnailHint: 'VIDEO',
    eyebrow: 'Immersive opening',
    title: '첫 화면에서 브랜드 장면을 바로 보여줍니다',
    copy: '강한 메시지, 짧은 설명, 즉시 행동 버튼을 한 화면 안에 집중시키는 히어로입니다.',
    ctaLabel: '영상 보기',
    accent: '#2563eb',
    background: '#0f172a',
    cardTint: '#1e293b',
    dark: true,
    cards: [
      ['Full-bleed motion', '배경 영상이나 이미지 위에 메시지를 안정적으로 배치합니다.', '01'],
      ['Readable overlay', '어두운 톤과 대비를 확보해 긴 제목도 선명하게 보입니다.', '02'],
      ['Action first', 'CTA와 보조 설명을 가까이 두어 전환 흐름을 줄입니다.', '03'],
    ],
  },
  {
    id: 'hero-minimal-eyebrow',
    name: 'Minimal Eyebrow Hero',
    category: 'hero',
    description: '얇은 eyebrow와 넓은 여백 중심의 미니멀 히어로',
    thumbnailHint: 'MIN',
    eyebrow: 'Quiet launch',
    title: '단정한 여백으로 메시지의 무게를 높입니다',
    copy: '전문 서비스, 컨설팅, 법률 페이지처럼 신뢰가 중요한 랜딩에 맞는 절제된 구성입니다.',
    ctaLabel: '시작하기',
    accent: '#0f766e',
    background: '#ffffff',
    cardTint: '#f0fdfa',
    cards: [
      ['Precise hierarchy', 'eyebrow, title, copy의 거리와 크기를 명확히 나눕니다.', 'A'],
      ['Calm surface', '카드와 액센트가 배경을 과하게 흔들지 않습니다.', 'B'],
      ['Fast scan', '핵심 문장을 짧게 읽고 바로 다음 행동으로 이동합니다.', 'C'],
    ],
  },
  {
    id: 'hero-parallax-layers',
    name: 'Parallax Layer Hero',
    category: 'hero',
    description: '겹친 도형과 카드로 깊이를 만든 히어로',
    thumbnailHint: 'LAYER',
    eyebrow: 'Layered depth',
    title: '겹친 카드와 도형으로 제품의 깊이를 만듭니다',
    copy: 'SaaS, 스타트업, 앱 랜딩처럼 기능 이미지를 여러 층으로 보여줘야 할 때 사용합니다.',
    ctaLabel: '데모 보기',
    accent: '#7c3aed',
    background: '#f5f3ff',
    cardTint: '#ffffff',
    cards: [
      ['Product card', '주요 화면을 대표하는 카드를 앞쪽에 배치합니다.', 'I'],
      ['Proof layer', '수치와 로고를 보조 레이어로 분리합니다.', 'II'],
      ['Soft motion', 'heuristic entrance가 레이어별로 자연스럽게 적용됩니다.', 'III'],
    ],
  },
  {
    id: 'features-4-column',
    name: 'Four Column Features',
    category: 'features',
    description: '네 가지 강점을 촘촘하게 정리하는 feature band',
    thumbnailHint: '4COL',
    eyebrow: 'Feature grid',
    title: '핵심 기능을 빠르게 비교하도록 정리합니다',
    copy: '서비스 소개, 제품 기능, 프로그램 혜택을 네 개의 요약 카드로 구조화합니다.',
    ctaLabel: '기능 살펴보기',
    accent: '#1d4ed8',
    background: '#f8fafc',
    cardTint: '#ffffff',
    cards: [
      ['Plan', '초기 목표와 필요한 자료를 정렬합니다.', '01'],
      ['Build', '중요 항목을 카드 단위로 빠르게 구성합니다.', '02'],
      ['Launch', '완성된 섹션을 저장하고 재사용합니다.', '03'],
    ],
  },
  {
    id: 'features-alternating-rows',
    name: 'Alternating Feature Rows',
    category: 'features',
    description: '좌우 교차형 기능 설명 섹션',
    thumbnailHint: 'ROWS',
    eyebrow: 'Alternating story',
    title: '긴 설명을 지루하지 않게 단계별로 나눕니다',
    copy: '프로세스, 서비스 패키지, 교육 커리큘럼처럼 순서가 있는 콘텐츠에 맞습니다.',
    ctaLabel: '프로세스 보기',
    accent: '#be123c',
    background: '#fff1f2',
    cardTint: '#ffffff',
    cards: [
      ['Discover', '문제와 대상을 먼저 정의합니다.', 'STEP 1'],
      ['Design', '해결 방법과 전달 방식을 정리합니다.', 'STEP 2'],
      ['Deliver', '운영 가능한 결과물로 전환합니다.', 'STEP 3'],
    ],
  },
  {
    id: 'features-large-card',
    name: 'Large Feature Card',
    category: 'features',
    description: '하나의 대표 기능과 보조 기능을 함께 보여주는 카드',
    thumbnailHint: 'CARD',
    eyebrow: 'Feature spotlight',
    title: '대표 기능 하나를 크게 보여주고 주변 기능을 붙입니다',
    copy: '제품 상세 페이지나 서비스 소개 페이지에서 주력 기능을 강조하는 섹션입니다.',
    ctaLabel: '자세히 보기',
    accent: '#c2410c',
    background: '#fff7ed',
    cardTint: '#ffffff',
    cards: [
      ['Main benefit', '가장 중요한 성과를 큰 카드로 설명합니다.', 'MAIN'],
      ['Support A', '보조 기능을 짧은 근거로 연결합니다.', 'A'],
      ['Support B', '고객 관점의 사용 시나리오를 추가합니다.', 'B'],
    ],
  },
  {
    id: 'testimonials-single-spotlight',
    name: 'Single Spotlight Testimonial',
    category: 'testimonials',
    description: '하나의 큰 추천사를 중심으로 신뢰를 만드는 섹션',
    thumbnailHint: 'QUOTE',
    eyebrow: 'Customer proof',
    title: '한 명의 강한 추천사를 크게 보여줍니다',
    copy: '긴 인용문, 역할, 성과 지표를 함께 보여줘 신뢰 근거를 빠르게 전달합니다.',
    ctaLabel: '사례 보기',
    accent: '#0f766e',
    background: '#ecfdf5',
    cardTint: '#ffffff',
    cards: [
      ['Quote', '핵심 변화와 전환 전후를 한 문장으로 담습니다.', '“ ”'],
      ['Role', '발화자의 직책과 맥락을 명확히 표시합니다.', 'ID'],
      ['Outcome', '수치나 기간처럼 확인 가능한 성과를 붙입니다.', '+'],
    ],
  },
  {
    id: 'testimonials-video-story',
    name: 'Video Story Testimonial',
    category: 'testimonials',
    description: '영상 후기 카드와 요약 포인트를 결합',
    thumbnailHint: 'PLAY',
    eyebrow: 'Video proof',
    title: '영상 후기와 요약 포인트를 나란히 보여줍니다',
    copy: '인터뷰, 리뷰, 사례 발표를 소개할 때 영상 플레이스홀더와 핵심 문장을 결합합니다.',
    ctaLabel: '후기 재생',
    accent: '#db2777',
    background: '#fdf2f8',
    cardTint: '#ffffff',
    cards: [
      ['Watch', '영상 영역을 대표하는 플레이 카드로 시선을 모읍니다.', '▶'],
      ['Problem', '고객이 겪던 문제를 짧게 정리합니다.', '01'],
      ['Result', '해결 후 얻은 결과를 구체적으로 적습니다.', '02'],
    ],
  },
  {
    id: 'testimonials-logo-grid',
    name: 'Logo Trust Grid',
    category: 'testimonials',
    description: '고객사 로고와 짧은 신뢰 문구 조합',
    thumbnailHint: 'LOGOS',
    eyebrow: 'Trusted by teams',
    title: '로고 그리드와 신뢰 문장을 함께 배치합니다',
    copy: 'B2B, SaaS, 전문 서비스 페이지에서 고객사나 파트너를 정돈된 그리드로 보여줍니다.',
    ctaLabel: '파트너 보기',
    accent: '#334155',
    background: '#f8fafc',
    cardTint: '#ffffff',
    cards: [
      ['Enterprise', '대형 고객에게 맞는 안정성을 강조합니다.', 'A'],
      ['Startup', '빠른 실행과 실험을 지원한다는 인상을 줍니다.', 'B'],
      ['Public', '기관, 교육, 비영리 협업에도 맞게 확장됩니다.', 'C'],
    ],
  },
  {
    id: 'cta-gradient-band',
    name: 'Gradient CTA Band',
    category: 'cta',
    description: '그라디언트 느낌의 강한 전환 배너',
    thumbnailHint: 'GRAD',
    eyebrow: 'Ready next',
    title: '다음 행동을 한 문장으로 강하게 유도합니다',
    copy: '페이지 하단이나 긴 상세 페이지 중간에 넣기 좋은 고대비 CTA 밴드입니다.',
    ctaLabel: '문의 시작',
    accent: '#6366f1',
    background: '#eef2ff',
    cardTint: '#ffffff',
    cards: [
      ['One action', '사용자가 해야 할 다음 클릭을 하나로 줄입니다.', 'CTA'],
      ['Support copy', '행동 전 불안을 낮추는 짧은 문장을 둡니다.', 'WHY'],
      ['Visual cue', '도형과 카드가 버튼 쪽으로 시선을 유도합니다.', 'GO'],
    ],
  },
  {
    id: 'cta-dark-band',
    name: 'Dark CTA Band',
    category: 'cta',
    description: '어두운 배경과 밝은 버튼으로 만든 CTA',
    thumbnailHint: 'DARK',
    eyebrow: 'High contrast',
    title: '어두운 밴드로 페이지 흐름을 확실히 끊습니다',
    copy: '전환 전 마지막 설득 구간이나 premium 서비스 소개에 맞는 다크 CTA입니다.',
    ctaLabel: '예약하기',
    accent: '#f59e0b',
    background: '#0f172a',
    cardTint: '#1e293b',
    dark: true,
    cards: [
      ['Premium tone', '어두운 배경이 고가 서비스의 무게감을 만듭니다.', '01'],
      ['Clear CTA', '밝은 버튼으로 클릭 위치를 명확하게 표시합니다.', '02'],
      ['Short proof', '짧은 근거 카드가 마지막 이탈을 줄입니다.', '03'],
    ],
  },
  {
    id: 'cta-newsletter',
    name: 'Newsletter CTA',
    category: 'cta',
    description: '뉴스레터 구독 유도와 혜택 카드',
    thumbnailHint: 'MAIL',
    eyebrow: 'Stay updated',
    title: '구독 전환을 위한 짧고 명확한 CTA',
    copy: '매거진, 블로그, 교육 사이트에서 이메일 수집 전환을 부드럽게 유도합니다.',
    ctaLabel: '구독하기',
    accent: '#0891b2',
    background: '#ecfeff',
    cardTint: '#ffffff',
    cards: [
      ['Weekly', '정기 발송 주기와 기대 콘텐츠를 설명합니다.', 'W'],
      ['No spam', '불필요한 메일이 없다는 신뢰 문구를 둡니다.', '✓'],
      ['Best picks', '인기 글이나 자료를 큐레이션한다는 가치를 줍니다.', '*'],
    ],
  },
  {
    id: 'footer-newsletter-columns',
    name: 'Newsletter Footer Columns',
    category: 'footer',
    description: '푸터 링크와 뉴스레터를 함께 담은 다단 구성',
    thumbnailHint: 'FOOT',
    eyebrow: 'Footer system',
    title: '푸터에서도 전환과 탐색을 함께 제공합니다',
    copy: '브랜드 소개, 주요 링크, 연락처, 구독 CTA를 한 번에 정리하는 footer template입니다.',
    ctaLabel: '뉴스레터 신청',
    accent: '#38bdf8',
    background: '#0f172a',
    cardTint: '#111827',
    dark: true,
    cards: [
      ['Explore', '주요 페이지 링크를 그룹별로 묶습니다.', 'NAV'],
      ['Contact', '연락처와 운영 시간을 빠르게 확인합니다.', 'INFO'],
      ['Subscribe', '푸터에서도 장기 관계 전환을 만듭니다.', 'MAIL'],
    ],
  },
  {
    id: 'footer-contact-bar',
    name: 'Footer Contact Bar',
    category: 'footer',
    description: '짧은 연락처 바와 링크 묶음',
    thumbnailHint: 'BAR',
    eyebrow: 'Contact footer',
    title: '연락처와 기본 링크를 낮은 높이로 정리합니다',
    copy: '랜딩 페이지 끝에서 빠르게 연락처를 확인하고 다음 링크로 이동할 수 있는 footer입니다.',
    ctaLabel: '연락하기',
    accent: '#0f766e',
    background: '#f8fafc',
    cardTint: '#ffffff',
    cards: [
      ['Phone', '전화나 메신저 연락 수단을 노출합니다.', 'TEL'],
      ['Address', '오피스나 매장 위치를 짧게 표시합니다.', 'MAP'],
      ['Legal', '약관, 개인정보, 고지 링크를 정리합니다.', 'DOC'],
    ],
  },
  {
    id: 'legal-cookie-banner',
    name: 'Cookie Notice Banner',
    category: 'legal',
    description: '쿠키 안내와 설정 버튼을 포함한 legal notice',
    thumbnailHint: 'COOKIE',
    eyebrow: 'Privacy notice',
    title: '쿠키와 개인정보 안내를 명확하게 보여줍니다',
    copy: '하단 안내, 설정 버튼, 정책 링크를 함께 넣을 수 있는 법적 고지용 섹션입니다.',
    ctaLabel: '설정 보기',
    accent: '#475569',
    background: '#f8fafc',
    cardTint: '#ffffff',
    cards: [
      ['Essential', '필수 쿠키와 서비스 운영 목적을 설명합니다.', '01'],
      ['Analytics', '분석 목적과 선택 가능성을 구분합니다.', '02'],
      ['Policy', '상세 정책 링크로 사용자를 안내합니다.', '03'],
    ],
  },
  {
    id: 'stats-counter-row',
    name: 'Counter Row',
    category: 'stats',
    description: '네 개 지표를 가로로 보여주는 stats row',
    thumbnailHint: 'NUM',
    eyebrow: 'Metrics',
    title: '성과 지표를 한 줄로 선명하게 보여줍니다',
    copy: '서비스 신뢰도, 성장률, 프로젝트 수 같은 숫자 근거를 빠르게 전달합니다.',
    ctaLabel: '성과 보기',
    accent: '#2563eb',
    background: '#eff6ff',
    cardTint: '#ffffff',
    cards: [
      ['128+', '완료 프로젝트나 고객 수를 크게 보여줍니다.', 'TOTAL'],
      ['94%', '만족도나 재방문율을 근거로 제시합니다.', 'RATE'],
      ['24h', '응답 시간처럼 사용자가 체감할 숫자를 둡니다.', 'SLA'],
    ],
  },
  {
    id: 'stats-metric-grid',
    name: 'Metric Grid',
    category: 'stats',
    description: '카드형 지표 그리드',
    thumbnailHint: 'GRID',
    eyebrow: 'Metric cards',
    title: '각 지표의 의미를 카드별로 설명합니다',
    copy: '단순 숫자보다 맥락 설명이 필요한 서비스나 리포트 페이지에 맞습니다.',
    ctaLabel: '리포트 보기',
    accent: '#7c3aed',
    background: '#f5f3ff',
    cardTint: '#ffffff',
    cards: [
      ['Growth', '증가 추세와 전년 대비 변화를 함께 적습니다.', '+38%'],
      ['Coverage', '제공 범위나 지역 수를 직관적으로 보여줍니다.', '12'],
      ['Retention', '사용자 유지나 고객 관계를 수치로 설명합니다.', '89%'],
    ],
  },
  {
    id: 'stats-logo-strip',
    name: 'Logo Strip Stats',
    category: 'stats',
    description: '로고 스트립과 핵심 수치를 조합',
    thumbnailHint: 'LOGO',
    eyebrow: 'Trusted scale',
    title: '파트너 신뢰와 수치를 한 화면에 묶습니다',
    copy: 'B2B 랜딩에서 고객사 로고와 숫자 근거를 균형 있게 보여주는 섹션입니다.',
    ctaLabel: '고객 보기',
    accent: '#0f766e',
    background: '#ecfdf5',
    cardTint: '#ffffff',
    cards: [
      ['Partners', '주요 파트너군을 카드 형태로 암시합니다.', 'P'],
      ['Regions', '서비스 범위가 넓다는 인상을 줍니다.', 'R'],
      ['Cases', '실제 사례 수로 경험을 설명합니다.', 'C'],
    ],
  },
  {
    id: 'stats-award-badges',
    name: 'Award Badges',
    category: 'stats',
    description: '수상 배지와 인증 카드',
    thumbnailHint: 'AWARD',
    eyebrow: 'Awards',
    title: '수상, 인증, 평가 근거를 정돈합니다',
    copy: '교육, 의료, 전문 서비스에서 신뢰 배지를 섹션 단위로 보여주기 좋습니다.',
    ctaLabel: '인증 보기',
    accent: '#ca8a04',
    background: '#fefce8',
    cardTint: '#ffffff',
    cards: [
      ['Award', '대표 수상 이력을 간결하게 표시합니다.', '★'],
      ['Certified', '인증이나 심사 통과 여부를 보여줍니다.', '✓'],
      ['Rated', '평점이나 리뷰 수를 함께 제공합니다.', '5.0'],
    ],
  },
  {
    id: 'pricing-three-tier',
    name: 'Three Tier Pricing',
    category: 'pricing',
    description: '세 가지 요금제를 비교하는 pricing section',
    thumbnailHint: '$$$',
    eyebrow: 'Pricing',
    title: '세 가지 플랜을 한눈에 비교합니다',
    copy: 'SaaS, 교육, 멤버십 서비스의 가격 차이를 명확하게 설명하는 섹션입니다.',
    ctaLabel: '플랜 선택',
    accent: '#2563eb',
    background: '#f8fafc',
    cardTint: '#ffffff',
    cards: [
      ['Starter', '작게 시작하는 사용자를 위한 기본 플랜입니다.', '$'],
      ['Growth', '가장 많이 선택되는 중간 플랜을 강조합니다.', '$$'],
      ['Scale', '팀과 기업을 위한 고급 옵션을 설명합니다.', '$$$'],
    ],
  },
  {
    id: 'pricing-two-tier-comparison',
    name: 'Two Tier Comparison',
    category: 'pricing',
    description: '두 플랜을 크게 비교하는 pricing layout',
    thumbnailHint: '2UP',
    eyebrow: 'Compare',
    title: '두 가지 선택지를 명확하게 나눕니다',
    copy: '개인/팀, 기본/프리미엄처럼 결정 구조가 단순한 가격 페이지에 적합합니다.',
    ctaLabel: '비교하기',
    accent: '#9333ea',
    background: '#faf5ff',
    cardTint: '#ffffff',
    cards: [
      ['Solo', '개인 사용자에게 필요한 핵심 기능만 담습니다.', '1'],
      ['Team', '협업과 관리 기능을 포함한 선택지입니다.', '2'],
      ['Add-ons', '추가 서비스나 옵션을 별도로 안내합니다.', '+'],
    ],
  },
  {
    id: 'pricing-single-plan',
    name: 'Single Plan Spotlight',
    category: 'pricing',
    description: '단일 대표 상품을 크게 보여주는 pricing card',
    thumbnailHint: 'ONE',
    eyebrow: 'Best value',
    title: '하나의 대표 플랜에 집중합니다',
    copy: '코칭, 컨설팅, 이벤트처럼 단일 패키지를 판매하는 페이지에 맞는 구성입니다.',
    ctaLabel: '신청하기',
    accent: '#c2410c',
    background: '#fff7ed',
    cardTint: '#ffffff',
    cards: [
      ['Package', '포함 범위를 구체적으로 요약합니다.', 'PKG'],
      ['Timeline', '제공 기간과 진행 방식을 설명합니다.', 'TIME'],
      ['Guarantee', '환불, 보장, 후속 지원 같은 신뢰 요소를 둡니다.', 'SAFE'],
    ],
  },
  {
    id: 'pricing-table-summary',
    name: 'Pricing Table Summary',
    category: 'pricing',
    description: '테이블형 비교를 카드로 압축',
    thumbnailHint: 'TABLE',
    eyebrow: 'Plan matrix',
    title: '복잡한 비교표를 요약 카드로 단순화합니다',
    copy: '많은 기능 차이를 전부 쓰기 전, 상단에서 핵심 차이를 먼저 보여줍니다.',
    ctaLabel: '전체 비교',
    accent: '#0f766e',
    background: '#f0fdfa',
    cardTint: '#ffffff',
    cards: [
      ['Feature set', '기능 묶음을 큰 범주로 정리합니다.', 'F'],
      ['Usage', '사용량이나 좌석 수 제한을 보여줍니다.', 'U'],
      ['Support', '지원 수준의 차이를 직관적으로 설명합니다.', 'S'],
    ],
  },
  {
    id: 'team-grid-cards',
    name: 'Team Grid Cards',
    category: 'team',
    description: '팀 멤버를 카드 그리드로 소개',
    thumbnailHint: 'TEAM',
    eyebrow: 'Meet the team',
    title: '팀의 역할과 전문성을 카드로 보여줍니다',
    copy: '프로필, 역할, 담당 영역을 빠르게 훑을 수 있는 팀 소개 섹션입니다.',
    ctaLabel: '팀 보기',
    accent: '#2563eb',
    background: '#eff6ff',
    cardTint: '#ffffff',
    cards: [
      ['Lead', '대표나 리더의 전문 영역을 소개합니다.', 'L'],
      ['Ops', '운영 담당자가 제공하는 안정성을 설명합니다.', 'O'],
      ['Design', '창의적 역할과 결과물 관점을 보여줍니다.', 'D'],
    ],
  },
  {
    id: 'team-horizontal-row',
    name: 'Horizontal Team Row',
    category: 'team',
    description: '팀을 한 줄 프로필로 보여주는 섹션',
    thumbnailHint: 'ROW',
    eyebrow: 'Team lineup',
    title: '핵심 팀원을 한 줄로 빠르게 소개합니다',
    copy: '작은 조직이나 프로젝트 팀의 담당자를 간결하게 보여주는 프로필 row입니다.',
    ctaLabel: '소개 보기',
    accent: '#0f766e',
    background: '#ecfdf5',
    cardTint: '#ffffff',
    cards: [
      ['Strategy', '전략과 방향성을 책임지는 역할입니다.', '01'],
      ['Execution', '실행과 일정 관리를 맡는 역할입니다.', '02'],
      ['Support', '고객 지원과 후속 관리를 담당합니다.', '03'],
    ],
  },
  {
    id: 'team-featured-leader',
    name: 'Featured Leader',
    category: 'team',
    description: '대표 인물을 크게 강조하는 team section',
    thumbnailHint: 'LEAD',
    eyebrow: 'Featured expert',
    title: '대표 전문가를 크게 소개하고 팀을 보조로 붙입니다',
    copy: '법률, 의료, 컨설팅처럼 개인 신뢰가 중요한 페이지에서 사용합니다.',
    ctaLabel: '프로필 보기',
    accent: '#7c3aed',
    background: '#f5f3ff',
    cardTint: '#ffffff',
    cards: [
      ['Expertise', '주요 전문 분야를 짧게 나열합니다.', 'EXP'],
      ['Experience', '경력과 사례 기반 신뢰를 제공합니다.', 'YRS'],
      ['Team', '함께 일하는 팀의 보조 역량을 설명합니다.', 'T'],
    ],
  },
  {
    id: 'team-mosaic',
    name: 'Team Mosaic',
    category: 'team',
    description: '모자이크 카드로 다양한 팀 분위기를 표현',
    thumbnailHint: 'MOSAIC',
    eyebrow: 'People mosaic',
    title: '다양한 역할을 모자이크처럼 보여줍니다',
    copy: '크리에이티브 팀, 에이전시, 스타트업 소개에 어울리는 시각적 팀 섹션입니다.',
    ctaLabel: '함께하기',
    accent: '#db2777',
    background: '#fdf2f8',
    cardTint: '#ffffff',
    cards: [
      ['Creative', '시각, 콘텐츠, 브랜드 담당을 묶어 보여줍니다.', 'C'],
      ['Tech', '기술과 제품 구현 역량을 강조합니다.', 'T'],
      ['Growth', '마케팅과 운영 성과를 연결합니다.', 'G'],
    ],
  },
  {
    id: 'gallery-grid',
    name: 'Gallery Grid',
    category: 'gallery',
    description: '작품이나 현장을 그리드로 보여주는 gallery section',
    thumbnailHint: 'GRID',
    eyebrow: 'Visual gallery',
    title: '이미지 중심 콘텐츠를 정돈된 그리드로 보여줍니다',
    copy: '포트폴리오, 여행, 레스토랑, 웨딩 사이트에 넣기 좋은 이미지 갤러리입니다.',
    ctaLabel: '갤러리 보기',
    accent: '#2563eb',
    background: '#f8fafc',
    cardTint: '#ffffff',
    cards: [
      ['Grid A', '대표 이미지 한 장의 설명을 카드로 보조합니다.', '01'],
      ['Grid B', '두 번째 이미지 묶음의 분위기를 전달합니다.', '02'],
      ['Grid C', '세 번째 이미지와 CTA를 자연스럽게 연결합니다.', '03'],
    ],
  },
  {
    id: 'gallery-masonry',
    name: 'Masonry Gallery',
    category: 'gallery',
    description: '다양한 크기의 이미지 카드를 암시하는 masonry layout',
    thumbnailHint: 'MASON',
    eyebrow: 'Masonry',
    title: '서로 다른 비율의 이미지를 리듬 있게 배치합니다',
    copy: '사진, 매거진, 이벤트 페이지에서 이미지의 다양성을 살리는 갤러리입니다.',
    ctaLabel: '작품 보기',
    accent: '#be123c',
    background: '#fff1f2',
    cardTint: '#ffffff',
    cards: [
      ['Tall', '세로형 이미지를 위한 설명 카드입니다.', 'T'],
      ['Wide', '가로형 장면을 강조하는 영역입니다.', 'W'],
      ['Detail', '디테일 컷이나 후기 링크를 붙입니다.', 'D'],
    ],
  },
  {
    id: 'gallery-carousel-thumbs',
    name: 'Carousel Thumbnails',
    category: 'gallery',
    description: '대표 이미지와 하단 썸네일 흐름',
    thumbnailHint: 'SLIDE',
    eyebrow: 'Carousel',
    title: '대표 이미지와 썸네일 흐름을 함께 제공합니다',
    copy: '상품 상세, 숙소, 차량, 작품 페이지에서 여러 이미지를 순차 탐색하게 합니다.',
    ctaLabel: '슬라이드 보기',
    accent: '#0f766e',
    background: '#ecfdf5',
    cardTint: '#ffffff',
    cards: [
      ['Main frame', '가장 큰 이미지를 중심에 배치합니다.', 'MAIN'],
      ['Thumbs', '하단 썸네일로 탐색 가능성을 암시합니다.', 'TH'],
      ['Caption', '이미지 설명과 행동 버튼을 연결합니다.', 'CAP'],
    ],
  },
  {
    id: 'gallery-lightbox-grid',
    name: 'Lightbox Grid',
    category: 'gallery',
    description: '라이트박스 진입을 위한 이미지 grid',
    thumbnailHint: 'LIGHT',
    eyebrow: 'Open detail',
    title: '이미지를 클릭해 자세히 볼 수 있다는 흐름을 만듭니다',
    copy: '작품, 공간, 행사 이미지가 많은 사이트에서 상세 보기 전환을 유도합니다.',
    ctaLabel: '크게 보기',
    accent: '#9333ea',
    background: '#faf5ff',
    cardTint: '#ffffff',
    cards: [
      ['Preview', '작은 카드에서 전체 분위기를 보여줍니다.', 'P'],
      ['Open', '클릭 가능한 상세 보기 흐름을 만듭니다.', 'O'],
      ['Share', '이미지 설명과 공유 CTA를 같이 둡니다.', 'S'],
    ],
  },
  {
    id: 'faq-accordion',
    name: 'FAQ Accordion',
    category: 'faq',
    description: '자주 묻는 질문을 접는 형태로 정리',
    thumbnailHint: 'FAQ',
    eyebrow: 'Questions',
    title: '반복 질문을 짧고 명확하게 정리합니다',
    copy: '서비스 전환 전 가장 많이 나오는 질문을 카드형 accordion으로 안내합니다.',
    ctaLabel: '질문 보기',
    accent: '#2563eb',
    background: '#eff6ff',
    cardTint: '#ffffff',
    cards: [
      ['Cost', '가격과 결제 방식에 대한 질문을 다룹니다.', 'Q1'],
      ['Timeline', '진행 기간과 준비물을 설명합니다.', 'Q2'],
      ['Support', '후속 지원과 연락 방식을 안내합니다.', 'Q3'],
    ],
  },
  {
    id: 'faq-two-column-grid',
    name: 'Two Column FAQ Grid',
    category: 'faq',
    description: 'FAQ를 두 열 카드로 나누는 구성',
    thumbnailHint: '2FAQ',
    eyebrow: 'Help center',
    title: '질문을 주제별 두 열로 나눕니다',
    copy: 'FAQ가 많은 페이지에서 질문 그룹을 빠르게 스캔하도록 돕는 레이아웃입니다.',
    ctaLabel: '도움말 열기',
    accent: '#0f766e',
    background: '#f0fdfa',
    cardTint: '#ffffff',
    cards: [
      ['Before start', '신청 전 확인할 질문을 묶습니다.', 'A'],
      ['During work', '진행 중 발생하는 질문을 다룹니다.', 'B'],
      ['After launch', '완료 후 관리 질문을 정리합니다.', 'C'],
    ],
  },
  {
    id: 'faq-category-tabs',
    name: 'FAQ Category Tabs',
    category: 'faq',
    description: 'FAQ 카테고리 탭을 암시하는 섹션',
    thumbnailHint: 'TABS',
    eyebrow: 'Categorized FAQ',
    title: '질문을 카테고리별로 탐색하게 만듭니다',
    copy: '복잡한 서비스나 SaaS 도움말 페이지에서 카테고리별 질문 흐름을 제공합니다.',
    ctaLabel: '전체 FAQ',
    accent: '#7c3aed',
    background: '#f5f3ff',
    cardTint: '#ffffff',
    cards: [
      ['Account', '계정과 권한 관련 질문을 모읍니다.', 'TAB'],
      ['Billing', '결제와 영수증 흐름을 설명합니다.', 'TAB'],
      ['Technical', '기술 지원과 장애 대응을 다룹니다.', 'TAB'],
    ],
  },
  {
    id: 'services-3-col-icon',
    name: 'Three Service Icons',
    category: 'services',
    description: '세 가지 서비스를 아이콘 카드로 정리',
    thumbnailHint: 'SERV',
    eyebrow: 'Services',
    title: '서비스 패키지를 세 가지 카드로 나눕니다',
    copy: '전문 서비스, 병원, 에이전시, 교육 과정의 주요 제공 범위를 설명합니다.',
    ctaLabel: '서비스 문의',
    accent: '#2563eb',
    background: '#eff6ff',
    cardTint: '#ffffff',
    cards: [
      ['Consulting', '문제 진단과 전략 수립을 제공합니다.', '01'],
      ['Implementation', '실제 실행과 제작을 지원합니다.', '02'],
      ['Support', '완료 후 운영과 개선을 이어갑니다.', '03'],
    ],
  },
  {
    id: 'services-list-with-image',
    name: 'Service List With Image',
    category: 'services',
    description: '서비스 목록과 비주얼을 함께 배치',
    thumbnailHint: 'LIST',
    eyebrow: 'Service menu',
    title: '서비스 목록을 이미지 카드와 함께 보여줍니다',
    copy: '업무 범위가 많은 사이트에서 목록과 대표 이미지를 균형 있게 배치합니다.',
    ctaLabel: '목록 보기',
    accent: '#c2410c',
    background: '#fff7ed',
    cardTint: '#ffffff',
    cards: [
      ['Audit', '현재 상태를 진단하고 우선순위를 잡습니다.', 'A'],
      ['Roadmap', '실행 가능한 단계와 일정을 제안합니다.', 'R'],
      ['Delivery', '결과물을 검수 가능한 단위로 제공합니다.', 'D'],
    ],
  },
  {
    id: 'services-accordion',
    name: 'Service Accordion',
    category: 'services',
    description: '서비스 상세를 접고 펼치는 레이아웃',
    thumbnailHint: 'ACC',
    eyebrow: 'Expandable services',
    title: '서비스 상세를 단계별로 펼쳐 보게 합니다',
    copy: '긴 서비스 설명을 한 화면에 모두 드러내지 않고 탐색 가능한 카드로 나눕니다.',
    ctaLabel: '상세 보기',
    accent: '#0f766e',
    background: '#ecfdf5',
    cardTint: '#ffffff',
    cards: [
      ['Scope', '포함 범위와 제외 범위를 명확히 합니다.', '1'],
      ['Process', '진행 단계와 담당 역할을 설명합니다.', '2'],
      ['Deliverables', '최종 산출물을 구체적으로 안내합니다.', '3'],
    ],
  },
  {
    id: 'services-pricing-card',
    name: 'Service Pricing Card',
    category: 'services',
    description: '서비스 소개와 가격 CTA 결합',
    thumbnailHint: 'PRICE',
    eyebrow: 'Service package',
    title: '서비스 설명과 가격 행동을 한 카드에 담습니다',
    copy: '컨설팅, 코칭, 유지보수 같은 서비스 패키지를 판매하는 섹션입니다.',
    ctaLabel: '견적 요청',
    accent: '#9333ea',
    background: '#faf5ff',
    cardTint: '#ffffff',
    cards: [
      ['Package', '기본 포함 항목을 요약합니다.', 'PKG'],
      ['Estimate', '가격 범위나 상담 기준을 안내합니다.', '$'],
      ['Next step', '문의 후 진행 흐름을 설명합니다.', 'GO'],
    ],
  },
  {
    id: 'services-bento-practice',
    name: 'Practice Bento Board',
    category: 'services',
    description: '업무분야를 bento 카드 보드로 정리',
    thumbnailHint: 'BENTO',
    eyebrow: 'Practice board',
    title: '주요 업무를 한눈에 비교하는 보드로 보여줍니다',
    copy: '로펌, 회계, 컨설팅처럼 여러 전문 영역을 짧은 카드로 빠르게 비교해야 하는 페이지에 맞습니다.',
    ctaLabel: '업무 선택',
    accent: '#1d4ed8',
    background: '#eef2ff',
    cardTint: '#ffffff',
    cards: [
      ['Corporate', '회사설립, 지배구조, 주주계약 쟁점을 묶어 보여줍니다.', '01'],
      ['Disputes', '협상, 조정, 소송 대응 흐름을 업무 카드로 나눕니다.', '02'],
      ['Compliance', '규제 검토와 내부 절차 정비를 별도 항목으로 설명합니다.', '03'],
    ],
  },
  {
    id: 'services-process-ladder',
    name: 'Service Process Ladder',
    category: 'services',
    description: '서비스 진행 단계를 계단형 카드로 안내',
    thumbnailHint: 'STEP',
    eyebrow: 'Service flow',
    title: '상담부터 실행까지 진행 순서를 단계별로 보여줍니다',
    copy: '복잡한 전문 서비스를 처음 문의하는 사용자가 다음 행동을 이해하도록 만드는 안내형 섹션입니다.',
    ctaLabel: '절차 확인',
    accent: '#0f766e',
    background: '#f0fdfa',
    cardTint: '#ffffff',
    cards: [
      ['Intake', '기본 정보와 긴급도를 확인해 상담 범위를 정합니다.', '1'],
      ['Review', '자료와 계약서를 검토하고 핵심 리스크를 표시합니다.', '2'],
      ['Action', '우선순위에 따라 실행 문서와 연락 계획을 만듭니다.', '3'],
    ],
  },
  {
    id: 'services-risk-matrix',
    name: 'Risk Matrix Services',
    category: 'services',
    description: '리스크 수준별 서비스를 매트릭스로 설명',
    thumbnailHint: 'RISK',
    eyebrow: 'Risk map',
    title: '리스크 수준에 맞춰 필요한 업무를 고르게 합니다',
    copy: '법률·보안·재무처럼 위험도와 대응 수준을 함께 설명해야 하는 전문 서비스에 적합합니다.',
    ctaLabel: '위험도 진단',
    accent: '#dc2626',
    background: '#fef2f2',
    cardTint: '#ffffff',
    cards: [
      ['Prevent', '계약 전 검토와 체크리스트로 문제를 예방합니다.', 'LOW'],
      ['Respond', '분쟁 조짐이 있을 때 증거와 협상 전략을 정리합니다.', 'MID'],
      ['Resolve', '소송, 집행, 합의 등 강한 대응 절차를 안내합니다.', 'HIGH'],
    ],
  },
  {
    id: 'services-retainer-packages',
    name: 'Retainer Packages',
    category: 'services',
    description: '월 자문·패키지 서비스를 카드로 비교',
    thumbnailHint: 'PLAN',
    eyebrow: 'Retainer plans',
    title: '반복 자문과 프로젝트 서비스를 패키지로 비교합니다',
    copy: '고문계약, 유지보수, 월간 자문처럼 지속 서비스의 포함 범위를 보여줄 때 쓰기 좋습니다.',
    ctaLabel: '패키지 문의',
    accent: '#7c3aed',
    background: '#f5f3ff',
    cardTint: '#ffffff',
    cards: [
      ['Essential', '월간 기본 질의와 문서 1차 검토를 포함합니다.', 'S'],
      ['Growth', '계약 협상과 운영 리스크 점검까지 확장합니다.', 'M'],
      ['Priority', '긴급 대응과 전담 커뮤니케이션을 우선 처리합니다.', 'L'],
    ],
  },
  {
    id: 'services-industry-solutions',
    name: 'Industry Solution Cards',
    category: 'services',
    description: '산업별 서비스 솔루션을 구분',
    thumbnailHint: 'IND',
    eyebrow: 'Industry fit',
    title: '산업별로 다른 문제를 맞춤 솔루션처럼 보여줍니다',
    copy: 'B2B, 의료, 제조, 스타트업 등 산업마다 다른 고객 언어를 한 섹션 안에서 분리합니다.',
    ctaLabel: '산업 선택',
    accent: '#c2410c',
    background: '#fff7ed',
    cardTint: '#ffffff',
    cards: [
      ['Startup', '투자, 스톡옵션, 지식재산권 이슈를 빠르게 정리합니다.', 'ST'],
      ['Manufacturing', '공급계약, 품질, 클레임 대응을 중심으로 설명합니다.', 'MF'],
      ['Healthcare', '인허가, 개인정보, 광고 규제 검토를 안내합니다.', 'HC'],
    ],
  },
  {
    id: 'services-comparison-table',
    name: 'Service Comparison Table',
    category: 'services',
    description: '서비스 옵션을 표처럼 비교하는 구성',
    thumbnailHint: 'TABLE',
    eyebrow: 'Compare options',
    title: '비슷한 서비스 옵션의 차이를 명확히 보여줍니다',
    copy: '사용자가 어떤 서비스를 선택해야 하는지 헷갈릴 때 범위, 산출물, 일정 차이를 나눠 보여줍니다.',
    ctaLabel: '옵션 비교',
    accent: '#334155',
    background: '#f8fafc',
    cardTint: '#ffffff',
    cards: [
      ['One-time review', '단건 문서 검토와 의견서 중심으로 진행합니다.', 'A'],
      ['Project counsel', '거래 전체 일정에 맞춰 단계별 검토를 제공합니다.', 'B'],
      ['Ongoing desk', '반복 문의와 월간 운영 리스크를 함께 관리합니다.', 'C'],
    ],
  },
  {
    id: 'services-cross-border-desk',
    name: 'Cross-border Desk',
    category: 'services',
    description: '국가 간 업무 데스크를 강조',
    thumbnailHint: 'GLOBAL',
    eyebrow: 'Cross-border desk',
    title: '한국과 대만 사이의 업무를 하나의 데스크로 연결합니다',
    copy: '해외 진출, 현지 계약, 분쟁 대응처럼 국가 간 커뮤니케이션이 중요한 서비스에 맞춘 템플릿입니다.',
    ctaLabel: '해외 업무 상담',
    accent: '#0284c7',
    background: '#f0f9ff',
    cardTint: '#ffffff',
    cards: [
      ['Korea intake', '한국어로 쟁점과 자료를 먼저 정리합니다.', 'KR'],
      ['Taiwan review', '대만 현지 법률과 실무 관행을 함께 확인합니다.', 'TW'],
      ['Execution', '번역, 문서, 커뮤니케이션을 실행 계획으로 묶습니다.', 'EX'],
    ],
  },
  {
    id: 'services-case-intake-flow',
    name: 'Case Intake Flow',
    category: 'services',
    description: '상담 접수 흐름을 서비스형 섹션으로 안내',
    thumbnailHint: 'INTAKE',
    eyebrow: 'Case intake',
    title: '문의 전 준비할 내용을 서비스 흐름으로 안내합니다',
    copy: '법률 상담, 병원 예약, 전문 견적처럼 사전 정보가 중요한 문의 전환 구간에 적합합니다.',
    ctaLabel: '접수 시작',
    accent: '#059669',
    background: '#ecfdf5',
    cardTint: '#ffffff',
    cards: [
      ['Facts', '사실관계와 관련 당사자를 짧게 정리합니다.', '01'],
      ['Documents', '계약서, 통지서, 증빙자료를 준비하게 안내합니다.', '02'],
      ['Urgency', '마감일과 긴급도를 표시해 우선순위를 정합니다.', '03'],
    ],
  },
  {
    id: 'contact-form-with-info',
    name: 'Contact Form With Info',
    category: 'contact',
    description: '문의 폼과 연락 정보를 함께 배치',
    thumbnailHint: 'FORM',
    eyebrow: 'Contact',
    title: '문의 전 필요한 정보를 한 화면에 정리합니다',
    copy: '문의 폼 옆에 연락처, 운영 시간, 준비 자료를 함께 보여주는 contact section입니다.',
    ctaLabel: '문의 작성',
    accent: '#2563eb',
    background: '#eff6ff',
    cardTint: '#ffffff',
    cards: [
      ['Email', '이메일이나 메신저 연락 경로를 표시합니다.', '@'],
      ['Hours', '운영 시간과 응답 기준을 안내합니다.', 'H'],
      ['Prepare', '문의 전 준비할 자료를 알려줍니다.', 'P'],
    ],
  },
  {
    id: 'contact-map-and-form',
    name: 'Map And Form',
    category: 'contact',
    description: '지도 영역과 문의 입력을 결합',
    thumbnailHint: 'MAP',
    eyebrow: 'Visit us',
    title: '위치와 문의 흐름을 같은 섹션에 둡니다',
    copy: '오프라인 매장, 병원, 스튜디오, 사무실 소개 페이지에 적합합니다.',
    ctaLabel: '길찾기',
    accent: '#0f766e',
    background: '#ecfdf5',
    cardTint: '#ffffff',
    cards: [
      ['Location', '주소와 주변 정보를 짧게 표시합니다.', 'MAP'],
      ['Booking', '방문 예약이나 상담 신청을 연결합니다.', 'BOOK'],
      ['Transit', '주차, 대중교통, 입구 정보를 안내합니다.', 'INFO'],
    ],
  },
  {
    id: 'contact-split-info',
    name: 'Split Contact Info',
    category: 'contact',
    description: '연락처 정보를 좌우로 나누는 contact layout',
    thumbnailHint: 'INFO',
    eyebrow: 'Reach out',
    title: '연락 채널을 목적별로 나누어 보여줍니다',
    copy: '일반 문의, 제휴, 고객 지원 등 연락 목적이 여러 개인 사이트에 사용합니다.',
    ctaLabel: '채널 선택',
    accent: '#7c3aed',
    background: '#f5f3ff',
    cardTint: '#ffffff',
    cards: [
      ['Sales', '구매나 견적 문의 채널을 표시합니다.', 'S'],
      ['Support', '기존 고객 지원 경로를 안내합니다.', 'CS'],
      ['Partnership', '제휴와 미디어 문의를 분리합니다.', 'P'],
    ],
  },
];

export const BUILT_IN_SECTIONS: BuiltInSectionTemplate[] = [
  defineTemplate({
    id: 'hero-centered-cta',
    name: 'Centered CTA Hero',
    category: 'hero',
    description: '중앙 정렬 헤드라인과 두 개의 주요 행동 버튼',
    thumbnailHint: 'HERO',
    width: 1120,
    height: 430,
    rootStyle: { backgroundColor: '#f8fafc' },
    children: (rootId) => [
      textNode({
        id: 'hero-centered-cta-eyebrow',
        parentId: rootId,
        rect: { x: 380, y: 58, width: 360, height: 30 },
        zIndex: 1,
        text: 'Taiwan legal desk',
        fontSize: 14,
        color: '#0f766e',
        fontWeight: 'bold',
        align: 'center',
      }),
      headingNode({
        id: 'hero-centered-cta-title',
        parentId: rootId,
        rect: { x: 210, y: 104, width: 700, height: 108 },
        zIndex: 2,
        text: '대만 법률 리스크를 빠르게 정리합니다',
        level: 1,
        fontSize: 46,
        align: 'center',
      }),
      textNode({
        id: 'hero-centered-cta-copy',
        parentId: rootId,
        rect: { x: 270, y: 226, width: 580, height: 62 },
        zIndex: 3,
        text: '계약, 회사설립, 분쟁 대응까지 한국어로 이해하기 쉬운 실행 계획을 제공합니다.',
        fontSize: 18,
        color: '#475569',
        align: 'center',
      }),
      buttonNode({
        id: 'hero-centered-cta-primary',
        parentId: rootId,
        rect: { x: 390, y: 318, width: 166, height: 52 },
        zIndex: 4,
        label: '상담 예약',
      }),
      buttonNode({
        id: 'hero-centered-cta-secondary',
        parentId: rootId,
        rect: { x: 574, y: 318, width: 156, height: 52 },
        zIndex: 5,
        label: '서비스 보기',
        href: '#services',
        buttonStyle: 'secondary-outline',
        style: { shadowY: 0, shadowBlur: 0 },
      }),
    ],
  }),
  defineTemplate({
    id: 'hero-split-image',
    name: 'Split Image Hero',
    category: 'hero',
    description: '좌측 카피와 우측 이미지가 있는 랜딩 히어로',
    thumbnailHint: 'SPLIT',
    width: 1120,
    height: 460,
    rootStyle: { backgroundColor: '#ffffff' },
    children: (rootId) => [
      textNode({
        id: 'hero-split-image-eyebrow',
        parentId: rootId,
        rect: { x: 64, y: 70, width: 320, height: 30 },
        zIndex: 1,
        text: 'Cross-border counsel',
        fontSize: 14,
        color: '#1d4ed8',
        fontWeight: 'bold',
      }),
      headingNode({
        id: 'hero-split-image-title',
        parentId: rootId,
        rect: { x: 64, y: 112, width: 480, height: 116 },
        zIndex: 2,
        text: '대만 비즈니스 의사결정에 필요한 법률 검토',
        level: 1,
        fontSize: 42,
      }),
      textNode({
        id: 'hero-split-image-copy',
        parentId: rootId,
        rect: { x: 64, y: 250, width: 450, height: 78 },
        zIndex: 3,
        text: '현지 제도와 실무 관행을 함께 검토해 계약 전 단계부터 분쟁 대응까지 우선순위를 잡습니다.',
        fontSize: 17,
      }),
      buttonNode({
        id: 'hero-split-image-primary',
        parentId: rootId,
        rect: { x: 64, y: 356, width: 178, height: 52 },
        zIndex: 4,
        label: '문의하기',
      }),
      imageNode({
        id: 'hero-split-image-visual',
        parentId: rootId,
        rect: { x: 620, y: 62, width: 420, height: 336 },
        zIndex: 5,
        src: '/images/header-skyline-ratio.webp',
        alt: 'Taipei skyline',
        style: {
          borderRadius: 28,
          shadowY: 22,
          shadowBlur: 48,
          shadowColor: 'rgba(15, 23, 42, 0.16)',
        },
      }),
    ],
  }),
  defineTemplate({
    id: 'features-3-column',
    name: 'Three Feature Columns',
    category: 'features',
    description: '세 가지 핵심 강점을 카드로 정리',
    thumbnailHint: '3COL',
    width: 1120,
    height: 390,
    rootStyle: { backgroundColor: '#f8fafc' },
    children: (rootId) => [
      headingNode({
        id: 'features-3-column-title',
        parentId: rootId,
        rect: { x: 66, y: 54, width: 520, height: 58 },
        zIndex: 1,
        text: '업무를 명확하게 나누어 진행합니다',
        fontSize: 34,
      }),
      textNode({
        id: 'features-3-column-copy',
        parentId: rootId,
        rect: { x: 66, y: 120, width: 530, height: 52 },
        zIndex: 2,
        text: '초기 진단, 문서 검토, 실행 지원을 분리해 필요한 단계만 빠르게 선택할 수 있습니다.',
        fontSize: 16,
      }),
      ...featureCard('features-3-column-01', rootId, 66, 204, '초기 진단', '사안의 쟁점과 가능한 선택지를 빠르게 분류합니다.', 3),
      ...featureCard('features-3-column-02', rootId, 403, 204, '문서 검토', '계약서와 증빙자료의 리스크 조항을 표시합니다.', 7),
      ...featureCard('features-3-column-03', rootId, 740, 204, '실행 지원', '현지 커뮤니케이션과 후속 일정까지 관리합니다.', 11),
    ],
  }),
  defineTemplate({
    id: 'features-icon-grid',
    name: 'Icon Grid Features',
    category: 'features',
    description: '네 개 항목을 촘촘하게 보여주는 기능 그리드',
    thumbnailHint: 'GRID',
    width: 1120,
    height: 540,
    rootStyle: { backgroundColor: '#ffffff' },
    children: (rootId) => [
      headingNode({
        id: 'features-icon-grid-title',
        parentId: rootId,
        rect: { x: 70, y: 52, width: 450, height: 52 },
        zIndex: 1,
        text: '자주 필요한 법률 지원',
        fontSize: 34,
      }),
      textNode({
        id: 'features-icon-grid-copy',
        parentId: rootId,
        rect: { x: 70, y: 112, width: 520, height: 48 },
        zIndex: 2,
        text: '회사 운영, 거래, 인사, 분쟁 대응을 한 화면에서 설명할 수 있는 구성입니다.',
        fontSize: 16,
      }),
      ...featureCard('features-icon-grid-01', rootId, 70, 190, '회사설립', '법인, 지점, 대표처 선택과 등록 절차를 정리합니다.', 3),
      ...featureCard('features-icon-grid-02', rootId, 405, 190, '계약 검토', '거래구조와 책임 범위를 조항별로 확인합니다.', 7),
      ...featureCard('features-icon-grid-03', rootId, 70, 350, '노무 자문', '고용계약, 해고, 퇴직금 쟁점을 검토합니다.', 11),
      ...featureCard('features-icon-grid-04', rootId, 405, 350, '분쟁 대응', '협상, 내용증명, 소송 준비 단계를 설계합니다.', 15),
    ],
  }),
  defineTemplate({
    id: 'testimonials-cards',
    name: 'Testimonial Cards',
    category: 'testimonials',
    description: '고객 후기를 세 장의 카드로 표시',
    thumbnailHint: 'QUOTE',
    width: 1120,
    height: 400,
    rootStyle: { backgroundColor: '#f8fafc' },
    children: (rootId) => [
      headingNode({
        id: 'testimonials-cards-title',
        parentId: rootId,
        rect: { x: 70, y: 52, width: 560, height: 58 },
        zIndex: 1,
        text: '의사결정이 빨라졌다는 평가',
        fontSize: 34,
      }),
      textNode({
        id: 'testimonials-cards-copy',
        parentId: rootId,
        rect: { x: 70, y: 118, width: 560, height: 48 },
        zIndex: 2,
        text: '복잡한 현지 법률 이슈를 실행 가능한 언어로 정리했다는 후기를 강조합니다.',
        fontSize: 16,
      }),
      ...quoteCard('testimonials-cards-01', rootId, 70, 198, '계약 전 위험 조항을 미리 확인해 협상이 훨씬 수월했습니다.', '제조업 법무팀', 3),
      ...quoteCard('testimonials-cards-02', rootId, 405, 198, '한국어 설명과 현지 문서 검토가 함께 진행되어 일정 지연을 줄였습니다.', '스타트업 대표', 6),
      ...quoteCard('testimonials-cards-03', rootId, 740, 198, '쟁점과 다음 행동이 명확해 내부 보고서 작성 시간이 줄었습니다.', '해외사업 담당자', 9),
    ],
  }),
  defineTemplate({
    id: 'testimonials-quote-grid',
    name: 'Quote Grid',
    category: 'testimonials',
    description: '대형 인용문과 신뢰 포인트 조합',
    thumbnailHint: 'PROOF',
    width: 1120,
    height: 380,
    rootStyle: { backgroundColor: '#ffffff' },
    children: (rootId) => [
      containerNode({
        id: 'testimonials-quote-grid-main-card',
        parentId: rootId,
        rect: { x: 70, y: 62, width: 520, height: 250 },
        zIndex: 1,
        label: 'Featured quote',
        style: {
          backgroundColor: '#0f172a',
          borderColor: '#0f172a',
          borderWidth: 1,
          borderRadius: 22,
          shadowY: 18,
          shadowBlur: 42,
          shadowColor: 'rgba(15, 23, 42, 0.18)',
        },
      }),
      textNode({
        id: 'testimonials-quote-grid-quote',
        parentId: 'testimonials-quote-grid-main-card',
        rect: { x: 34, y: 36, width: 440, height: 120 },
        zIndex: 2,
        text: '대만 법률 이슈를 내부 의사결정자에게 바로 공유할 수 있는 형태로 정리해 주었습니다.',
        fontSize: 24,
        color: '#ffffff',
        fontWeight: 'bold',
        lineHeight: 1.28,
      }),
      textNode({
        id: 'testimonials-quote-grid-name',
        parentId: 'testimonials-quote-grid-main-card',
        rect: { x: 34, y: 178, width: 360, height: 28 },
        zIndex: 3,
        text: 'Global operations lead',
        fontSize: 15,
        color: '#cbd5e1',
        fontWeight: 'medium',
      }),
      ...featureCard('testimonials-quote-grid-01', rootId, 640, 62, '응답 속도', '초기 질의와 자료 요청 범위를 빠르게 정리합니다.', 4),
      ...featureCard('testimonials-quote-grid-02', rootId, 640, 224, '보고 친화적', '핵심 쟁점과 권고안을 내부 공유용으로 구조화합니다.', 8),
    ],
  }),
  defineTemplate({
    id: 'cta-banner-centered',
    name: 'Centered CTA Banner',
    category: 'cta',
    description: '짧은 메시지와 단일 CTA 버튼',
    thumbnailHint: 'CTA',
    width: 1120,
    height: 280,
    rootStyle: { backgroundColor: '#eef2ff', borderColor: '#c7d2fe' },
    children: (rootId) => [
      headingNode({
        id: 'cta-banner-centered-title',
        parentId: rootId,
        rect: { x: 220, y: 58, width: 680, height: 62 },
        zIndex: 1,
        text: '지금 필요한 법률 검토부터 시작하세요',
        fontSize: 36,
        align: 'center',
      }),
      textNode({
        id: 'cta-banner-centered-copy',
        parentId: rootId,
        rect: { x: 280, y: 126, width: 560, height: 42 },
        zIndex: 2,
        text: '자료를 보내주시면 우선순위와 예상 일정을 먼저 정리해 드립니다.',
        fontSize: 17,
        color: '#475569',
        align: 'center',
      }),
      buttonNode({
        id: 'cta-banner-centered-button',
        parentId: rootId,
        rect: { x: 470, y: 190, width: 180, height: 52 },
        zIndex: 3,
        label: '상담 요청',
      }),
    ],
  }),
  defineTemplate({
    id: 'cta-split-with-image',
    name: 'Split CTA With Image',
    category: 'cta',
    description: '이미지와 문의 유도 카피를 나란히 배치',
    thumbnailHint: 'SPLIT',
    width: 1120,
    height: 340,
    rootStyle: { backgroundColor: '#ffffff' },
    children: (rootId) => [
      imageNode({
        id: 'cta-split-with-image-visual',
        parentId: rootId,
        rect: { x: 64, y: 48, width: 390, height: 244 },
        zIndex: 1,
        src: '/images/hero-bg-02.webp',
        alt: 'Law office consultation',
        style: { borderRadius: 22 },
      }),
      headingNode({
        id: 'cta-split-with-image-title',
        parentId: rootId,
        rect: { x: 520, y: 70, width: 470, height: 84 },
        zIndex: 2,
        text: '문서와 상황을 함께 보내주세요',
        fontSize: 34,
      }),
      textNode({
        id: 'cta-split-with-image-copy',
        parentId: rootId,
        rect: { x: 520, y: 164, width: 480, height: 62 },
        zIndex: 3,
        text: '계약서, 상대방 연락, 일정 정보를 바탕으로 가능한 대응 방안을 정리합니다.',
        fontSize: 17,
      }),
      buttonNode({
        id: 'cta-split-with-image-button',
        parentId: rootId,
        rect: { x: 520, y: 248, width: 180, height: 52 },
        zIndex: 4,
        label: '자료 보내기',
      }),
    ],
  }),
  defineTemplate({
    id: 'footer-3-column',
    name: 'Three Column Footer',
    category: 'footer',
    description: '브랜드 소개, 링크, 연락처를 나눈 푸터',
    thumbnailHint: 'FOOT',
    width: 1120,
    height: 300,
    rootStyle: { backgroundColor: '#0f172a', borderColor: '#0f172a', borderRadius: 18 },
    children: (rootId) => [
      headingNode({
        id: 'footer-3-column-brand',
        parentId: rootId,
        rect: { x: 64, y: 56, width: 300, height: 44 },
        zIndex: 1,
        text: 'Tseng Law',
        level: 3,
        fontSize: 30,
        color: '#ffffff',
      }),
      textNode({
        id: 'footer-3-column-copy',
        parentId: rootId,
        rect: { x: 64, y: 112, width: 330, height: 70 },
        zIndex: 2,
        text: '대만 현지 법률 이슈를 한국어로 설명하고 실행 가능한 대응 계획을 제공합니다.',
        fontSize: 15,
        color: '#cbd5e1',
      }),
      textNode({
        id: 'footer-3-column-links-title',
        parentId: rootId,
        rect: { x: 470, y: 60, width: 180, height: 28 },
        zIndex: 3,
        text: '바로가기',
        fontSize: 15,
        color: '#ffffff',
        fontWeight: 'bold',
      }),
      textNode({
        id: 'footer-3-column-links',
        parentId: rootId,
        rect: { x: 470, y: 100, width: 180, height: 96 },
        zIndex: 4,
        text: '서비스\n변호사\n자주 묻는 질문\n문의',
        fontSize: 14,
        color: '#cbd5e1',
        lineHeight: 1.55,
      }),
      textNode({
        id: 'footer-3-column-contact-title',
        parentId: rootId,
        rect: { x: 720, y: 60, width: 220, height: 28 },
        zIndex: 5,
        text: '연락처',
        fontSize: 15,
        color: '#ffffff',
        fontWeight: 'bold',
      }),
      textNode({
        id: 'footer-3-column-contact',
        parentId: rootId,
        rect: { x: 720, y: 100, width: 300, height: 96 },
        zIndex: 6,
        text: 'contact@example.com\nTaipei, Taiwan\n월-금 09:00-18:00',
        fontSize: 14,
        color: '#cbd5e1',
        lineHeight: 1.55,
      }),
      textNode({
        id: 'footer-3-column-rights',
        parentId: rootId,
        rect: { x: 64, y: 234, width: 520, height: 28 },
        zIndex: 7,
        text: '© 2026 Tseng Law. All rights reserved.',
        fontSize: 13,
        color: '#94a3b8',
      }),
    ],
  }),
  defineTemplate({
    id: 'footer-minimal',
    name: 'Minimal Footer',
    category: 'footer',
    description: '한 줄 브랜드와 링크 중심의 간결한 푸터',
    thumbnailHint: 'MINI',
    width: 1120,
    height: 180,
    rootStyle: { backgroundColor: '#ffffff', borderColor: '#dbe4ee', borderRadius: 14 },
    children: (rootId) => [
      headingNode({
        id: 'footer-minimal-brand',
        parentId: rootId,
        rect: { x: 64, y: 54, width: 260, height: 38 },
        zIndex: 1,
        text: 'Tseng Law',
        level: 3,
        fontSize: 26,
      }),
      textNode({
        id: 'footer-minimal-links',
        parentId: rootId,
        rect: { x: 420, y: 62, width: 420, height: 28 },
        zIndex: 2,
        text: 'Services  /  Attorneys  /  FAQ  /  Contact',
        fontSize: 14,
        color: '#334155',
        fontWeight: 'medium',
      }),
      textNode({
        id: 'footer-minimal-rights',
        parentId: rootId,
        rect: { x: 64, y: 112, width: 500, height: 26 },
        zIndex: 3,
        text: '© 2026 Tseng Law. Legal information is not a substitute for case-specific advice.',
        fontSize: 13,
        color: '#64748b',
      }),
    ],
  }),
  defineTemplate({
    id: 'legal-disclaimer',
    name: 'Legal Disclaimer',
    category: 'legal',
    description: '법률 정보 고지와 상담 전 확인사항',
    thumbnailHint: 'LEGAL',
    width: 1120,
    height: 280,
    rootStyle: { backgroundColor: '#f8fafc', borderColor: '#dbe4ee' },
    children: (rootId) => [
      headingNode({
        id: 'legal-disclaimer-title',
        parentId: rootId,
        rect: { x: 64, y: 48, width: 430, height: 52 },
        zIndex: 1,
        text: '법률 정보 이용 안내',
        fontSize: 32,
      }),
      textNode({
        id: 'legal-disclaimer-copy',
        parentId: rootId,
        rect: { x: 64, y: 112, width: 930, height: 74 },
        zIndex: 2,
        text: '이 페이지의 내용은 일반 정보 제공을 위한 것이며 구체적인 사건에 대한 법률 의견이 아닙니다. 개별 사안은 자료 검토와 상담을 통해 판단해야 합니다.',
        fontSize: 16,
      }),
      textNode({
        id: 'legal-disclaimer-list',
        parentId: rootId,
        rect: { x: 64, y: 198, width: 850, height: 54 },
        zIndex: 3,
        text: '상담 전 관련 계약서, 상대방 연락, 기한 정보를 함께 준비해 주세요.\n긴급 사건은 관할 기관 기한을 먼저 확인해야 합니다.',
        fontSize: 14,
        color: '#64748b',
        lineHeight: 1.5,
      }),
    ],
  }),
  defineTemplate({
    id: 'legal-privacy-summary',
    name: 'Privacy Summary',
    category: 'legal',
    description: '개인정보 처리 핵심 항목 요약',
    thumbnailHint: 'PRIV',
    width: 1120,
    height: 350,
    rootStyle: { backgroundColor: '#ffffff' },
    children: (rootId) => [
      headingNode({
        id: 'legal-privacy-summary-title',
        parentId: rootId,
        rect: { x: 64, y: 48, width: 520, height: 52 },
        zIndex: 1,
        text: '개인정보 처리 요약',
        fontSize: 32,
      }),
      textNode({
        id: 'legal-privacy-summary-copy',
        parentId: rootId,
        rect: { x: 64, y: 108, width: 620, height: 46 },
        zIndex: 2,
        text: '문의 대응과 사건 검토를 위해 필요한 범위에서 정보를 수집하고 보관합니다.',
        fontSize: 16,
      }),
      ...featureCard('legal-privacy-summary-01', rootId, 64, 184, '수집 항목', '이름, 연락처, 문의 내용, 첨부 자료를 확인합니다.', 3),
      ...featureCard('legal-privacy-summary-02', rootId, 400, 184, '이용 목적', '상담 가능성 검토와 후속 연락을 위해 사용합니다.', 7),
      ...featureCard('legal-privacy-summary-03', rootId, 736, 184, '보관 기간', '법령과 내부 기준에 따라 필요한 기간만 보관합니다.', 11),
    ],
  }),
  ...EXPANDED_SECTION_SPECS.map(defineExpandedTemplate),
];

export function getBuiltInSectionsByCategory(): Record<BuiltInSectionCategory, BuiltInSectionTemplate[]> {
  const buckets = Object.fromEntries(
    BUILT_IN_SECTION_CATEGORIES.map((category) => [category, [] as BuiltInSectionTemplate[]]),
  ) as Record<BuiltInSectionCategory, BuiltInSectionTemplate[]>;

  for (const template of BUILT_IN_SECTIONS) {
    buckets[template.category].push(template);
  }

  return buckets;
}
