const baseStyle = {
  backgroundColor: 'transparent',
  borderColor: '#cbd5e1',
  borderStyle: 'solid',
  borderWidth: 0,
  borderRadius: 0,
  shadowX: 0,
  shadowY: 0,
  shadowBlur: 0,
  shadowSpread: 0,
  shadowColor: 'rgba(15, 23, 42, 0.16)',
  opacity: 100,
};

export function bookingWidgetDocument(token: string, serviceId: string, staffId: string): Record<string, unknown> {
  const now = new Date().toISOString();
  return {
    version: 1,
    locale: 'ko',
    updatedAt: now,
    updatedBy: `w200-booking-widget-${token}`,
    stageWidth: 1280,
    stageHeight: 760,
    nodes: [
      {
        id: `root-${token}`,
        kind: 'container',
        rect: { x: 0, y: 0, width: 1280, height: 760 },
        style: baseStyle,
        zIndex: 0,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          label: 'W200 booking root',
          background: '#ffffff',
          borderColor: 'transparent',
          borderStyle: 'solid',
          borderWidth: 0,
          borderRadius: 0,
          padding: 0,
          layoutMode: 'absolute',
          as: 'main',
        },
      },
      {
        id: `heading-${token}`,
        kind: 'text',
        parentId: `root-${token}`,
        rect: { x: 72, y: 38, width: 760, height: 58 },
        style: baseStyle,
        zIndex: 1,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          text: `W200 공개 예약 ${token}`,
          fontSize: 34,
          color: '#172033',
          fontWeight: 'bold',
          align: 'left',
          lineHeight: 1.2,
          letterSpacing: 0,
          fontFamily: 'system-ui',
          verticalAlign: 'top',
          textTransform: 'none',
          as: 'h1',
        },
      },
      {
        id: `booking-${token}`,
        kind: 'booking-widget',
        parentId: `root-${token}`,
        rect: { x: 72, y: 118, width: 860, height: 620 },
        style: baseStyle,
        zIndex: 2,
        rotation: 0,
        locked: false,
        visible: true,
        content: {
          eyebrow: 'Bookings',
          title: 'W200 public booking flow',
          locale: 'ko',
          serviceId,
          staffId,
          successMessage: `W200 예약 완료 ${token}`,
          redirectAfterBooking: '',
          showCaseSummary: false,
          caseSummaryLabel: '사건 개요',
          showAttachmentLinks: false,
          attachmentLinksLabel: '첨부 링크',
          customFieldLabels: '',
        },
      },
    ],
  };
}
